### PR TITLE
[DF] Resolve alias, if any, before getting a column type

### LINKED ISSUE #7058: [DF] crash when asking for type of aliased columns
RDF is crashing when asking for type of aliased columns.
Here is a small reproducer:
```
root [0] // We create an empty data frame of 100 entries
root [1] ROOT::RDataFrame df(100);
root [2] gRandom->SetSeed(1);
root [3] auto df_1 = df.Define("rnd", []() { return gRandom->Gaus(); });
root [4] auto df_2=df_1.Alias("rnd2", "rnd")
(ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager, void> &) @0x7faf7b7c2098
root [5] std::cout<<df_2.GetColumnType("rnd")<<std::endl;
double
root [6] std::cout<<df_2.GetColumnType("rnd2")<<std::endl;
Error in <TRint::HandleTermInput()>: std::out_of_range caught: map::at
```

### PR DESCRIPTION
**Pull request by eguiraud**
Otherwise we end up trying to access a Defined column that does not
exist. This fixes #7058.

### CODE REVIEW

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx [hunk 1]
```diff
@@ -1854,12 +1854,19 @@ public:
    ///
    std::string GetColumnType(std::string_view column)
```
Comment (Axel-Naumann) [inline tree/dataframe/inc/ROOT/RDF/RInterface.hxx:1855]: Can you not just take a `std::string` here?

**Review by Axel-Naumann — APPROVED** [review]
LGTM but see comment.

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx (hunk 1 above)
Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/RInterface.hxx:1855]: You might remember there was a bit of a string_view hype in ROOT 2-3 years ago :smile: 
The purported advantage is that with string_view you can also pass in TStrings.
I think it's to late to change this anyway..?

**Comment by eguiraud** [comment]
Merging as I don't think we can do anything about the string_view parameter

**Comment by pcanal** [comment]
> Merging as I don't think we can do anything about the string_view parameter (EDIT: otherwise I can tackle that in another PR)

What about another overload taking an std::string?

**Comment by eguiraud** [comment]
> What about another overload taking an std::string?

The performance gains of skipping a string construction would be almost non-existing (both STLs have small-string optimizations so this is not even a heap allocation in most cases), and this function is not called in a hot loop and it might even invoke the interpreter.
