### PR TITLE
Fix TTreeCache Scaling with the number of clusters/baskets.

### LINKED ISSUE #12649: TTreeCache scale (very) poorly with number of baskets/clusters.
As described in https://root-forum.cern.ch/t/interactively-working-with-large-ntuple-tree-files-discovered-big-difference-between-old-and-new-root-versions-in-speed-7s-vs-1-hour-response-time/54312, when a file/`TTree` is created such that the cluster is actually pretty small (in bytes) and thus the number of cluster in the file is very larges (100,000+ clusters), the `TTreeCache` scale poorly (since v6.14/00).

In particular in the described case, the run-time increase from a few second (7s) to more than one hour.

### PR DESCRIPTION
**Pull request by pcanal**
On an extreme example:
```
    15,272,928 entries
       152,739 baskets (and as many clusters)
        10,000 Actual TTreeCache buffer size (minimum allowed)
         8,442 estimated buffer size of TTreeCache (1.5 times compressed buffer size)
           400 bytes per baskets
           100 entries per baskets (i.e. per clusters)
            25 number of cluster per TTreeCache buffer for single branch with default size.
             1 float per entry (reading a single branch).
```

This repairs the performance of a simple `TTree::Draw` of a single branch
from 1 hour back down to 7s (performance seem in v6.12).

One additional improvement, increase the performance by 20% on that same example.

This fixes #12649.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

File: tree/tree/src/TTree.cxx [hunk 1]
```diff
@@ -5390,40 +5433,14 @@ Long64_t TTree::GetCacheAutoSize(Bool_t withDefault /* = kFALSE */ )
...
 
    if (cacheSize == 0 && withDefault) {
-      if (fAutoFlush < 0) {
-         cacheSize = -fAutoFlush;
-      } else if (fAutoFlush == 0) {
-         const auto medianClusterSize = GetMedianClusterSize();
-         if (medianClusterSize > 0)
-            cacheSize = Long64_t(1.5 * medianClusterSize * GetZipBytes() / (fEntries + 1));
-         else
-            cacheSize = Long64_t(cacheFactor * 1.5 * 30000000); // use the default value of fAutoFlush
```
Comment (jblomer) [inline tree/tree/src/TTree.cxx:5423]: Using the new `calculateCacheSize`, this line would always use `1.0` for the cache factor (which may or may not be inteded).

File: tree/tree/src/TTreeCache.cxx [hunk 2]
```diff
@@ -1332,18 +1332,20 @@ Bool_t TTreeCache::FillBuffer()
...
    auto perfStats = GetTree()->GetPerfStats();
+
+   struct collectionInfo {
+      Int_t fClusterStart{-1}; // First basket belonging to the current cluster
+      Int_t fCurrent{-1};       // Currently visited basket
+      Bool_t fLoadedOnce{kFALSE};
+
+      void Rewind() { fCurrent = (fClusterStart >= 0) ? fClusterStart : 0; }
+   };
+   std::vector<collectionInfo> cursor(fNbranches);
```
Comment (jblomer) [inline tree/tree/src/TTreeCache.cxx:1343]: In this new version, `cursor` is not anymore initialized at the beginning of the loop. Is this a problem? Perhaps the `do {} while` loop could be prepended by a comment explaining what is being looped over.

**Review by jblomer — CHANGES_REQUESTED** [review]

File: tree/tree/src/TTreeCache.cxx (hunk 2 above)
Comment (pcanal) [reply tree/tree/src/TTreeCache.cxx:1343]: This lack of reset is the crux of the fix.   This loop is a loop over the clusters (for when the cache can hold more than one cluster worth of the selected branches).   If we reset the cursor within the loop, then we have to find the cluster boundary/start every iteration of the loop (hence the O(N^2))

I am adding the doc:
```
   // Main loop to fill the cache, inside each loop we will loop over 
   // all the cached branch and collect the baskets within the 'current'
   // range/cluster.  If there is still space in the cache after that, we 
   // will do another iteration to add one more cluster to the cache.
   // i.e. essentially loop over the clusters.
```

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
Hi @pcanal, our AddressSanitizer build reports a `heap-buffer-overflow`: https://lcgapp-services.cern.ch/root-jenkins/job/root-asan/LABEL=ROOT-centos8,SPEC=asan,V=master/lastCompletedBuild/testReport/projectroot.roottest.root.tree/stl/roottest_root_tree_stl_make/

I bisected this to commit 2fa93de2a51e248a56418d8c6488b043746d0925; the error message says "0x60700022d458 is located 8 bytes to the left of 80-byte region". However, the stack trace points to the loop immediately after the added condition to perform the binary search. Could you take a look, please? What does `TMath::BinarySearch` return in case the element is not found?
