### PR TITLE
[DF] Improve Snapshot branch-address-resetting logic 

### LINKED ISSUE #7727: TChain::CopyAddresses:0 warning in RDataFrame Snapshot of TChain with multiple files with objects
- [x] Checked for duplicates

### Describe the bug
1. Use `TChain` with >1 root files as an input for RDataFrame
2. TChain should have objects like `XYZVector` or `vector <double>`, etc.
3. Snapshot RDataFrame providing list of columns
4. Warning `TChain::CopyAddresses:0: RuntimeWarning: Could not find branch named 'xxx' in tree named 'xxx'`appears
5. Warning appears on the transition between files.

### Expected behavior
Expected no warning if it has no effect on the output.
Error, if it effects the output.
List of possible scenarios  when it cause code to break?

### To Reproduce
Compact reproducer:

```
import ROOT

ROOT.gInterpreter.Declare(
'''
#include "Math/Vector3D.h"
using namespace ROOT::Math;
''')

def test_warning():
    # Create two files to read data from
    # Warning appears only for cpp_vec and phys_vec branches
    for i in range(2):
        ROOT.RDataFrame(10).Define("simple_number", "rdfentry_")\
                           .Define("cpp_vec", "std::vector<double>{-1, 42, -1}")\
                           .Define("phys_vec", "XYZVector(-1, 42, -1)")\
                           .Snapshot("test_tree", "file{}.root".format(i))

    ch = ROOT.TChain("test_tree")
 
    # Using only one file shows No warning...
    # ch.Add("./file1.root")
    ch.Add("./file[01].root")

    df = ROOT.RDataFrame(ch).Filter('{cout<<"Event: "<<rdfentry_<< endl;} return true;')
    df = df.Define("new_var", "phys_vec.Y()*cpp_vec[1]")

    # Snapshoting w/o branch list shows no warning too
    # df.Snapshot("new_tree", "new_file.root")
    df.Snapshot("new_tree", "new_file.root", ["new_var"])


test_warning()
```

### Setup
1. ROOT 6.22/00 from  /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc10-opt/bin/root
2. Centos 7
4. Python 3.7.6

### Additional Information

This behaviour was spotted and discussed at ROOT forum:
https://root-forum.cern.ch/t/warning-in-tchain-copyaddresses-could-not-find-branch-named/35055
https://root-forum.cern.ch/t/tchain-0-warning-with-rdataframe-could-not-find-branch-named/44186

### LINKED ISSUE #8295: TChain::AddClone failing for sub-branches of branch of type with ClassDef
- [X] Checked for duplicates

### To Reproduce

The following code, which emulates what happens inside a RDataFrame Snapshot, silently writes wrong data:

```cpp
// xy_t.h
#pragma once
#include <Rtypes.h>

class xy_t {
public:
  double x;
  double y;

  xy_t() : x(-1), y(-1) {}
  ~xy_t(){};
  ClassDef(xy_t, 1); // remove this to remove the problem
};
```
```cpp
// main.cpp
#include <TFile.h>
#include <TChain.h>
#include <TSystem.h>
#include <TTree.h>
#include <TTreeReader.h>
#include <iostream>
#include "xy_t.h"

void write_inputs() {
  xy_t xy;
  int i = 0;
  {
    TFile f("in1.root", "recreate");
    TTree t("t", "t");
    t.Branch("xy", &xy);
    t.Branch("i", &i);
    i = 1;
    xy.x = xy.y = 1;
    t.Fill();
    t.Write();
    f.Close();
  }
  {
    TFile f("in2.root", "recreate");
    TTree t("t", "t");
    t.Branch("xy", &xy);
    t.Branch("i", &i);
    i = 2;
    xy.x = xy.y = 2;
    t.Fill();
    t.Write();
    f.Close();
  }
}

int main() {
  write_inputs();

  TChain c("t");
  c.Add("in1.root");
  c.Add("in2.root");
  TTreeReader r(&c);
  TTreeReaderValue<int> ri(r, "i");
  TTreeReaderValue<double> rx(r, "x");
  TTreeReaderValue<xy_t> rxy(r, "xy");

  {
    r.Next();
    TFile f("out.root", "recreate");
    TTree t("t", "t");
    c.AddClone(&t);
    t.Branch("i", &(*ri));
    t.Branch("x", &(*rx));
    t.Branch("xy", &(*rxy));
    std::cout << "x: " << *rx << '\n';
    t.Fill();
    r.Next();
    *ri;
    *rx;
    *rxy;
    std::cout << "x: " << *rx << '\n';
    t.Fill();
    t.Write();
  }

  TFile f("out.root");
  f.Get<TTree>("t")->Scan();
}
```

Can be run with:

```
$ root -l -b -q xy_t.h+; g++ -o main main.cpp xy_t_h.so $(root-config --libs --cflags) && env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./main
```

Reading and writing of the `xy` branch can be removed, in which case a warning is printed but wrong data is still written to file.

Removing the `ClassDef` from `xy_t` removes the problem and the correct data is written out.

### Additional context

The original report is https://root-forum.cern.ch/t/rdataframe-multi-file-with-class-branch-bug-report/45156, in the context of RDataFrame::Snapshot.

### PR DESCRIPTION
**Pull request by eguiraud**
Instead of TTree::AddClone + TTree::CopyAddresses, use the data-block
callback mechanism to reset addresses when needed.
We cannot trust TTree::CopyAddresses to do the right thing because
the output branch might be a different kind of branch than the input
branch (e.g. TBranch vs TBranchElement), which leads to the problem
described at #8295 .

This fixes #8295 for what regards Snapshot.

This PR also adds support for "data-block" callbacks, wired to `TChain`'s `TNotify` mechanism, to be able to react to changes of the underlying TTree (e.g. by resetting the input address of Snapshot's output branches). This is a pre-requisite for the fix, but it also makes it relatively simple to implement `DefinePerSample` as requested in #6745 .

As a side-effect, since we now don't rely on `TTree::CopyAddresses` in `Snapshot` anymore, this PR should also fix #7727 .

### CODE REVIEW

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx [hunk 1]
```diff
@@ -1352,6 +1415,12 @@ public:
    }
 
    std::string GetActionName() { return "Snapshot"; }
+
+   std::function<void(unsigned int)> GetDataBlockCallback() final
+   {
+      auto callback = [this](unsigned int) mutable { fBranchAddressesNeedReset = true; };
+      return {callback};
```
Comment (Axel-Naumann) [inline tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1422]: Why not just
```suggestion
      return [this](unsigned int) mutable { fBranchAddressesNeedReset = true; };
```
?

File: tree/dataframe/test/dataframe_datablockcallback.cxx [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+TEST_P(RDFDataBlockCallback, TTree) {
+   const std::string prefix = "rdfdatablockcallback_ttree";
+   InputFilesRAII file(1u, prefix);
+   ROOT::RDataFrame df("t", prefix + "*");
+   auto result = df.Book<>(CounterHelper(), {});
+   EXPECT_EQ(*result, 1u);
+}
+
+TEST_P(RDFDataBlockCallback, TChain) {
+   const std::string prefix = "rdfdatablockcallback_ttree";
```
Comment (Axel-Naumann) [inline tree/dataframe/test/dataframe_datablockcallback.cxx:84]: Should this have a different prefix?
```suggestion
   const std::string prefix = "rdfdatablockcallback_tchain";
```

**Review by Axel-Naumann — APPROVED** [review]

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx (hunk 1 above)
Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1422]: leftover from a previous iteration where the return type was `vector<function<..>>`, thanks!

File: tree/dataframe/test/dataframe_datablockcallback.cxx (hunk 2 above)
Comment (eguiraud) [reply tree/dataframe/test/dataframe_datablockcallback.cxx:84]: definitely!

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx [hunk 3]
```diff
@@ -93,6 +96,41 @@ using namespace ROOT::Detail::RDF;
 
 using Hist_t = ::TH1D;
 
+class RBranchSet {
+   std::vector<TBranch *> fBranches;
+   std::vector<std::string> fNames;
```
Comment (pcanal) [inline tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:101]:
```suggestion
   std::vector<std::pair<TBranch *, std::string> fBranches;
```
since the 2 must to be in sync. (and then using std::find_if and a lamba still allows the needed searches).

Comment (pcanal) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:101]: fair enough

**Review by pcanal — APPROVED** [review]

**Comment by eguiraud** [comment]
Rebased just to clean the commit history a bit, the set of changes is exactly the same.
