### PR TITLE
Fix the #8155 and #8092

### LINKED ISSUE #8155: Error opening remote root file LCG_100
- [ ] Checked for duplicates

### Describe the bug
Running our test on SWAN, I found that TFIile can not read anymore a remote ROOT file from github.
The code
`
TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");
`

produces
`
Error in <DavixOpen>: can not open file "https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root" with davix: Result HTTP 404 : File not found  after 3 attempts (18) 
`
The file exists and the code works with LCG_99.

I did an additional test with a ROOT different ROOT file inside the domain cern.ch and it works for LCG_100
`
TFile::Open("https://root.cern.ch/files/summer_student_tutorial_tracks.root");
`

### Expected behavior
TFIle should be able to read the file from github.

### To Reproduce
on lxplus
`
source /cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/setup.sh

[ozapatam@lxplus7103 ~]$ root -l -b

root [0] auto f=TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");

Error in <DavixOpen>: can not open file "https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root" with davix: Result HTTP 404 : File not found  after 3 attempts (18)
`

on LCG_99 it works
`
source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc8-opt/setup.sh 

[ozapatam@lxplus7120 ~]$ root -l

root [0] auto f=TFile::Open("https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root");

root [1] f->ls();
TDavixFile**            https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
 TDavixFile*            https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/inputdata.root
  KEY: TTree    TreeS;1 TreeS
  KEY: TTree    TreeB;1 TreeB
  KEY: TTree    Sig;1   TreeS
  KEY: TTree    Bkg;1   TreeB
`

### Setup
ROOT Version: 6.24/00
Built for linuxx8664gcc on Apr 14 2021, 14:33:50
From tags/v6-24-00@v6-24-00

LCG_100

### PR DESCRIPTION
**Pull request by oshadura**
Fix the bug in the check if Bearer token for Davix actually was discovered (not empty)
Fixes #8155 and #8092

### CODE REVIEW

File: net/davix/src/TDavixFile.cxx [hunk 1]
```diff
@@ -535,8 +535,9 @@ void TDavixFileInternal::parseConfig()
    // WLCG Bearer tokens check
    std::string prefix = "Bearer ";
    auto token = DiscoverToken();
-   if (token.c_str()) {
+   if (!token.empty()) {
       // header: "Authorization: Bearer mytoken"
+      R__LOG_INFO(TDavixLogChannel()) << "Using Bearer token: " << token;
```
Comment (Axel-Naumann) [inline net/davix/src/TDavixFile.cxx:540]: I'd remove this - this can easily become a security issue, depending on where logs end up. If you want to keep it then shorten it to
```suggestion
      R__LOG_INFO(TDavixLogChannel()) << "Using Bearer token starting with: " << token.substr(0, 3);
```

**Review by Axel-Naumann — APPROVED** [review]
