### PR TITLE
[RF] Handle variables having numeric value as name in RooFormula

### LINKED ISSUE #11992: [RF] RooFormulaVar is too eager in variable name substitution
- [x] Checked for duplicates

### Describe the bug

When passing a argument to a formula based RooFit function (e.g. `RooFormulaVar` or `RooGenericPdf`), RooFit will search for all occurrences of the object name in the formula and replace them with an ordinal parameter (needed for the underling `TFormula`). However, when the argument is a `RooConst` the name is just a string containing the value and this can break if there are numeric literals inside the formula.
For example
```
RooFormulaVar f("f", "2.7*@0", RooFit::RooConst(2.))
```
becomes inside the `TFormula`
```
x[0].7*x[0]
```
because the name 2 of the `RooConst` matched the 2 of the numeric literal. This of course breaks during formula compilation.

### Expected behavior

The variables do not replace numeric literals no matter the name. Possibly `RooConst`s should be matched only by index?

### To Reproduce

```
RooFormulaVar f("f", "2.7*@0", RooFit::RooConst(2.))
```

### Setup

HEAD of ROOT 6.26 from LCG dev4

### Additional context

`RooFormulaVar f("f", "2.7*@0", RooFit::RooConst(2.7))` creates `x[0]*x[0]`, which is mostly fine but may break if servers are redirected

### PR DESCRIPTION
**Pull request by Ban42**
# This Pull request:

As requested in #11992 changes the way RooFormulaVar performs variable names substitutions.

## Changes or fixes:
Before performing a substitution in the formula based on variable name, the code now checks if the variable to be substituted has a number as name. 
Variables where the name is a number are now only be matched by index. If there is a variable with a name that is a number that is not a RooConstVar where the value is equal to the name, an exception will be thrown. 

## Checklist:

- [x] tested changes locally: Yes, 227 - gtest-roofit-roofitcore-testRooFormula fails, throwing one of the two exceptions I have created. I either have to update it, or double-check for mistakes on my side.
- [ ] updated the docs : Let me know if I should.
- [x] Add tests: I probably need to add a test for this

This PR fixes #11992

### CODE REVIEW

**Comment by Ban42** [comment]
Hi @guitargeek ,
This is the solution I have found which should match the specification you described in #11992 

The test "227 - gtest-roofit-roofitcore-testRooFormula" fails, which means I have made a mistake or I have to update it. Before doing so, I wanted you to have a quick look and confirm this approach is the desired one.

Thank you :)

**Comment by dpiparo** [comment]
let's start with the CI, to see where we stand.

File: roofit/roofitcore/test/testRooFormula.cxx [hunk 1]
```diff
@@ -5,6 +5,7 @@
 #include "../src/RooFormula.h"
```
Comment (Ban42) [inline roofit/roofitcore/test/testRooFormula.cxx:6]: Hi guys,
I know is a bit silly, but since I have added a new test here can I add my name in the list of authors at the beginning of the file? :grimacing:

Comment (dpiparo) [reply roofit/roofitcore/test/testRooFormula.cxx:6]: yes, of course.

**Comment by dpiparo** [comment]
Let's fix the formatting in the test (which can be coupled with adding the author name to the file). After that, if @guitargeek agrees, for me this is ready to be merged.

**Comment by dpiparo** [comment]
rebased the code and restarted the tests... @guitargeek fyi
