### PR TITLE
[ntuple] Fix automatic schema evolution of record fields

### LINKED ISSUE #19254: [ntuple] Schema evolution of record fields
### Check duplicate issues.

- [x] Checked for duplicates

### Description

We currently have no `RRecordField::BeforeConnectPageSource` that either checks or correctly schema evolves record fields.

### Reproducer

```c++
#include <ROOT/RNTupleModel.hxx>
#include <ROOT/RNTupleReader.hxx>
#include <ROOT/RNTupleWriter.hxx>

#include <cstdint>
#include <string>
#include <tuple>

void ntuple_tuple() {
  {
    auto model = ROOT::RNTupleModel::Create();
    using TupType = std::tuple<std::int32_t, std::string>;
    auto tup = model->MakeField<TupType>("tup");
    auto writer = ROOT::RNTupleWriter::Recreate(std::move(model), "ntpl", "ntuple_tuple.root");

    *tup = {42, "abc"};
    writer->Fill();
  }

  { // 1
    auto model = ROOT::RNTupleModel::Create();
    using TupType = std::tuple<std::int32_t, std::string, float>;
    auto tup = model->MakeField<TupType>("tup");
    try {
      auto reader = ROOT::RNTupleReader::Open(std::move(model), "ntpl", "ntuple_tuple.root");
    } catch (const ROOT::RException &e) {
      std::cout << e.GetError().GetReport() << "\n";
    }
  }

  { // 2
    auto model = ROOT::RNTupleModel::Create();
    using TupType = std::tuple<std::string>;
    auto tup = model->MakeField<TupType>("tup");
    try {
    auto reader = ROOT::RNTupleReader::Open(std::move(model), "ntpl", "ntuple_tuple.root");
      reader->LoadEntry(0);
      std::cout << "0: string = " << std::get<0>(*tup) << "\n";
    } catch (const ROOT::RException &e) {
      std::cout << e.GetError().GetReport() << "\n";
    }
  }
}
```

This macro writes a `std::tuple<std::int32_t, std::string>` and then demonstrates two cases:
1. When trying to read back as a `std::tuple<std::int32_t, std::string, float>`, the additional `float` leaf field complains:
```
No on-disk field information for `tup._2`
At:
  const ROOT::RFieldBase::ColumnRepresentation_t &ROOT::RFieldBase::EnsureCompatibleColumnTypes(const ROOT::RNTupleDescriptor &, std::uint16_t) const
```
2. With an imposed field type of `std::variant<std::string>`, the user could expect that the string is read back. Instead it (correctly) throws:
```
On-disk column types {`SplitInt32`} for field `tup._0` cannot be matched to its in-memory type `std::string` (representation index: 0)                                                                 
At:
  const ROOT::RFieldBase::ColumnRepresentation_t &ROOT::RFieldBase::EnsureCompatibleColumnTypes(const ROOT::RNTupleDescriptor &, std::uint16_t) const
```

### ROOT version

`master`

### Installation method

from source

### Operating system

Linux

### Additional context

We discussed a conservative approach to check exact identity of the type name.

### PR DESCRIPTION
**Pull request by jblomer**
Includes automatic schema evolution for `std::pair` and `std::tuple`, which are implemented as descendants of the `RRecordField`.

Fixes #19254

### CODE REVIEW

File: tree/ntuple/inc/ROOT/RFieldBase.hxx [hunk 1]
```diff
@@ -421,6 +420,11 @@ protected:
    static void CallConstructValueOn(const RFieldBase &other, void *where) { other.ConstructValue(where); }
    static std::unique_ptr<RDeleter> GetDeleterOf(const RFieldBase &other) { return other.GetDeleter(); }
 
+   /// Allow parents to mark their childs as artificial fields (used in class and record fields)
+   void CallSetArtificialOn(RFieldBase &other) { other.SetArtificial(); }
+   /// Allow class fields to adjust the type alias of their members
+   void SetTypeAliasOf(RFieldBase &other, const std::string &alias) { other.fTypeAlias = alias; }
```
Comment (hahnjo) [inline tree/ntuple/inc/ROOT/RFieldBase.hxx]: I believe these functions can be `static`?

```suggestion
   static void CallSetArtificialOn(RFieldBase &other) { other.SetArtificial(); }
   /// Allow class fields to adjust the type alias of their members
   static void SetTypeAliasOf(RFieldBase &other, const std::string &alias) { other.fTypeAlias = alias; }
```

File: tree/ntuple/src/RField.cxx [hunk 2]
```diff
@@ -605,7 +606,20 @@ void ROOT::RRecordField::ReadInClusterImpl(RNTupleLocalIndex localIndex, void *t
 
 void ROOT::RRecordField::ReconcileOnDiskField(const RNTupleDescriptor &desc)
```
Comment (hahnjo) [inline tree/ntuple/src/RField.cxx:608]: If I understand correctly, this function is now only for untyped record fields because `RPairField` and `RTupleField` provide their own override. Maybe we can add a comment and
```c++
R__ASSERT(fName.empty());
```
(or whatever other method we have to identify untyped record fields) to ensure this invariant is not violated in the future?

File: tree/ntuple/src/RField.cxx [hunk 3]
```diff
@@ -605,7 +606,20 @@ void ROOT::RRecordField::ReadInClusterImpl(RNTupleLocalIndex localIndex, void *t
...
 {
-   EnsureMatchingOnDiskField(desc.GetFieldDescriptor(GetOnDiskId()), kDiffTypeName | kDiffTypeVersion);
+   const auto &fieldDesc = desc.GetFieldDescriptor(GetOnDiskId());
+   EnsureMatchingOnDiskField(fieldDesc, kDiffTypeName | kDiffTypeVersion);
+
+   // The on-disk ID of subfields is matched by field name. So we inherently support reordering of fields
+   // and we will ignore extra on-disk fields.
+   // It remains to mark the extra in-memory fields as artificial.
+   std::unordered_set<std::string> onDiskSubfields;
```
Comment (silverweed) [inline tree/ntuple/src/RField.cxx]: These can be `string_view`s to avoid an unneeded copy

File: tree/ntuple/src/RFieldMeta.cxx [hunk 4]
```diff
@@ -1151,6 +1166,22 @@ ROOT::RTupleField::RTupleField(std::string_view fieldName, std::vector<std::uniq
    }
 }
 
+void ROOT::RTupleField::ReconcileOnDiskField(const RNTupleDescriptor &desc)
+{
+   static const std::vector<std::string> prefixes = {"std::pair<", "std::tuple<"};
```
Comment (silverweed) [inline tree/ntuple/src/RFieldMeta.cxx:1189]: We should probably change `EnsureMatchingTypePrefix` to accept a `span` so we can avoid creating `vector`s for things that should really be static arrays

Comment (jblomer) [reply tree/ntuple/src/RFieldMeta.cxx:1189]: Ok, I'd like to do that in a separate PR.

File: tree/ntuple/src/RField.cxx (hunk 2 above)
Comment (jblomer) [reply tree/ntuple/src/RField.cxx:608]: Good point! It actually revealed another bug.

**Review by hahnjo — APPROVED** [review]
LGTM, thanks!
