### PR TITLE
[DF][10484] Finalize actions if an exception occurs during evt loop

### LINKED ISSUE #10484: `Graph` and `GraphAsymmErrors` Action Helpers not deallocating memory when event loop is interrupted
Issue spotted by @eguiraud [here](https://github.com/root-project/root/pull/9760#discussion_r796863943). The classes `Graph` and `GraphAsymmErrors` action helpers inside `tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx` allocate memory with `new`, but never deallocate it.

Note that `HIST` also allocates with `new` but inside its `Finalize()` method, it takes care of deallocation.

### PR DESCRIPTION
**Pull request by dpiparo**
Exceptions thrown in an event loop are caught to print a message. This catch block is leveraged to finalize all scheduled actions in order to properly deallocate memory where needed and save the partial results which are obtained.

# This Pull request:
Is work in progress and lacks a test battery
## Changes or fixes:
Allows to finalize actions scheduled in a RDF analysis in case an exception is thrown during the event loop.

## Checklist:

- [V] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #10484

### CODE REVIEW

**Comment by dpiparo** [comment]
All tests pass except some which are related to something very different. A note about code formatting: I applied the suggestions of the bot, all but one, since I refuse to spreade a lambda function in a lambda function on two subsequent lines: the readability is severely affected.

**Review by vepadulano — COMMENTED** [review]
I like the approach a lot, the fact we were leaving the RDF usable but not in a valid state after throwing an exception in the evt loop was probably not ideal. I think we should document this behavioural change, but I'm not sure where. At least a line in the release notes, but maybe not point it out explicitly in the docs because the old behaviour was a sort of exploit

File: tree/dataframe/src/RLoopManager.cxx [hunk 1]
```diff
@@ -835,10 +835,31 @@ void RLoopManager::Run(bool jit)
    if (jit)
       Jit();
 
-   InitNodes();
+   // Exceptions can occur during the event loop. In order to ensure proper cleanup and logging
+   // we use RAII: even in case of an exception, the deconstructor of the object is invoked and
```
Comment (eguiraud) [inline tree/dataframe/src/RLoopManager.cxx:839]:
```suggestion
   // we use RAII: even in case of an exception, the destructor of the object is invoked and
```

**Review by eguiraud — COMMENTED** [review]
Thank you @dpiparo !

I have a couple of considerations, up to you and Vincenzo to decide whether you want to do anything about them.

1. it seems to me that the `RunKeeperRAII` is doing too much (initialization, clean-up, stopwatch stuff, logging). It moves some logic further from "where it belongs", and because it does a few different things it ends up with a generic non-descriptive name. maybe consider only using the RAII to call CleanUpNodes, which is what's needed to avoid leaks.

3. I am not sure that we should increment the number of `fNRuns` and log as if everything went fine if an exception was thrown during the event loop. a different message might be warranted.

3. it's unclear to me in what state the computation graph is left when an exception is raised during the event loop. in this sense, my understanding is that the situation is the same as before and I'm not sure there is anything new to document (in regards to Vincenzo's comment above). the improvement with this PR is that we call `CleanUpNodes()`, so we avoid leaking some things

**Comment by vepadulano** [comment]
> in this sense, my understanding is that the situation is the same as before

Not exactly the same, consider the following repro taken from Danilo's new test

```cpp
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RDFHelpers.hxx>
#include <memory>
#include <TTreeReader.h>
#include <iostream>


class SimpleActionHelper : public ROOT::Detail::RDF::RActionImpl<SimpleActionHelper> {
public:
   using Result_t = int;

private:
   std::shared_ptr<Result_t> fValue;
   int &fTestVal;

public:
   static constexpr int fgRefVal = 42;
   SimpleActionHelper(int &testVal) : fValue(new int), fTestVal(testVal) {}
   SimpleActionHelper(SimpleActionHelper &&) = default;
   SimpleActionHelper(const SimpleActionHelper &) = delete;
   std::shared_ptr<int> GetResultPtr() const { return fValue; }
   void Initialize() {}
   void InitTask(TTreeReader *, unsigned int) {}
   template <typename... ColumnTypes>
   void Exec(unsigned int, ColumnTypes...)
   {
   }
   void Finalize() { fTestVal = SimpleActionHelper::fgRefVal; }
   std::string GetActionName() { return "SimpleAction"; }
};

int main()
{
   auto exceptionThrower = [](ULong64_t ievt) {
      if (ievt == 4) {
         throw std::invalid_argument("Time to throw.");
      }
      return int(0);
   };

   int testVal = 123;
    std::cout << "Testing value " << testVal << std::endl;
   SimpleActionHelper helper(testVal);
   auto rdf = ROOT::RDataFrame(8).Define("dummy", exceptionThrower, {"rdfentry_"});
   auto valRes = rdf.Book<int>(std::move(helper), {"dummy"});

    try{
        valRes.GetValue();
    } catch (...){

    }

    std::cout << "Testing value " << testVal << std::endl;
}
```
Then

```
./repro_628.out 
Testing value 123
RDataFrame::Run: event loop was interrupted
Testing value 123
```
```
./repro_danilo_patch.out 
Testing value 123
RDataFrame::Run: event loop was interrupted
Testing value 42
```

Still, this is probably not something to write in the docs.

**Comment by vepadulano** [comment]
> I am not sure that we should increment the number of fNRuns and log as if everything went fine if an exception was thrown during the event loop. a different message might be warranted.

Indeed this could be a good idea, to further clarify that the RDF is not usable anymore and should just be thrown away

**Comment by eguiraud** [comment]
> Not exactly the same

Sorry, I meant it's the same in the context that I mentioned: the computation graph is left in a state that at least I do not completely understand and I cannot guarantee is fully usable.

**Comment by dpiparo** [comment]
Thanks both, @vepadulano and @eguiraud. I will consider all of your comments, which I find very relevant, and propose a new solution based on them.

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
@phsft-bot build

**Review by vepadulano — APPROVED** [review]
The changes look good to me now, the new test shows the fix of the behaviour, thanks!

**Review by martamaja10 — APPROVED** [review]
It is a really nice improvement, thanks Danilo! I looked through the changes and the conversation, and I don't have anything more to add.
