### PR TITLE
Fix #6393

### LINKED ISSUE #6393: PyROOT cannot call templated ctors on Windows
## Describe the bug

Templated ctors cannot be called on Windows because demangling of the constructor *template* (!) fails - likely because there is no mangling standard for the template. See https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx#L1693

## Expected behavior

Template ctor should be called.

## To Reproduce

@hageboeck has it.

## Setup

Master, with MSVC.

## Additional context

Instead of demangling and looking for '<' we could add a new interface: `TFunction::`-is-this-a-template.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Fix #6393 (at least incrementally) by avoiding the demangling step, and instead exposing the template-ness consistently.

### CODE REVIEW

**Review by hageboeck — APPROVED** [review]
LGTM!

File: core/metacling/test/TClingMethodInfoTests.cxx [hunk 1]
```diff
@@ -257,119 +254,146 @@ namespace ROOT11010 {
...
+   // > // as eg. constructors do not receive their proper/full name from GetName()
+
+   gInterpreter->Declare(R"CODE(
+struct TemplateFun {
+   template <class T>
+   TemplateFun(int, T);
+
+   template <class T>
+   int NonCtor(float, T);
+};
```
Comment (pcanal) [inline core/metacling/test/TClingMethodInfoTests.cxx:386]:
```suggestion
};
struct InheritTemplateFun {
    using TemplateFun::TemplateFun;
};
```
and associated testing.

**Review by pcanal — APPROVED** [review]

File: core/metacling/test/TClingMethodInfoTests.cxx (hunk 1 above)
Comment (Axel-Naumann) [reply core/metacling/test/TClingMethodInfoTests.cxx:386]: That's a very distinct rabbit hole: our `LookupHelper` cannot instantiate function templates, which would cause this test to fail even if the using decl is indeed injecting the base class template. I have added the test skeleton, commented it, and created #6481 #6482

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-debian10-i386/cxx14

**Review by etejedor — APPROVED** [review]
