### PR TITLE
[hist] Ndim: correctly set axes title from histo title

### LINKED ISSUE #21484: Last axis title is not set for THn and THnSparseD histograms, affects also HistoND and HistoNSparseD
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Last axis title is not set. Other titles are ok. The bug is very likely in this function:
https://root.cern.ch/doc/master/THnBase_8cxx_source.html#l01214

The bug has larger impact on HistoND and HistoNSparseD because it is not possible to set axis title manually without triggering the loop.

### Reproducer

Last axis title is empty string in THnSparseD and THnD constructors:
```
std::vector<double> xmin = {0,0,0,0,0};
std::vector<double> xmax = {1,1,1,1,1};
std::vector<int> nbins = {1,1,1,1,1};
auto h = new THnSparseD("name", "title;title_0;title_1;title_2;title_3;title_4", 5, nbins.data(), xmin.data(), xmax.data());
std::cout << h->GetAxis(0)->GetTitle() << std::endl; // Correct
std::cout << h->GetAxis(1)->GetTitle() << std::endl; // Correct
std::cout << h->GetAxis(2)->GetTitle() << std::endl; // Correct
std::cout << h->GetAxis(3)->GetTitle() << std::endl; // Correct
std::cout << h->GetAxis(4)->GetTitle() << std::endl; // Wrong - empty string
```

The same behavior observed with HistoNSparseD in python
```
import ROOT
import numpy as np

# -----------------------------
# Define binning for 3 axes
# -----------------------------
nbins = np.array([1, 1, 1], dtype=np.int32)
xmin = np.array([0.0, 0.0, 0.0], dtype=np.float64)
xmax = np.array([1.0, 1.0, 1.0], dtype=np.float64)

# Title string with 3 axis titles (TH1-style)
title = "Sparse;A;B;C"

# -----------------------------
# Create a simple RDF
# -----------------------------
N = 1000
df = ROOT.RDataFrame(N)
df = df.Define("x", "gRandom->Uniform(0,10)")
df = df.Define("y", "gRandom->Uniform(0,10)")
df = df.Define("z", "gRandom->Uniform(0,10)")

# -----------------------------
# Create THnSparseD via RDF
# -----------------------------
# Syntax:
# df.HistoNSparseD(name, title, columns, nbins, axes)
#
# nbins: list of ints
# axes: list of numpy arrays (float64)
#
model = ROOT.RDF.THnSparseDModel("hSparse", title, 3, nbins, xmin, xmax)
h_ptr = df.HistoNSparseD(model, ["x", "y", "z"])

# Force computation
h = h_ptr.GetValue()

# -----------------------------
# Print axis titles to show the bug
# -----------------------------
print("Axis titles after creation via RDF.HistoNSparseD:")
for i in range(3):
    print(f" Axis {i}: '{h.GetAxis(i).GetTitle()}'")
```

### ROOT version

Always there. Reproducers tested in 6.38.00

### Installation method

cvmfs

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dpiparo**
and preserve axis titles if any if the c'tor is invoked passing a vector of axes.

Fixes #21484

### CODE REVIEW

File: hist/hist/src/THnBase.cxx [hunk 1]
```diff
@@ -1201,6 +1201,29 @@ void THnBase::SetBinEdges(Int_t idim, const Double_t* bins)
...
+   TString titleStr = title;
+   titleStr.ReplaceAll("#;",2,"#semicolon",10);
+
+   Ssiz_t from = 0;
+   titleStr.Tokenize(fTitle, from, ";");
+   fTitle.ReplaceAll("#semicolon", 10, ";", 1);
+
+   TString axisTitle;
+   Int_t dim = 0;
+   while(titleStr.Tokenize(axisTitle, from, ";")) {
```
Comment (ferdymercury) [inline hist/hist/src/THnBase.cxx:1215]: Thanks! Non-important: a more modern alternative to Tokenize could be:
ROOT::Split (https://root.cern.ch/doc/master/StringUtils_8hxx_source.html)

Comment (dpiparo) [reply hist/hist/src/THnBase.cxx:1215]: Indeed. Since we were dealing with TStrings, I thought I would stick to the way the code was written at the time.
Ideally, what could be also useful, is a tokenizer that produces a collection of string_view pointing to the string being tokenized, to avoid all copies. In this and many other cases, there would be no measurable impact on the performance, but in principle that is the "right" thing to do maybe....
