### PR TITLE
[ntuple] Implement `Detail::RRawPtrWriteEntry`

### LINKED ISSUE #17900: [ntuple] Add write API with const pointers
During the HEP-CCE review and when implementing the RNTuple prototype in CMSSW, it became clear that the current `REntry` interface doesn't work for writing `const` objects (via raw pointers). This was confirmed by ATLAS in yesterday's RNTuple planning discussion. As `REntry` and `RFieldBase::RValue` heavily rely on shared ownership of the objects, a possibility would be to introduce a separate `RConstEntry` (name to be discussed) that only works for writing and acts as a sort of container for raw pointers only.

### PR DESCRIPTION
**Pull request by hahnjo**
It is a container of `const` raw pointers that can be used to write constant data products in frameworks.

Closes #17900

### CODE REVIEW

File: tree/ntuple/v7/inc/ROOT/RFieldToken.hxx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+class REntry;
+class RNTupleModel;
+
+namespace Detail {
+class RRawPtrWriteEntry;
+} // namespace Detail
+
+// clang-format off
+/**
+\class ROOT::Experimental::RFieldToken
```
Comment (hahnjo) [inline tree/ntuple/v7/inc/ROOT/RFieldToken.hxx:33]: Shall I move the class out of `Experimental` directly? @silverweed

Comment (silverweed) [reply tree/ntuple/v7/inc/ROOT/RFieldToken.hxx:33]: I think so. But maybe we can double check with @jblomer to see if he has any objection to this.

Comment (hahnjo) [reply tree/ntuple/v7/inc/ROOT/RFieldToken.hxx]: I rebased the PR, resolved the conflicts, and moved to `ROOT::RFieldToken`.

**Review by jblomer — APPROVED** [review]
Thanks! LGTM!

File: tree/ntuple/v7/inc/ROOT/RFieldToken.hxx [hunk 2]
```diff
@@ -36,8 +42,9 @@ It can be used for fast indexing in REntry's methods, e.g. REntry::BindValue().
 class RFieldToken {
    friend class REntry;
    friend class RNTupleModel;
+   friend class Experimental::Detail::RRawPtrWriteEntry;
 
-   std::size_t fIndex = 0;                      ///< The index in `fValues` that belongs to the field
+   std::size_t fIndex = 0;                      ///< The index of the top-level field
```
Comment (enirolf) [inline tree/ntuple/v7/inc/ROOT/RFieldToken.hxx:47]: With the addition of `REntry::RegisterSubfield`, this doesn't necessarily only have to be a top-level field.

File: tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx [hunk 3]
```diff
@@ -110,6 +111,18 @@ public:
    /// Fill an entry into this ntuple, but don't commit the cluster. The calling code must pass an RNTupleFillStatus
    /// and check RNTupleFillStatus::ShouldFlushCluster.
    void FillNoFlush(ROOT::REntry &entry, RNTupleFillStatus &status) { fFillContext.FillNoFlush(entry, status); }
+
+   /// Fill an RRawPtrWriteEntry into this ntuple.  This method will perform
+   /// a light check whether the entry comes from the ntuple's own model
```
Comment (enirolf) [inline tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx:116]: What exactly does "light check" mean? Is there something that's not checked that the caller should take of themselves?

**Review by enirolf — APPROVED** [review]
LGTM! I added two minor documentation-related comments but otherwise good to go.

File: tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx (hunk 3 above)
Comment (silverweed) [reply tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx:116]: I think it just means that the check itself is not computationally expensive. The caller should not have to do specific checks in the code (unless they are weirdly mixing up entries from different models).

File: tree/ntuple/v7/inc/ROOT/RFieldToken.hxx [hunk 4]
```diff
@@ -0,0 +1,57 @@
+/// \file ROOT/RFieldToken.hxx
+/// \ingroup NTuple ROOT7
+/// \author Jonas Hahnfeld <jonas.hahnfeld@cern.ch>
+/// \date 2015-03-19
```
Comment (vepadulano) [inline tree/ntuple/v7/inc/ROOT/RFieldToken.hxx:4]:
```suggestion
/// \date 2025-03-19
```

**Review by vepadulano — APPROVED** [review]
Thanks!

File: tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx (hunk 3 above)
Comment (hahnjo) [reply tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx]: I amended the documentation to talk about the model ID, and mention that the method throws an exception otherwise.
