### PR TITLE
Fix #7016 Do no leak Conversion StreamerInfo for unversion classes.

### LINKED ISSUE #7016: Memory leak during schema evolution of some classes
### Describe the bug

The DUNE experiment ran into a situation where instances of class `recob::Track` were written to disk with version 13, but were read with a dictionary whose class version was 17.  Although an I/O rule was written, it appears to not have been applied, possibly because version 13 was not specified in selection XML file.  Philippe would know the exact reason.

Significant memory growth was observed, and Philippe confirmed that a memory leak is encountered.

### Reproduction and setup

Philippe already has the appropriate setup instructions for diagnosing this error.  This bug report was opened at his request.

### PR DESCRIPTION
**Pull request by pcanal**
The leak is related to the handling of conversion from unversioned class from MathCore
(namely from ```ROOT::Math::Cartesian3D<double>``` to ```ROOT::Math::Cartesian3D<Double32_t>``` and
```ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::GlobalCoordinateSystemTag>```
to ```ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::GlobalCoordinateSystemTag>```

In some circumstances (involving which StreamerInfo was recorded in an acceleration structure/cache), TClass was
not remembering that it already created the Conversion StreamerInfo from one to the other and recreating from each object read.

In the case of DUNE, the leak was triggered by running:
```
   Events->Draw("recob::Tracks_pandoraTrack__DecoderandReco.obj.fTraj.fMomenta.fCoordinates.fX");
```
or similar.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The errors are unrelated.
ROOT-fedora31/noimt: ` error: failed to write new configuration file /build/workspace/root-pullrequests-build/root/.git/config.lock`

ROOT-performance-centos8-multicore/default:
df105_WBosonAnalysis_py: timeout
roottest_root_multicore_tExecutor: odd crash

ROOT-ubuntu16/nortcxxmod: IncrementalExecutor::executeFunction: symbol '_ZNK4ROOT15TThreadExecutor11GetPoolSizeEv' unresolved while linking symbol 'atexit'!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

File: core/meta/src/TClass.cxx [hunk 1]
```diff
@@ -7061,7 +7061,7 @@ TVirtualStreamerInfo *TClass::GetConversionStreamerInfo( const TClass* cl, Int_t
          arr = it->second;
       }
 
-      if( arr && version > -1 && version < arr->GetSize() && arr->At( version ) )
+      if( arr && version >= -1 && version < arr->GetSize() && arr->At( version ) )
```
Comment (Axel-Naumann) [inline core/meta/src/TClass.cxx:7064]: `arr` can handle an index of `-1`?

Comment (Axel-Naumann) [inline core/meta/src/TClass.cxx:7064]: What is the effect of having an entry at `-1` on `GetSize()`? I.e. `version < arr->GetSize()` might now not do what the original code expected, with `GetSize()` returning 1 with an element at index `-1`, yet for `version == 0` no element `arr->At(0)` exists despite `version < arr->GetSize()`.

**Review by Axel-Naumann — APPROVED** [review]
Always assuming you know what you're doing ;-)

File: core/meta/src/TClass.cxx [hunk 2]
```diff
@@ -7113,6 +7118,11 @@ TVirtualStreamerInfo *TClass::GetConversionStreamerInfo( const TClass* cl, Int_t
       }
       (*fConversionStreamerInfo)[cl->GetName()] = arr;
    }
+   if (arr->At(info->GetClassVersion())) {
+      Error("GetConversionStreamerInfo", "Conversion StreamerInfo from %s to %s version %d has already been created",
+            this->GetName(), info->GetName(), info->GetClassVersion());
+      delete arr->At(info->GetClassVersion());
+   }
    arr->AddAtAndExpand( info, info->GetClassVersion() );
```
[the remark this answers is not in the document]
Comment (pcanal) [reply core/meta/src/TClass.cxx:7126]: less than -1 are invalid values.  The array's index is [-1, +inf or whatever :) ], so attempting to store -2 would result in memory over-write.

File: core/meta/src/TClass.cxx (hunk 1 above)
Comment (pcanal) [reply core/meta/src/TClass.cxx:7064]: Yes :) ... This category of arrays is created with:
```
new TObjArray(version+10, -1);
```

Comment (pcanal) [reply core/meta/src/TClass.cxx:7064]: The array has an effective offset of +1, so the "real" indices are from [0 to max]. 

The array is not expected to be contiguous filled (in practice it is in most case filled in a couple of place, current version number and whatever old version was read).

For versioned class, the current version is stored both at -1 and 1.  Slot 0 is rarely used/filled as 0 indicates a class with all data members marked transient (so it happens only if such a class is used as base class).

> What is the effect of having an entry at -1 on GetSize()

it increases the size by 1 if the slot was previously empty.

**Comment by pcanal** [comment]
The errors on ROOT-performance-centos8-multicore/default. are pre-existing.
