### PR TITLE
Resolve issue when dictionary with std::tuple is unloaded.

### LINKED ISSUE #12358: Self-reference through a map of tuples breaks the interpreter (2023.02.20.)
- [x] Checked for duplicates

### Describe the bug

The following type of error appeared in the ATLAS analysis software (I believe...) when we switched to ROOT 6.26/08. Though when I now produced a standalone reproducer for it, I couldn't make it work with 6.24/06 either. (Which is what we used for a long time, apparently without this issue.)

Take the following struct:

```c++
struct ConfigType {
   std::map<std::string, std::tuple<ConfigType, std::string> > m_children;
};
```

When I build a (Reflex) dictionary for it, it seems to work fine.

```
[bash][atspot01]:self-reference > root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jul 28 2022, 18:08:51                 |
  | From tags/v6-26-06@v6-26-06                                      |
  | With c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0                   |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0] ConfigType c;
root [1]
```

I can also happily write objects of this type into ROOT files. But as soon as I try to merge two such ROOT files with `hadd`, I get:

```
hadd Target file: output.root
hadd compression setting for all output: 1
hadd Source file 1: input1.root
hadd Source file 2: input2.root
hadd Target path: output.root:/
input_line_32:7:15: error: field has incomplete type 'ConfigType'
   ConfigType _0;
              ^
libSelfReferenceDict dictionary forward declarations' payload:5:68: note: forward declaration of 'ConfigType'
struct __attribute__((annotate("$clingAutoload$ConfigType.hpp")))  ConfigType;
                                                                   ^
Error in <Load>: Could not declare TEmulatedTuple<ConfigType,string>

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f45ad4d0c3a in __GI___wait4 (pid=33425, stat_loc=stat_loc
entry=0x7fff23a485e8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f45ad4d0bfb in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7fff23a485e8, options=options
entry=0) at waitpid.c:38
#2  0x00007f45ad43ff67 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007f45adc84afe in TUnixSystem::StackTrace() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#4  0x00007f45adc81985 in TUnixSystem::DispatchSignals(ESignals) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#5  <signal handler called>
#6  0x00007f45a9283076 in TClingClassInfo::Property() const () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#7  0x00007f45a91ecb45 in TCling::SetClassInfo(TClass*, bool) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#8  0x00007f45adc22963 in TClass::SetUnloaded() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#9  0x00007f45adbc9b38 in ROOT::RemoveClass(char const*) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#10 0x00007f45adc3e1cf in ROOT::TGenericClassInfo::~TGenericClassInfo() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#11 0x00007f45ad4348a7 in __run_exit_handlers (status=0, listp=0x7f45ad5da718 <__exit_funcs>, run_list_atexit=run_list_atexit
entry=true, run_dtors=run_dtors
entry=true) at exit.c:108
#12 0x00007f45ad434a60 in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007f45ad41208a in __libc_start_main (main=0x55c185446100 <main>, argc=5, argv=0x7fff23a4b5a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff23a4b598) at ../csu/libc-start.c:342
#14 0x000055c18544868e in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f45a9283076 in TClingClassInfo::Property() const () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#7  0x00007f45a91ecb45 in TCling::SetClassInfo(TClass*, bool) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#8  0x00007f45adc22963 in TClass::SetUnloaded() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#9  0x00007f45adbc9b38 in ROOT::RemoveClass(char const*) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#10 0x00007f45adc3e1cf in ROOT::TGenericClassInfo::~TGenericClassInfo() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#11 0x00007f45ad4348a7 in __run_exit_handlers (status=0, listp=0x7f45ad5da718 <__exit_funcs>, run_list_atexit=run_list_atexit
entry=true, run_dtors=run_dtors
entry=true) at exit.c:108
#12 0x00007f45ad434a60 in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007f45ad41208a in __libc_start_main (main=0x55c185446100 <main>, argc=5, argv=0x7fff23a4b5a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff23a4b598) at ../csu/libc-start.c:342
#14 0x000055c18544868e in _start ()
===========================================================
```

### Expected behavior

The struct above, while weird, is valid C\+\+ code. It would be nice if we could write such objects into ROOT files.

### To Reproduce

Attached is a small reproducer, which works on Linux (and possibly macOS). (I didn't bother with setting up a CMake based build for Windows compatibility.)

[self-reference.zip](https://github.com/root-project/root/files/10786205/self-reference.zip)

It should be able to reproduce the issue with:

```
[bash][atspot01]:self-reference > make
genreflex SelfReferenceDict.hpp -o SelfReferenceDict.cpp --rootmap=libSelfReferenceDict.rootmap \
        --rootmap-lib=libSelfReferenceDict.so --library=libSelfReferenceDict.so --select=selection.xml
c++ -pthread -std=c++17 -m64 -I/software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/include -fPIC   -c -o SelfReferenceDict.o SelfReferenceDict.cpp
c++ -o libSelfReferenceDict.so -shared -m64 -L/software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -Wl,-rpath,/software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib -pthread -lm -ldl -rdynamic SelfReferenceDict.o
[bash][atspot01]:self-reference > ./test.py 
hadd Target file: output.root
hadd compression setting for all output: 1
hadd Source file 1: input1.root
hadd Source file 2: input2.root
hadd Target path: output.root:/
input_line_32:7:15: error: field has incomplete type 'ConfigType'
   ConfigType _0;
              ^
libSelfReferenceDict dictionary forward declarations' payload:5:68: note: forward declaration of 'ConfigType'
struct __attribute__((annotate("$clingAutoload$ConfigType.hpp")))  ConfigType;
                                                                   ^
Error in <Load>: Could not declare TEmulatedTuple<ConfigType,string>

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f052580ec3a in __GI___wait4 (pid=34047, stat_loc=stat_loc
entry=0x7ffc6b5a07e8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f052580ebfb in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffc6b5a07e8, options=options
entry=0) at waitpid.c:38
#2  0x00007f052577df67 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007f0525fc2afe in TUnixSystem::StackTrace() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#4  0x00007f0525fbf985 in TUnixSystem::DispatchSignals(ESignals) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#5  <signal handler called>
#6  0x00007f05215c1076 in TClingClassInfo::Property() const () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#7  0x00007f052152ab45 in TCling::SetClassInfo(TClass*, bool) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#8  0x00007f0525f60963 in TClass::SetUnloaded() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#9  0x00007f0525f07b38 in ROOT::RemoveClass(char const*) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#10 0x00007f0525f7c1cf in ROOT::TGenericClassInfo::~TGenericClassInfo() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#11 0x00007f05257728a7 in __run_exit_handlers (status=0, listp=0x7f0525918718 <__exit_funcs>, run_list_atexit=run_list_atexit
entry=true, run_dtors=run_dtors
entry=true) at exit.c:108
#12 0x00007f0525772a60 in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007f052575008a in __libc_start_main (main=0x556722a83100 <main>, argc=5, argv=0x7ffc6b5a37b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6b5a37a8) at ../csu/libc-start.c:342
#14 0x0000556722a8568e in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f05215c1076 in TClingClassInfo::Property() const () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#7  0x00007f052152ab45 in TCling::SetClassInfo(TClass*, bool) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCling.so
#8  0x00007f0525f60963 in TClass::SetUnloaded() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#9  0x00007f0525f07b38 in ROOT::RemoveClass(char const*) () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#10 0x00007f0525f7c1cf in ROOT::TGenericClassInfo::~TGenericClassInfo() () from /software/root/6.26.06/x86_64-ubuntu2004-gcc9-opt/lib/libCore.so
#11 0x00007f05257728a7 in __run_exit_handlers (status=0, listp=0x7f0525918718 <__exit_funcs>, run_list_atexit=run_list_atexit
entry=true, run_dtors=run_dtors
entry=true) at exit.c:108
#12 0x00007f0525772a60 in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007f052575008a in __libc_start_main (main=0x556722a83100 <main>, argc=5, argv=0x7ffc6b5a37b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6b5a37a8) at ../csu/libc-start.c:342
#14 0x0000556722a8568e in _start ()
===========================================================


[bash][atspot01]:self-reference >
```

### Setup

I tried various (but not too many) ROOT 6.2X/YY versions. They all failed to handle this example type correctly.

### Additional context

This is connected to (for ATLAS users only): https://its.cern.ch/jira/browse/ATLASG-2456

### PR DESCRIPTION
**Pull request by pcanal**
This fixes #12358.

When unloading a 'compiled' TClass, TClass sets the state of the TClass to the most information possible.  This usually means setting the ClassInfo if the interpreter information is still known about the class.  In the case of `std::tuple` is order to do that we need to generate code that depends on other types (that may also be unloaded), so skip that steps (which lead to 'compilation error' from the interpreter in the report cases (and a crash due to a couple of others issues solved also in this PR).

### CODE REVIEW

File: core/metacling/src/TClingClassInfo.cxx [hunk 1]
```diff
@@ -1262,7 +1262,7 @@ long TClingClassInfo::Property() const
 
    const clang::DeclContext *ctxt = GetDecl()->getDeclContext();
    clang::NamespaceDecl *std_ns =fInterp->getSema().getStdNamespace();
-   while (! ctxt->isTranslationUnit())  {
+   while (ctxt && ! ctxt->isTranslationUnit())  {
```
Comment (jblomer) [inline core/metacling/src/TClingClassInfo.cxx:1265]: (how) is this related to the patch in TCling.cxx?

**Review by Axel-Naumann — APPROVED** [review]

File: core/metacling/src/TClingClassInfo.cxx (hunk 1 above)
Comment (pcanal) [reply core/metacling/src/TClingClassInfo.cxx:1265]: While debug the invalid state, I discover this issue (which was the actual location of the crash).   `TClingClassInfo` was not able to handle the case where it was ask to describe the global name space (empty name and has a decl with 'no' decl context).  Apply this fix, prevented the crash but did not solve the underlying issue (that we inadvertently asked for the global namespace when dealing with `std::tuple` emulation).
