### PR TITLE
In TStreamerInfo::GenerateInfoForPair use a non-zero size enums.

### LINKED ISSUE #6726: TStreamerInfo::GenerateInfoForPair generates the wrong offset if an enum type is first.
As reported by CMSSW tests (for example: https://github.com/cms-sw/cmsdist/pull/6314#issuecomment-713547097) where the data appear odd/corrupted, there is an issue in TStreamerInfo::GenerateInfoForPair (which is almost always used for std::pair in the tip of v6.22 and master).

The problem is when calculating the offset of the second data member, TStreamerInfo::GenerateInfoForPair  uses (unwittingly, of course :) ), the value zero for the size of the enums.

In addition (see https://github.com/root-project/root/issues/6725), the TEnum size information is no yet available in rootpcm files. (i.e. a fix to this bug will work only for default size enums until #6725 is fixed).

### PR DESCRIPTION
**Pull request by pcanal**
This fix #6726

As reported by CMSSW tests (for example: cms-sw/cmsdist#6314 (comment)) where the data appear odd/corrupted, there is an issue in TStreamerInfo::GenerateInfoForPair (which is almost always used for std::pair in the tip of v6.22 and master).

The problem is when calculating the offset of the second data member, TStreamerInfo::GenerateInfoForPair uses (unwittingly, of course :) ), the value zero for the size of the enums.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@build just on ROOT-performance-centos8-multicore/default

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
Test will be in an upcoming roottest PR.

File: core/meta/inc/TEnum.h [hunk 1]
```diff
@@ -37,6 +37,7 @@ class TEnum : public TDictionary {
    ClassInfo_t *fInfo;          //!interpreter information, owned by TEnum
    TClass      *fClass;         //!owning class
    std::string  fQualName;      // fully qualified type name
+   EDataType    fUnderlyingType;// Type (size) used to store the enum in memory
```
Comment (Axel-Naumann) [inline core/meta/inc/TEnum.h:40]:
```suggestion
   EDataType    fUnderlyingType = kInt;// Type (size) used to store the enum in memory
```

File: core/meta/src/TEnum.cxx [hunk 2]
```diff
@@ -106,9 +106,7 @@ Long_t TEnum::Property() const
 
 EDataType TEnum::GetUnderlyingType() const
 {
-   if (fInfo)
-      return gInterpreter->ClassInfo_GetUnderlyingType(fInfo);
-   return kNumDataTypes;
+   return fUnderlyingType;
```
Comment (Axel-Naumann) [inline core/meta/src/TEnum.cxx:109]: Inline this function?

File: io/io/src/TStreamerInfo.cxx [hunk 3]
```diff
@@ -5589,15 +5589,18 @@ static TStreamerElement* R__CreateEmulatedElement(const char *dmName, const std:
       }
       TClass *clm = TClass::GetClass(dmType);
       if (!clm) {
-         if (TEnum::GetEnum(dmType, TEnum::kNone)) {
-            Int_t dtype = kInt_t;
-            return new TStreamerBasicType(dmName,dmTitle,offset,dtype,dmFull.c_str());
+         auto enumdesc = TEnum::GetEnum(dmType, TEnum::kNone);
+         if (enumdesc) {
```
Comment (Axel-Naumann) [inline io/io/src/TStreamerInfo.cxx:5593]:
```suggestion
         if (auto enumdesc = TEnum::GetEnum(dmType, TEnum::kNone)) {
```

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by Axel-Naumann — APPROVED** [review]

File: core/meta/inc/TEnum.h (hunk 1 above)
Comment (pcanal) [reply core/meta/inc/TEnum.h:40]: Humm .. other members are not going using this syntax yet.

File: core/meta/src/TEnum.cxx (hunk 2 above)
Comment (pcanal) [reply core/meta/src/TEnum.cxx:109]: Sure.

File: core/meta/inc/TEnum.h (hunk 1 above)
Comment (Axel-Naumann) [reply core/meta/inc/TEnum.h:40]: I still think it's the more robust syntax, even for gradual changes, and even if introduced gradually. E.g. it doesn't require the reviewer to check whether you have adapted all constructors ;-)

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
Test failures are unrelated.
