### PR TITLE
[meta] Correctly treat data member types containing functions

### LINKED ISSUE #18833: segfault in TStreamerInfo::Compile with type involving std::function
### Check duplicate issues.

- [x] Checked for duplicates

### Description

hi -

In the dev3 lcg nightly, i ran into an segfault running rootcling
in a debug build.

To reproduce, create x.h:

```
#include <functional>
#include <vector>

struct Foo {};
struct egammaMVACalibTool
{
  std::vector<std::vector<std::function<float(int, const Foo*)> > > m_funcs;
};
```

and sel.xml:

```
<lcgdict>
   <class name="egammaMVACalibTool" />
</lcgdict>
```

Then set up a recent dev3 dbg nightly (tested on May 20):

```
export LCG_ROOT=/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon
export LCG_CONFIG=x86_64-el9-gcc13-dbg
. $LCG_ROOT/ROOT/HEAD/$LCG_CONFIG/ROOT-env.sh
```

Then running rootcling crashes:

```
$ mkdir -p out
$ rootcling -f out/xout.cc  -reflex x.h sel.xml
 #0 0x00007fcb3ade22ab llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/ROOT/HEAD/x86_64-el9-gcc13-dbg/bin/../lib/libCling.so+0x5de22ab)
 #1 0x00007fcb3addf45b llvm::sys::RunSignalHandlers() (/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/ROOT/HEAD/x86_64-el9-gcc13-dbg/bin/../lib/libCling.so+0x5ddf45b)
 #2 0x00007fcb3addf585 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fcb3403e730 __restore_rt (/lib64/libc.so.6+0x3e730)
 #4 0x00007fcb3d779c13 TStreamerInfo::Compile() /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/io/src/TStreamerInfoActions.cxx:4237:27
 #5 0x00007fcb3d754d25 TStreamerInfo::Build(bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/io/src/TStreamerInfo.cxx:406:19
 #6 0x00007fcb34bfc964 TClass::GetStreamerInfoImpl(int, bool) const /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:4798:4
 #7 0x00007fcb34bfc6ed TClass::GetStreamerInfo(int, bool) const /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:4756:30
 #8 0x00007fcb34bfd40c TClass::InheritsFrom(TClass const*) const /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:5019:50
 #9 0x00007fcb34c0199d TClass::Property() const /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:6257:4
#10 0x00007fcb34becd60 TBuildRealData::Inspect(TClass*, char const*, char const*, void const*, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:942:44
#11 0x00007fcb35af6716 TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/metacling/src/TCling.cxx:2984:11
#12 0x00007fcb34bf4485 TClass::CallShowMembers(void const*, TMemberInspector&, bool) const /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:2331:17
#13 0x00007fcb34bf397d TClass::BuildRealData(void*, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:2185:9
#14 0x00007fcb34c341a4 TProtoClass::TProtoClass(TClass*) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TProtoClass.cxx:114:52
#15 0x00007fcb3d9bb962 CloseStreamerInfoROOTFile /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/rootpcm/src/rootclingIO.cxx:224:27
#16 0x00007fcb35a4b12e FinalizeStreamerInfoWriting(cling::Interpreter&, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:2644:8
#17 0x00007fcb35a4bbf3 GenerateFullDict(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, cling::Interpreter&, RScanner&, std::__cxx11::list<ROOT::TMetaUtils::RConstructorType, std::allocator<ROOT::TMetaUtils::RConstructorType>> const&, bool, bool, bool, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:2803:51
#18 0x00007fcb35a59b92 RootClingMain(int, char**, bool) /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:4964:43
#19 0x00007fcb35a5f4c6 ROOT_rootcling_Driver /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:6247:29
#20 0x0000000000401259 main /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/main/src/rootcling.cxx:43:51
#21 0x00007fcb340295d0 __libc_start_call_main (/lib64/libc.so.6+0x295d0)
#22 0x00007fcb34029680 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x29680)
#23 0x0000000000401105 _start (/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/ROOT/HEAD/x86_64-el9-gcc13-dbg/bin/rootcling+0x401105)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: rootcling -f out/xout.cc -reflex x.h sel.xml

 *** Break *** segmentation violation
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/ROOT/HEAD/x86_64-el9-gcc13-dbg/lib',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/xrootd/5.8.2/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/pycparser/2.22/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/cffi/1.14.6/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/wheel/0.37.1/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/llvmlite/0.44.0/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/numba/0.61.0/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/protobuf/4.25.4/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/meson/1.3.2/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/pip/23.3.1/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/setuptools/69.5.1/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/Python/3.11.9/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/cython/3.0.10/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/numpy/1.26.4/x86_64-el9-gcc13-dbg/lib/python3.11/site-packages',
    '/afs/cern.ch/user/s/ssnyder/public/MISSING-RPMS9/usr/lib/python3.9/site-packages',
    '/afs/cern.ch/user/s/ssnyder/public/MISSING-RPMS9/usr/lib64/python3.9/site-packages',
    '/afs/cern.ch/user/s/ssnyder/pyrex/Pyrex-0.9.8.5',
    '/afs/cern.ch/user/s/ssnyder/scripts/stgit',
    '',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/Python/3.11.9/x86_64-el9-gcc13-dbg/lib64/python39.zip',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/Python/3.11.9/x86_64-el9-gcc13-dbg/lib64/python3.9',
    '/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Mon/Python/3.11.9/x86_64-el9-gcc13-dbg/lib64/python3.9/lib-dynload',
```

If i run in a debugger:

```
(gdb) bt
#0  0x00007ffff7b79c13 in TStreamerInfo::Compile (this=0x2c38c10)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/io/src/TStreamerInfoActions.cxx:4237
#1  0x00007ffff7b54d25 in TStreamerInfo::Build (this=0x2c38c10, 
    isTransient=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/io/src/TStreamerInfo.cxx:405
#2  0x00007fffeeffc964 in TClass::GetStreamerInfoImpl (this=0x2818df0, 
    version=6, silent=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:4796
#3  0x00007fffeeffc6ed in TClass::GetStreamerInfo (this=0x2818df0, version=6, 
    isTransient=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:4756
#4  0x00007fffeeffd40c in TClass::InheritsFrom (this=0x2818df0, cl=0x1b31370)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:5019
#5  0x00007fffef00199d in TClass::Property (this=0x2818df0)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:6257
#6  0x00007fffeefecd60 in TBuildRealData::Inspect (this=0x7fffffff4e90, 
    cl=0x16d7600, pname=0x30ce500 "", mname=0x7fffffff4aa0 "m_funcs", add=0x0, 
    isTransient=true)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:942
#7  0x00007fffefef6716 in TCling::InspectMembers (this=0x4dac20, insp=..., 
    obj=0x0, cl=0x16d7600, isTransient=true)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/metacling/src/TCling.cxx:2982
#8  0x00007fffeeff4485 in TClass::CallShowMembers (this=0x16d7600, obj=0x0, 
    insp=..., isTransient=true)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:2330
#9  0x00007fffeeff397d in TClass::BuildRealData (this=0x16d7600, pointer=0x0, 
    isTransient=true)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TClass.cxx:2185
#10 0x00007fffef0341a4 in TProtoClass::TProtoClass (this=0x2813ee0, 
    cl=0x16d7600)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/meta/src/TProtoClass.cxx:110
#11 0x00007ffff7dbb962 in CloseStreamerInfoROOTFile (writeEmptyRootPCM=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/io/rootpcm/src/rootclingIO.cxx:224
#12 0x00007fffefe4b12e in FinalizeStreamerInfoWriting (interp=..., 
    writeEmptyRootPCM=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:2644

#13 0x00007fffefe4bbf3 in GenerateFullDict (dictStream=..., dictName=..., 
    interp=..., scan=..., ctorTypes=..., isSplit=false, isGenreflex=true, 
    isSelXML=true, writeEmptyRootPCM=false)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:2803
#14 0x00007fffefe59b92 in RootClingMain (argc=6, argv=0x7fffffff8e38, 
    isGenreflex=true)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:4964
#15 0x00007fffefe5f4c6 in ROOT_rootcling_Driver (argc=6, argv=0x7fffffff8e38, 
    config=...)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/core/dictgen/src/rootcling_impl.cxx:6247
#16 0x0000000000401259 in main (argc=6, argv=0x7fffffff8e38)
    at /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/sr--Type <RET> for more, q to quit, c to continue without paging--
c/ROOT/HEAD/main/src/rootcling.cxx:43
# line is:
#       fComp[fNdata].fType = element->GetType();
(gdb) p fComp
$1 = (TStreamerInfo::TCompInfo *) 0x0
(gdb) p fNdata
$2 = 0
(gdb) p fNslots
$3 = 0
(gdb) p ndata
$4 = 1
```

That's a bit strange, since earlier we had

```
   fNslots = ndata + ndata/2 + 1;
```

What's happening is that from this call:

```
      Int_t asize = element->GetSize();
```

we call TClass::GetClass for vector<function<float(int,const Foo*> >.

But note that the class name has been mangled --- we're missing the
closing paren.  The result is that in TClass::Init we trip the test here:

```
      TIter next( fgClassTypedefHash->GetListForObject(resolvedThis) );
      while ( TNameMapNode* htmp = static_cast<TNameMapNode*> (next()) ) {
         if (resolvedThis != htmp->String()) continue;
         oldcl = (TClass*)gROOT->GetListOfClasses()->FindObject(htmp->fOrigName); // gROOT->GetClass (htmp->fOrigName, kFALSE);
         if (oldcl && oldcl != this) {
            persistentRef = oldcl->fPersistentRef.exchange(nullptr);
            ForceReload (oldcl);
         }
      }
```

and call ForceReload, which ends up calling TStreamerInfo::Clear on the
object we're in the middle of using in Compile.

So the possibility of the TStreamerInfo changing underneath us while
running Compile is kind of janky, but the real issue is what happened
to the class name.

The name is correct in the TStreamerInfo itself:

```
(gdb) p this
$22 = (TStreamerInfo * const) 0x2ddf2e0
(gdb) p this->fName
$23 = {_vptr.TString = 0x7fffef733208 <vtable for TString+16>, fRep = {{
      fLong = {fCap = 49, fSize = 40, 
        fData = 0x283d480 "vector<function<float(int,const Foo*)> >"}, 
      fShort = {fSize = 49 '1', 
        fData = "\000\000\000(\000\000\000\200ԃ\002\000\000\000"}, fRaw = {
        fWords = {49, 40, 42194048, 0}}}}, static kNPOS = -1}
```

The mangling happens in the TClassEdit::ResolveTypedef call from the TStreamerElement
ctor.  This doesn't even try to deal with parentheses in class names.
It ends up trying to process as type names 'float(int' and 'const Foo*)'.
In particular, the calls in ResolveTypedefProcessType

```
   if (gInterpreterHelper->ExistingTypeCheck(type, typeresult)
       || gInterpreterHelper->GetPartiallyDesugaredNameWithScopeHandling(type, typeresult, false)) {
```

change 'Foo*)' to 'Foo*', which is where the closing paren gets lost.

If i change ResolveTypedef to try to treat () like <>, then the problem
goes away.  (I have tested this otherwise, though!)

```
diff --git a/core/foundation/src/TClassEdit.cxx b/core/foundation/src/TClassEdit.cxx
index e12cd8d4024..572a653532e 100644
--- a/core/foundation/src/TClassEdit.cxx
+++ b/core/foundation/src/TClassEdit.cxx
@@ -1652,6 +1652,7 @@ static void ResolveTypedefImpl(const char *tname,
             prevScope = cursor+1;
             break;
          }
+         case '(':
          case '<': {
             // push information on stack
             if (modified) {
@@ -1683,6 +1684,11 @@ static void ResolveTypedefImpl(const char *tname,
                if (modified) result += " >";
                return;
             }
+            if ( (cursor+1)<len && tname[cursor+1] == ')') {
+               ++cursor;
+               if (modified) result += ")";
+               return;
+            }
             if ( (cursor+1) >= len) {
                return;
             }
@@ -1699,7 +1705,7 @@ static void ResolveTypedefImpl(const char *tname,
             while ((cursor+1)<len && tname[cursor+1] == ' ') ++cursor;
 
             auto next = cursor+1;
-            if (strncmp(tname+next,"const",5) == 0 && ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == ']'))
+            if (strncmp(tname+next,"const",5) == 0 && ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == ')' || tname[next+5] == ']'))
             {
                // A first const after the type needs to be move in the front.
                if (!modified) {
@@ -1719,7 +1725,7 @@ static void ResolveTypedefImpl(const char *tname,
                cursor += 5;
                end_of_type = cursor+1;
                prevScope = end_of_type;
-               if ((next+5)==len || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == '[') {
+               if ((next+5)==len || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == ')' || tname[next+5] == '[') {
                   break;
                }
             } else if (next!=len && tname[next] != '*' && tname[next] != '&') {
@@ -1736,7 +1742,7 @@ static void ResolveTypedefImpl(const char *tname,
             // check and skip const (followed by *,&, ,) ... what about followed by ':','['?
             auto next = cursor+1;
             if (strncmp(tname+next,"const",5) == 0) {
-               if ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == '[') {
+               if ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == ')' || tname[next+5] == '[') {
                   next += 5;
                }
             }
@@ -1745,7 +1751,7 @@ static void ResolveTypedefImpl(const char *tname,
                ++next;
                // check and skip const (followed by *,&, ,) ... what about followed by ':','['?
                if (strncmp(tname+next,"const",5) == 0) {
-                  if ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>' || tname[next+5] == '[') {
+                  if ((next+5)==len || tname[next+5] == ' ' || tname[next+5] == '*' || tname[next+5] == '&' || tname[next+5] == ',' || tname[next+5] == '>'|| tname[next+5] == ')' || tname[next+5] == '[') {
                      next += 5;
                   }
                }
@@ -1765,13 +1771,15 @@ static void ResolveTypedefImpl(const char *tname,
             if (modified) result += ',';
             return;
          }
+         case ')':
          case '>': {
+            char c = tname[cursor];
             if (modified && prevScope) {
                result += std::string(tname+prevScope,(end_of_type == 0 ? cursor : end_of_type)-prevScope);
             }
             ResolveTypedefProcessType(tname,len,cursor,constprefix,start_of_type,end_of_type,mod_start_of_type,
                                       modified, result);
-            if (modified) result += '>';
+            if (modified) result += c;
             return;
          }
          default:
```

For the record, the ATLAS class that provoked this is here:
https://gitlab.cern.ch/atlas/athena/-/blob/main/Reconstruction/egamma/egammaMVACalib/egammaMVACalib/egammaMVACalibTool.h?ref_type=heads
(But the failure was seen only in the AnalysisBase build.)

### Reproducer

See above.

### ROOT version

lcg dev3

### Installation method

lcg

### Operating system

lxplus9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dpiparo**
This commit fixes #18833, by reverting 0f8670. 
It also honours #18842, without breaking DD4HEP.
Moreover it adds back a test and enhances it.

### CODE REVIEW

File: core/foundation/src/TClassEdit.cxx [hunk 1]
```diff
@@ -1652,7 +1652,15 @@ static void ResolveTypedefImpl(const char *tname,
             prevScope = cursor+1;
             break;
          }
+         case '(':
          case '<': {
+            // We move on in presence of function pointers, for example cases like
+            // pair<dd4hep::sim::Geant4Sensitive*,Geant4HitCollection*(*)(const std::string&,const std::string&,Geant4Sensitive*)>
+            // This honors #18842 without breaking #1833.
```
Comment (andresailer) [inline core/foundation/src/TClassEdit.cxx]:
```suggestion
            // This honors #18842 without breaking #18833.
```

Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: 🤦 thanks.

**Comment by dpiparo** [comment]
Thanks to @andresailer this was tested on top of all other packages in `dev3`. The builds were successful.

File: core/foundation/src/TClassEdit.cxx [hunk 2]
```diff
@@ -1652,7 +1652,15 @@ static void ResolveTypedefImpl(const char *tname,
...
          }
+         case '(':
          case '<': {
+            // We move on in presence of function pointers, for example cases like
+            // pair<dd4hep::sim::Geant4Sensitive*,Geant4HitCollection*(*)(const std::string&,const std::string&,Geant4Sensitive*)>
+            // This honors #18842 without breaking #18833.
+            if ('(' == tname[cursor] && '*' == tname[cursor + 1] && ')' == tname[cursor + 2]) {
+               cursor += 3;
+               break;
+            }
```
Comment (pcanal) [inline core/foundation/src/TClassEdit.cxx]:
```suggestion
            // We move on in presence of function pointers, for example cases like
            // pair<dd4hep::sim::Geant4Sensitive*,Geant4HitCollection*(*)(const std::string&,const std::string&,Geant4Sensitive*)>
            // This honors #18842 without breaking #18833.
            if ('*' == tname[cursor + 1] && ')' == tname[cursor + 2]) {
               cursor += 3;
               break;
            }
            // Intentional fall-through.
         case '<': {
```

File: core/foundation/src/TClassEdit.cxx [hunk 3]
```diff
@@ -1652,7 +1652,15 @@ static void ResolveTypedefImpl(const char *tname,
             prevScope = cursor+1;
             break;
          }
+         case '(':
          case '<': {
+            // We move on in presence of function pointers, for example cases like
+            // pair<dd4hep::sim::Geant4Sensitive*,Geant4HitCollection*(*)(const std::string&,const std::string&,Geant4Sensitive*)>
+            // This honors #18842 without breaking #18833.
+            if ('(' == tname[cursor] && '*' == tname[cursor + 1] && ')' == tname[cursor + 2]) {
```
Comment (pcanal) [inline core/foundation/src/TClassEdit.cxx]: I suspect that there we could also have some spaces before the star.  i.e. the user may have written/passed:
```
pair<dd4hep::sim::Geant4Sensitive*,Geant4HitCollection*(  *  )(const std::string&,const std::string&,Geant4Sensitive*)>
```

File: core/foundation/src/TClassEdit.cxx (hunk 2 above)
Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: That is may not be fully correct, as it would not take into account std::functions. For example, we would not be able to correctly close the round braces.

File: core/foundation/src/TClassEdit.cxx (hunk 3 above)
Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: I do not thing that parsing white spaces will be a problem. Could you please make an example of a type for which the current parsing fails?

Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: For example, at the prompt:
```
auto cl="pair<TAttMarker*,TGraph*(  *  )(const std::string&,const std::string&,TH1F*)>";
auto c=TClass::GetClass(cl);
cout << c->GetName() << endl;
// (const char *) "pair<TAttMarker*,TGraph*(*)(const std::string&,const std::string&,TH1F*)>"
```

Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: and
```
root [0] auto cl="pair<TAttMarker*,TGraphErrors*(        *  )(const std::string&,const std::string&,TH1F*)>"
(const char *) "pair<TAttMarker*,TGraphErrors*(        *  )(const std::string&,const std::string&,TH1F*)>"
root [1] string n;TClassEdit::GetNormalizedName(n,cl)
root [2] n
(std::string &) "pair<TAttMarker*,TGraphErrors*(*)(const std::string&,const std::string&,TH1F*)>"
```

Comment (pcanal) [reply core/foundation/src/TClassEdit.cxx]: It is likely this is sufficient is fine.  However, this might  fail:
```
TClassEdit::ResolveTypedef("pair<TAttMarker*,TGraph*(  *  )(const std::string&,const std::string&,TH1F*)>");
```

Comment (dpiparo) [reply core/foundation/src/TClassEdit.cxx]: you are right. I am preparing an improvement of the changes, I did not think about that particular code path. It's a very nice one-line test, btw.

File: roottest/root/meta/rootcling/CMakeLists.txt [hunk 4]
```diff
@@ -28,3 +28,7 @@ ROOTTEST_ADD_TEST(selectUnion
 ROOTTEST_ADD_TEST(ROOT10798
                   COMMAND ${ROOT_rootcling_CMD} -f ROOT10798Dict.cxx ${CMAKE_CURRENT_SOURCE_DIR}/ROOT10798LinkDef.h)
 
+# Issue #18833
+ROOTTEST_ADD_TEST(streamerInfoStdFunction
```
Comment (pcanal) [inline roottest/root/meta/rootcling/CMakeLists.txt:33]: Should we add a test that the dictionary can be loaded and has reasonable content?

Comment (dpiparo) [reply roottest/root/meta/rootcling/CMakeLists.txt:33]: good point.

**Review by pcanal — APPROVED** [review]
