### PR TITLE
[math] Fix Delaunay2D interpolation for input degenerate points

### LINKED ISSUE #10266: TGraph2D interpolation hangs for degenerate points
When points in one coordinate are degenerate, i.e. all have the same value, the interpolation algorithm used to find the Delauney triangles can hang for ever as reported in 
https://root-forum.cern.ch/t/tgraph2d-setmaximum-seems-to-hang-forever/49392

A protection for this case should be added in TGraph2D

### PR DESCRIPTION
**Pull request by lmoneta**
When xmin=xmax or ymin=ymax the transformed min max are Nan and this causes the
routine to find the triangles to hang forever.
Now in this case and when also no trisangles are found the default zero value is always return

Update also the documentation of the class and of TGraphDelaunay2D.

This Pull request fixes #10266

### CODE REVIEW

File: hist/hist/src/TGraphDelaunay2D.cxx [hunk 1]
```diff
@@ -17,13 +17,17 @@ ClassImp(TGraphDelaunay2D);
...
-This software cannot be guaranteed to work under all circumstances. They
-were originally written to work with a few hundred points in an XY space
-with similar X and Y ranges.
+TGraphDelaunay2D generates a Delaunay triangulation of a TGraph2D.
+The algorithm used for finding the triangles is based on on
+**Triangle**, a two-dimensional quality mesh generator and
+Delaunay triangulator from Jonathan Richard Shewchuk.
+See [http://www.cs.cmu.edu/~quake/triangle.html]
+The ROOT::Math::Delaunay2D class provides a wrapper for using
+the **Trinagle** library.
```
Comment (couet) [inline hist/hist/src/TGraphDelaunay2D.cxx:26]: Typo: it should be "Triangle"

File: hist/hist/src/TGraphDelaunay2D.cxx [hunk 2]
```diff
@@ -17,13 +17,17 @@ ClassImp(TGraphDelaunay2D);
...
+
+This implementation provides large improvements in terms of computational performances
+compared to the legacy one available in TGraphDelaunay, and it is by default
+used in TGraph2D.
```
Comment (couet) [inline hist/hist/src/TGraphDelaunay2D.cxx:30]: Should we tell the legacy one can be accessed via the "old" option ?

**Review by couet — APPROVED** [review]
LGMT. 
Only one typo to be fixed.

File: hist/hist/src/TGraphDelaunay2D.cxx (hunk 2 above)
Comment (lmoneta) [reply hist/hist/src/TGraphDelaunay2D.cxx:30]: Yes, good point! I see the option "old" is available for TGraph2D::GetHistogram and also for TGraph2D::Paint(), this means that is then also available for TGraph2D::Draw, correct ?

Comment (couet) [reply hist/hist/src/TGraphDelaunay2D.cxx:30]: yes
