### PR TITLE
[math] Add virtual destructor to Fitter and fix an issue for PyROOT

### LINKED ISSUE #12391: [PyROOT] TypeError: no python-side overrides supported (failed to compile the dispatcher code)
- [X] Checked for duplicates

### Describe the bug

First seen on the forum (see [here](https://root-forum.cern.ch/t/typeerror-no-python-side-overrides-supported-failed-to-compile-the-dispatcher-code/53198)).  The Python code below
```python
import ROOT

class Fitter(ROOT.Fit.Fitter):
    def __init__(self):
        super().__init__()
```
triggers the following error
```
/tmp/ipykernel_2130/1942954617.py:1: RuntimeWarning: class "ROOT::Fit::Fitter" has no virtual destructor
  class Fitter(ROOT.Fit.Fitter):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 class Fitter(ROOT.Fit.Fitter):
      2     def __init__(self):
      3         super().__init__()

TypeError: no python-side overrides supported (failed to compile the dispatcher code)
input_line_54:41:12: error: cannot initialize return object of type 'ROOT::Math::IBaseFunctionMultiDimTempl<double> *' with an rvalue of type 'const ROOT::Math::IMultiGenFunction *' (aka 'const IBaseFunctionMultiDimTempl<double> *')
    return Fitter::ObjFunction();
```

### Setup
1. ROOT version: fails both in 6.29/01 (Python 3.11), and 6.26/10 (Python 3.10)
2. Operating system: Linux x86_64

### Additional context
The issue has been tracked down to the introduction of the `Fitter::ObjFunction()` in [commit 9d322a6a38fca106d0e5b6064bd09c8c6dbb979a](https://github.com/root-project/root/commit/9d322a6a38fca106d0e5b6064bd09c8c6dbb979a).

### PR DESCRIPTION
**Pull request by lmoneta**
When constructing in Python a derived class from Fitter an error occurred caused probably of a not understanding a typedef. See issue #12391

This PR fixes #12391

### CODE REVIEW

**Comment by guitargeek** [comment]
Hi! I'm not sure if this is a good idea. The ROOT Fitter is not meant to be inherited from in C++, right? It has no virtual functions, and nowhere do we inherit from it.

I'm worried that encouraging users to inherit from the Fitter like this will cause further complications, so maybe it's good that it doesn't work? What is the benefit of this?

If you think this is really necessary, maybe better add a comment to the destructor explaining why it needs to be `virtual` for PyROOT, because when reading the C++ code it's not clear why it should be there and there is the risk that future developers interpret it as an accidentally added keyword and remove it.

**Review by guitargeek — APPROVED** [review]
LGTM, thanks for the clarification of the forum! I thought the missing `virtual` caused an error in PyROOT, not a warning :+1:

I would maybe add some comments inline why the `virtual` and especially the written-out type is required so it is not accidentally changed again.

File: math/mathcore/inc/Fit/Fitter.h [hunk 1]
```diff
@@ -521,7 +521,8 @@ class Fitter {
    /// return pointer to used objective function
    /// if using an external one use external, otherwise use the one stored
    /// in shared ptr
-   const ROOT::Math::IMultiGenFunction * ObjFunction() const {
+   const ROOT::Math::IBaseFunctionMultiDimTempl<double> * ObjFunction() const {
+   //const ROOT::Math::IMultiGenFunction * ObjFunction() const {
```
Comment (jalopezg-git) [inline math/mathcore/inc/Fit/Fitter.h:525]: Thanks for working on this, @lmoneta!  Is this worth keeping as a comment? -- I would delete otherwise.
