### PR TITLE
[skip-ci][DF] Add example how to correctly vs incorrectly run event-loop.

### LINKED ISSUE #13440: [DF] Add a warning if the second event loop on the same RDataFrame is started
### Explain what you would like to see improved and how.

Sometimes the users unintentionally start a new event loop. This can cause issues in the MT mode, as lack of order in processing entries may impact the results. This is motivated by the issue discussed on the forum: https://root-forum.cern.ch/t/unstable-results-when-enabling-mt-and-filling-a-thnd-histogram-using-take/

### ROOT version

up to 6.28.04

### Installation method

built from source

### Operating system

MacOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by martamaja10**
Adding a very simple example (as we were showing in the student course) to showcase the difference between running the event loop vs running it multiple times. 

This PR fixes #13440.

### CODE REVIEW

File: tree/dataframe/src/RDataFrame.cxx [hunk 1]
```diff
@@ -456,6 +456,40 @@ executed at the moment they are called, but they are **lazy**, i.e. delayed unti
 accessed through the smart pointer. At that time, the event loop is triggered and *all* results are produced
 simultaneously.
 
+For yet another example of the difference between the correct and incorrect running of the event-loop, see the following
```
Comment (vepadulano) [inline tree/dataframe/src/RDataFrame.cxx:459]: I would add a paragraph title here, maybe like `How to properly exploit RDataFrame lazyness` or something like that

File: tree/dataframe/src/RDataFrame.cxx [hunk 2]
```diff
@@ -456,6 +456,40 @@ executed at the moment they are called, but they are **lazy**, i.e. delayed unti
...
+two code snippets. We assume our ROOT file has branches a, b and c.
+
+The correct way - the dataset is only processed once.
+~~~{.cpp}
```
Comment (vepadulano) [inline tree/dataframe/src/RDataFrame.cxx:463]: Thanks for the example, could I ask you to also provide the Python equivalent and write it before the C++, or maybe just the Python version?

**Review by vepadulano — CHANGES_REQUESTED** [review]
Thanks this is nice, some minor comments

File: tree/dataframe/src/RDataFrame.cxx [hunk 3]
```diff
@@ -456,6 +456,42 @@ executed at the moment they are called, but they are **lazy**, i.e. delayed unti
...
+
+h_a = df_correct.Histo1D("a")
+h_b = df_correct.Histo1D("b")
+h_c = df_correct.Histo1D("c")
+
+h_a_val = h_a.GetValue()
+h_b_val = h_b.GetValue()
+h_c_val = h_c.GetValue()
+
+print(f"How many times was the data set processed? {df_wrong.GetNRuns()} time/s.") # The answer will be 1 time.
```
Comment (vepadulano) [inline tree/dataframe/src/RDataFrame.cxx:476]: Sorry I didn't notice before, I wouldn't use `time/s` as it may be read as "time per second" (at least that was my immediate reaction, might be biased). Maybe we can compute the extra "s" token by checking the number returned by `GetNRuns()`, or simply write `time(s)`.

**Review by vepadulano — COMMENTED** [review]
Sorry one last comment and it's good to go

File: tree/dataframe/src/RDataFrame.cxx (hunk 3 above)
Comment (martamaja10) [reply tree/dataframe/src/RDataFrame.cxx:476]: fair enough, it does look a bit funny indeed, I think for this example it can be just as simple as time for one case and times for the other case

**Review by vepadulano — APPROVED** [review]
Thank you!
