### PR TITLE
[ntuple] clarify diamond inheritance

### LINKED ISSUE #15048: [ntuple] Handling of virtual inheritance broken
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Reading back objects with virtual diamond inheritance does not work correctly. RNTuple should forbid virtual inheritance.

Diamond inheritance without virtual inheritance works as expected.

Follow-up of https://github.com/root-project/root/pull/14822#discussion_r1522390235

### Reproducer

tbd

### ROOT version

master

### Installation method

From sources

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jblomer**
# This Pull request:

Adds a unit test for regular (non-virtual) inheritance. Forbids virtual inheritance (and tests for it).

## Changes or fixes:

Fixes #15048

## Checklist:

- [X] tested changes locally
- [X] updated the docs (if necessary)

### CODE REVIEW

File: tree/ntuple/v7/test/CustomStruct.hxx [hunk 1]
```diff
@@ -218,4 +218,32 @@ struct Unsupported {
...
+};
+
+struct DiamondC : public DiamondA {
+   float c = 0.0;
+};
+
+struct DiamondD : public DiamondB, public DiamondC {
+   float d = 0.0;
+};
+
```
Comment (pcanal) [inline tree/ntuple/v7/test/CustomStruct.hxx:248]: Vaguely more 'accurate' names:
```suggestion
struct BaseA {
   float a = 0.0;
};

struct DiamondVirtualB : virtual public BaseA {
   float b = 0.0;
};

struct DiamondVirtualC : virtual public BaseA {
   float c = 0.0;
};

struct DiamondVirtualD : public DiamondVirtualB, public DiamondVirtualC {
   float d = 0.0;
};

struct DuplicateBaseB : public BaseA {
   float b = 0.0;
};

struct DuplicateBaseC : public BaseA {
   float c = 0.0;
};

struct DuplicateBaseD : public DuplicateBaseB, public DuplicateBaseC {
   float d = 0.0;
};
```
