### PR TITLE
[hist] TH1::GetCumulative: fix error setting

### LINKED ISSUE #11947: [hist] TH1::GetCumulative doesn't set the bin error for the generated histogram, but change that of the original hist instead
- [X] Checked for duplicates

### Describe the bug

When calling the `TH1::GetCumulative()` method, it should generate a cumulative histogram and with its error (`fSumw2`) set, and should not change the original histogram. However, it turns out that it doesn't set the error for the new histogram, but (incorrectly) modify the bin error of the original histogram into the value that should have been assigned to the generated histogram.

### Expected behavior

The `TH1::GetCumulative()` method generates the corresponding cumulative histogram with `fSumw2` set (when the original histogram has its `fSumw2` set) while keeping the original histogram intact.

### To Reproduce

In the ROOT interactive prompt,
```
root [0] TH1 *h1 = new TH1D("h1", "h1", 8, 0., 8.);
root [1] for (int i=0; i<8; ++i) h1->Fill(0.5 + i, 0.5);
root [2] for (int i=0; i<8; ++i) h1->Fill(0.5 + i, 0.5);
root [3] h1->GetBinError(1)
(double) 0.70710678
root [4] h1->GetBinError(2)
(double) 0.70710678
root [5] sqrt(2) / 2
(double) 0.70710678
root [6] TH1 *h1Cumu = h1->GetCumulative(false);
root [7] h1Cumu->GetBinError(1)
(double) 0.0000000
root [8] h1Cumu->GetBinError(2)
(double) 0.0000000
root [9] h1->GetBinError(1)
(double) 2.0000000
root [10] h1->GetBinError(2)
(double) 1.8708287
```

### Setup

1. ROOT Version: 6.26/08
2. Built for linuxx8664gcc (NixOS) on Jan 01 1980, 00:00:00
3. From [Nixpkgs](https://github.com/NixOS/nixpkgs)

### Additional context

The error may be caused by 
https://github.com/root-project/root/blob/master/hist/hist/src/TH1.cxx#L2619
and
https://github.com/root-project/root/blob/master/hist/hist/src/TH1.cxx#L2633
where the cumulative error is assigned to the `fSumw2` of the original histogram.

### PR DESCRIPTION
**Pull request by ShamrockLee**
# This Pull request:

## Changes or fixes:

This PR fixes the `TH1::GetCumulative()` method by assigning the cumulative error to the newly generated histogram instead of the original one.

## Checklist:

- [X] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #11947

### CODE REVIEW

File: hist/hist/src/TH1.cxx [hunk 1]
```diff
@@ -2616,7 +2616,7 @@ TH1 *TH1::GetCumulative(Bool_t forward, const char* suffix) const
                hintegrated->AddBinContent(bin, sum);
                if (fSumw2.fN) {
                   esum += GetBinErrorSqUnchecked(bin);
-                  fSumw2.fArray[bin] = esum;
+                  hintegrated->GetSumw2()->SetAt(esum, bin);
```
Comment (lmoneta) [inline hist/hist/src/TH1.cxx:2619]: It is maybe shorter and more efficient to write: 
```
hintegrated->fSumw2.fArray[bin] = esum;
```

**Review by lmoneta — APPROVED** [review]
Thank you for this fix. I agree this was a bug,  great you have found it. 
Just a small comment for avoid using virtual functions (TArray::SetAt) for better efficiency

File: hist/hist/src/TH1.cxx (hunk 1 above)
Comment (ShamrockLee) [reply hist/hist/src/TH1.cxx:2619]: Cool! But why are these protective attributes of a non-self TH1 instance accessible here?

Comment (ShamrockLee) [reply hist/hist/src/TH1.cxx]: > It is maybe shorter and more efficient to write:
> 
> ```
> hintegrated->fSumw2.fArray[bin] = esum;
> ```

Updated and tested.

**Review by lmoneta — APPROVED** [review]

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by ShamrockLee** [comment]
Is there something I need to fix?

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you for this fix!
