### PR TITLE
[RF] Correct RooPoisson integral if integrated from a > 0 to infinity

### LINKED ISSUE #10868: [RF] Wrong integral for RooPoisson if integrated from a > 0 to infinity
### Describe the bug

The analytical integral of the RooPoisson is implemented wrongly for the case where the boundaries are `0 < a < 1e30` and `b >= 1e30`.

### Expected behavior

The integral should be correct.

### To Reproduce

The wrong integral can be reproduced with this code snippet.

```C++
void testPoissonIntegral() {

   const double mu = 100;
   const double inf = std::numeric_limits<double>::max();

   // 1. Should be 1 because the probability to have x greater than 100000 is
   // basically zero.
   std::cout << getPoissonIntegral(0, 100000, mu) << std::endl;

   // 2. Should be around 0.5, as the range of x is from the mean of the
   // Poisson to basically infinity.
   std::cout << getPoissonIntegral(100, 100000, mu) << std::endl;

   // 3. Should be the same as the first integral
   std::cout << getPoissonIntegral(0, inf, mu) << std::endl;

   // 3. Should be the same as the second integral but it isn't!
   std::cout << getPoissonIntegral(100, inf, mu) << std::endl;
}
```

### Setup

Any setup will do.

### Additional context

The problem is most likely that in the analytical integration code for the RooPoisson, it is hardcoded to return 1.0 if the upper boundary is infinite:
https://github.com/root-project/root/blob/master/roofit/roofit/src/RooPoisson.cxx#L102

An addition code branch is required for the case where the upper bound is infinite and the lower bound greater than zero.

### PR DESCRIPTION
**Pull request by guitargeek**
In the RooPoisson integration code, it is hardcoded to return 1.0 if the upper boundary is infinite. But this should only be done if the lower boundary is not greater than zero.

Closes #10868.

### CODE REVIEW

File: roofit/roofit/src/RooPoisson.cxx [hunk 1]
```diff
@@ -99,7 +99,7 @@ double RooPoisson::analyticalIntegral(Int_t code, const char* rangeName) const
     if (xmax < 0. || xmax < xmin) {
       return 0.;
     }
-    if (!x.hasMax() || RooNumber::isInfinite(xmax)) {
+    if ((!x.hasMax() || RooNumber::isInfinite(xmax)) && xmin <= 0.0) {
```
Comment (lmoneta) [inline roofit/roofit/src/RooPoisson.cxx:102]: Maybe we could use a cutoff (e.g. 100)  like : 
`xmin  < max( mu -  100*sqrt(mu),0) && xmax > mu + 100 * sqrt(mu)`

**Review by lmoneta — APPROVED** [review]
LGTM!
Just a small comment that could be useful to speedup integrals in some cases

File: roofit/roofit/src/RooPoisson.cxx (hunk 1 above)
Comment (guitargeek) [reply roofit/roofit/src/RooPoisson.cxx:102]: Good idea! I will try this out
