### PR TITLE
TTree::GetEntry() entry parameter default value fix

### LINKED ISSUE #8300: TTree::GetEntry should not take the entry number as default parameter
### Explain what you would like to see improved

In:

https://root.cern.ch/doc/master/classTTree.html#a9fc48df5560fce1a2d63ecd1ac5b40cb

the entry number is zero by default, that should not be a default parameter. If I wanted to get the zeroth entry, I would just get the zeroth entry. On the other hand, If the user forgets to put the entry there, the compiler will be fine with it and we won't find the mistake until we check the outputs that will all correspond to the zeroth entry.

### PR DESCRIPTION
**Pull request by AdvaitDhingra**
# This Pull request:

## Changes or fixes:

I fixed the issue, where if no value for entry was provided, it would automatically set to 0. This has the result that the user has many outputs that correspond to the 0th entry.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #8300

### CODE REVIEW

**Comment by eguiraud** [comment]
Backward-incompatible. @pcanal leaving it up as a reminder to decide what to do with #8300

File: tree/tree/src/TTree.cxx [hunk 1]
```diff
@@ -5581,11 +5581,13 @@ Long64_t TTree::GetEntriesFriend() const
 
 Int_t TTree::GetEntry(Long64_t entry, Int_t getall)
 {
-
    // We already have been visited while recursively looking
    // through the friends tree, let return
    if (kGetEntry & fFriendLockStatus) return 0;
-
+   if (!entry) {
```
Comment (pcanal) [inline tree/tree/src/TTree.cxx:5587]: zero is a valid value!!!  It is the 'first' entry per se.

File: tree/tree/inc/TTree.h [hunk 2]
```diff
@@ -460,7 +460,7 @@ class TTree : public TNamed, public TAttLine, public TAttFill, public TAttMarker
    virtual Long64_t        GetEntriesFast() const   { return fEntries; }
    virtual Long64_t        GetEntriesFriend() const;
    virtual Long64_t        GetEstimate() const { return fEstimate; }
-   virtual Int_t           GetEntry(Long64_t entry = 0, Int_t getall = 0);
+   virtual Int_t           GetEntry(Long64_t entry, Int_t getall = 0);
            Int_t           GetEvent(Long64_t entry = 0, Int_t getall = 0) { return GetEntry(entry, getall); }
```
Comment (pcanal) [inline tree/tree/inc/TTree.h:464]: If we update `GetEntry` we should probably also update `GetEvent`

File: tree/tree/src/TTree.cxx (hunk 1 above)
Comment (AdvaitDhingra) [reply tree/tree/src/TTree.cxx:5587]: But doesn't `!entry` mean that no value for entry was provided?

File: tree/tree/inc/TTree.h (hunk 2 above)
Comment (AdvaitDhingra) [reply tree/tree/inc/TTree.h:464]: Okay. Does that mean I should reopen this PR?

File: tree/tree/src/TTree.cxx (hunk 1 above)
Comment (pcanal) [reply tree/tree/src/TTree.cxx:5587]: Nope.  The user can provide 0 explicitly and there is no way of seeing the difference.  And since 0 is the first entry, it will be almost always being passed the first time `GetEntry` is called :)

**Comment by AdvaitDhingra** [comment]
@pcanal I have thought of a "solution". If we remove the default value, set `event` to 0 in the method itself and simply warn the user that he/she has not provided a value for `event`, the user will know and other classes that rely on the default value of 0 still work.

**Comment by AdvaitDhingra** [comment]
> I am not sure how this would work. Can you make a concrete (code) proposal?

I had something like this in mind:

So the declarations in TTree.h remain unchanged, i.e. 0 is the default value for ´entry´

However, by adding this line to both GetEntry() and GetEvent() in TTree.cxx:

´´´
if (!event) Warning("TTree::GetEvent", "No value for event providied. Set to default value 0");
´´´
The user gets notified if he forgets to provide a value for ´event but other classes that rely on ´event´ being the default value of 0 work as they did before. Would this work?

**Comment by pcanal** [comment]
Well, wouldn't that issue a spurrious/wrong warning in the following case (i.e the normal usage):
```
for(Long64_t entry = 0; entry < tree->GetEntriesFast(); ++entry)
{
     tree->GetEntry(entry);
}
```
[Slightly related question, did you run any of the test after successfully compiling?]

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default

**Comment by AdvaitDhingra** [comment]
> Well, wouldn't that issue a spurrious/wrong warning in the following case (i.e the normal usage):
> 
> ```
> for(Long64_t entry = 0; entry < tree->GetEntriesFast(); ++entry)
> {
>      tree->GetEntry(entry);
> }
> ```
> 
> [Slightly related question, did you run any of the test after successfully compiling?]

Actually I had some triuble compiling in my usual manor. But when I tried to compile upstream/master it also failed so the failure didn't seem to originate from my chnages. I wasnt sure what to do so I was hoping I could see what phsft-bot has to say before I do anything.

This is how I build:

```
mkdir rootbuild rootinstall 
cd rootbuild
cmake -DCMAKE_INSTALL_PREFIX=../rootinstall/ ../root/
cmake --build . -- -j4
cd bin
source thisroot.sh
root
```

**Comment by AdvaitDhingra** [comment]
> Well, wouldn't that issue a spurrious/wrong warning in the following case (i.e the normal usage):
> 
> ```
> for(Long64_t entry = 0; entry < tree->GetEntriesFast(); ++entry)
> {
>      tree->GetEntry(entry);
> }
> ```
> 
> [Slightly related question, did you run any of the test after successfully compiling?]

But here the user would be providin a value for `entry` that is 0. The warning would only trigger if entry is not provided at all, i.e. `!entry` is true.

**Comment by eguiraud** [comment]
`!entry == true` if `entry == 0`: `0` is fals-y in C++

**Comment by AdvaitDhingra** [comment]
> `!entry == true` if `entry == 0`: `0` is fals-y in C++

Ohh I didn't know that. Then maybe one could simply check if entry is undefined. Or does that cause the same error?

**Comment by AdvaitDhingra** [comment]
This is what I got when I built upstream/master as well

**Comment by AdvaitDhingra** [comment]
Is this because 0 is no longer the default value?

**Comment by AdvaitDhingra** [comment]
> There is no "undefined" value for an integer variable. The test failures are because with these changes we are printing errors that were not printed before.

Ah ok

**Review by pcanal — CHANGES_REQUESTED** [review]
Please remove the `if (!entry)` test and associated warning.
Please also change the signature of GetEvent.

**Comment by AdvaitDhingra** [comment]
> Please remove the `if (!entry)` test and associated warning.
> Please also change the signature of GetEvent.

okay. But I did some internet research and couldn't find a way to check if no entry parameter was given by the user without also raising the error when the user enters 0 (since !entry == true if entry == 0)

**Comment by pcanal** [comment]
If we wanted to catch those case, we would just add a new overload
```
Int_t GetEntry() { 
   Warning("TTree::GetEvent", "No value for event providied. Set to default value 0");
   return GetEntry(0);
}
```
but I don't think it is necessary/needed.

File: tree/tree/inc/TTree.h (hunk 2 above)
Comment (pcanal) [inline tree/tree/inc/TTree.h:464]:
```suggestion
           Int_t           GetEvent(Long64_t entry, Int_t getall = 0) { return GetEntry(entry, getall); }
```

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by AdvaitDhingra** [comment]
@pcanal if we can't detect if the event parameter was provided by the user, how can we fix this issue? I can't think of another way 😅

**Comment by AdvaitDhingra** [comment]
Build seems to have succeeded.

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
Thank you very much!

**Comment by AdvaitDhingra** [comment]
> Thank you very much!

Thank you for your help. I learn something new with every PR :D

**Comment by pcanal** [comment]
Final note:  In the commits left on the branch there was a "merge" commit, we want to avoid them.  When updating your branch with the content of the master branch, please use 'git rebase' rather than `git merge`.  Also we tend to prefer to simplify the history by keeping only the effective commits. [For example, in this case, you could (have done)/do `git rebase -i` to remove the commit that was reverse and its reversal :)].

For this PR, I effectively handled these changes by doing a "merge and squash" but this works out only for PR that have one effective commit (the case here).

**Comment by AdvaitDhingra** [comment]
> Final note: In the commits left on the branch there was a "merge" commit, we want to avoid them. When updating your branch with the content of the master branch, please use 'git rebase' rather than `git merge`. Also we tend to prefer to simplify the history by keeping only the effective commits. [For example, in this case, you could (have done)/do `git rebase -i` to remove the commit that was reverse and its reversal :)].
> 
> For this PR, I effectively handled these changes by doing a "merge and squash" but this works out only for PR that have one effective commit (the case here).

Ah ok. I recently learned what rebase -i is, so I'll use that next time. Thanks for the tip

**Comment by Axel-Naumann** [comment]
This is a breaking change (we want it, it's still a breaking change). Could you add a note in `README/ReleaseNotes/v626/index.md`, section `## Deprecation and Removal` (which you could - please - rename to `## Deprecation, Removal, Backward Incompatibilities`

**Comment by AdvaitDhingra** [comment]
> @AdvaitDhingra This is a breaking change (we want it, it's still a breaking change). Could you add a note in `README/ReleaseNotes/v626/index.md`, section `## Deprecation and Removal` (which you could - please - rename to `## Deprecation, Removal, Backward Incompatibilities`

Would that require a seprate PR?

**Comment by Axel-Naumann** [comment]
> Would that require a separate PR?

Yes, please!

**Comment by AdvaitDhingra** [comment]
> > Would that require a separate PR?
> 
> Yes, please!

Okay I'll get started :D

**Comment by AdvaitDhingra** [comment]
@Axel-Naumann  can I also add my name to the list of contributors?

**Comment by Axel-Naumann** [comment]
> @Axel-Naumann can I also add my name to the list of contributors?

We really appreciate small fixes like those, but we generally only call out the authors of larger / continuous contributions. We'll think of another way to show our appreciation! :-)

**Comment by AdvaitDhingra** [comment]
> > @Axel-Naumann can I also add my name to the list of contributors?
> 
> We really appreciate small fixes like those, but we generally only call out the authors of larger / continuous contributions. We'll think of another way to show our appreciation! :-)

Ah ok, that makes sense 😅. I'll make the PR now.
