### PR TITLE
Respect the user-provided number of entries to be displayed

### LINKED ISSUE #11390: Display does not respect parameters if another operation is booked before printing
### Describe the bug

Apparently calling `Display` with some extra parameter like `nRows` is not respected if before calling `Print` one adds any other operation to the graph.

### To Reproduce
```cpp
#include <ROOT/RDataFrame.hxx>
#include <TString.h>
#include <string>
#include <vector>
#include <memory>
void write_tree()
{
    int x{};
    TString s{};

    TFile file{"dataset.root", "recreate"};
    TTree tree{"events", "events"};
    tree.Branch("nJets", &x, "nJets/I");
    tree.Branch("systName", &s);

    std::vector<std::string> values{"nominal", "up", "down"};

    for (int i = 0; i < 3; i++)
    {
        x = i + 1;
        s.Replace(0, s.Length(), values[i]);
        tree.Fill();
    }

    tree.Write();
}

void read_tree()
{
    TFile file{"dataset.root", "read"};
    std::unique_ptr<TTree> tree{file.Get<TTree>("events")};
    tree->Scan("*");
}

void analyze()
{
    ROOT::RDataFrame df{"events", "dataset.root"};

    // Book display
    auto disp = df.Display("systName", 1);

    // Do anything else
    df.Count().GetValue();

    // The display doesn't respect the original parameters
    // Prints all 3 rows whereas it should print only one
    disp->Print();
}

int main()
{
    write_tree();
    read_tree();
    analyze();
}
```

### Additional context
Fedora 36
ROOT 6.26/06 from conda

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #11390

Improves the workflow of `DisplayHelper::Exec` as follows:
1. We always check whether there are entries to be displayed with `RDisplay::HasNext`. If so, add one row to the display object
2. If no more entries should be displayed, signal this node has finished its job. Make sure the call to `StopProcessing` is done only once with a boolean flag, to avoid early stop of the execution due to more stop signals than the children who actually have finished their job.

### CODE REVIEW

File: tree/dataframe/test/dataframe_display.cxx [hunk 1]
```diff
@@ -635,3 +635,54 @@ TEST(RDFDisplayTests, PrintWideTables3)
...
+
+   EXPECT_EQ(strCout.str(), "+-----+----+\n"
+                            "| Row | b1 | \n"
+                            "+-----+----+\n");
+}
+
+TEST(RDFDisplayTests, DisplayLimitWithOtherOps)
+{
+   ROOT::RDataFrame d{10};
+   auto d1 = d.Define("b1", [] { return 42; });
```
Comment (ikabadzhov) [inline tree/dataframe/test/dataframe_display.cxx:661]: A small addition I would suggest to this test is to also Define an extra column, but not Display it.

So that we show that other Actions do not spoil the list of columns in Display.

**Review by ikabadzhov — APPROVED** [review]
The clang format should be fixed. But other than that and my minor comment, the PR looks good to me! Thanks for taking care of this!

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx [hunk 2]
```diff
@@ -1331,9 +1332,34 @@ public:
...
+         // sending the signal through the StopProcessing method. We add a boolean
+         // flag internal to this class, to make sure StopProcessing is only called
+         // once. Without it, this method would be called at each entry that is
+         // processed after the first condition is false, leading to a buggy
+         // scenario where this helper could stop the entire computation graph
+         // by adding as many "stop" signals as the number of nodes of the graph.
+         // This would trigger the stop mechanism in RLoopManager.
+      } else if (!fStopCalled) {
          fPrevNode->StopProcessing();
+         fStopCalled = true;
```
Comment (eguiraud) [inline tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1362]: Thank you very much for the debugging and the fix. The fact that we need this amount of text to explain these lines suggests that we might want to simplify this further.

I think it would be better if here we could just write:

```cpp
template <typename... Columns>
void Exec(unsigned int, Columns &... columns)
{
   if (fEntriesToProcess == 0)
      return;

   fDisplayerHelper->AddRow(columns...);
   --fEntriesToProcess;
   if (fEntriesToProcess == 0) // we are done, send a one-time stop signal upstream
      fPrevNode->StopProcessing();
}
```

This way we can also avoid adding the extra boolean `fStopCalled` and we can completely remove the method `RDisplay::HasNext`.

The requirement for implementing things this way is to move `RDisplay::fEntries` to `RDisplayHelper::fEntriesToProcess`, which requires small changes to `RInterface::Display` and `BuildAction(..., ActionTags::Display)` to pass that parameter to `RDisplayHelper`'s ctor instead of `RDisplay`'s ctor.

**Review by eguiraud — APPROVED** [review]
LGTM, but see below for an alternative fix that might result in overall simpler code (might be subjective :) ).

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx (hunk 2 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1362]: It may work, but I also need to add an overload of `CreateAction` that accepts also an extra `nEntries` parameter, but that seems too overkill to me

Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1362]: Or we can just live with two instances of `fEntries`, one in the display and one in the helper. The one in the display is `const` and never touched, is just there to be passed to the constructor of the helper.

Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1362]: > I also need to add an overload of CreateAction that accepts also an extra nEntries parameter

I don't think so, you should be able to pass extra things to `CreateAction` in the `helperArg` argument

Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1362]: Fair enough, an `std::pair` it is then

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@phsft-bot build
