### PR TITLE
[textinput] Fix implementation of the `kCmdWordTo{Lower,Upper}` editor commands

### LINKED ISSUE #10136: [textinput] Esc,L and Esc,U not finding word boundary
### Describe the bug
Esc,L and Esc,U  are supposed to lower or upper the word, but they seem to apply on the character.

### Expected behavior
It applies capitalization on the word.

### To Reproduce

- Write AbCd EfGh
- Try to apply Esc,L, and Esc,U

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 12 2022, 10:17:19                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

### Additional context
https://github.com/root-project/root/pull/10121

### PR DESCRIPTION
**Pull request by jalopezg-r00t**
These commands, bound respectively to `ESC l` and `ESC u`, should {lower,upper}case the next word; however, only the first character was changed.

## Checklist:
- [X] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #10136.

### CODE REVIEW

File: core/textinput/src/textinput/Editor.cpp [hunk 1]
```diff
@@ -371,15 +371,15 @@ namespace textinput {
         size_t posWord = FindWordBoundary(1);
         if (M == kCmdWordToUpper) {
           for (size_t i = Cursor; i < posWord; ++i) {
-            Line[Cursor] =  toupper(Line[Cursor]);
```
Comment (Axel-Naumann) [inline core/textinput/src/textinput/Editor.cpp:374]: Oh man 😅 Thank you!
