### PR TITLE
[VecOps] Fix #10297. Teach Rvec's to swap small and adopting vectors

### LINKED ISSUE #10297: RVec's swap is broken when RVec is adopting memory
`std::swap` seems to be working fine, but the custom `swap` implementation is broken. Self-contained reproducer by @ikabadzhov :

```cpp
#include <ROOT/RVec.hxx>
#include <iostream>
#include <vector>

int main() {
  std::vector<int> v = {1};
  ROOT::RVecI rvec1(v.data(), v.size());
  ROOT::RVecI rvec2 = {2};
  swap(rvec1, rvec2);
  v[0] = 3;
  std::cout << rvec1 << '\n' << rvec2 << '\n';
}
```

This should print 2 and 3 but instead it prints 3 and 1.

Critically, this might be problematic for non-trivial usage of RVecs inside RDF code.

### PR DESCRIPTION
**Pull request by ikabadzhov**
## Changes or fixes:
* Rvec can now correctly swap small and adopting vectors with RVec's `swap` function
* Introduce ROOT::Detail::VecOps::IsSmall(v) and ROOT::Detail::VecOps::IsAdopting(v) to check whether an RVec is small and owning its memory respectively
* Added a corresponding test suite

## Checklist:
- [x] tested changes locally
This PR fixes #10297

### CODE REVIEW

File: math/vecops/test/vecops_rvec.cxx [hunk 1]
```diff
@@ -1347,3 +1323,470 @@ TEST(VecOps, NoExceptionSafety)
...
+   RVec<int> vreg4{15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
+   // vreg4 is a regular vector that cannot "fit" to small vector
+
+   // verify that initally vectors are not small
+   EXPECT_FALSE(IsSmall(vreg1));
+   EXPECT_FALSE(IsSmall(vreg2));
+   EXPECT_FALSE(IsSmall(vreg3));
+   EXPECT_FALSE(IsSmall(vreg4));
+
+   swap(vsmall1, vreg1); // small <-> regular (same size)
```
Comment (eguiraud) [inline math/vecops/test/vecops_rvec.cxx:1562]: just noticed. shouldn't this and the calls below be `test_swap`?

Comment (ikabadzhov) [reply math/vecops/test/vecops_rvec.cxx:1562]: Actually no. I have a comment on the top of the block (line ~1520). In this case `swap` produces a small and a regular vector, while `std::swap` produces 2 regular vectors. As possible solutions I can:
1. Write explicitly another test for `std::swap`.
2. Disable the check for small or/and regular on the vector that differs.
3. Simply mention on the top of the test block: `therefore ROOT::VecOps::swap-s are mainly used "alone"`.

I am not able to write `if (GetValue()) <expect true> else <expect false>`. I considered it as the "cleanest" solution to just stick to `swap`.
