### PR TITLE
Fix #8033: string array StreamerElement not recorded properly

### LINKED ISSUE #8033: StreamerElement retrieved from file has incorrect element name for (some) arrays.
This was first reported at: https://cdcvs.fnal.gov/redmine/issues/25615
with the error:
```
    Fatal Root Error: TBranchElement::InitializeOffsets
    Could not find the real data member 'fOutputNames' when constructing the branch '4anab::MVADescriptions_emtrkmichelid_emtrkmichel_Reco1.obj' [Likely an internal error, please report to the developers].
    ROOT severity: 6000
```
during the creation of a branch.

With a class like:
```
class mystrarray {
public:
  string         fDataTag;        ///< offset=  0 type=300 ,stl=365, ctype=365, Tag of the reco data products (art::InputTag format)
  string         fOutputInstance; ///< offset= 32 type=300 ,stl=365, ctype=365, Instance name of the feature vector collection
  string         fOutputNames[4]; ///<   offset= 64 type=320 ,stl=365, ctype=365, Feature vector entries names/meaning

  static short Class_Version() { return 10; }
};
```
creating any split branch containing this kind of object (or collection there of) will work fine.

But if a file containing the `StreamerInfo` for `mystrarray` version 10 before loading the library containing its dictionary then the `StreamerInfo` from the file  (since it has the same checksum has the one that would come from the dictionary info) is used.

However, instead of
```
root [1] TClass::GetClass("mystrarray")->GetStreamerInfo()->GetElement(2)->GetFullName()
(const char *) "fOutputNames[4]"
```
it produces:
```
root [1] TClass::GetClass("mystrarray")->GetStreamerInfo()->GetElement(2)->GetFullName()
(const char *) "fOutputNames"
```
Which does not match the expectation of `TBranchElement::InitializeOffsets`.

### PR DESCRIPTION
**Pull request by pcanal**
The number of dimensions was not properly recorded in TStreamerSTL's custom streamer.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

File: core/meta/src/TStreamerElement.cxx [hunk 1]
```diff
@@ -1955,6 +1955,13 @@ void TStreamerSTL::Streamer(TBuffer &R__b)
          R__b >> fCtype;
          R__b.CheckByteCount(R__s, R__c, TStreamerSTL::IsA());
       }
+      // In old versions (prior to v6.24/02) the value of fArrayDim was not stored properly.
+      if (fArrayDim == 0 && fArrayLength > 0)
+      {
```
Comment (Axel-Naumann) [inline core/meta/src/TStreamerElement.cxx:1960]: What coding convention is that?! ;-)

```suggestion
      if (fArrayDim == 0 && fArrayLength > 0) {
```

File: core/meta/src/TStreamerElement.cxx [hunk 2]
```diff
@@ -1955,6 +1955,13 @@ void TStreamerSTL::Streamer(TBuffer &R__b)
...
+         while(fMaxIndex[fArrayDim] != 0 && fArrayDim < 5) {
```
Comment (Axel-Naumann) [inline core/meta/src/TStreamerElement.cxx:1961]: I think you meant
```suggestion
         while(fArrayDim < 5 && fMaxIndex[fArrayDim] != 0) {
```
(else you'll access `fMaxIndex[5]`, no?)

**Review by Axel-Naumann — APPROVED** [review]
But see comments

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default
