### PR TITLE
Avoid calling TTree::ChangeFile if file is TMemFile

### LINKED ISSUE #6523: TBufferMerger cannot handle TTree spanning over multiple files
## Describe the bug

This is a continuation of a jira issue originally found in multithreaded RDF [ROOT-10896](https://sft.its.cern.ch/jira/browse/ROOT-10896).

If a TTree spans over multiple files (i.e. when its size is higher than `fgMaxTreeSize`) TBufferMerger cannot correctly save its contents to the (multiple) TBufferMergerFile(s) in its queue. This is due to the original TFile being deleted in [`TTree::ChangeFile`](https://github.com/root-project/root/blob/4342e397b3c2a97a6851d895983291eddf8f033f/tree/tree/src/TTree.cxx#L2703) but not updated in TBufferMergerFile which then holds a dangling pointer. The program crashes with the following stacktrace (not really helpful even with debug symbols enabled in ROOT as well):
```
vpadulan@fedorathinkpad-T550 [~/Projects/ROOT-10896]: ./tbuffermerger_setmaxsize_seq 
Fill: Switching to new file: tbuffermerger_sequential_1.root
Fill: Switching to new file: tbuffermerger_sequential_2.root

 *** Break *** segmentation violation
===========================================================
There was a crash (kSigSegmentationViolation).
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f4fca7fbeca in wait4 () from /lib64/libc.so.6
#1  0x00007f4fca777aa7 in do_system () from /lib64/libc.so.6
#2  0x00007f4fcd15e590 in TUnixSystem::Exec (this=0xe4c800, shellcmd=0x1f92840 "/home/vpadulan/Programs/rootproject/rootinstall/devdebugtest/etc/gdb-backtrace.sh 8100 1>&2") at /home/vpadulan/Programs/rootproject/root/core/unix/src/TUnixSystem.cxx:2120
#3  0x00007f4fcd15edf6 in TUnixSystem::StackTrace (this=0xe4c800) at /home/vpadulan/Programs/rootproject/root/core/unix/src/TUnixSystem.cxx:2411
#4  0x00007f4fcd16271a in TUnixSystem::DispatchSignals (this=0xe4c800, sig=kSigSegmentationViolation) at /home/vpadulan/Programs/rootproject/root/core/unix/src/TUnixSystem.cxx:3649
#5  0x00007f4fcd15a82a in SigHandler (sig=kSigSegmentationViolation) at /home/vpadulan/Programs/rootproject/root/core/unix/src/TUnixSystem.cxx:407
#6  0x00007f4fcd162628 in sighandler (sig=11) at /home/vpadulan/Programs/rootproject/root/core/unix/src/TUnixSystem.cxx:3620
#7  <signal handler called>
#8  0x0000000000000000 in ?? ()
#9  0x00000000004012fb in main () at tbuffermerger_setmaxsize_seq.cpp:25
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#8  0x0000000000000000 in ?? ()
#9  0x00000000004012fb in main () at tbuffermerger_setmaxsize_seq.cpp:25
===========================================================
```

## Expected behavior

The program doesn't crash. TBufferMergerFile is updated alongside the tree (i.e. it should be the same pointer as `TTree::GetCurrentFile()`) and the partial files are correctly saved when the TTree changes to new ones.

## To Reproduce

See the following gist:
https://gist.github.com/vepadulano/fc09150516193f1a801e0991591958ee

## Setup

1. ROOT master
2. Fedora 32
3. ROOT built with cmake: `cmake -GNinja -Ddev=ON -DCMAKE_BUILD_TYPE=Debug -Dtesting=ON -Droottest=ON`

## Additional Context

Some print statements from `gdb`, also commented in the gist.
Before filling the TTree we can see that the current TFile of the tree is correctly the TBufferMergerFile (`tbmfile`):
```
(gdb) p tbmfile.get()
$4 = (std::__shared_ptr<ROOT::Experimental::TBufferMergerFile, (__gnu_cxx::_Lock_policy)2>::element_type *) 0x1f0e750
(gdb) p tree.GetCurrentFile()
$5 = (TFile *) 0x1f0e750
(gdb) p tree.GetDirectory()  
$6 = (TDirectory *) 0x1f0e750
(gdb) p tbmfile.get()->GetName()
$7 = 0x1eca1f0 "tbuffermerger_sequential.root"
(gdb) p tree.GetDirectory()->GetName()
$8 = 0x1eca1f0 "tbuffermerger_sequential.root"
(gdb) p tree.GetCurrentFile()->GetName()
$9 = 0x1eca1f0 "tbuffermerger_sequential.root"
```
But after the event loop the TTree changes files twice and the latest file it points to is called "tbuffermerger_sequential_2.root", but this is not reflected correctly in the TBufferMergerFile:
```
(gdb) p tbmfile.get()
$10 = (std::__shared_ptr<ROOT::Experimental::TBufferMergerFile, (__gnu_cxx::_Lock_policy)2>::element_type *) 0x1f0e750
(gdb) p tree.GetDirectory()                  
$11 = (TDirectory *) 0x19865c0
(gdb) p tree.GetCurrentFile()                
$12 = (TFile *) 0x19865c0
(gdb) p tree.GetCurrentFile()->GetName()
$13 = 0x1db1780 "tbuffermerger_sequential_2.root"
(gdb) p tree.GetDirectory()->GetName()       
$14 = 0x1db1780 "tbuffermerger_sequential_2.root"
(gdb) p tbmfile.get()->GetName()

Program received signal SIGSEGV, Segmentation fault.
```

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #6523 .

As per comments by Philippe and Guilherme, the behaviour triggered by `TTree::Fill` to change the associated TFile when reaching a size greater than `fgMaxTreeSize` doesn't fit within the scope of TBufferMerger. Avoid calling `TTree::ChangeFile` doesn't change anything from the user perspective and doesn't interfere with the I/O mechanism of TBufferMerger (and thus of the multithreaded RDF Snapshot as well). 

While fixing the above issue I found another one that may be related to this. Meanwhile the draft can be discussed.

TODO
- [x] Update docs in TTree::Fill, TTree::ChangeFile and TBufferMerger. Tell the users that TBufferMergerFile doesn't trigger this behaviour
- [x] Include the reproducer as test

### CODE REVIEW

**Comment by eguiraud** [comment]
For my education, what's the motivation for TTree::Fill to switch to a new file after a while, and if TBufferMerger can do without, couldn't normal TTree also not change files? (question more for @pcanal than for @vepadulano I guess)

**Comment by pcanal** [comment]
`TTree::ChangeFile` dates back to the days where there was no way to create files larger than 2Gb.  It is still "useful" in case where the user wants to control the output size of the files.

File: tree/tree/src/TTree.cxx [hunk 1]
```diff
@@ -4703,8 +4704,9 @@ Int_t TTree::Fill()
    // to the case where the tree is in the top level directory.
    if (fDirectory)
       if (TFile *file = fDirectory->GetFile())
-         if ((TDirectory *)file == fDirectory && (file->GetEND() > fgMaxTreeSize))
-            ChangeFile(file);
+         if (static_cast<TDirectory *>(file) == fDirectory && (file->GetEND() > fgMaxTreeSize))
+            if (!(dynamic_cast<ROOT::Experimental::TBufferMergerFile *>(file)))
```
Comment (pcanal) [inline tree/tree/src/TTree.cxx:4708]:
```suggestion
            if (!(dynamic_cast<TMemFile*>(file)))
```
is probably as clear (abeit, the non TBufferMergeFile would not reach here because of line 4705 ... but on the other hand users might have other classes derived from TMemFile).

**Comment by eguiraud** [comment]
Ok, maybe there is motivation to change the default behavior to never switching to a new file then -- the switching is a surprising thing, it could happen that you run a long job on some remote machine and then only copy back `file.root`, forgetting/ignoring `f__1.root`, `f__2.root` etc. What do you think?

File: tree/tree/src/TTree.cxx (hunk 1 above)
Comment (eguiraud) [reply tree/tree/src/TTree.cxx:4708]: i thought we shunned `dynamic_cast` and preferred using `TClass` & company for RTTI

**Comment by pcanal** [comment]
Yes, we might want to.   Note that the current default is 100,000,000 bytes (100GB ish)

File: tree/tree/src/TTree.cxx (hunk 1 above)
Comment (pcanal) [reply tree/tree/src/TTree.cxx:4708]: @Axel-Naumann ? [For equality TClass is faster, for base class dynamic_cast might be faster]

Comment (amadio) [reply tree/tree/src/TTree.cxx:4708]: Performance is likely not a concern here. This function is called very rarely...

Comment (vepadulano) [reply tree/tree/src/TTree.cxx]: I updated with a cast to `TMemFile`. I'll gather more information on the usage of TClass for RTTI before merging the PR

Comment (Axel-Naumann) [reply tree/tree/src/TTree.cxx]: For the record, casting an object of the stated type through a `TObject*` to a `TNamed*`:
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
BM_stddyn_TNamed       14.5 ns         14.5 ns     48150881
BM_TClass_TNamed       15.4 ns         15.4 ns     45324619
BM_stddyn_TExec        27.9 ns         27.9 ns     25078317
BM_TClass_TExec        36.3 ns         36.3 ns     19301438
BM_stddyn_TBits        27.1 ns         27.1 ns     25844223
BM_TClass_TBits         338 ns          338 ns      2081282
BM_stddyn_2nd          31.3 ns         31.3 ns     22456278
BM_TClass_2nd          48.3 ns         48.3 ns     14494924
```
("2nd" is "a class where TNamed is the second base".) Where do you want me to upload that code?

Comment (vepadulano) [reply tree/tree/src/TTree.cxx]: Great, thanks!

**Review by pcanal — APPROVED** [review]

**Comment by vepadulano** [comment]
Another issue has emerged with multithreaded RDF snapshot of a TChain. It seems like `TTree::ChangeFile` is still called, but this time within `TTree::CopyEntries`. It may be better to treat is in a different PR, since this one solves the original issue

**Comment by pcanal** [comment]
> It seems like TTree::ChangeFile is still called, but this time within TTree::CopyEntries. 

This tells us that we might want to move the protection inside TTree::ChangeFile.

Independently, before we close this, we need to understand why TTree::ChangeFile was triggered in the first place for a TMemFile (as the default size is .. 100GB).

File: io/io/test/TBufferMerger.cxx [hunk 2]
```diff
@@ -229,3 +229,63 @@ TEST(TBufferMerger, CheckTreeFillResults)
...
+      int nentries{20000};
+      int maxtreesize{1000};
+
+      TTree tree{"T", "SetMaxTreeSize(1000)"};
+      tree.SetMaxTreeSize(maxtreesize);
+      // The resetting of the kCleanup bit below is necessary to avoid leaving
+      // the management of this object to ROOT, which leads to a race condition
+      // that may cause a crash once all threads are finished and the final
+      // merge is happening
+      tree.ResetBit(kMustCleanup);
```
Comment (amadio) [inline io/io/test/TBufferMerger.cxx:262]: If I recall correctly, @pcanal indicated to me that this workaround might not be necessary anymore.
It would be great if you could check if that's really the case and then remove it from the `TBufferMerger` tests.

File: tree/tree/src/TTree.cxx [hunk 3]
```diff
@@ -4703,8 +4708,10 @@ Int_t TTree::Fill()
    // to the case where the tree is in the top level directory.
    if (fDirectory)
       if (TFile *file = fDirectory->GetFile())
-         if ((TDirectory *)file == fDirectory && (file->GetEND() > fgMaxTreeSize))
-            ChangeFile(file);
+         if (static_cast<TDirectory *>(file) == fDirectory && (file->GetEND() > fgMaxTreeSize))
+            // Changing file clashes with the design of TMemFile and derivates, see #6523.
+            if (!(dynamic_cast<TMemFile *>(file)))
+               ChangeFile(file);
```
Comment (amadio) [inline tree/tree/src/TTree.cxx:4714]: @pcanal, instead of checking for a `TMemFile` here, would there be a way to check for a file on disk and revert the condition? For example, if `file` is a `TDirectoryFile`. The question is really, for which of the classes below it makes sense to call `ChangeFile()`?
```bash
$ git grep -o 'class T.*File.*public T.*File'
dcache/inc/TDCacheFile.h:class TDCacheFile : public TFile
gfal/inc/TGFALFile.h:class TGFALFile : public TFile
io/inc/ROOT/TBufferMerger.hxx:class TBufferMergerFile : public TMemFile
io/inc/TFile.h:class TFile : public TDirectoryFile
io/inc/TMemFile.h:class TMemFile : public TFile
io/inc/TZIPFile.h:class TZIPFile : public TArchiveFile
mpi/inc/TMPIFile.h:class TMPIFile : public TMemFile
sql/inc/TSQLFile.h:class TSQLFile final : public TFile
xml/inc/TXMLFile.h:class TXMLFile final : public TFile
```

**Comment by vepadulano** [comment]
> > It seems like TTree::ChangeFile is still called, but this time within TTree::CopyEntries.
> 
> This tells us that we might want to move the protection inside TTree::ChangeFile.

I moved it and it still triggers it with this new reproducer https://gist.github.com/vepadulano/1cd2ac2296f85d10cf140166b08cf5c3

What happens is that when finalizing the MT Snapsho the TBufferMerger destructor, then follow `TBufferMerger::Merge` and `TFileMerger::PartialMerge`. The interesting part is that while usually `TFileMerger::fOutputFile` should be a derived of `TMemFile` (and that's why this PR works), in this particular case it isn't .Here is a call stack:
```
#0  TFileMerger::PartialMerge (this=0x44b0108, in_type=14) at /home/vpadulan/Programs/rootproject/root/io/io/src/TFileMerger.cxx:815
#1  0x00007ffff7182b07 in ROOT::Experimental::TBufferMerger::Merge (this=0x44b00f0)
    at /home/vpadulan/Programs/rootproject/root/io/io/src/TBufferMerger.cxx:117
#2  0x00007ffff71826a7 in ROOT::Experimental::TBufferMerger::~TBufferMerger (this=0x44b00f0, __in_chrg=<optimized out>)
    at /home/vpadulan/Programs/rootproject/root/io/io/src/TBufferMerger.cxx:51
#3  0x00007ffff71826f6 in ROOT::Experimental::TBufferMerger::~TBufferMerger (this=0x44b00f0, __in_chrg=<optimized out>)
    at /home/vpadulan/Programs/rootproject/root/io/io/src/TBufferMerger.cxx:52
#4  0x00000000004760c0 in std::default_delete<ROOT::Experimental::TBufferMerger>::operator() (this=0x16ecdb0, __ptr=0x44b00f0)
    at /usr/include/c++/10/bits/unique_ptr.h:85
#5  0x0000000000489453 in std::__uniq_ptr_impl<ROOT::Experimental::TBufferMerger, std::default_delete<ROOT::Experimental::TBufferMerger> >::reset (this=0x16ecdb0, __p=0x0) at /usr/include/c++/10/bits/unique_ptr.h:182
#6  0x0000000000488bc1 in std::unique_ptr<ROOT::Experimental::TBufferMerger, std::default_delete<ROOT::Experimental::TBufferMerger> >::reset (
    this=0x16ecdb0, __p=0x0) at /usr/include/c++/10/bits/unique_ptr.h:456
#7  0x00000000004876c9 in ROOT::Internal::RDF::SnapshotHelperMT<int>::Finalize (this=0x16ecda0)
    at /home/vpadulan/Programs/rootproject/rootinstall/devdebugtest/include/ROOT/RDF/ActionHelpers.hxx:1530
```
And gdb tells us we're not dealing with a TMemFile anymore:
```
(gdb) p this
$1 = (TFileMerger * const) 0x44b0108
(gdb) p this->fOutputFile
$2 = (TFile *) 0x4d63230
(gdb) p this->fOutputFile->InheritsFrom("TMemFile")
$3 = false
```
> Independently, before we close this, we need to understand why TTree::ChangeFile was triggered in the first place for a TMemFile (as the default size is .. 100GB).

The original issue that triggered this investigation is in PyRDF (linked a few messages above). Unfortunately we don't have a full reproducer from the user, we just know that they were using IMT, although at some point in the discussion they tried with sequential execution and still got segfault. The fixes in this PR may be worth nonetheless though

**Comment by vepadulano** [comment]
Update:

After a very productive chat with @eguiraud we found out that this time `TTree::ChangeFile` is not trying to delete the `TBufferMergerFile`s attached to the `TBufferMerger`, but the `TFileMerger` attached to said `TBufferMerger`. The initial patch does not work since the `fOutputFile` member of `TFileMerger` is not a derivate of `TMemFile` and is the one that is getting changed in the process.

The design of `TFileMerger` is of using `fOutputFile` as the file where all the data is merged, so of course it should never be deleted. A simple call to `TTree::SetMaxTreeSize()` with a very large size inside `ROOT::Detail::RDF::SnapshotHelperMT::Finalize()` solves the reproducer I attached in the last message. But this solution would only work for IMT RDF Snapshot, while it would be desirable to solve it directly in TFileMerger.

A tentative solution will come in the next commit.

**Comment by vepadulano** [comment]
Latest commit adds a fix in MT RDF Snapshot that should be reverted once #6640 will be solved. Another test has been added in RDF as well. This PR should now be ready to merge

File: io/io/test/TBufferMerger.cxx (hunk 2 above)
Comment (vepadulano) [reply io/io/test/TBufferMerger.cxx:262]: If this is true I will open another PR to modify all the tests in TBufferMerger, thank you for the hint!

File: tree/tree/src/TTree.cxx (hunk 3 above)
Comment (vepadulano) [reply tree/tree/src/TTree.cxx:4714]: The original issue and the new one described in #6640 are addressed in the PR, if you think the solution should be modified I'm open to discussion :smile: .

File: io/io/test/TBufferMerger.cxx (hunk 2 above)
Comment (eguiraud) [reply io/io/test/TBufferMerger.cxx:262]: @vepadulano can you take care of this (in another PR)? e.g. here, for sure the ResetBit(kMustCleanup) is not needed to prevent lifetime issues because the TTree goes out of scope before the file that contains it (and TTree deregisters itself from the file at destruction time).

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx [hunk 4]
```diff
@@ -1527,7 +1527,12 @@ public:
 
       // flush all buffers to disk by destroying the TBufferMerger
       fOutputFiles.clear();
+      // TODO: Remove the calls to TTree::SetMaxTreeSize after issue #6640 is fixed
+      auto old_maxtreesize{TTree::GetMaxTreeSize()};
+      TTree::SetMaxTreeSize(std::numeric_limits<Long64_t>::max());
       fMerger.reset();
+      TTree::SetMaxTreeSize(old_maxtreesize);
```
Comment (eguiraud) [inline tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1534]: for consistency we should do the same also for single-thread Snapshot, I think?

**Review by eguiraud — CHANGES_REQUESTED** [review]

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx (hunk 4 above)
Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1534]: @vepadulano can you do the same for single-thread Snapshot please?

**Comment by eguiraud** [comment]
@pcanal @amadio anything blocking these fixes to be merged, on your side?

**Comment by eguiraud** [comment]
@phsft-bot build please

**Comment by amadio** [comment]
No, not for me.

File: io/io/test/TBufferMerger.cxx (hunk 2 above)
Comment (vepadulano) [reply io/io/test/TBufferMerger.cxx:262]: Yeah sure!

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx (hunk 4 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1534]: Yes, I'll push a new commit with the latest modifications

**Comment by eguiraud** [comment]
@vepadulano the test failures look real

**Comment by vepadulano** [comment]
@eguiraud on it!

**Comment by vepadulano** [comment]
Updates on the failing tests:
* Centos8/multicore: Failure because the same wrong mechanism of changing files happens in `FinalizeSlot` instead of `Finalize` in `SnapshotHelperMT`. Weirdly this didn't happen on my machine with 8 threads but it does on this node with 16 threads, still not sure what's the real difference there.
* MacOS: Both failures happen in the dataframe test, but in the **single threaded** Snapshot, that is in the `Finalize` method of the `SnapshotHelper` class. At first this PR wasn't even considering the single threaded case, that's also why `SnapshotHelper` wasn't modified. So there was this difference between the single threaded Snapshot that still used the weird ChangeFile behaviour (although it shouldn't have triggered a segfault anyway since it's using a plain TFile), and the multithreaded Snapshot that got its behaviour changed to avoid the issue

Considering both types of failures, and the fact that a coherent behaviour across the two Snapshot modes is desirable, I would refactor the usage of `TTree::SetMaxTreeSize` inside of RDF Snapshot in a single common point that both single-thread and multi-thread operations have to go through, if that exists. Or in alternative, the workaround should be done at construction time of both helpers and then removed at destruction time (or in `Initialize` and `Finalize` methods).

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx [hunk 5]
```diff
@@ -1252,6 +1252,7 @@ class SnapshotHelper : public RActionImpl<SnapshotHelper<ColTypes...>> {
    BoolArrayMap fBoolArrays; // Storage for C arrays of bools to be written out
    std::vector<TBranch *> fBranches;     // Addresses of branches in output, non-null only for the ones holding C arrays
    std::vector<void *> fBranchAddresses; // Addresses associated to output branches, non-null only for the ones holding C arrays
+   Long64_t fMaxTreeSize{TTree::GetMaxTreeSize()}; // Revert when #6640 will be solved
```
Comment (eguiraud) [inline tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1255]: This leaves the world in a bad state in case an exception is thrown during the event loop (which happens 
Can you please use instead a RAII object instantiated at the beginning of RLoopManager::Run? Something like

```cpp
struct MaxTreeSizeRAII {
   Long64_t fOldMaxTreeSize;
   MaxTreeSizeRAII() : fOldMaxTreeSize(TTree::GetMaxTreeSize()) {
      TTree::SetMaxTreeSize(std::numeric_limits<Long64_t>::max());
   }
   ~MaxTreeSizeRAII() {
      TTree::SetMaxTreeSize(fOldMaxTreeSize);
   }
};

**Review by eguiraud — CHANGES_REQUESTED** [review]
last one I promise :smile:

File: tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx (hunk 5 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx:1255]: Yes this makse totally sense, thank you!

File: tree/dataframe/src/RLoopManager.cxx [hunk 6]
```diff
@@ -203,6 +205,25 @@ static void ThrowIfNSlotsChanged(unsigned int nSlots)
...
+\brief Scope-bound change of `TTree::fgMaxTreeSize`.
+
+This RAII object stores the current value result of `TTree::GetMaxTreeSize`,
+changes it to maximum at construction time and restores it back at destruction
+time. Needed for issue #6523 and should be reverted when #6640 will be solved.
+*/
+struct MaxTreeSizeRAII {
+   Long64_t fOldMaxTreeSize;
+
+   explicit MaxTreeSizeRAII() : fOldMaxTreeSize(TTree::GetMaxTreeSize())
```
Comment (eguiraud) [inline tree/dataframe/src/RLoopManager.cxx:219]: afaik `explicit` does not do anything here

```suggestion
   MaxTreeSizeRAII() : fOldMaxTreeSize(TTree::GetMaxTreeSize())
```

**Review by eguiraud — APPROVED** [review]
LGTM, thanks a lot for pushing this to the finish line @vepadulano

File: tree/dataframe/src/RLoopManager.cxx (hunk 6 above)
Comment (vepadulano) [reply tree/dataframe/src/RLoopManager.cxx:219]: I thought it made the code cleaner, but yes probably there won't be any actual case where this does something.

**Comment by vepadulano** [comment]
@phsft-bot build please
