### PR TITLE
[tree] fix TBranchElement for split collection with renamed inner type

### LINKED ISSUE #19650: [tree] missing staged data in I/O rules of split vector<T> --> vector<U>
### Check duplicate issues.

- [x] Checked for duplicates

### Description

This issue is described in https://root-forum.cern.ch/t/manual-schema-evolution-with-i-o-rules-and-branches-containing-vector-t/64026

We have an I/O rule that converts members of type `T` to type `U`. If we store split `vector<T>` and try to read it as a `vector<U>`, the I/O rule runs but it seems that the staged `oldObj` has not been populated with data. 

The same test with an unsplit tree works fine.

### Reproducer

Extract the tarball and run

    make
    ./check

The output is with `splitLevel = 99` is

    tree has 1 entry
    I/O rule runs!
    vector size: 1; fNewMember: 0 (expected: 1.0)

The relevant output of `gROOT->GetListOfStreamerInfo()->ls();` is

```
StreamerInfo for conversion to vector<ExampleMC_V3> from: vector<ExampleMC_V2>, version=6, checksum=0xb7ad9f7e
  vector<ExampleMC_V2> This            offset=  0 type=300 stl=1 ctype=61 <ExampleMC_V2> Used to call the proper TStreamerInfo case
   i= 0, This            type=300, offset=  0, len=1, method=0

StreamerInfo for conversion to ExampleMC_V3 from: ExampleMC_V2, version=2, checksum=0xe447ef4e
  ExampleMC_V2@@2 @@alloc         offset=  0 type=1001                     
  float          fOldMember      offset=  8 type= 5  (cached)                     
  float          fOldMember      offset=99999 type= 5  (write)                     
  float          fNewMember      offset=  0 type=1000                     
  ExampleMC_V2@@2 @@dealloc       offset=  0 type=1002                     
   i= 0, @@alloc         type=1001, offset=  0, len=1, method=0
   i= 1, fOldMember      type=  5, offset=  8, len=1, method=0 [cached]
   i= 2, fOldMember      type=  5, offset=99999, len=1, method=0 [write]
   i= 3, fNewMember      type=1000, offset=  0, len=1, method=0
   i= 4, @@dealloc       type=1002, offset=  0, len=1, method=0

StreamerInfo for class: ExampleMC_V3, version=3, checksum=0xe50525f0
  float          fNewMember      offset=  0 type= 5                     
   i= 0, fNewMember      type=  5, offset=  0, len=1, method=0

StreamerInfo for class: ExampleMC_V2@@2, version=2, checksum=0xe447ef4e
  float          fOldMember      offset=  8 type= 5                     
   i= 0, fOldMember      type=  5, offset=  8, len=1, method=0
```

The output of `tree->Print("debugInfo");` is

```
******************************************************************************
*Tree    :events    :                                                        *
*Entries :        1 : Total =            1753 bytes  File  Size =        774 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
Branch MCParticles uses:
  float          fNewMember      offset=  0 type=1000                     
   with read actions:
TVectorLoopConfig: increment=4
StreamerInfoAction, class:ExampleMC_V3, name=fNewMember, fType[3]=1000, TStreamerArtificial, offset=0 (), elemnId=3 
   with write actions:
TVectorLoopConfig: increment=4
Branch MCParticles.fOldMember uses:
   With elements:
  float          fOldMember      offset=  8 type= 5  (cached)                     
  float          fOldMember      offset=99999 type= 5  (write)                     
   with read actions:
TVectorLoopConfig: increment=4
StreamerInfoAction, class:ExampleMC_V3, name=fOldMember, fType[1]=5, TStreamerBasicType, offset=8 (cached), elemnId=1 
   with write actions:
TVectorLoopConfig: increment=4
StreamerInfoAction, class:ExampleMC_V3, name=fOldMember, fType[2]=5, TStreamerBasicType, offset=99999 (write), elemnId=2 
```

[ExampleMC.tar.gz](https://github.co/user-attachments/files/21791755/ExampleMC.tar.gz)

### ROOT version

master

### Installation method

from sources

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jblomer**
When setting up the branch addresses of `TBranchElement` for a `vector<U>` that is a `vector<T>` on disk, `InitInfo` fails to recognize that the parent branch and the sub branch should share the staging object.

Fixes  #19650

### CODE REVIEW

File: tree/tree/test/evolution.cxx [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+      auto file = std::unique_ptr<TFile>(TFile::Open(fileName, "RECREATE"));
+      TTree tree = TTree("t", "");
+
+      auto vec = new std::vector<EvolutionStruct_V2>({EvolutionStruct_V2{1.0}});
+      tree.Branch("vec", "std::vector<EvolutionStruct_V2>", &vec, 32000, 99);
+
+      tree.Fill();
+      tree.Write();
+
+      file->Close();
```
Comment (pcanal) [inline tree/tree/test/evolution.cxx:29]:
```suggestion
      file->Write();
```
This will `Write` both the `TFile` and `TTree`.  The `TFile` destructor will `Close` the file.

**Review by pcanal — APPROVED** [review]
Thanks.
