### PR TITLE
Make sure the temporary file is closed before renaming it. Fixes #9730

### LINKED ISSUE #9730: When working on a Windows partition from Linux, rootcling is not able to rename an output file
See the discussion at https://root-forum.cern.ch/t/rootcint-cannot-create-dictionary-in-a-vm/48580 .

In short, in certain situations in which the platform is Linux but the working directory belongs to a Windows file system, [this call to std::rename](https://github.com/root-project/root/blob/7a2612dc7ae62832c7683081020e190c49b75569/core/dictgen/src/rootcling_impl.cxx#L2956-L2958) fails because "Windows" does not allow renaming files that are currently in use.

Something like the logic that we already apply for Windows at https://github.com/root-project/root/blob/7a2612dc7ae62832c7683081020e190c49b75569/core/dictgen/src/rootcling_impl.cxx#L2944-L2955 might be needed on Linux as well.

### PR DESCRIPTION
**Pull request by bellenot**
As reported [on the forun](https://root-forum.cern.ch/t/rootcint-cannot-create-dictionary-in-a-vm/48580), make sure the temporary file is closed before renaming it. Should fix #9730

### CODE REVIEW

File: core/dictgen/src/rootcling_impl.cxx [hunk 1]
```diff
@@ -2941,12 +2941,14 @@ class tempFileNamesCatalog {
          std::ifstream ifile(tmpName);
          if (!ifile)
             ROOT::TMetaUtils::Error(nullptr, "Cannot find %s!\n", tmpName);
+         // make sure the file is closed, mostly for Windows FS, also when
+         // accesing it from a Linux VM via a shared folder
```
Comment (Axel-Naumann) [inline core/dictgen/src/rootcling_impl.cxx:2945]:
```suggestion
         // Make sure the file is closed, mostly for Windows FS, also when
         // accessing it from a Linux VM via a shared folder
```

**Review by Axel-Naumann — APPROVED** [review]
Thanks!
