### PR TITLE
Fix compilation errors with the `/permissive-` compiler flag on Windo…

### LINKED ISSUE #9607: [MSVC][std:c++latest][permissive-] root failed to build on MSVC
### Describe the bug
The MSVC team recently added root as part of RWC testing. And we found some errors when building root with '/std:c++latest' and '/permissive-'. Could you please help look at this issue or provide some workarounds? Thanks in advance.
### Expected behavior
root project could build successfully under '/std:c++latest' and '/permissive-' mode.
### To Reproduce
1. git clone https://github.com/root-project/root F:\gitP\root-project\root
2. mkdir F:\gitP\root-project\root\build_amd64
2. set CL= /std:c++latest or set CL= /permissive-
3. set PATH=%PATH:C:\Strawberry\perl\bin;=%
4. msbuild /m /p:Platform=x64 /p:Configuration=Release ALL_BUILD.vcxproj /t:Rebuild
### Setup
Visual Studio 2019 16.11.8
### Additional context
Build.log:
/std:c++latest: [build.log](https://github.com/root-project/root/files/7889383/build.log)
/permissive-: [build.log](https://github.com/root-project/root/files/7889386/build.log)

### PR DESCRIPTION
**Pull request by bellenot**
…ws. Resolves #9607

Fix the following compilation errors when using the `/permissive-` compiler flag:
```
  hist\hist\inc\TF1.h(463,1): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      hist\hist\inc\TF1.h(463,1): message : could be 'TString'
      hist\hist\inc\TF1.h(463,1): message : or       'const char *'

  hist\hist\src\TH1.cxx(3128,91): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      hist\hist\src\TH1.cxx(3128,91): message : could be 'TString'
      hist\hist\src\TH1.cxx(3128,91): message : or       'const char *'

  gui\gui\src\TGFileDialog.cxx(390,53): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      gui\gui\src\TGFileDialog.cxx(390,53): message : could be 'TString'
      gui\gui\src\TGFileDialog.cxx(390,53): message : or       'const char *'

  graf2d\win32gdk\src\TGWin32.cxx(2690,47): error C2664: 'void gdk_gc_set_clip_mask(GdkGC *,GdkBitmap *)': cannot convert argument 2 from 'const unsigned long' to 'GdkBitmap *'
  graf2d\win32gdk\src\TGWin32.cxx(3055,44): error C2664: 'void gdk_gc_set_clip_mask(GdkGC *,GdkBitmap *)': cannot convert argument 2 from 'const unsigned long' to 'GdkBitmap *'
```

### CODE REVIEW

File: gui/gui/src/TGFileDialog.cxx [hunk 1]
```diff
@@ -387,7 +387,7 @@ TGFileDialog::TGFileDialog(const TGWindow *p, const TGWindow *main,
 TGFileDialog::~TGFileDialog()
 {
    if (IsZombie()) return;
-   TString str = fCheckB ? fCheckB->GetString() : "";
+   TString str = fCheckB ? fCheckB->GetString() : (TString)"";
```
Comment (pcanal) [inline gui/gui/src/TGFileDialog.cxx:390]:
```suggestion
   TString str = fCheckB ? fCheckB->GetString() : TString();
```

File: hist/hist/inc/TF1.h [hunk 2]
```diff
@@ -465,7 +465,7 @@ class TF1 : public TNamed, public TAttLine, public TAttFill, public TAttMarker {
    }
    virtual TString  GetExpFormula(Option_t *option = "") const
    {
-      return (fFormula) ? fFormula->GetExpFormula(option) : "";
+      return (fFormula) ? fFormula->GetExpFormula(option) : (TString)"";
```
Comment (pcanal) [inline hist/hist/inc/TF1.h:468]:
```suggestion
      return (fFormula) ? fFormula->GetExpFormula(option) : TString();
```

File: hist/hist/src/TH1.cxx [hunk 3]
```diff
@@ -3125,7 +3125,7 @@ TH1 *TH1::DrawCopy(Option_t *option, const char * name_postfix) const
    TString opt = option;
    opt.ToLower();
    if (gPad && !opt.Contains("same")) gPad->Clear();
-   TString newName = (name_postfix) ?  TString::Format("%s%s",GetName(),name_postfix) : "";
+   TString newName = (name_postfix) ?  TString::Format("%s%s",GetName(),name_postfix) : (TString)"";
```
Comment (pcanal) [inline hist/hist/src/TH1.cxx:3128]:
```suggestion
   TString newName = (name_postfix) ?  TString::Format("%s%s",GetName(),name_postfix) : TString();
```

**Review by pcanal — APPROVED** [review]

**Comment by bellenot** [comment]
Thanks @pcanal !

**Comment by bellenot** [comment]
The error on Windows is not an error (it's coming from the commit log). Merging
