### PR TITLE
Fix for TRatioPlot axes sync

### LINKED ISSUE #9263: TRatioPlot axes sync
Disclaimer: I'm new to this sort of thing but keen to contribute. Please let me know if I'm going about this the wrong way!

### Explain what you would like to see improved
At present, changing the x axis range on the lower panel of a TRatioPlot does not automatically zoom the top panel. The axes update but the histogram is not redrawn with the correct scale.

### Optional: share how it could be improved
As far as I can tell, what happens is this:

```
THistPainter::Paint() is called
    -> PaintInit() is called, this populates the Hparam structure with the old axis ranges
    -> PaintFrame() is called
          -> RecalculateRange() is called
                 -> gPad->RangeAxis() is called with the old ranges, and emits the RangeAxisChanged() signal
                 -> TRatioPlot::RangeAxisChanged() updates the axis ranges for the top panel
          -> The frame is painted with the old axis ranges
    -> The histogram is drawn with old ranges
```

The most straightforward way that I can see to fix this is to simply call PaintInit() and PaintFrame() again, directly after. This does solve the problem but seems quite inelegant. 

Another idea would be to emit the RangeAxisChanged() signal before PaintInit() so that all the painting proceeds with correct ranges. This could be done by overloading a TPad::RangeAxis() to have an implementation with no arguments that only emits the signal.

### To Reproduce
Simple macro - try zooming on the lower axis:
`
{
  TH1D* hist = new TH1D("hist", "hist", 512, -10, 10);
  hist->FillRandom("gaus", 10000);
  TF1 *func = new TF1("func", "gaus");
  hist->Fit(func);
  TRatioPlot *plot = new TRatioPlot(hist);
  plot->Draw();
}
`

### Setup
1. ROOT 6.25/01
2. macOS 11.4
3. build from git

### Additional context
There is a comment 
"// @TODO: Updating is not working when zooming on the lower plot. Axes update, but upper hist only on resize"
in TRatioPlot.cxx so I assume at least one other person knows about this behavior

### PR DESCRIPTION
**Pull request by belmakier**
# This Pull request:

## Changes or fixes:
Fix for TRatioPlot axes sync:
   - Added TPad::RangeAxis() which only emits the RangeAxisChanged() signal
   - Call this before PaintInit() in THistPainter::Paint()
   - This correctly syncs the histogram axes before the upper histogram is drawn

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #9263

### CODE REVIEW

File: graf2d/gpad/src/TPad.cxx [hunk 1]
```diff
@@ -5234,6 +5234,12 @@ void TPad::RangeAxis(Double_t xmin, Double_t ymin, Double_t xmax, Double_t ymax)
    RangeAxisChanged();
 }
 
+void TPad::RangeAxis()
```
Comment (couet) [inline graf2d/gpad/src/TPad.cxx:5237]: I must have missed something but I don't understand why you need this intermediate method which only call RangeAxisChanged(); ?

File: hist/histpainter/src/THistPainter.cxx [hunk 2]
```diff
@@ -4569,6 +4569,7 @@ void THistPainter::Paint(Option_t *option)
       return;
    }
 
+   gPad->RangeAxis(); //emit RangeAxisChanged() signal to sync axes
```
Comment (couet) [inline hist/histpainter/src/THistPainter.cxx:4572]: Why don't you call RangeAxisChanged directly ?

Comment (belmakier) [reply hist/histpainter/src/THistPainter.cxx:4572]: This compilation error: 

`error: no member named 'RangeAxisChanged' in 'TVirtualPad'
   gPad->RangeAxisChanged();
   ~~~~  ^
1 error generated.
`

I guess because RangeAxisChanged() is only defined for a TPad not a TVirtualPad?

Comment (couet) [reply hist/histpainter/src/THistPainter.cxx:4572]: In that case it might be simply to define `RangeAxisChanged` in `TVirtualPad` than creating a new method which does simply a call to RangeAxisChanged ?

Comment (belmakier) [reply hist/histpainter/src/THistPainter.cxx]: Ok sure, I have changed it to that now

File: graf2d/gpad/inc/TPad.h [hunk 3]
```diff
@@ -307,7 +307,7 @@ class TPad : public TVirtualPad, public TAttBBox2D {
    void              Range(Double_t x1, Double_t y1, Double_t x2, Double_t y2) override; // *MENU* *ARGS={x1=>fX1,y1=>fY1,x2=>fX2,y2=>fY2}
    virtual void      RangeChanged() { Emit("RangeChanged()"); } // *SIGNAL*
    void              RangeAxis(Double_t xmin, Double_t ymin, Double_t xmax, Double_t ymax) override;
-   virtual void      RangeAxisChanged() { Emit("RangeAxisChanged()"); } // *SIGNAL*
+   virtual void      RangeAxisChanged() override { Emit("RangeAxisChanged()"); } // *SIGNAL*
```
Comment (couet) [inline graf2d/gpad/inc/TPad.h:310]: As the implementation of RangeAxisChanged is nos in TVirtualPad, you do not need to have it in TPad. Like UnZoomed

**Review by couet — APPROVED** [review]
No need to have RangeAxisChanged in TPad.

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
@phsft-bot build please
