### PR TITLE
[TMVA] Fix using GUI functions TMVA::mva and TMVA::mvaeffs running in batch

### LINKED ISSUE #6479: [TMVA] TMVAGui functions crash in batch mode
As reported in https://root-forum.cern.ch/t/tmva-mvaeffs-crashes-when-disabling-graphical-output/40198
calling functions of TMVAGui in batch result in a crash.

Also reproducer reported in ROOT-9483 is still crashing

Code reproducing the issue
```
void tmva_plot(std::string infilename) {

    gROOT->SetBatch(kTRUE);

    TFile* myFile = TFile::Open(infilename.c_str());
    std::cout << myFile << std::endl;
    
    TMVA::mvas("dataset", infilename, static_cast<TMVA::HistType>(3));
    TMVA::mvaeffs("dataset", infilename);
}

```

### PR DESCRIPTION
**Pull request by lmoneta**
This fixes #6479 when running ROOT in batch (with root -b), but still
a problem is present when running ROOT in a standalone application (see #6483).

- improve TMVA::mva fixing a problem in storing output plots.
   - Create the full path to the directory `dataset/plot`
   - Add option via TMVA::Config::VariablePlotting::fPlotFormat
 to specify plot output format

- in TMVA::mvaeffs do not create a GUI dialog to set number of signal and background events for efficiency plots when running in batch mode
- add option to pass events number in TMVA::mvaeffs function call

The last commit provide the fix for ROOT-9483 (https://sft.its.cern.ch/jira/browse/ROOT-9483)

### CODE REVIEW

File: tmva/tmvagui/inc/TMVA/mvaeffs.h [hunk 1]
```diff
@@ -15,7 +15,8 @@
 
 namespace TMVA{
 
-   void mvaeffs(TString dataset, TString fin = "TMVA.root", 
+   void mvaeffs(TString dataset, TString fin = "TMVA.root",
+                Float_t nSingal = 1000, Float_t nBackground = 1000,
```
Comment (stwunsch) [inline tmva/tmvagui/inc/TMVA/mvaeffs.h:19]: Why do you put 1000 here? I don't understand it :thinking:

**Review by stwunsch — COMMENTED** [review]
In principle, LGTM. But I cannot follow fully this one point (see the comment).

File: tmva/tmvagui/inc/TMVA/mvaeffs.h (hunk 1 above)
Comment (stwunsch) [reply tmva/tmvagui/inc/TMVA/mvaeffs.h:19]: ah, and there's a typo in `nSingal`!

Comment (lmoneta) [reply tmva/tmvagui/inc/TMVA/mvaeffs.h:19]: 1000 are default values previously hard-coded in the code (line 533 in mvaeffs.cxx) 
```
StatDialogMVAEffs* gGui = new StatDialogMVAEffs(dataset, graphicsClient->GetRoot(), 1000, 1000);
```

Thank you for finding the typo. 

I will update now this PR with the fix for avoiding #6483

**Review by stwunsch — APPROVED** [review]
Thanks, LGTM!

File: tmva/tmvagui/inc/TMVA/mvaeffs.h (hunk 1 above)
Comment (stwunsch) [reply tmva/tmvagui/inc/TMVA/mvaeffs.h]: Ah I see! Thanks :)
