### PR TITLE
[RF] Fixup `RooLinkedList::setHashTableSize()`

### LINKED ISSUE #20904: [RF] RooWorkspace::data returns null pointer if the workspace contains 52 or more datasets
### Check duplicate issues.

- [x] Checked for duplicates

### Description

as the title says...

reproducer below prints:
`dataset retrieval failed with 52 datasets`

### Reproducer

```python
import ROOT


max_n = 100

for n in range(1, max_n):
    w = ROOT.RooWorkspace("w", "workspace")
    obs = [ROOT.RooRealVar("O", "O", 0., -1., 1.)]
    w.Import(obs)
    for i in range(n):
        ds_name = f"dataset_{i}"
        ds = ROOT.RooDataSet(ds_name, ds_name, obs)
        w.Import(ds)
    test_ds = w.data("dataset_0")
    if not test_ds:
        print(f"dataset retrieval failed with {n} datasets")
        break

```

### ROOT version

```   
------------------------------------------------------------------
  | Welcome to ROOT 6.38.00                        https://root.cern |
  | (c) 1995-2025, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Dec 21 2025, 15:58:20                 |
  | From tags/6-38-00@6-38-00                                        |
  | With g++ (Spack GCC) 14.2.0 std202002                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

`source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2026-01-15`

### Operating system

Alma9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by guitargeek**
This fixes a regression introduced in 318faa0, where I forgot to backfill newly-created hash tables.

A unit test with the reproducer from the issue is also implemented.

Some simple RooFit unit tests are grouped in a single executable to not create too many test executabled.

Closes #20904.

Needs to be backported to ROOT 6.38

### CODE REVIEW

File: roofit/roofitcore/test/testRooLinkedList.cxx [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+      auto found = dataList.FindObject("dataset_0");
+
+      EXPECT_TRUE(found) << "dataset retrieval failed with " << n << " datasets";
+
+      dataList.Delete();
+
+      // No point in continuing
+      if (!found) {
+         break;
+      }
```
Comment (hageboeck) [inline roofit/roofitcore/test/testRooLinkedList.cxx]: Assert aborts after failure, so this gets a bit shorter:
```suggestion
      ASSERT_TRUE(found) << "dataset retrieval failed with " << n << " datasets";

      dataList.Delete();
```

**Comment by guitargeek** [comment]
No problem, I'll split it up. Thanks for the review!

File: roofit/roofitcore/src/RooLinkedList.cxx [hunk 2]
```diff
@@ -342,6 +342,11 @@ void RooLinkedList::setHashTableSize(Int_t size)
...
       _htableName = std::make_unique<HashTableByName>(size);
       _htableLink = std::make_unique<HashTableByLink>(size);
+
+      for (RooLinkedListElem *elem = _first; elem; elem = elem->_next) {
+         _htableName->insert({elem->_arg->GetName(), elem->_arg});
+         _htableLink->insert({elem->_arg, reinterpret_cast<TObject *>(elem)});
+      }
    }
 
    _htableName->reserve(size);
```
Comment (ferdymercury) [inline roofit/roofitcore/src/RooLinkedList.cxx:352]:
```suggestion

      for (RooLinkedListElem *elem = _first; elem; elem = elem->_next) {
         _htableName->insert({elem->_arg->GetName(), elem->_arg});
         _htableLink->insert({elem->_arg, reinterpret_cast<TObject *>(elem)});
      }
   }
   else {
   _htableName->reserve(size);
```

no need to call reserve if you already did `std::make_unique<HashTableByName>(size);` right?

**Review by ferdymercury — CHANGES_REQUESTED** [review]

File: roofit/roofitcore/src/RooLinkedList.cxx (hunk 2 above)
Comment (guitargeek) [reply roofit/roofitcore/src/RooLinkedList.cxx:352]: Yes, I was thinking about that when writing that code. This is a `no-op` if the size is already the same (or at least just a `std::size_t` comparison).

In the end I don't like branchy code, so in that case I decided to not do that microoptimization for the sake of one code branch less.

File: roofit/roofitcore/test/testRooLinkedList.cxx (hunk 1 above)
Comment (guitargeek) [reply roofit/roofitcore/test/testRooLinkedList.cxx]: Cool, I didn't know! Thanks

**Review by ferdymercury — APPROVED** [review]
