### PR TITLE
Fix Display output when friend trees are present

### LINKED ISSUE #8450: [DF] `Display` gets confused by friend columns, prints them twice
The following code:

```cpp
#include <ROOT/RDataFrame.hxx>
#include <TFile.h>
#include <TTree.h>

int main() {
  ROOT::RDataFrame(32).Define("idx", "rdfentry_").Snapshot("t1", "f.root");

  ROOT::RDF::RSnapshotOptions opts;
  opts.fMode = "update";
  ROOT::RDataFrame("t1", "f.root")
      .Define("x", "idx*idx")
      .Snapshot("t2", "f.root", {"x", "idx"}, opts);

  TFile f("f.root");
  auto *tmain = f.Get<TTree>("t1");
  auto *tfriend = f.Get<TTree>("t2");
  tmain->AddFriend(tfriend);

  ROOT::RDataFrame(*tmain).Display(".*", 100)->Print();

  return 0;
}
```
prints

```
idx | t2.x | x   | t2.idx |
0   | 0    | 0   | 0      |
1   | 1    | 1   | 1      |
2   | 4    | 4   | 2      |
3   | 9    | 9   | 3      |
4   | 16   | 16  | 4      |
5   | 25   | 25  | 5      |
```

where `idx` and `t2.idx` are actually two different columns (one in the main tree and the other in the friend tree) but `x` and `t2.x` are two valid spellings of the _same_ column, which should then be printed only once.

I think `Display` gets tripped up by the output of `RLoopManager::GetColumnNames()`, which reports the two valid spellings of `x`. It should instead use the same logic as `Snapshot`, which removes duplicates.

### PR DESCRIPTION
**Pull request by eguiraud**
Before this patch, friend branches or leaves were listed in the output of `GetColumnNames` twice, as `friendname.bname` and as `bname`. Now we only list the longer version.

This fixes #8450 as a side-effect.

This PR also adds a test and improves the related docs.

Rationale for the change in behavior of `GetColumnNames`: currently, in RDataFrame we have (fairly convoluted) logic to retrieve 3 different lists of branch names given a TTree/TChain:

1. a user-readable of list of available column names returned by `df.GetColumnNames()`
2. a larger list of all valid spellings for all column names, used to validate user inputs (this includes all names returned by `df.GetColumnNames()` plus alternative spellings such as `branchname.leafname` when `branchname == leafname`, shorthands for `friendname.branchname` as just `branchname`, etc.
3. a list of only top-level branches that we use as the list of branches to `Snapshot` by default

Before this patch `df.GetColumnNames()` returned multiple valid spellings for the same friend branch. That can be confusing, so I'd rather (try to) return only one valid spelling for each available branch/leaf. For consistency with `Display` and to not withhold information from users, among the two valid spellings we always show the "fully qualified friendname.branchname". Users can still use the shorthand "branchname" if it's not ambiguous, as the relevant documentation now points out.
I think this solution is the sweet spot between not being surprising (to users and to RDF developers), being easy to implement without further complicating or completely refactoring the branch-retrieval logic and being somewhat backward-compatible.

### CODE REVIEW

File: tree/dataframe/src/RDataFrame.cxx [hunk 1]
```diff
@@ -990,19 +990,25 @@ You see how we created one `double` variable for each thread in the pool, and la
...
-t.AddFriend(ft, "myFriend");
+t.AddFriend(&ft, "myFriend");
 
 RDataFrame d(t);
 auto f = d.Filter("myFriend.MyCol == 42");
 ~~~
 
-Friend TTrees with a TTreeIndex are supported from ROOT v6.24.
+Columns coming from the friend trees can be referred to by their full name, like in the example above,
+or the friend tree name can be omitted in case the branch name is not ambiguous (e.g. "MyCol" could be used instead of
```
Comment (etejedor) [inline tree/dataframe/src/RDataFrame.cxx:1009]: I guess this is already tested elsewhere? The fact that one can refer to a non-ambiguous friend column omitting the friend tree name or not.

**Review by etejedor — APPROVED** [review]

File: tree/dataframe/src/RDataFrame.cxx (hunk 1 above)
Comment (eguiraud) [reply tree/dataframe/src/RDataFrame.cxx:1009]: yes `dataframe_friends.cxx` tests it
