### PR TITLE
[hist] Code improvements to `TH1::SmoothArray()`

### LINKED ISSUE #7029: Minor refactoring of TH1::SmoothArray
### Explain what you would like to see improved
Looking through `TH1::SmoothArray`, I noticed a few minor things. I am happy to submit a PR with the following changes if desired.

1) The `hh` array
https://github.com/root-project/root/blob/ac22e5a2952150f59c502c7c09692d261bcf31d9/hist/hist/src/TH1.cxx#L6733
is used to store various intermediate values for the running median calculation and the quadratic interpolation. While it has length 6, the last entry is never used. The fourth and fifth entries are used when calculating the running median with length 5, and while the full array is passed to `TMath::Median`, only the first five entries are used at most (when `medianType==5`).

2) The function also contains an `assert` that can be removed: 
https://github.com/root-project/root/blob/ac22e5a2952150f59c502c7c09692d261bcf31d9/hist/hist/src/TH1.cxx#L6749-L6755
Since `ifirst` is either `1` or `2`, and `ii>=ifirst` in the loop, `ii - ifirst >= 0` is always true.

3) The calculation of the running median with window length 5 for the second-to-last bin
https://github.com/root-project/root/blob/ac22e5a2952150f59c502c7c09692d261bcf31d9/hist/hist/src/TH1.cxx#L6780-L6784
has a slightly misleading comment. Instead of handling the last two entries in the array, this code finds the value for the second-to-last bin by using window length 3.

### Optional: share how it could be improved
`hh` can be length 5, the `assert` can be removed and the comment can be updated.

### To Reproduce
Anything that calls `TH1::SmoothArray`
```c++
#include <TH1.h>

void script() {
    const int nbins = 5;
    double hist[nbins] = {10, 12, 16, 13, 16};
    TH1::SmoothArray(nbins, hist);
}
```
or `TH1::Smooth`.

### Setup
1. ROOT version: 6.22.06
2. Operating system: Debian 10.4
3. How you obtained ROOT: built from source

### Additional context
none

### PR DESCRIPTION
**Pull request by guitargeek**
Closes #7029.

### CODE REVIEW

File: hist/hist/src/TH1.cxx [hunk 1]
```diff
@@ -6781,36 +6782,27 @@ void  TH1::SmoothArray(Int_t nn, Double_t *xx, Int_t ntimes)
             // do all elements beside the first and last point for median 3
             //  and first two and last 2 for median 5
             for  ( ii = ifirst; ii < ilast; ii++)  {
-               assert(ii - ifirst >= 0);
-               for  (int jj = 0; jj < medianType; jj++)   {
-                  hh[jj] = yy[ii - ifirst + jj ];
-               }
-               zz[ii] = TMath::Median(medianType, hh);
+               zz[ii] = TMath::Median(medianType, yy.data() + ii - ifirst);
             }
```
Comment (lmoneta) [inline hist/hist/src/TH1.cxx:6787]: Should not be here `if (kk != 1)` ? 
Otherwise in the case `kk = 2`  the first and last point are not used ? 

And do we have a test for this function ? Maybe we should add one

**Review by lmoneta — COMMENTED** [review]
LGTM!
The changes are fine, the code should do the same as before, but maybe there are some further improvements and it would be nice to include also a test

File: hist/hist/src/TH1.cxx (hunk 1 above)
Comment (guitargeek) [reply hist/hist/src/TH1.cxx:6787]: As we figured out in the offline chat, the first and last point stay the same in the third iteration. I will add a comment to clarify that.

**Review by lmoneta — APPROVED** [review]
Thanks Jonas for the update in the comments and adding a test!
