### PR TITLE
Fix for calling static method with default argument

### LINKED ISSUE #15217: cppyy now fails to call a static method on an object instance
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The new cppyy in ROOT 6.32 has a problem calling a static class method when the call is done on an instance of that class. It worked before and I think conceptually it should still be ok, right?

Edit: actually, I now see that it has something to do with the optional parameter, because a call with 2 arguments works OK
### Reproducer
```
import cppyy
cppyy.cppdef("""
   class MyClass {  public:
   void static statMethod(const std::string& astr, const std::string& path = "") {}
   };""")
obj = cppyy.gbl.MyClass()
obj.statMethod("first")
TypeError: static void MyClass::statMethod(const string& astr, const string& path) =>
    TypeError: could not convert argument 1
```

### ROOT version

6.32-patches

### Installation method

lcg dev3/dev4

### Operating system

alma9

### PR DESCRIPTION
**Pull request by vepadulano**
Backports of 

https://github.com/wlav/CPyCppyy/commit/e40a3fbab87304deb4ed37e217f66d87cc3ceba7
https://github.com/wlav/cppyy/commit/6556a62ee1a3e53b4b2057f46d87b5fe2fe89dbf

Fixes #15217

### CODE REVIEW

**Comment by vepadulano** [comment]
This PR fixes #15217

**Review by guitargeek — APPROVED** [review]
Thank you! This one should be backported to 6.32 I think.

I didn't know that it's possible to preserve authorship in the commits when porting them to a different repo! Which git command did you use? Does is just magically work with patch files?

**Comment by guitargeek** [comment]
You're missing a bracket:
```txt
  /github/home/ROOT-CI/src/bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx: In member function ‘virtual PyObject* CPyCppyy::CPPClassMethod::Call(CPyCppyy::CPPInstance*&, CPyCppyy_PyArgs_t, size_t, PyObject*, CPyCppyy::CallContext*)’:
  Error: /github/home/ROOT-CI/src/bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx:38:43: error: expected ‘)’ before ‘{’ token
     38 |                 (fArgsRequired <= nargs-1) {
        |                                           ^~
        |                                           )
  /github/home/ROOT-CI/src/bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx:37:12: note: to match this ‘(’
     37 |         if ((CPPInstance_Check(arg0) && ((CPPInstance*)arg0)->ObjectIsA() == GetScope()) && \
        |           
```

**Comment by andresailer** [comment]
> Thank you! This one should be backported to 6.32 I think.
> 
> I didn't know that it's possible to preserve authorship in the commits when porting them to a different repo! Which git command did you use? Does is just magically work with patch files?

Maybe he used: https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---allow-unrelated-histories

File: bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx [hunk 1]
```diff
@@ -35,7 +35,7 @@ PyObject* CPyCppyy::CPPClassMethod::Call(CPPInstance*&
     if ((!self || (PyObject*)self == Py_None) && nargs) {
         PyObject* arg0 = CPyCppyy_PyArgs_GET_ITEM(args, 0);
         if ((CPPInstance_Check(arg0) && ((CPPInstance*)arg0)->ObjectIsA() == GetScope()) && \
-                (fArgsRequired <= nargs-1) && (GetMaxArgs() < nargs)) {
+                (fArgsRequired <= nargs-1) {
```
Comment (andresailer) [inline bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx:38]:
```suggestion
                (fArgsRequired <= nargs-1)) {
```
Stealing suggestion from @guitargeek

**Comment by vepadulano** [comment]
> @vepadulano is travelling to Fermilab, so I updated this PR instead. Then it can be merged and backported quickly.

Sorry I didn't see this comment before re-pushing the commits! Anyway, now the changes should be good, let's see if the CI agrees

**Comment by guitargeek** [comment]
It does! I'll take care of the backport then.
