### PR TITLE
Check for existing type before removing whitespaces

### LINKED ISSUE #19022: Can not access REntry fields with DataVector in python
### Check duplicate issues.

- [x] Checked for duplicates

### Description

An error is reported when trying to access REntry fields of type related to DataVector (a class with a default template argument) in python:

```
entry["HLTNav_RepackedFeatures_MET"]      # field of type: DataVector<xAOD::TrigMissingET_v1>

 File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Tue/ROOT/HEAD/x86_64-el9-gcc13-opt/lib/ROOT/_pythonization/_rntuple.py", line 28, in _REntry_getitem
    ptr_proxy = self._CallGetPtr(key)
 File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Tue/ROOT/HEAD/x86_64-el9-gcc13-opt/lib/ROOT/_pythonization/_rntuple.py", line 24, in _REntry_CallGetPtr
    return self._GetPtr[fieldType](key)
TypeError: Could not find "GetPtr<DataVector<xAOD::TrigMissingET_v1>>" (set cppyy.set_debug() for C++ errors):
  Failed to instantiate "GetPtr<DataVector<xAOD::TrigMissingET_v1>>(::ROOT::RFieldToken&)"

```
### Reproducer

```
# standard ATLAS Athena setup:
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh
asetup main--dev3LCG,latest,Athena,gcc14
python

import ROOT
rnt = ROOT.RNTupleReader.Open("EventData", "/afs/cern.ch/user/m/mnowak/public/DAOD_PHYS.rntuple.pool.root")
entry = rnt.CreateEntry()
rnt.LoadEntry(1, entry)
entry["HLTNav_RepackedFeatures_MET"]

```

### ROOT version

master

### Installation method

LCG dev3

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #19022 

See first commit description for an explanation.

Third commit provides a reproducer of the linked issue, removing the first commit will produce the same exception from RField

### CODE REVIEW

**Review by jblomer — APPROVED** [review]
Good work! (Still an issue with the new test to be fixed)

File: core/clingutils/src/TClingUtils.cxx [hunk 1]
```diff
@@ -549,6 +548,17 @@ bool TClingLookupHelper::ExistingTypeCheck(const std::string &tname,
    else return false;
 }
 
+bool TClingLookupHelper::CheckInClassTable(const std::string &tname, std::string &result)
```
Comment (pcanal) [inline core/clingutils/src/TClingUtils.cxx:551]: Consider adding the `////...` seen before other functions ... and documentation string (which indeed is missing in most other functions :( ).

**Review by pcanal — APPROVED** [review]
LGTM.  Thanks.
