### PR TITLE
[treereader] Try harder when looking for a leaf

### LINKED ISSUE #6881: [TTreeReader] Partial leaf/branch names not recognized in cases that TTree::Draw supports
- [x] Checked for duplicates

### Describe the bug

First reported [here](https://root-forum.cern.ch/t/tchain-parallel-reading-more-than-1-branch/42348/13).
For this TTree (the file is linked from the forum post):

```
root [12] DmpMCEvtNtup->Print("NUD_total_ADC*")
******************************************************************************
*Tree    :DmpMCEvtNtup: DAMPE MC Event nTuple Tree                             *
*Entries :    30000 : Total =        42024515 bytes  File  Size =    5331016 *
*        :          : Tree compression factor =   7.90                       *
******************************************************************************
*Br    0 :NUD_total_ADC : nud_total_adc/D                                    *
*Entries :    30000 : Total  Size=     241261 bytes  File Size  =       7509 *
*Baskets :        8 : Basket Size=      32000 bytes  Compression=  32.06     *
*............................................................................*
```

```
DmpMCEvtNtup->Draw("NUD_total_ADC")
```
works, while
```
root [13] TTreeReader r(DmpMCEvtNtup);
root [14] TTreeReaderValue<double> rv(r, "NUD_total_ADC");
root [15] r.Next()
Error in <TTreeReaderValueBase::GetBranchDataType()>: The branch NUD_total_ADC was created using a leaf list and cannot be represented as a C++ type. Please access one of its siblings using a TTreeReaderArray:
Error in <TTreeReaderValueBase::GetBranchDataType()>:    NUD_total_ADC.nud_total_adc
Error in <TTreeReaderValueBase::CreateProxy()>: The branch NUD_total_ADC contains data of type {UNDETERMINED TYPE}, which does not have a dictionary.
(bool) false
```

does not. `TTreeReader` instead requires the full leaf name:

```
root [1] TTreeReader r(DmpMCEvtNtup);
root [2] TTreeReaderValue<double> rv(r, "NUD_total_ADC.nud_total_adc");
root [3] r.Next()
(bool) true
root [4] *rv
(double) -999.00000
```

### Expected behavior

`TTreeReader` should support the same set of "valid branch names" that `TTree::Draw` supports.

### Setup

Reproduced with 6.22/02 and master@4ea4d8943 .

### Additional context

This looks similar to https://sft.its.cern.ch/jira/browse/ROOT-7984 and it is (at least part of) the cause of https://sft.its.cern.ch/jira/browse/ROOT-9558 .

### PR DESCRIPTION
**Pull request by eguiraud**
Before this patch, given a TTree with a branch with name different
from its leaf, e.g. like this:

```
*Br    0 :NUD_total_ADC : nud_total_adc/D
```

TTreeReaderValue failed to retrieve the leaf when the named passed
to the constructor was just "NUD_total_ADC" (while it worked fine
with "NUD_total_ADC.nud_total_adc"). In comparison, in a similar
situation `TTree::Draw` "tries harder" and it assumes that the
desired leaf is the first sub-leaf of the specified branch.

With this patch, TTreeReaderValue tries `FindLeaf` after `GetLeaf`
and as a last resort it picks the branch sub-leaf if it exists and
it is unique.

This fixes #6881.

### CODE REVIEW

**Comment by eguiraud** [comment]
Now with a test :smile:

File: tree/treeplayer/test/leafs.cxx [hunk 1]
```diff
@@ -234,3 +235,18 @@ TEST(TTreeReaderLeafs, MultipleReaders) {
...
+// Test for https://github.com/root-project/root/issues/6881
+TEST(TTreeReaderLeafs, BranchAndLeafWithDifferentNames)
+{
+   TTree t("t", "t");
+   int x = 42;
+   t.Branch("x", &x, "y/I");
+   t.Fill();
+
+   TTreeReader r(&t);
+   TTreeReaderValue<int> rv(r, "x");
```
Comment (pcanal) [inline tree/treeplayer/test/leafs.cxx:248]:
```suggestion
   TTreeReaderValue<int> rv(r, "x");
   TTreeReaderValue<int> rvfull(r, "x.y");
```
and maybe 
```
   TTreeReaderValue<int> rvleaf(r, "y");
```

**Review by pcanal — APPROVED** [review]

File: tree/treeplayer/test/leafs.cxx (hunk 1 above)
Comment (eguiraud) [reply tree/treeplayer/test/leafs.cxx:248]: `TreeReaderValue<int> rvleaf(r, "y");` does not work with branch name "x", leaf name "y":
```
Error in <TTreeReaderValueBase::CreateProxy()>: The tree does not have a branch called y. You could check with TTree::Print() for available branches.
```

is that ok?
