### PR TITLE
[df] Manage resources created via TFile::Get

### LINKED ISSUE #21962: Memory leak when reading RNTuples using RDataFrame
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

I was profiling the FastFrames code using valgrind and I found memory leaks when reading RNTuples using RDataFrame directly. Here an example:

```
==7316== 72 bytes in 1 blocks are definitely lost in loss record 8,904 of 15,942
==7316==    at 0x484DFD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==7316==    by 0x675F5CD: new_ROOTcLcLRNTuple (G__ROOTNTuple.cxx:164)
==7316==    by 0x675F5CD: ROOT::new_ROOTcLcLRNTuple(void*) (G__ROOTNTuple.cxx:163)
==7316==    by 0x6FBADD8: TClass::NewObject(TClass::ENewType, bool) const (TClass.cxx:5058)
==7316==    by 0x6FBB283: TClass::New(TClass::ENewType, bool) const (TClass.cxx:5035)
==7316==    by 0x69B7BE9: TKey::ReadObjectAny(TClass const*) (TKey.cxx:1095)
==7316==    by 0x6971419: TDirectoryFile::GetObjectChecked(char const*, TClass const*) (TDirectoryFile.cxx:1127)
==7316==    by 0x6495409: Get<ROOT::RNTuple> (TDirectory.h:208)
==7316==    by 0x6495409: Get<ROOT::RNTuple> (TDirectoryFile.h:84)
==7316==    by 0x6495409: ROOT::Detail::RDF::CreateLMFromFile(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (RLoopManager.cxx:1257)
==7316==    by 0x640FBA3: ROOT::RDataFrame::RDataFrame(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (RDataFrame.cxx:2182)
==7316==    by 0x62BBC85: Utils::getBranchesFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Utils.cc:695)
==7316==    by 0x62AE86A: SystematicReplacer::readSystematicMapFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::shared_ptr<Systematic>, std::allocator<std::shared_ptr<Systematic> > > const&) (SystematicReplacer.cc:31)
==7316==    by 0x60EB488: MainFrame::processUniqueSample(std::shared_ptr<Sample> const&, UniqueSampleID const&) (MainFrame.cc:298)
==7316==    by 0x60ECF75: MainFrame::processHistogramsSplitPerUniqueSample(std::shared_ptr<Sample> const&) (MainFrame.cc:139)
```

I wrote a simple snippet that reproduces the issue:
```
==31052== 72 bytes in 1 blocks are definitely lost in loss record 6,987 of 9,898
==31052==    at 0x488CFD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==31052==    by 0x4FB45CD: new_ROOTcLcLRNTuple (G__ROOTNTuple.cxx:164)
==31052==    by 0x4FB45CD: ROOT::new_ROOTcLcLRNTuple(void*) (G__ROOTNTuple.cxx:163)
==31052==    by 0x4B63DD8: TClass::NewObject(TClass::ENewType, bool) const (TClass.cxx:5058)
==31052==    by 0x4B64283: TClass::New(TClass::ENewType, bool) const (TClass.cxx:5035)
==31052==    by 0x5BDABE9: TKey::ReadObjectAny(TClass const*) (TKey.cxx:1095)
==31052==    by 0x5B94419: TDirectoryFile::GetObjectChecked(char const*, TClass const*) (TDirectoryFile.cxx:1127)
==31052==    by 0x516E409: Get<ROOT::RNTuple> (TDirectory.h:208)
==31052==    by 0x516E409: Get<ROOT::RNTuple> (TDirectoryFile.h:84)
==31052==    by 0x516E409: ROOT::Detail::RDF::CreateLMFromFile(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (RLoopManager.cxx:1257)
==31052==    by 0x50E8BA3: ROOT::RDataFrame::RDataFrame(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (RDataFrame.cxx:2182)
==31052==    by 0x4024A34: main (memoryLeakRNTuple.cxx:17)
```

### Reproducer

Here it is the minimal reproducer:
```C++
#include "ROOT/RDataFrame.hxx"
#include "ROOT/RNTupleWriter.hxx"
#include "ROOT/RNTupleModel.hxx"
#include <iostream>

int main() {
    const std::string name = "mytuple";
    const std::string file = "test_rntuple.root";

    {
        auto model = ROOT::RNTupleModel::Create();
        model->MakeField<float>("x");
        auto writer = ROOT::RNTupleWriter::Recreate(std::move(model), name, file);
        writer->Fill();
    } 

    ROOT::RDataFrame rdf(name, file);

    return 0;
}
```
Compiled as follow: `c++ -O0 -g -std=c++17 memoryLeakRNTuple.cxx -o memoryLeakRNTuple $(root-config --cflags --libs)`
And executed with valgrind as: `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes   --log-file=valgrind-memoryLeak.txt --suppressions=$ROOTSYS/etc/valgrind-root.supp ./memoryLeakRNTuple`

### ROOT version

ROOT Version: 6.39.01

### Installation method

Build from source

### Operating system

Ubuntu 25.10

### Additional context

_No response_

### LINKED ISSUE #21987: Memory leak when using snapshot to write RNTuples using RDataFrame
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Following the issue #21962, I recompiled root from the branch that solved the issue and tested again in the FastFrames code. This time most of the original "definitely lost" memory leaks disappeared but I found new ones:
```
==8511== 72 bytes in 1 blocks are definitely lost in loss record 8,490 of 14,373
==8511==    at 0x484DFD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==8511==    by 0x67605CD: new_ROOTcLcLRNTuple (G__ROOTNTuple.cxx:164)
==8511==    by 0x67605CD: ROOT::new_ROOTcLcLRNTuple(void*) (G__ROOTNTuple.cxx:163)
==8511==    by 0x6FBBDD8: TClass::NewObject(TClass::ENewType, bool) const (TClass.cxx:5058)
==8511==    by 0x6FBC283: TClass::New(TClass::ENewType, bool) const (TClass.cxx:5035)
==8511==    by 0x69B8BE9: TKey::ReadObjectAny(TClass const*) (TKey.cxx:1095)
==8511==    by 0x6972419: TDirectoryFile::GetObjectChecked(char const*, TClass const*) (TDirectoryFile.cxx:1127)
==8511==    by 0x644F550: Get<ROOT::RNTuple> (TDirectory.h:208)
==8511==    by 0x644F550: Get<ROOT::RNTuple> (TDirectoryFile.h:84)
==8511==    by 0x644F550: (anonymous namespace)::EnsureValidSnapshotRNTupleOutput(ROOT::RDF::RSnapshotOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (RDFSnapshotHelpers.cxx:263)
==8511==    by 0x644FD80: ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper::UntypedSnapshotRNTupleHelper(unsigned int, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&, ROOT::Detail::RDF::RLoopManager*, ROOT::Detail::RDF::RLoopManager*, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (RDFSnapshotHelpers.cxx:887)
==8511==    by 0x61EE230: std::unique_ptr<ROOT::Internal::RDF::RActionBase, std::default_delete<ROOT::Internal::RDF::RActionBase> > ROOT::Internal::RDF::BuildAction<ROOT::Detail::RDF::RNodeBase>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<ROOT::Internal::RDF::SnapshotHelperArgs> const&, unsigned int, std::shared_ptr<ROOT::Detail::RDF::RNodeBase>, ROOT::Internal::RDF::RColumnRegister const&, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (InterfaceUtils.hxx:353)
==8511==    by 0x61F0081: ROOT::RDF::RInterface<ROOT::Detail::RDF::RNodeBase>::Snapshot(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&) (RInterface.hxx:1402)
==8511==    by 0x60F5872: MainFrame::processSingleTruthTreeNtuple(std::shared_ptr<Truth> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<Sample> const&, UniqueSampleID const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (MainFrame.cc:2606)
==8511==    by 0x60F7066: MainFrame::processUniqueSampleNtuple(std::shared_ptr<Sample> const&, UniqueSampleID const&) (MainFrame.cc:600)
==8511== 
==8511== 72 bytes in 1 blocks are definitely lost in loss record 8,491 of 14,373
==8511==    at 0x484DFD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==8511==    by 0x67605CD: new_ROOTcLcLRNTuple (G__ROOTNTuple.cxx:164)
==8511==    by 0x67605CD: ROOT::new_ROOTcLcLRNTuple(void*) (G__ROOTNTuple.cxx:163)
==8511==    by 0x6FBBDD8: TClass::NewObject(TClass::ENewType, bool) const (TClass.cxx:5058)
==8511==    by 0x6FBC283: TClass::New(TClass::ENewType, bool) const (TClass.cxx:5035)
==8511==    by 0x69B8BE9: TKey::ReadObjectAny(TClass const*) (TKey.cxx:1095)
==8511==    by 0x6972419: TDirectoryFile::GetObjectChecked(char const*, TClass const*) (TDirectoryFile.cxx:1127)
==8511==    by 0x644F550: Get<ROOT::RNTuple> (TDirectory.h:208)
==8511==    by 0x644F550: Get<ROOT::RNTuple> (TDirectoryFile.h:84)
==8511==    by 0x644F550: (anonymous namespace)::EnsureValidSnapshotRNTupleOutput(ROOT::RDF::RSnapshotOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (RDFSnapshotHelpers.cxx:263)
==8511==    by 0x644FD80: ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper::UntypedSnapshotRNTupleHelper(unsigned int, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&, ROOT::Detail::RDF::RLoopManager*, ROOT::Detail::RDF::RLoopManager*, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (RDFSnapshotHelpers.cxx:887)
==8511==    by 0x62096B3: std::unique_ptr<ROOT::Internal::RDF::RActionBase, std::default_delete<ROOT::Internal::RDF::RActionBase> > ROOT::Internal::RDF::BuildAction<ROOT::Detail::RDF::RLoopManager>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<ROOT::Internal::RDF::SnapshotHelperArgs> const&, unsigned int, std::shared_ptr<ROOT::Detail::RDF::RLoopManager>, ROOT::Internal::RDF::RColumnRegister const&, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (InterfaceUtils.hxx:353)
==8511==    by 0x620BB2B: ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager>::Snapshot(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&) (RInterface.hxx:1402)
==8511==    by 0x61FF27D: ObjectCopier::copyTreesTo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool, bool) const (ObjectCopier.cc:184)
==8511==    by 0x60F7177: MainFrame::processUniqueSampleNtuple(std::shared_ptr<Sample> const&, UniqueSampleID const&) (MainFrame.cc:619)
```

They seem to point to Snapshot, so I tried to reproduce them with a minimal macro and got the same error plus a new one:
```
==17653== 72 bytes in 1 blocks are definitely lost in loss record 6,992 of 9,905
==17653==    at 0x48D3FD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==17653==    by 0x5B535CD: new_ROOTcLcLRNTuple (G__ROOTNTuple.cxx:164)
==17653==    by 0x5B535CD: ROOT::new_ROOTcLcLRNTuple(void*) (G__ROOTNTuple.cxx:163)
==17653==    by 0x4BAADD8: TClass::NewObject(TClass::ENewType, bool) const (TClass.cxx:5058)
==17653==    by 0x4BAB283: TClass::New(TClass::ENewType, bool) const (TClass.cxx:5035)
==17653==    by 0x66C9BE9: TKey::ReadObjectAny(TClass const*) (TKey.cxx:1095)
==17653==    by 0x6683419: TDirectoryFile::GetObjectChecked(char const*, TClass const*) (TDirectoryFile.cxx:1127)
==17653==    by 0x4E9D550: Get<ROOT::RNTuple> (TDirectory.h:208)
==17653==    by 0x4E9D550: Get<ROOT::RNTuple> (TDirectoryFile.h:84)
==17653==    by 0x4E9D550: (anonymous namespace)::EnsureValidSnapshotRNTupleOutput(ROOT::RDF::RSnapshotOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (RDFSnapshotHelpers.cxx:263)
==17653==    by 0x4E9DD80: ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper::UntypedSnapshotRNTupleHelper(unsigned int, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&, ROOT::Detail::RDF::RLoopManager*, ROOT::Detail::RDF::RLoopManager*, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (RDFSnapshotHelpers.cxx:887)
==17653==    by 0x4057522: std::unique_ptr<ROOT::Internal::RDF::RActionBase, std::default_delete<ROOT::Internal::RDF::RActionBase> > ROOT::Internal::RDF::BuildAction<ROOT::Detail::RDF::RLoopManager>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<ROOT::Internal::RDF::SnapshotHelperArgs> const&, unsigned int, std::shared_ptr<ROOT::Detail::RDF::RLoopManager>, ROOT::Internal::RDF::RColumnRegister const&, std::vector<std::type_info const*, std::allocator<std::type_info const*> > const&) (InterfaceUtils.hxx:353)
==17653==    by 0x40548E4: ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager>::Snapshot(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ROOT::RDF::RSnapshotOptions const&) (RInterface.hxx:1402)
==17653==    by 0x40516CE: ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager>::Snapshot(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::initializer_list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, ROOT::RDF::RSnapshotOptions const&) (RInterface.hxx:1511)
==17653==    by 0x404B48C: snapshot_again(char const*, char const*) (repro_rntuple_leak.cxx:17)
==17653== 
==17653== 216 (184 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 8,282 of 9,905
==17653==    at 0x48D3FD3: operator new(unsigned long) (vg_replace_malloc.c:487)
==17653==    by 0x4B06A3C: TStorage::ObjectAlloc(unsigned long) (TStorage.cxx:292)
==17653==    by 0x6696D9B: operator new (TObject.h:189)
==17653==    by 0x6696D9B: TFile::Recover() (TFile.cxx:2174)
==17653==    by 0x66A258A: TFile::Init(bool) (TFile.cxx:869)
==17653==    by 0x66A332F: TFile::TFile(char const*, char const*, char const*, int) (TFile.cxx:583)
==17653==    by 0x66A763F: TFile::Open(char const*, char const*, char const*, int, int) (TFile.cxx:3979)
==17653==    by 0x4E9E5C9: ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper::Initialize() (RDFSnapshotHelpers.cxx:940)
==17653==    by 0x4067167: ROOT::Internal::RDF::RActionSnapshot<ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper, ROOT::Detail::RDF::RLoopManager>::Initialize() (RActionSnapshot.hxx:137)
==17653==    by 0x4ED757C: ROOT::Detail::RDF::RLoopManager::InitNodes() (RLoopManager.cxx:804)
==17653==    by 0x4EE0C6E: ROOT::Detail::RDF::RLoopManager::Run(bool) (RLoopManager.cxx:943)
==17653==    by 0x405C881: ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager> >::TriggerRun() (RResultPtr.hxx:418)
==17653==    by 0x405ADEC: ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager> >::GetSharedPtr() (RResultPtr.hxx:232)
```

### Reproducer

The minimal reproducer is:
```C++
#include <ROOT/RDataFrame.hxx>

void create_initial(const char* fname, const char* ntname) {
    ROOT::RDataFrame df(5);
    auto df2 = df.Define("x", [](){ return 42; });
    ROOT::RDF::RSnapshotOptions opts;
    opts.fOutputFormat = ROOT::RDF::ESnapshotOutputFormat::kRNTuple;
    df2.Snapshot(ntname, fname, {"x"}, opts);
}

void snapshot_again(const char* fname, const char* ntname) {
    ROOT::RDataFrame df(ntname, fname);
    ROOT::RDF::RSnapshotOptions opts;
    opts.fOutputFormat = ROOT::RDF::ESnapshotOutputFormat::kRNTuple;
    opts.fMode = "UPDATE";
    opts.fOverwriteIfExists = true;
    df.Snapshot(ntname, fname, {"x"}, opts);
}

int main() {
    const char* file  = "repro_leak.root";
    const char* ntuple = "myNTuple";

    create_initial(file, ntuple);   
    snapshot_again(file, ntuple);   
    return 0;
}
```
Compiled with: `g++ -g -O0  -o repro_rntuple_leak     repro_rntuple_leak.cxx     $(root-config --cflags --libs)`
Run with valgrind as: `valgrind     --leak-check=full     --show-leak-kinds=definite     --track-origins=yes     --error-exitcode=1     --log-file=valgrind-repro-leak.txt     --suppressions=$ROOTSYS/etc/valgrind-root.supp     ./repro_rntuple_leak`

### ROOT version

https://github.com/vepadulano/root/tree/gh-21962

### Installation method

Build from source

### Operating system

Ubuntu 25.10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes https://github.com/root-project/root/issues/21962

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]

**Comment by vepadulano** [comment]
Also fixes #21987 since the two issues stem from the same pattern.

**Review by ferdymercury — COMMENTED** [review]
According to my local tests on my branch: the full valgrind memleak report only disappared after I added:

https://github.com/root-project/root/pull/21990/changes/7003f23c05f5fe3a979ae829dec381a50318454f

Maybe with your approach this is not needed anymore, but it would still be useful to add a comment into TFile.cxx as to why key is not deleted / purposely leaked if StreamerInfo not found.

**Comment by vepadulano** [comment]
> According to my local tests on my branch: the full valgrind memleak report only disappared after I added:
> 
> [7003f23](https://github.com/root-project/root/commit/7003f23c05f5fe3a979ae829dec381a50318454f)
> 
> Maybe with your approach this is not needed anymore, but it would still be useful to add a comment into TFile.cxx as to why key is not deleted / purposely leaked if StreamerInfo not found.

I don't see the originally reported leaks with valgrind anymore. There's something weird I still see with the original reproducer:
```
==167542== 216 (184 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 5,720 of 7,089
==167542==    at 0x48412AC: operator new(unsigned long) (vg_replace_malloc.c:488)
==167542==    by 0x49AA1FB: TStorage::ObjectAlloc(unsigned long) (TStorage.cxx:292)
==167542==    by 0x4904F54: TObject::operator new(unsigned long) (TObject.h:189)
==167542==    by 0x5026A13: TFile::Recover() (TFile.cxx:2174)
==167542==    by 0x502186B: TFile::Init(bool) (TFile.cxx:869)
==167542==    by 0x501FE9E: TFile::TFile(char const*, char const*, char const*, int) (TFile.cxx:583)
==167542==    by 0x502F668: TFile::Open(char const*, char const*, char const*, int, int) (TFile.cxx:3979)
==167542==    by 0x7B1727F: ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper::Initialize() (RDFSnapshotHelpers.cxx:894)
==167542==    by 0x4193C3: ROOT::Internal::RDF::RActionSnapshot<ROOT::Internal::RDF::UntypedSnapshotRNTupleHelper, ROOT::Detail::RDF::RLoopManager>::Initialize() (RActionSnapshot.hxx:137)
==167542==    by 0x7B8B1BF: ROOT::Detail::RDF::RLoopManager::InitNodes() (RLoopManager.cxx:804)
==167542==    by 0x7B8CB51: ROOT::Detail::RDF::RLoopManager::Run(bool) (RLoopManager.cxx:943)
==167542==    by 0x41016B: ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager> >::TriggerRun() (RResultPtr.hxx:418)
==167542==
```

Which to me looks like a false positive since that line is using standard `unique_ptr` semantics https://github.com/root-project/root/blob/a9c706ebd6e16bd3724312f3b19ad07fc4a3fb90/tree/dataframe/src/RDFSnapshotHelpers.cxx#L961

**Comment by ferdymercury** [comment]
> 
> Which to me looks like a false positive since that line is using standard `unique_ptr` semantics
>  ==167542==    by 0x5026A13: TFile::Recover() (TFile.cxx:2174)


Yep, saw the same. I don't think it's a false positive, since it got solved with:
https://github.com/root-project/root/commit/7003f23c05f5fe3a979ae829dec381a50318454f

**Comment by vepadulano** [comment]
@ferdymercury now I understand what you mean, apologies for being slow! I see that's indeed another leak, good catch! I think that deserves a separate PR on its own (probably can be reproduced standalone even without RDF).

**Comment by vepadulano** [comment]
@ferdymercury I have created a reproducer and issue for the TFile::Open leak at https://github.com/root-project/root/issues/21997

**Comment by vepadulano** [comment]
@dpiparo this should go to 6.40

**Comment by dpiparo** [comment]
Let's put it in 6.40.00-rc1

File: tree/dataframe/src/RDFSnapshotHelpers.cxx [hunk 1]
```diff
@@ -209,88 +209,40 @@ void CreateFundamentalTypeBranch(TTree &outputTree, RBranchData &bd, void *value
...
-      if (outTree->InheritsFrom("TTree")) {
-         static_cast<TTree *>(outTree)->Delete("all");
+      if (auto existingTree = outFile->Get<TTree>(objName.c_str()); existingTree) {
+         // Special case for TTree. TTree::Delete invalidates the 'this' pointer, so we don't wrap it in a
+         // std::unique_ptr.
+         existingTree->Delete("all");
       } else {
-         outFile->Delete(treeName.c_str());
+         // Ensure deletion of object and all its cycles.
+         outFile->Delete((objName + ";*").c_str());
```
Comment (pcanal) [inline tree/dataframe/src/RDFSnapshotHelpers.cxx:240]: That feels wrong. What if the object is semantically the same?  In that case this deletes all previous 'backup' copies of the object, is that really the intent?  (usually the over-write only over-write the lastest key and keeps the backup)?  

Related though, the `TTree::Delete("all");` has no choice but to delete also the backup copies since it removes from the files all the `TBasket` that they share.
