### PR TITLE
Reimplement TGraph::Sort using std::stable_sort

### LINKED ISSUE #13632: Segmentation fault in TGraph::Sort with large number of entries
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Currently, when using the ```TGraph::Sort``` function with a large number of entries, a segmentation fault (stack overflow) occurs due to deep recursion inside the implemented quicksort algorithm.

### Reproducer

```
import ROOT

d = ROOT.RDataFrame(1000000)
dd = d.Alias("x", "rdfentry_").Define("y", "x*x")
 
graph = dd.Graph("x", "y")
 
c = ROOT.TCanvas()

graph.Sort()
graph.Draw()

```

### ROOT version

v6.29/01

### Installation method

Compiled from source

### Operating system

Fedora 38

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by siliataider**
# This Pull request:

## Changes or fixes:
Reimplement the TGraph::Sort function using std::sort to avoid a segmentation fault when used with a large number of entries.

It's also faster, ex. for a `10000 points`:
```
BEFORE CHANGES -> Sort execution time: 148100 microseconds

AFTER CHANGES -> Sort execution time: 7065 microseconds
```
## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #13632

### CODE REVIEW

File: hist/hist/src/TGraph.cxx [hunk 1]
```diff
@@ -2456,35 +2456,40 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
+   if (high == -1111)
+      high = GetN() - 1;
+
+   // Termination condition
+   if (high <= low)
+      return;
+
+   // Create a vector to hold the indices of the graph points
+   std::vector<Int_t> index(fNpoints);
+   for(Int_t i = 0; i < fNpoints; i++) { index[i] = i; }
```
[the remark this answers is not in the document]
Comment (siliataider) [reply hist/hist/src/TGraph.cxx:2474]: Absolutely, thanks

**Review by couet — APPROVED** [review]
LGTM

File: hist/hist/src/TGraph.cxx [hunk 2]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
 
 void TGraph::Sort(Bool_t (*greaterfunc)(const TGraph*, Int_t, Int_t) /*=TGraph::CompareX()*/,
-                  Bool_t ascending /*=kTRUE*/, Int_t low /* =0 */, Int_t high /* =-1111 */)
+                  Bool_t ascending /*=kTRUE*/, Int_t low /*=0*/, Int_t high /*=-1111*/)
 {
-
-   // set the bit in case of an ascending =sort in X
-   if (greaterfunc == TGraph::CompareX && ascending  && low == 0 && high == -1111)
+   // set the bit in case of an ascending =sort in X   
+   if (greaterfunc == TGraph::CompareX && ascending && low == 0 && high == -1111)
```
Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2463]: I don't know why github highlights these two lines as changed, there doesn't seem to me anything changed here. Can you double check?

File: hist/hist/src/TGraph.cxx [hunk 3]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
-   }
-   // right is final position for the pivot
-   if (right > low)
-      SwapPoints(low, right);
-   Sort(greaterfunc, ascending, low, right - 1);
-   Sort(greaterfunc, ascending, right + 1, high);
+   if (high == -1111) high = fNpoints;
+   
+   // Create a vector to hold the indices of the graph points
+   std::vector<Int_t> index(fNpoints);
```
Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2469]: So in principle a vector of indices would be better described by a `std::vector<ULong64_t>`. But, the `Int_t` type is imposed by the signature of the comparison operator input argument `Bool_t (*greaterfunc)(const TGraph*, Int_t, Int_t)`. Can you please document this in the declaration of the vector?

Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2469]:
```suggestion
   std::vector<Int_t> indices(fNpoints);
```

File: hist/hist/test/test_TGraph.cxx [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+    graph.Sort();
+
+    // Check if the graph is sorted
+    bool isSorted = true;
+    for (int i = 1; i < numEntries; i++) {
+        if (graph.GetX()[i] < graph.GetX()[i - 1]) {
+            isSorted = false;
+            break;
+        }
+    }
```
Comment (vepadulano) [inline hist/hist/test/test_TGraph.cxx:28]: Use https://en.cppreference.com/w/cpp/algorithm/is_sorted here

**Review by vepadulano — CHANGES_REQUESTED** [review]
Great work debugging the issue and finding a solution! See some minor comments attached. Feel free to clean already the commit history after addressing them, in the end we want 1 commit for implementation and 1 for the test.

File: hist/hist/src/TGraph.cxx [hunk 5]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
+   std::iota(index.begin(), index.end(), 0);
+
+   // Sort the indices using the provided comparison function
+   std::sort(index.begin() + low, index.begin() + high + 1, [&](const auto &left, const auto &right) {
+      return (ascending ? !greaterfunc(this, left, right) : greaterfunc(this, left, right));
+   });
+
+   Int_t numSortedPoints = high - low + 1;
```
Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2477]:
```suggestion
   const auto numSortedPoints = high - low + 1;
```

File: hist/hist/src/TGraph.cxx [hunk 6]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
+
+   std::vector<Double_t> fXSorted(numSortedPoints);
+   std::vector<Double_t> fYSorted(numSortedPoints);
+   
+   // Fill the sorted X and Y values based on the sorted indices
+   std::generate(fXSorted.begin(), fXSorted.end(), [low, &index, this]() mutable {return fX[index[low++]];});
```
Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2483]:
```suggestion
   std::generate(fXSorted.begin(), fXSorted.end(), [begin=low, &index, this]() mutable {return fX[index[begin++]];});
```

Although the pass by copy `low` parameter is completely safe, I believe the explicit variable assignment better conveys the intent of having a new index variable that will be local to the `mutable` lambda without modifying external variables.

**Review by vepadulano — COMMENTED** [review]
Another two (extremely minor) comments for your consideration

File: hist/hist/src/TGraph.cxx [hunk 7]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
+   if (high == -1111) high = fNpoints;
+   
+   // Create a vector to hold the indices of the graph points
+   std::vector<Int_t> index(fNpoints);
+   std::iota(index.begin(), index.end(), 0);
+
+   // Sort the indices using the provided comparison function
+   std::sort(index.begin() + low, index.begin() + high + 1, [&](const auto &left, const auto &right) {
+      return (ascending ? !greaterfunc(this, left, right) : greaterfunc(this, left, right));
+   });
```
Comment (ferdymercury) [inline hist/hist/src/TGraph.cxx:2475]: If you want to keep relative order when to points have the same value, then it's better to use std::stable_sort (https://stackoverflow.com/a/12399290/7471760), but maybe it's not useful here.

File: hist/hist/src/TGraph.cxx [hunk 8]
```diff
@@ -2456,35 +2457,35 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
-   Sort(greaterfunc, ascending, right + 1, high);
+   if (high == -1111) high = fNpoints;
+   
+   // Create a vector to hold the indices of the graph points
+   std::vector<Int_t> index(fNpoints);
+   std::iota(index.begin(), index.end(), 0);
+
+   // Sort the indices using the provided comparison function
+   std::sort(index.begin() + low, index.begin() + high + 1, [&](const auto &left, const auto &right) {
+      return (ascending ? !greaterfunc(this, left, right) : greaterfunc(this, left, right));
```
Comment (ferdymercury) [inline hist/hist/src/TGraph.cxx:2476]: can be compacted a little bit with an XOR:
`greaterfunc(this, left, right) != ascending`

**Comment by vepadulano** [comment]
@phsft-bot build

**Review by ferdymercury — APPROVED** [review]

**Comment by couet** [comment]
@phsft-bot build

File: hist/hist/src/TGraph.cxx [hunk 9]
```diff
@@ -2568,6 +2556,25 @@ void TGraph::SwapPoints(Int_t pos1, Int_t pos2)
    SwapValues(fY, pos1, pos2);
 }
 
+////////////////////////////////////////////////////////////////////////////////
+/// Update the fX and fY arrays with the sorted values.
+
+void TGraph::UpdateArrays(std::vector<Int_t> sorting_indices, Int_t numSortedPoints, Int_t low)
```
Comment (ferdymercury) [inline hist/hist/src/TGraph.cxx:2562]: maybe it would be better to mark it as a constant reference to avoid copying if the vector is large? Or otherwise, just marking it as "const".

Comment (vepadulano) [reply hist/hist/src/TGraph.cxx:2562]: Indeed, the signature should be 
```suggestion
void TGraph::UpdateArrays(const std::vector<Int_t> &sorting_indices, Int_t numSortedPoints, Int_t low)
```

For `TGraph` and all derived classes

**Comment by siliataider** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@phsft-bot build

File: hist/hist/src/TGraph.cxx [hunk 10]
```diff
@@ -2455,36 +2456,28 @@ Double_t **TGraph::ShrinkAndCopy(Int_t size, Int_t oend)
...
-         SwapPoints(left, right);
-   }
-   // right is final position for the pivot
-   if (right > low)
-      SwapPoints(low, right);
-   Sort(greaterfunc, ascending, low, right - 1);
-   Sort(greaterfunc, ascending, right + 1, high);
+   // Create a vector to store the indices of the graph data points.
+   // We use std::vector<Int_t> instead of std::vector<ULong64_t> to match the input type
+   // required by the comparison operator's signature provided as `greaterfunc`
```
Comment (vepadulano) [inline hist/hist/src/TGraph.cxx:2471]: Could you also add a comment here about the reason why we needed to use `stable_sort`? Namely, the `std::sort` implementation of libc++ is not standard-compliant until LLVM 14 and this was probably the cause of errors on mac nodes of our CI. We can point to the related github issue https://github.com/llvm/llvm-project/issues/21211

**Review by vepadulano — CHANGES_REQUESTED** [review]
Congratulations for this nice piece of code modernization, with a related test to verify we no longer trigger the segfault for large arrays of values. There are no related failures on any platform now, mac nodes seem to be happy about the changes.

Before merging, can I ask you to address clang-format suggestions and clean the commit history? I believe we should have one commit with the implementations in `inc` and `src` directories and another commit with the new test.

Thank you!

**Comment by vepadulano** [comment]
@phsft-bot build

**Review by vepadulano — APPROVED** [review]
LGTM now! Very nice work, thanks again!
