### PR TITLE
[TMVA] TSpline2: fix memory issues

### LINKED ISSUE #8021: Possible Buffer Overflow in TSpline2
- [x] Checked for duplicates

### Describe the bug

While hunting for some other problem using address sanitizer our unit tests ran into a heap-buffer-overflow in `TSpline2`:

```
Warning in <TH1::TH1>: nbins is <=0 - set to nbins = 1me left: 0 sec) 
Warning in <TH1::TH1>: nbins is <=0 - set to nbins = 1
=================================================================
==903254==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020001549e0 at pc 0x7f530c576a66 bp 0x7ffc17738f20 sp 0x7ffc17738f18
READ of size 8 at 0x6020001549e0 thread T0
    #0 0x7f530c576a65 in TMVA::TSpline2::Eval(double) const root/tmva/tmva/src/TSpline2.cxx:84
    #1 0x7f530c3dd685 in TMVA::PDF::FillSplineToHist() root/tmva/tmva/src/PDF.cxx:539
    #2 0x7f530c3de1e8 in TMVA::PDF::BuildSplinePDF() root/tmva/tmva/src/PDF.cxx:364
    #3 0x7f530c3dfc62 in TMVA::PDF::BuildPDF(TH1 const*) root/tmva/tmva/src/PDF.cxx:299
    #4 0x7f530be8247c in TMVA::MethodBase::CreateMVAPdfs() root/tmva/tmva/src/MethodBase.cxx:2220
    #5 0x7f530beaaa67 in TMVA::MethodBase::TrainMethod() root/tmva/tmva/src/MethodBase.cxx:691
    #6 0x7f530bd67bb7 in TMVA::Factory::TrainAllMethods() root/tmva/tmva/src/Factory.cxx:1173
    #7 0x7f5311416107 in Belle2::MVA::TMVATeacher::trainFactory(TMVA::Factory&, TMVA::DataLoader&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const belle2/mva/methods/src/TMVA.cc:164
    #8 0x7f5311418389 in Belle2::MVA::TMVATeacherClassification::train(Belle2::MVA::Dataset&) const belle2/mva/methods/src/TMVA.cc:303
    #9 0x90859d in (anonymous namespace)::TMVATest_TMVAClassificationInterface_Test::TestBody() belle2/mva/methods/tests/test_TMVA.cc:153
```

Looking at the TH1 Warning about only having one bin and the code in `TSpline2::Eval` there is indeed a problem if the histogram/TGraph has only one point as (bin+2) is accessed.

Now I'm fully aware interpolating a 1 point histogram doesn't make much sense but still, a heap-overflow is not the expected behavior.

### Expected behavior

Probably just return the value itself if only one point is in the graph.

### To Reproduce

```c++
void tspline() {
    double x{1};
    TGraph* g = new TGraph(1, &x, &x);
    TMVA::TSpline2 s("spline", g);
    s.Eval(x);
}
```

### Setup

* ROOT 6.24.0
* GCC 10.2
* Ubuntu 18.04

## Additional Context

I would also like to point out that `TSpline2.cxx` claims it doesn't own the `TGraph` instance in a comment in the constructor and contradicts this ten lines later.

### PR DESCRIPTION
**Pull request by aalkin**
* Avoids deleting non-owned pointer in destructor
* In a case where the graph does not have enough points for interpolation graph values are returned directly and a warning is emitted; this avoids heap overflow when trying to address graph points outside of the point array range

This PR resolves #8021

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

File: tmva/tmva/src/TSpline2.cxx [hunk 1]
```diff
@@ -51,10 +51,7 @@ TMVA::TSpline2::TSpline2( const TString& title, TGraph* theGraph )
 ////////////////////////////////////////////////////////////////////////////////
 /// destructor
 
-TMVA::TSpline2::~TSpline2( void )
-{
-   if (fGraph) delete fGraph; // ROOT's spline classes also own the TGraph
-}
+TMVA::TSpline2::~TSpline2(void) {}
```
Comment (ferdymercury) [inline tmva/tmva/src/TSpline2.cxx:54]: Suggestion: extend on line 42 the documentation, saying that TGraph is not owned by TSpline

Comment (aalkin) [reply tmva/tmva/src/TSpline2.cxx:54]: Updated.

**Review by vepadulano — APPROVED** [review]
LGTM thanks a lot! Let's wait for the CI to finish running

**Review by lmoneta — CHANGES_REQUESTED** [review]
In my opinion,  it would be better to pass a const TGraph pointer in the Graph constructor and have the TSpline2 (and similar also TSpline1) managing the TGraph by making a copy in its constructor. 
It will make the class more self-consistent, it is not critical the constructor of the class and it will be safer. 
If we go with the solution of not managing the TGraph, we should also change how it is currently used (see tmva/src/PDF.cxx); otherwise, there will be a memory leak. 
Actually, looking at the current code in PDF.cxx, there is a memory leak now when using TSpline3 and TSpline5. In those cases, the TGraph passed to the spline classes is not deleted.

**Comment by aalkin** [comment]
Thank you for the additional information. In my personal opinion it would make more sense to have splines non-owning, however the decision is not up to me. To summarize, you suggest changing all the spline classes so they always copy the graph passed by a pointer in the constructor?

**Comment by lmoneta** [comment]
Yes, I would do it for TSpline1 and TSpline2. Note that TSpline3 and TSpline5 from the hist library used the passed TGraph just to get the points. 
A possible alternative, which I would even prefer more, it would be to store in TSpline1 and TSpline2 just the data points (e.g. as 2 std::vector's). Nobody uses these classes for I/O (class version is 0), so it should be fine

**Comment by aalkin** [comment]
Indeed, storing only the points would be even better. I will make the changes.

**Comment by lmoneta** [comment]
Great. Can you please change also in PDF.cxx to not create a new TGraph (for all TSpline classes) see: 

https://github.com/root-project/root/blob/master/tmva/tmva/src/PDF.cxx#L341

Thank you !

File: tmva/tmva/inc/TMVA/TSpline1.h [hunk 2]
```diff
@@ -53,11 +52,10 @@ namespace TMVA {
       virtual void BuildCoeff( void );
       virtual void GetKnot( Int_t i, Double_t& x, Double_t& y ) const;
 
-      const TGraph* GetGraph() const { return fGraph; }
-
    private:
-
-      TGraph *fGraph;  ///< graph that is splined
+      int N;
```
Comment (lmoneta) [inline tmva/tmva/inc/TMVA/TSpline1.h:56]: I don't think N is needed as data member. One can just use X.size()

File: tmva/tmva/inc/TMVA/TSpline1.h [hunk 3]
```diff
@@ -53,11 +52,10 @@ namespace TMVA {
...
+      std::vector<Double_t> X;
```
Comment (lmoneta) [inline tmva/tmva/inc/TMVA/TSpline1.h:57]: It would be better to follow the ROOT coding convention and have data members starting with the letter `f`.
So can you please rename `X` -> `fX`  and `Y` -> `fY` ?

**Review by lmoneta — COMMENTED** [review]
Thank you for improving the TSpline1 and 2  classes. 
I have just a comment on using N as class data member and the convention for their names.

**Review by lmoneta — APPROVED** [review]
LGTM!!
Thank you for this contribution!
