### PR TITLE
Automatically create an RDataFrame from TTree/RNTuple

### LINKED ISSUE #12932: Create RDataFrame from TTree or RNTuple, without specifying which one
### Explain what you would like to see improved

Currently, RDataFrame needs to be told whether the file contains a TTree or an RNTuple. We want RDF figure this one out automatically, so users can use the same code, whether TTree or RNTuple

### Share how it could be improved

_No response_

### How to reproduce?

Dunno

### ROOT version

master

### How did you install ROOT?

n/a

### Which operating system are you using?

Any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #12932

### CODE REVIEW

**Comment by vepadulano** [comment]
There are at least two things preventing this approach from working:
1. Opening the file for recognition of the data source type assumes that the input string `fileNameGlob` is actually a file name (`TFile::Open` doesn't accept globs, rightfully)
2. It introduces a broken interaction with `Snapshot` at https://github.com/root-project/root/blob/e70af8243c601b6b32b515d90c1f16500745d904/tree/dataframe/inc/ROOT/RDF/RInterface.hxx#L2837-L2838 . Since `Snapshot` creates a new `RDataFrame` invoking the constructor with two strings *before* the `Snapshot` actually happens, the file will always not exist. This alone is practically a blocker for this approach

**Comment by eguiraud** [comment]
My 2 cents:

1. You have to expand the glob to an actual list of files and grab e.g. the first file in the list. One (not elegant) way to do it is to go through `TChain::Add`. Just performing the glob expansion with TChain does not require that there are TTrees in the file:
```
/tmp touch foo.root
/tmp touch bar.root
/tmp root -l
root [0] TChain c;
root [1] c.Add("*.root")
(int) 2
root [2] c.GetListOfFiles()->GetEntries()
(int) 2
root [3] c.GetListOfFiles()->At(0)->GetName()
(const char *) ""
root [4] c.GetListOfFiles()->At(0)->GetTitle()
(const char *) "/tmp/bar.root"
root [5] c.GetListOfFiles()->At(1)->GetTitle()
(const char *) "/tmp/foo.root"
```

2. The quick fix is to assume TTree if the file does not exist. The better fix is probably to delay the decision to right before the beginning of the event loop.

**Comment by vepadulano** [comment]
> You have to expand the glob to an actual list of files

Yes, I agree. This highlights a concrete use case for moving the globbing logic of `TChain` out of class. *It shouldn't be hard to do*:tm:

**Comment by vepadulano** [comment]
The current failing tests demonstrate possibly the only real blocker for this PR. The constructor now always opens the file to check the data format, and this is a backwards-incompatible change. Not a terrible one per se, but for example [test_headnode.py](https://github.com/root-project/root/blob/855f1790ab9a37637d7ddcc963b43247972f1d6e/bindings/experimental/distrdf/test/test_headnode.py#L153) test relies on the current constructor not opening the file argument. Maybe users in the wild could have a similar pattern, although this type of "exploit" may be also labeled as "unwanted/unsupported".

I think we need some concrete opinions from @eguiraud , @jblomer , @Axel-Naumann , @pcanal

**Comment by eguiraud** [comment]
As per the discussion with Vincenzo, we think we can provide the desired functionality without exposing `RSnapshotOptions::fOutputFormat` to users (until we can actually provide an output format other than TTree) and without breaking backwards-compatibility.

**Comment by vepadulano** [comment]
> we can always discuss separately whether we want to error out at construction time if an input file does not exist (I think we might want to)

I discussed about this at the I/O meeting last week, other comments were in favor of changing the behaviour and erroring out at construction time if the file does not exist. I think I will still move that part to another PR.

**Comment by vepadulano** [comment]
The new CI is able to trigger this kind of error in distrdf tests
```
  Error in <TROOT::WriteTObject>: The current directory (PyROOT) is not associated with a file. The object (x) has not been written.
```

Which (hopefully) stems from the fact we open the file in the RDF constructor without a `TDirectory::TContext` to save the state of the previous directory. I'll update the code to use TContext.

The real problem is that Jenkins is unable to trigger this error....

**Comment by eguiraud** [comment]
What is this error in readTotemNtuple? :eyes:

**Comment by eguiraud** [comment]
Ah I didn't realize there was a sibling PR to roottest that changed the reference, thanks.

I don't know why jenkins behaves differently from your local build, but taking a step back, why are you silencing these warnings?

**Comment by vepadulano** [comment]
>  why are you silencing these warnings?

This is to implement the changes in the way we discussed. We keep backwards compatibility for this PR, i.e. we don't throw an exception and we delegate the errors regarding non-existing files to the first time a branch is accessed, like it is currently done in RDF. The actual improvement, i.e. early error out, is left for another PR

**Comment by eguiraud** [comment]
I don't understand why to keep backwards compatibility we need to silence warnings that were previously not silenced..?

**Comment by vepadulano** [comment]
> I don't understand why to keep backwards compatibility we need to silence warnings that were previously not silenced..?

The warning is raised at the first `TFile::Open`.

Previously, that happened whenever a `Filter`,`Define` or any operation needed to access a branch of the TTree, i.e. after construction time. With this PR, it happens at construction time.

In order to keep backwards compatibility, we discussed that the call to `TFile::Open`, at least for the purposes of this PR, should not let the user know that their file cannot be opened (yet), and that it is deferred to the first `Define` as it currently happens.

Thus, we both do not raise an exception and we also have to hide the `Error: TFile cannot be opened` print statements to std::err that `TFile::Open` will trigger. So that's why I used the `RIgnoreErrorLevelRAII`.

The fact that the warnings of the `readTotem` test are also silenced is merely a side-effect of having to implement the funciton in the way we discussed.

At this point though, I am quite convinced that this is bringing more confusion than anything else, especially for a temporary quirk that I would have corrected in the next PR anyway. So I think I will just go with the final solution that we decided, i.e. throwing an exception right away at construction time. 

Note that I will still need to modify the `.ref` file of the `readTotem` test because the warnings about the missing dictionaries will happen at construction time rather than during the first `Foreach` call.

**Comment by eguiraud** [comment]
Ah I see, thanks

> I think I will just go with the final solution that we decided, i.e. throwing an exception right away at construction time.

sounds good

**Comment by vepadulano** [comment]
The `.ref` file in roottest now depends on the presence of `root7`... I'll see how to inject this knowledge in roottest

**Comment by vepadulano** [comment]
All builds are green now, this is ready for another review @jblomer , @eguiraud

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by eguiraud** [comment]
@phsft-bot build please

File: tree/dataframe/src/RDataFrame.cxx [hunk 1]
```diff
@@ -1562,15 +1631,37 @@ RDataFrame::RDataFrame(std::string_view treeName, TDirectory *dirPtr, const Colu
...
+/// Private constructor, only used by the Snapshot operation
+RDataFrame::RDataFrame(int /*tagForTTree*/, std::string_view datasetName, std::string_view fileNameGlob,
+                       const ColumnNames_t &defaultColumns)
+   : RInterface(CreateLMFromTTree(datasetName, fileNameGlob, defaultColumns))
+{
+}
+
+/// The function is declared in RInterface.hxx and defined here. This allows
+/// creating `shared_ptr<ROOT::RDataFrame>` using the private constructor in
+/// in functions that are defined in RInterface.hxx, even though RDataFrame.hxx
```
Comment (eguiraud) [inline tree/dataframe/src/RDataFrame.cxx:1650]: typo "in\nin"

File: tree/dataframe/src/RDataFrame.cxx [hunk 2]
```diff
@@ -1562,15 +1631,37 @@ RDataFrame::RDataFrame(std::string_view treeName, TDirectory *dirPtr, const Colu
...
+/// depends from RInterface.hxx.
+std::shared_ptr<ROOT::RDataFrame>
+ROOT::Internal::RDF::CreateRDFFromTTree(int tagForTTree, std::string_view treeName, std::string_view fileNameGlob,
+                                        const ROOT::RDF::ColumnNames_t &defaultColumns)
+{
+   return std::shared_ptr<ROOT::RDataFrame>(new ROOT::RDataFrame(tagForTTree, treeName, fileNameGlob, defaultColumns));
```
Comment (eguiraud) [inline tree/dataframe/src/RDataFrame.cxx:1656]: consider using `make_shared` instead (shortens the line and avoids the raw `new`)

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx [hunk 3]
```diff
@@ -89,6 +89,11 @@ class GraphCreatorHelper;
 void ChangeEmptyEntryRange(const ROOT::RDF::RNode &node, std::pair<ULong64_t, ULong64_t> &&newRange);
 void ChangeSpec(const ROOT::RDF::RNode &node, ROOT::RDF::Experimental::RDatasetSpec &&spec);
 void TriggerRun(ROOT::RDF::RNode node);
+#ifdef R__HAS_ROOT7
+std::shared_ptr<ROOT::RDataFrame> CreateRDFFromTTree(int tagForTTree, std::string_view treeName,
```
Comment (eguiraud) [inline tree/dataframe/inc/ROOT/RDF/RInterface.hxx:93]: the tag parameter here does not seem to be necessary

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx [hunk 4]
```diff
@@ -2849,8 +2859,14 @@ private:
          std::string(filename), std::string(dirname), std::string(treename), columnListWithoutSizeColumns, options});
 
       ::TDirectory::TContext ctxt;
+#ifdef R__HAS_ROOT7
+      int tagForTTree = 1; // Meaningless type, used to call the right constructor
+      auto newRDF = ROOT::Internal::RDF::CreateRDFFromTTree(tagForTTree, fullTreeName, filename,
+                                                            /*defaultColumns=*/columnListWithoutSizeColumns);
```
Comment (eguiraud) [inline tree/dataframe/inc/ROOT/RDF/RInterface.hxx:2865]: note that Snapshot only has to return a `RInterface<RLoopManager>`, so I think most of the gymnastic here to avoid the dependency cycle between RInterface and RDataFrame can be removed: it should be simpler to construct a `RInterface<RLoopManager>` directly, leaving the `RDataFrame` type out of the game.

IIUC you could move `CreateLMFrom{Tree,NTuple}` to `RLoopManager.{hxx,cxx}` and call `CreateLMFromTree` directly from here without risking dependency cycles and without needing an extra mechanism to bypass the file existence check.

File: tree/dataframe/src/RDataFrame.cxx [hunk 5]
```diff
@@ -1520,6 +1526,69 @@ Examples of implemented progress bars can be seen by running [Higgs to Four Lept
 */
 // clang-format on
 
+namespace {
+
+std::shared_ptr<ROOT::Detail::RDF::RLoopManager> CreateLMFromTTree(std::string_view datasetName,
```
Comment (eguiraud) [inline tree/dataframe/src/RDataFrame.cxx:1531]: if the above refactoring idea pans out these could become a single constructor in RLoopManager, e.g. `RLoopManager(EInputType, datasetName, fileNameGlob, defaultColumns)` with `EInputType` being an `enum class` with values `kTTree`, `kRNTuple`, `kInferred` or similar.

**Review by eguiraud — COMMENTED** [review]
Thank you @vepadulano , I have some refactoring suggestions to simplify commit number three, let's see if I haven't missed anything :sweat_smile:

File: tree/dataframe/src/RDataFrame.cxx (hunk 5 above)
Comment (vepadulano) [reply tree/dataframe/src/RDataFrame.cxx]: For now I will keep the functions separate and maybe converge on a single constructor in a separate PR

**Comment by hahnjo** [comment]
As a drive-by comment, just to throw out the idea: Instead of opening the file at construction time, we could invent an "indeterminate wrapper datasource" that opens the file only once needed and then decides to internally create a datasource for either TTree or RNTuple, forwarding future calls through one layer of indirection. As far as I can tell (without having implemented it), this should solve the problem of dealing with partially constructed `RDataFrame`s and not require a backwards-incompatible change in behavior. The cost would be one additional indirection, but this may be just fine given that `RDataSource` is already a `virtual` interface...

**Comment by vepadulano** [comment]
@hahnjo Thanks for the input, I am also wary about the backwards-incompatible change in behaviour. Your idea of the "lazy" wrapper source is sound and I also don't see major blockers against implementing it.

On the other hand, the current behaviour of RDataFrame, which does not open files at construction time but at JITting time, is not really a design choice but rather a side-effect of using `TChain` as the concrete IO backend for all TTree-based RDataFrame instances, whether the user is processing a single file or more. Every other data source, including the RNTuple data source, opens a file. We could foresee that even with chains of RNTuple we still want to open the first file right away to derive the schema and some metadata. From my current understanding and the time spent on this PR, my current belief is that the backwards-incompatible change is almost a bugfix, and opening just one file does not introduce practical penalties in users' workflows, rather it also allows for early error catching potentially. What do you think about this?

**Review by martamaja10 — APPROVED** [review]
Thanks for these few final changes Vincenzo!

**Comment by vepadulano** [comment]
I tested offline @hahnjo 's proposal, as it would have had the nice advantage of avoiding the backwards-incompatible change brought by the current status of this PR. A summary of the insights I gathered:

1. There are some technical obstacles, the main one being that we don't have a single, coherent code path for all data sources. Crucially, `TTree` is handled differently from any other data format (i.e. it doesn't use the `RDataSource` mechanism). This practically means that I cannot create a lazy `RDataSource` to handle them all. But in first approximation this could have been solved with one extra branching
2. It is not straightforward to know where exactly to trigger the inferring of the data source. Practically, this is needed at the very latest in `RLoopManager::Run`, i.e. right before the start of the event loop. But it can also be needed before that, namely whenever a node of the computation graph is created it might need to know about the column names it uses, so the dataset schema must be gathered thus the data source type must be inferred. Admittedly, this is also another fixable problem with a better documentation or cleaner code to explain exactly at what point of any RDataFrame application the loop manager would need the dataset schema in place
3. Probably the greatest obstacle posed by this idea is that it indeed fixes one backwards-incompatible change, but introduces another one. RDataFrame allows some operations to run without triggering the computation graph, actually without even needing to populate the computation graph at all. Specifically, `Describe` produces a string description of some metadata of the dataset wrapped by the RDataFrame, e.g. the name of the TTree and the file it is stored in. This info doesn't need file opening (at least with `TChain`). The lazy data source would effectively change the behaviour of `Describe` as it would hide the type of the data source even if in principle it could be known (supposing the same workflow with TChain as before)

Bottom line, it was worth to investigate this idea as it also gave more insights on some of the not-immediately-evident parts of the machinery. Given the insights listed above, I decide to merge the PR as it is.
