### PR TITLE
[ntuple] Introduce schema IDs and use for field tokens

### LINKED ISSUE #16236: [ntuple] Improve field token usage for parallel writing
A `REntry::RFieldToken` is currently bound to a specific model id. This prevents the following usage from working with parallel writing, as I wanted to recommend it to @siliataider:
```c++
#include <ROOT/RNTupleModel.hxx>
#include <ROOT/RNTupleParallelWriter.hxx>

using namespace ROOT::Experimental;

void parallel_writer() {
  auto model = RNTupleModel::CreateBare();
  model->MakeField<float>("e");
  model->Freeze();

  auto token = model->GetToken("e");

  auto writer = RNTupleParallelWriter::Recreate(std::move(model), "ntpl", "ntpl.root");

  // per thread
  auto context = writer->CreateFillContext();
  auto entry = context->CreateEntry();

  float e;
  entry->BindRawPtr(token, &e);
}
```

```
terminate called after throwing an instance of 'ROOT::Experimental::RException'
  what():  invalid token for this entry, make sure to use a token from the same model as this entry.
At:
  void ROOT::Experimental::REntry::EnsureMatchingModel(RFieldToken) const
```

This is because the `RNTupleParallelWriter` internally clones the model, so every thread has to get tokens from its entry:
```c++
  // per thread
  auto context = writer->CreateFillContext();
  auto entry = context->CreateEntry();
  auto token = entry->GetToken("e");
```

In principle, we could allow using a single set of tokens for all entries from any cloned model. This requires either not changing the model id when cloning, or having a second model id with that semantic.

### PR DESCRIPTION
**Pull request by hahnjo**
When cloning a frozen `RNTupleModel`, the schema ID will not change. This allows to use one set of field tokens for all model clones during parallel writing. Also allow creating tokens during model construction, before freezing, with already works when going via the default entry.

Closes #16236

### CODE REVIEW

File: tree/ntuple/v7/src/RNTupleModel.cxx [hunk 1]
```diff
@@ -416,17 +423,14 @@ std::unique_ptr<ROOT::Experimental::REntry> ROOT::Experimental::RNTupleModel::Cr
 
 ROOT::Experimental::REntry::RFieldToken ROOT::Experimental::RNTupleModel::GetToken(std::string_view fieldName) const
 {
-   if (!IsFrozen())
-      throw RException(R__FAIL("invalid attempt to get field token of unfrozen model"));
-
```
Comment (jblomer) [inline tree/ntuple/v7/src/RNTupleModel.cxx:421]: This seems to be a second, strictly speaking unrelated change that allows creating tokens for models under construction. This is fine but we may want to call it out in the PR description.

**Review by jblomer — APPROVED** [review]
Thanks! LGTM.

File: tree/ntuple/v7/src/RNTupleModel.cxx (hunk 1 above)
Comment (hahnjo) [reply tree/ntuple/v7/src/RNTupleModel.cxx:421]: Correct, I ran into this for the test of field tokens with parallel writing and decided to include it in this PR (instead of freezing manually). I extended the description accordingly.
