### PR TITLE
[ntuple] specialize RField for TObject

### LINKED ISSUE #14808: [ntuple] TObject serialization faulty
### Check duplicate issues.

- [X] Checked for duplicates

### Description

RNTuple serializes the two persistent fields of TObject, `fBits` and `fUniqueID`, as is. That is wrong, RNTuple needs to do what the `TObject` streamer does.

### Reproducer

Write a `TObject` into an RNTuple (to be refined)

### ROOT version

master

### Installation method

sources

### Operating system

Linux

### Additional context

Follow-up from https://github.com/root-project/root/pull/14728#discussion_r1489689085

### PR DESCRIPTION
**Pull request by jblomer**
Implement special treatment for fBits. Disable RNTuple I/O for referenced objects. Locks I/O support for TObject to class version 1, assuming that TObject won't further evolve.

Fixes #14808

### CODE REVIEW

File: tree/ntuple/v7/src/RField.cxx [hunk 1]
```diff
@@ -547,6 +548,8 @@ ROOT::Experimental::RFieldBase::Create(const std::string &fieldName, const std::
       return result;
    } else if (canonicalType == "std::string") {
       result = std::make_unique<RField<std::string>>(fieldName);
+   } else if (canonicalType == "TObject") {
+      result = std::make_unique<RTObjectField>(fieldName);
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RField.cxx:552]: should this be
```suggestion
      result = std::make_unique<RField<TObject>>(fieldName);
```
? (if not, I need to look into the distinction between `RTObjectField` and the `RField<>` specialization again)

**Review by hahnjo — COMMENTED** [review]
If I understand `RClassField` correctly, this change should also allow us to store objects inheriting from `TObject` because it's just a base. Maybe it would be good to have a test for that?

File: tree/ntuple/v7/src/RField.cxx (hunk 1 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:552]: It shouldn't matter which one it is.

Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:552]: Oh, now I understand: we don't need `RTObjectField` at all, just the template specialization. I'll fix that.

File: tree/ntuple/v7/src/RField.cxx [hunk 2]
```diff
@@ -1649,6 +1652,131 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+   return TClass::GetClass("TObject");
+}
+
+std::size_t ROOT::Experimental::RField<TObject>::GetOffsetOfMember(const char *name)
+{
+   for (auto dataMember : ROOT::Detail::TRangeStaticCast<TDataMember>(*GetClass()->GetListOfDataMembers())) {
+      if (strcmp(name, dataMember->GetName()) == 0)
+         return dataMember->GetOffset();
+   }
+   throw RException(R__FAIL("invalid data member"));
```
Comment (vepadulano) [inline tree/ntuple/v7/src/RField.cxx:1666]:
```suggestion
   throw RException(R__FAIL('\'' + std::string(name) + '\'' + "is an invalid data member"));
```

File: tree/ntuple/v7/src/RField.cxx [hunk 3]
```diff
@@ -1649,6 +1652,131 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+}
+
+ROOT::Experimental::RField<TObject>::RField(std::string_view fieldName)
+   : ROOT::Experimental::RFieldBase(fieldName, "TObject", ENTupleStructure::kRecord, false /* isSimple */)
+{
+   R__ASSERT(GetClass()->GetClassVersion() == 1);
```
Comment (vepadulano) [inline tree/ntuple/v7/src/RField.cxx:1672]: Why is this needed?

Comment (vepadulano) [reply tree/ntuple/v7/src/RField.cxx:1672]: That is, are we expecting TObject to ever change class version?

File: tree/ntuple/v7/src/RField.cxx [hunk 4]
```diff
@@ -1649,6 +1652,131 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
 
 //------------------------------------------------------------------------------
 
+TClass *ROOT::Experimental::RField<TObject>::GetClass()
+{
+   return TClass::GetClass("TObject");
```
Comment (vepadulano) [inline tree/ntuple/v7/src/RField.cxx:1657]: I don't remember right now if consecutive calls to TClass::GetClass will use a cached value. Otherwise since this is only calling it for `TObject` we might want to cache it here.

File: tree/ntuple/v7/test/rfield_class.cxx [hunk 5]
```diff
@@ -14,3 +19,74 @@ TEST(RNTuple, TClass) {
...
+      auto heapObj = std::make_unique<TObject>();
+      EXPECT_TRUE(heapObj->TestBit(TObject::kIsOnHeap));
+      EXPECT_TRUE(heapObj->TestBit(TObject::kNotDeleted));
+      heapObj->SetUniqueID(137);
+      entry->BindRawPtr("obj", heapObj.get());
+      writer->Fill(*entry);
+
+      heapObj->~TObject();
+      EXPECT_FALSE(heapObj->TestBit(TObject::kNotDeleted));
+      writer->Fill(*entry);
```
Comment (vepadulano) [inline tree/ntuple/v7/test/rfield_class.cxx:41]: Interesting, what are we expecting this to do now that the TObject was deleted?

**Review by vepadulano — CHANGES_REQUESTED** [review]
The overall logic looks good, some minor comments/questions

File: tree/ntuple/v7/src/RField.cxx (hunk 3 above)
Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1672]: We should not expect `TObject` to ever change and thus we should cost a run-time check for it.  (A regular `assert` costing only in debug build would be fine).

File: tree/ntuple/v7/src/RField.cxx [hunk 6]
```diff
@@ -1649,6 +1655,130 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+{
+   return TObject::Class();
+}
+
+std::size_t ROOT::Experimental::RField<TObject>::GetOffsetOfMember(const char *name)
+{
+   if (auto dataMember = GetClass()->GetDataMember(name)) {
+      return dataMember->GetOffset();
+   }
+   throw RException(R__FAIL('\'' + std::string(name) + '\'' + "is an invalid data member"));
```
Comment (vepadulano) [inline tree/ntuple/v7/src/RField.cxx:1668]: Sorry I think an extra whitespace slipped in my last review
```suggestion
   throw RException(R__FAIL('\'' + std::string(name) + '\'' + " is an invalid data member"));
```

File: tree/ntuple/v7/test/rfield_class.cxx (hunk 5 above)
Comment (vepadulano) [reply tree/ntuple/v7/test/rfield_class.cxx:45]: Ok, so what is `writer->Fill` going to fill with? A valid but "empty" TObject? What is the semantic meaning of doing what's happening in these few lines?

Comment (jblomer) [reply tree/ntuple/v7/test/rfield_class.cxx:45]: It may not make much sense, semantically. It's here to test that RNTuple does the same than the `TObject` custom streamer.

Comment (pcanal) [reply tree/ntuple/v7/test/rfield_class.cxx:45]: Consider adding a comment that the code is weird looking on purpose so that it is not 'fixed' by a  later maintainer.

File: tree/ntuple/v7/src/RField.cxx [hunk 7]
```diff
@@ -1652,6 +1658,130 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+{
+   // Cf. TObject::Streamer()
+
+   auto *obj = static_cast<const TObject *>(from);
+   if (obj->TestBit(TObject::kIsReferenced)) {
+      throw RException(R__FAIL("RNTuple I/O on referenced TObject is unsupported"));
+   }
+
+   std::size_t nbytes = 0;
+   nbytes += CallAppendOn(*fSubFields[0], reinterpret_cast<const unsigned char *>(from) + GetOffsetUniqueID());
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1706]: Are the `from` and the offset correct calculated when `TObject` is not the first base?  I.e. Can you add a test with:
```
class Left { ... };
class Derived : public Left, TObject {};
```

Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:1741]: The offset comes from `TBaseClass::GetDelta()` in the `RFieldClass` constructor. I added a unit test for the described case.

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1741]: Somewhat unrelated question, is that code (using `GetDelta`) sturdy against diamond inheritance? (as in either supports it or explicitly rejects it)

**Comment by jblomer** [comment]
Test failures seem unrelated. @vepadulano @pcanal is there anything else before this can be merged?

File: tree/ntuple/v7/inc/ROOT/RField.hxx [hunk 8]
```diff
@@ -2388,6 +2389,47 @@ public:
...
+   void ReadGlobalImpl(NTupleSize_t globalIndex, void *to) final;
+
+   void OnConnectPageSource() final;
+
+public:
+   static std::string TypeName() { return "TObject"; }
+
+   RField(std::string_view fieldName);
+   RField(RField &&other) = default;
+   RField &operator=(RField &&other) = default;
```
Comment (vepadulano) [inline tree/ntuple/v7/inc/ROOT/RField.hxx:2423]: Is copy allowed or should we disable it explicitly?

File: tree/ntuple/v7/inc/ROOT/RField.hxx [hunk 9]
```diff
@@ -2388,6 +2389,47 @@ public:
...
 
+/// TObject requires special handling of the fBits and fUniqueID members
+template <>
+class RField<TObject> final : public RFieldBase {
+   class RTObjectDeleter : public RDeleter {
+   public:
+      void operator()(void *objPtr, bool dtorOnly) final;
+   };
+
+   static TClass *GetClass();
```
Comment (vepadulano) [inline tree/ntuple/v7/inc/ROOT/RField.hxx:2400]: I wonder whether the `GetClass` method can be removed since it's an alias to `TObject::Class` in any case.

File: tree/ntuple/v7/test/CustomStruct.hxx [hunk 10]
```diff
@@ -208,4 +209,17 @@ class Cyclic {
...
+public:
+   float x = 1.0;
+   virtual ~Left() = default;
+   ClassDef(Left, 1)
+};
+
+class DerivedFromLeftAndTObject : public Left, public TObject {
+public:
+   virtual ~DerivedFromLeftAndTObject() = default;
+   ClassDef(DerivedFromLeftAndTObject, 1)
```
Comment (vepadulano) [inline tree/ntuple/v7/test/CustomStruct.hxx:222]: I believe this should be necessary for things to work as expected right?
```suggestion
   ClassDefOverride(DerivedFromLeftAndTObject, 1)
```

File: tree/ntuple/v7/test/rfield_class.cxx [hunk 11]
```diff
@@ -18,3 +26,107 @@ TEST(RNTuple, TClass) {
    FileRaii fileGuard("test_ntuple_tclass.root");
    auto ntuple = RNTupleWriter::Recreate(std::move(model), "f", fileGuard.GetPath());
 }
+
+TEST(RTNuple, TObject)
+{
+   EXPECT_THROW(std::make_unique<ROOT::Experimental::RClassField>("obj", "TObject"), RException);
```
Comment (vepadulano) [inline tree/ntuple/v7/test/rfield_class.cxx:32]: Although it's just one line, this is another test case IIUC. It should go in another TEST body

Comment (vepadulano) [reply tree/ntuple/v7/test/rfield_class.cxx:32]: Or at least a comment saying that this is testing the functionality of another class

File: tree/ntuple/v7/test/rfield_class.cxx [hunk 12]
```diff
@@ -18,3 +26,107 @@ TEST(RNTuple, TClass) {
...
+
+   auto heapObj = std::make_unique<TObject>();
+   entry->BindRawPtr("obj", heapObj.get());
+   reader->LoadEntry(2, *entry);
+   EXPECT_EQ(0u, heapObj->GetUniqueID());
+   EXPECT_TRUE(heapObj->TestBit(TObject::kIsOnHeap));
+   EXPECT_TRUE(heapObj->TestBit(TObject::kNotDeleted));
+
+   heapObj->SetBit(TObject::kIsReferenced);
+   EXPECT_THROW(reader->LoadEntry(2, *entry), RException);
```
Comment (vepadulano) [inline tree/ntuple/v7/test/rfield_class.cxx:88]: Also this part seems like it's testing some other functionality, maybe a comment or a separate test

File: tree/ntuple/v7/test/rfield_class.cxx [hunk 13]
```diff
@@ -18,3 +26,107 @@ TEST(RNTuple, TClass) {
...
+      "  \"obj\": {\n"
+      "    \"fUniqueID\": 137,\n"
+      "    \"fBits\": 33554432\n"
+      "  }\n"
+      "}\n"
+   };
+   // clang-format on
+   std::ostringstream os;
+   reader->Show(0, os);
+   EXPECT_EQ(expected, os.str());
```
Comment (vepadulano) [inline tree/ntuple/v7/test/rfield_class.cxx:102]: Also this part is testing some other functionality, maybe a comment or a separate test

File: tree/ntuple/v7/test/rfield_class.cxx [hunk 14]
```diff
@@ -18,3 +26,107 @@ TEST(RNTuple, TClass) {
...
+}
+
+TEST(RTNuple, TObjectDerived)
+{
+   FileRaii fileGuard("test_ntuple_tobject_derived.root");
+
+   {
+      auto model = RNTupleModel::Create();
+      auto ptrRotation = model->MakeField<TRotation>("rotation");
```
Comment (vepadulano) [inline tree/ntuple/v7/test/rfield_class.cxx:111]: What is the reason for using `TRotation` instead of some other class? I believe a comment would be helpful here

**Review by vepadulano — CHANGES_REQUESTED** [review]
The functionality overall looks good and the tests seem to be passing, thanks a lot! I have left mainly minor comments, the only one that I believe should really be addressed is the one about `ClassDefOverride`, feel free to consider the others or not.

File: tree/ntuple/v7/src/RField.cxx (hunk 7 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:1741]: Good point! Tracked here: https://github.com/root-project/root/issues/15048

File: tree/ntuple/v7/test/CustomStruct.hxx (hunk 10 above)
Comment (pcanal) [reply tree/ntuple/v7/test/CustomStruct.hxx:222]: Since there is no other function, it should make no practical difference.

File: tree/ntuple/v7/src/RField.cxx [hunk 15]
```diff
@@ -1747,6 +1753,125 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+   if (auto dataMember = TObject::Class()->GetDataMember(name)) {
+      return dataMember->GetOffset();
+   }
+   throw RException(R__FAIL('\'' + std::string(name) + '\'' + " is an invalid data member"));
+}
+
+ROOT::Experimental::RField<TObject>::RField(std::string_view fieldName)
+   : ROOT::Experimental::RFieldBase(fieldName, "TObject", ENTupleStructure::kRecord, false /* isSimple */)
+{
+   assert(TObject::Class()->GetClassVersion() == 1);
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1767]:
```suggestion
   TClass *cl = TObject:Class();
   assert(cl->GetClassVersion() == 1);
```
`::Class()` is not "super fast" (at least a function call and an atomic load) and this "also" save some characters :)

File: tree/ntuple/v7/src/RField.cxx [hunk 16]
```diff
@@ -1747,6 +1753,125 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+}
+
+std::uint32_t ROOT::Experimental::RField<TObject>::GetTypeVersion() const
+{
+   return TObject::Class()->GetClassVersion();
+}
+
+void ROOT::Experimental::RField<TObject>::ConstructValue(void *where) const
+{
+   TObject::Class()->New(where);
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1837]:
```suggestion
   new (where) TObject();
```

File: tree/ntuple/v7/src/RField.cxx [hunk 17]
```diff
@@ -1747,6 +1753,125 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+}
+
+void ROOT::Experimental::RField<TObject>::RTObjectDeleter::operator()(void *objPtr, bool dtorOnly)
+{
+   TObject::Class()->Destructor(objPtr, true /* dtorOnly */);
+   RDeleter::operator()(objPtr, dtorOnly);
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1843]: That looks like the `destructor` is being run twice.  Do we mean:
```suggestion
   reinterpret_cast<TObject*>(objPtr)->~TObject();
```
related question is (`objPtr` the start of the `TObject` part? (this would be required for both the old and proposed code).

File: tree/ntuple/v7/src/RField.cxx [hunk 18]
```diff
@@ -1747,6 +1753,125 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+
+ROOT::Experimental::RField<TObject>::RField(std::string_view fieldName)
+   : ROOT::Experimental::RFieldBase(fieldName, "TObject", ENTupleStructure::kRecord, false /* isSimple */)
+{
+   assert(TObject::Class()->GetClassVersion() == 1);
+
+   if (!(TObject::Class()->ClassProperty() & kClassHasExplicitCtor))
+      fTraits |= kTraitTriviallyConstructible;
+   if (!(TObject::Class()->ClassProperty() & kClassHasExplicitDtor))
+      fTraits |= kTraitTriviallyDestructible;
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1772]: Those are actually "invariant" (the boolean expression will always be false) and we could check only once per build (i.e. a static_assert rather than every run).

File: tree/ntuple/v7/src/RField.cxx (hunk 17 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx]: Yes, `objPtr` points to the (beginning of the) `TObject` object. I replaced the `TClass::Destructor` call by a cast + destructor call. The `RDeleter::operator()(objPtr, dtorOnly);` is still necessary to free the memory if `dtorOnly` is `false`.

File: tree/ntuple/v7/src/RField.cxx (hunk 18 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx]: The `TClass` pointer is not a local static variable only requested in debug mode.

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx]: This is not what I meant.  `TObject::Class()->ClassProperty() ` returns information from the class `TObject` and we know that it will (always) be both "not trivially constructible" and "not trivially destructible" and thus line 1770 and 1772 will never be executed.

File: tree/ntuple/v7/src/RField.cxx [hunk 19]
```diff
@@ -1751,6 +1757,126 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+ROOT::Experimental::RField<TObject>::RField(std::string_view fieldName)
+   : ROOT::Experimental::RFieldBase(fieldName, "TObject", ENTupleStructure::kRecord, false /* isSimple */)
+{
+#ifndef NDEBUG
+   static const auto cl = TObject::Class();
+#endif
+   assert(cl->GetClassVersion() == 1);
+   assert(cl->ClassProperty() & kClassHasExplicitCtor);
+   assert(cl->ClassProperty() & kClassHasExplicitDtor);
+   fTraits |= kTraitTriviallyConstructible | kTraitTriviallyDestructible;
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1777]: Is that correct or do we need the opposite?

File: tree/ntuple/v7/src/RField.cxx [hunk 20]
```diff
@@ -1751,6 +1757,126 @@ void ROOT::Experimental::RClassField::AcceptVisitor(Detail::RFieldVisitor &visit
...
+
+void ROOT::Experimental::RField<TObject>::ConstructValue(void *where) const
+{
+   new (where) TObject();
+}
+
+void ROOT::Experimental::RField<TObject>::RTObjectDeleter::operator()(void *objPtr, bool dtorOnly)
+{
+   static_cast<TObject *>(objPtr)->~TObject();
+   RDeleter::operator()(objPtr, dtorOnly);
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:1848]: Is this more than:
```suggestion
   if (dtorOnly)
      static_cast<TObject *>(objPtr)->~TObject();
   else
      delete static_cast<TObject *>(objPtr);
```

>   static_cast<TObject *>(objPtr)->~TObject();
>   RDeleter::operator()(objPtr, dtorOnly);

This code (and its previous version) is confusing me ... if `dtorOnly == false` isn't the destructor called twice?

File: tree/ntuple/v7/src/RField.cxx (hunk 19 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:1777]: That is true of course, TObject is _not_ trivially constructible/destructible. Actually, this bit can be simplified to just test the class version.

File: tree/ntuple/v7/src/RField.cxx (hunk 20 above)
Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1842]: What is the meaning of the 2nd parameter in:
```
   RDeleter::operator()(objPtr, dtorOnly);
```
if it is not to ask for the destructor to be called?

File: tree/ntuple/v7/src/RField.cxx (hunk 15 above)
Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1771]: Since the pointer is only use once now, the comment is moot.

**Review by vepadulano — APPROVED** [review]
Thank you! Looks good to me now!

File: tree/ntuple/v7/src/RField.cxx (hunk 20 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:1842]: If `dtorOnly` is true, the base class will do nothing. The alternative would be to have that if statement in all the derived classes.

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1842]: > If dtorOnly is true, the base class will do nothing.

This seems to be both by design and somewhat an happenstance (i.e. in a way the `RDeleter` base does call the destructor, it just happens that the destructor is always a no-op (actually doesn't exist) since it is for single instance of numerical types (no even arrays)).

Either way, it is 'hard' to read and maybe it would make more sense to use either the code I proposed or:
```
   static_cast<TObject *>(objPtr)->~TObject();
   RDeleter::operator()(objPtr, true /* dtorOnly */);
```
Related, I am not sure what is the value added of call `RDeleter` here rather than `operator delete`.

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:1842]: Conclusion of off-line discussion: Use `RTypedDeleter` here to be consistent.  The usage of `RDeleter` here (and elsewhere) is to insure a single point of control for the way the user datum are allocated.
