### PR TITLE
[PyROOT][6470] Fix virtual call issue in deep hierarchy

### LINKED ISSUE #6470: PyROOT:  virtual  C++ method overriden in python  ignored with  further inheritance chain
## Describe the bug

The virtual C++ methods overriden in some python class is ignored in the subsequent subclass. 

Simple examples is given in [here] (https://gist.github.com/VanyaBelyaev/fb58efd76b693a7777c9c83a6f43ae15)
In short:
 - C++ class A, 
 -  python class B, that inherits from   A  and override virtual method from A 
 -  python class C, that inherits from B  and override (the same) virual method  form A (and B)
 -  python class D, that inherits from B and has empty body  

And f one   call the method from A,  B, C , D 
 - for A one gets original        C++ behaviour  (OK)
 - for B one gets the overriden behaviour  (OK)
 - for C one gets overriden behaviour defined in C (OK)
 - for D one gets the     original C++ behaviour (  that is not OK) 

## Expected behavior

It is expected that    D  picks up   the overriden method from class B,   as naturally  expected for the inheritance pattern  

## To Reproduce

Simple gist is [here] (https://gist.github.com/VanyaBelyaev/fb58efd76b693a7777c9c83a6f43ae15)

## Setup

1. ROOT version   623/01
2. Operating system  CentOS7, lxplus x86, 64-centos7-gcc9-opt

3. How you obtained ROOT:  `dev3/latest`  nightly LCG  slot,

### PR DESCRIPTION
**Pull request by etejedor**
Fixes #6470 .

Fix how the inheritance hierarchy is constructed when there's more
than one level of cross-inheritance, for example C++ class ->
Py class 1 -> Py class 2. In the example, the C++ Dispatcher class
of Py class 2 should inherit from the Dispatcher class of Py class 1,
and not directly from the base C++ class. This was causing an
undesired behaviour in the resolution of some virtual calls, as
shown in the reproducer of 6470.

This PR is an adaptation of the code that is in upstream
cppyy, but it does not incorporate yet all the changes for
multiple cross-inheritance (i.e. a Python class that inherits
from more than one C++ class). Multiple cross-inheritance was
anyway not supported in old PyROOT, and its current implementation
in cppyy does not seem to support the inheritance from both a pure
Python class and a C++ class at the same time (even via the use
of cppyy.multi), and that case was supported in the old PyROOT.

### CODE REVIEW

File: bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx [hunk 1]
```diff
@@ -83,10 +84,9 @@ PyObject* CPyCppyy::CPPConstructor::Call(
         address = (ptrdiff_t)((CPPInstance*)pyobj)->GetObject();
         if (address) {
             ((CPPInstance*)pyobj)->CppOwns();
-            PyObject* pyoff = PyObject_CallMethod(dispproxy, (char*)"_dispatchptr_offset", nullptr);
-            size_t disp_offset = PyLong_AsSsize_t(pyoff);
-            Py_DECREF(pyoff);
-            new ((void*)(address + disp_offset)) DispatchPtr{(PyObject*)self};
+            PyObject* res = PyObject_CallMethodObjArgs(
+            dispproxy, PyStrings::gDispInit, pyobj, (PyObject*)self, nullptr);
+            Py_XDECREF(res);
```
Comment (stwunsch) [inline bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx:89]: Just for my understanding, there's a reason you used the `XDECREF` and not a simple `DECREF`?

**Review by stwunsch — APPROVED** [review]
LGTM!

File: bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx (hunk 1 above)
Comment (etejedor) [reply bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx:89]: I'd say the reason is that `PyObject_CallMethodObjArgs` can return null in case of failure, and `XDECREF` handles null unlike `DECREF`.
