### PR TITLE
[Tree] Emit error before crashing when reading type w/ no dictionary

### LINKED ISSUE #10254: [TTreeReader] No diagnostics printed before crash when reading a type with no dictionaries
Given a tree with a branch of type `map<string, bool>`, like the one [in this forum post](https://root-forum.cern.ch/t/sample-splitting-using-rdataframe-not-working-for-the-trees-which-contains-vector-branches/49377), reading it with TTreeReader just yields a crash, while reading it with TTree first prints an error about the missing dictionary, _then_ crashes.

### TTreeReader

```cpp
void repro_treereader() {
  TFile f("flatntuple_MC_.root");
  auto *t = f.Get<TTree>("ntuplizer/tree");
  R__ASSERT(t != nullptr);
  TTreeReader r(t);
  TTreeReaderValue<std::map<std::string, bool>> rv(r, "HLT_BPH_isFired");
  r.Next();
  *rv;
}
```
```cpp
$ root -l repro_treereader.C
root [0]
Processing repro_treereader.C...

 *** Break *** segmentation violation
Root > .qqqqq
Info in <TRint::ProcessLine>: Bye... (try '.qqqqqqq' if still running)

 *** Break *** segmentation violation
Root > .qqqqqqq
```

### TTree

```cpp
void repro_tree() {
  TFile f("flatntuple_MC_.root");
  auto *t = f.Get<TTree>("ntuplizer/tree");
  R__ASSERT(t != nullptr);
  std::map<std::string, bool> *m = nullptr;
  t->SetBranchAddress("HLT_BPH_isFired", &m);
  t->GetEntry(0);
}
```
```
$ root -l -b -q repro_tree.C

Processing repro_tree.C...
Error in <TTree::SetBranchAddress>: The class requested (map<string,bool>) for the branch "HLT_BPH_isFired" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (map<string,bool>) to avoid to write corrupted data.

 *** Break *** segmentation violation
Root >
 *** Break *** segmentation violation
 ```

The TTreeReader version should also print the error, so users [don't get confused](https://root-forum.cern.ch/t/sample-splitting-using-rdataframe-not-working-for-the-trees-which-contains-vector-branches/49377).

### PR DESCRIPTION
**Pull request by dpiparo**
as TTree would do.

Fixes #10254

### CODE REVIEW

File: tree/treeplayer/inc/TTreeReaderValue.h [hunk 1]
```diff
@@ -259,4 +259,19 @@ std::string printValue(TTreeReaderValue<T> *val)
 }
 } // namespace cling
 
+namespace ROOT::Internal::TTreeReaderHelpers {
```
Comment (pcanal) [inline tree/treeplayer/inc/TTreeReaderValue.h]: This seems to be unused.

Comment (dpiparo) [reply tree/treeplayer/inc/TTreeReaderValue.h]: Indeed, this is a remnant of a refactoring. Sorry about that.

File: io/io/inc/TEmulatedCollectionProxy.h [hunk 2]
```diff
@@ -130,4 +130,22 @@ class TEmulatedCollectionProxy : public TGenCollectionProxy  {
...
 };
 
+
+namespace ROOT::Internal::TEmulatedProxyHelpers {
+inline void PrintWriteStlWithoutProxyMsg(const char *where, const char *clName, const char *BranchName)
+{
+   const char *writeStlWithoutProxyMsg =
+      "The class requested (%s) for the branch \"%s\" "
+      "is an instance of an stl collection and does not have a compiled CollectionProxy. "
+      "Please generate the dictionary for this collection (%s) to avoid to write corrupted data.";
```
Comment (vepadulano) [inline io/io/inc/TEmulatedCollectionProxy.h]:
```suggestion
      "Please generate the dictionary for this collection (%s) to avoid writing corrupted data.";
```

File: io/io/inc/TEmulatedCollectionProxy.h [hunk 3]
```diff
@@ -130,4 +130,22 @@ class TEmulatedCollectionProxy : public TGenCollectionProxy  {
...
+   // This error message is repeated several times in the code. We write it once.
```
Comment (vepadulano) [inline io/io/inc/TEmulatedCollectionProxy.h:141]: What is this comment about? The error message will be printed once per function call, isn't it?

File: tree/treeplayer/src/TTreeReaderValue.cxx [hunk 4]
```diff
@@ -63,6 +64,11 @@ ROOT::Internal::TTreeReaderValueBase::TTreeReaderValueBase(TTreeReader *reader /
      fDict(dict),
      fOpaqueRead(opaqueRead)
 {
+   auto * cl = dynamic_cast<TClass *>(dict);
+   using namespace ROOT::Internal::TEmulatedProxyHelpers;
+   if (HasEmulatedProxy(cl)) {
+      PrintWriteStlWithoutProxyMsg("TTreeReaderValueBase", cl->GetName(), branchname);
+   }
```
Comment (vepadulano) [inline tree/treeplayer/src/TTreeReaderValue.cxx]: This logic seems backwards: if the class has an emulated proxy, we print a warning? Shouldn't it be the opposite?

File: tree/treeplayer/test/basic.cxx [hunk 5]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+            }
+         }
+      }
+      
+   }
+};
+TEST(TTreeReaderBasic, WarnNoDict)
+{
+   using rareType = std::map<std::string, bool>;
+   auto c = TClass::GetClass(typeid(rareType));
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: We need to check for validity of the `TClass *` here

File: tree/treeplayer/test/basic.cxx [hunk 6]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+   auto const rareTypeName = c->GetName();
+   // Let's check if we have a dict for it, if yes, we
+   // error out because the test needs to be modified.
+   if (c->HasDictionary()) {
+      throw std::runtime_error("The type used for the test has a dictionary while it should not.");
+   }
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: This file is already using gtest, might as well use the gtest API.
```suggestion
  ASSERT_FALSE(c->HasDictionary()) << "The type used for the test has a dictionary while it should not.";
```

File: tree/treeplayer/test/basic.cxx [hunk 7]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+
+   const auto fName = "10524_file.root";
+   const auto tName = "t";
+   const auto colName = "col";
+
+   Cleanup_10524_RAII cleanupRAII({fName, "AutoDict_"});
+
+   // Create the input file in a separate process.
+   // This is necessary because we want to create a dictionary but not have it at disposal
+   // for the read
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: In other tests we treat this situation with a separate executable that creates the dictionary, then use `ROOTTEST_GENERATE_DICTIONARY` with the proper `FIXTURES_SETUP` to create a build dependency. Ideally we would do the same here, although I wouldn't put this as a blocker for this PR.

File: tree/treeplayer/test/basic.cxx [hunk 8]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+   const auto pid = getpid();
+   auto createFile = [&]() {
+      if (pid == getpid()) {
+         throw std::runtime_error("The creation of the tree is not happening in a separate process");
+      }
+      gInterpreter->GenerateDictionary(rareTypeName, "map;string");
+      TFile f(fName, "RECREATE");
+      auto t = new TTree(tName, "test tree");
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: Too many times we've had random unexplicable failures because of stack-based TFiles/TTrees, we can't let this pass 😄 

```suggestion
      auto f = std::make_unique<TFile>(fName, "RECREATE");
      auto t = std::make_unique<TTree>(tName, "test tree");
```

File: tree/treeplayer/test/basic.cxx [hunk 9]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+      rareType o;
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: Ideally we would actually write something in the map, so the values can be checked again when reading

File: tree/treeplayer/test/basic.cxx [hunk 10]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+      f.Close();
+      return 0;
+   };
+
+   ROOT::TProcessExecutor pe(1);
+   pe.Map(createFile,1);
+
+   // OK, now we can read
+   TFile f(fName);
+   auto t = f.Get<TTree>(tName);
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]: Same thing here 

```suggestion
   auto f = std::make_unique<TFile>(fName);
   auto t = std::unique_ptr<TTree>(f->Get<TTree>(tName));
```

File: tree/treeplayer/test/basic.cxx [hunk 11]
```diff
@@ -572,6 +574,73 @@ TEST(TTreeReaderBasic, ZeroEntriesTreeCheckValueStatus)
...
+   TTreeReader r(t);
```
Comment (vepadulano) [inline tree/treeplayer/test/basic.cxx]:
```suggestion
   TTreeReader r(t.get());
```

File: tree/treeplayer/src/TTreeReaderValue.cxx (hunk 4 above)
Comment (vepadulano) [reply tree/treeplayer/src/TTreeReaderValue.cxx]: I see that the test checks for the error to be raised "in the right case", but I still don't understand how the logic here is the correct one. I'll write what I understand and then you can correct me: we check that the class exists, and it has only an **emulated** collection proxy, but not a fully-defined collection proxy, is that it? Then I wonder, if we can anyway emulate the collection proxy, what is the whole purpose of printing this warning? Can't we deal with this situation already some other way? I'm missing something big here I'm afraid.

File: io/io/inc/TEmulatedCollectionProxy.h (hunk 3 above)
Comment (dpiparo) [reply io/io/inc/TEmulatedCollectionProxy.h:141]: correct. I need to address that.

File: io/io/inc/TEmulatedCollectionProxy.h (hunk 2 above)
Comment (dpiparo) [reply io/io/inc/TEmulatedCollectionProxy.h]: thx.

File: tree/treeplayer/src/TTreeReaderValue.cxx (hunk 4 above)
Comment (dpiparo) [reply tree/treeplayer/src/TTreeReaderValue.cxx]: From TTree: https://github.com/root-project/root/blob/master/tree/tree/src/TTree.cxx#L1586

File: tree/treeplayer/test/basic.cxx (hunk 5 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: TClass will always return for templates, because of automatic instantiation. We can decide to be on the safe side though, and even put an error to detect the ill-defined case where that does not happen.

File: tree/treeplayer/test/basic.cxx (hunk 6 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: nice suggestion.

File: tree/treeplayer/test/basic.cxx (hunk 8 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: ah ah that is why it's on the heap. But your approach is better.

File: tree/treeplayer/test/basic.cxx (hunk 9 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: indeed. That would be a test of the IO capabilities while this is a test of the error, but why not.

File: tree/treeplayer/test/basic.cxx (hunk 10 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: thx.

File: tree/treeplayer/test/basic.cxx (hunk 8 above)
Comment (vepadulano) [reply tree/treeplayer/test/basic.cxx]: only the TTree was, not the TFile, who knows which could be triggering the issue.

File: tree/treeplayer/src/TTreeReaderValue.cxx (hunk 4 above)
Comment (vepadulano) [reply tree/treeplayer/src/TTreeReaderValue.cxx]: Ok, I see it's the same logic. I'm probably just missing the knowledge related to which case we can't deal with that this error is mentioning 👍

File: tree/treeplayer/test/basic.cxx (hunk 5 above)
Comment (vepadulano) [reply tree/treeplayer/test/basic.cxx]: Shouldn't it be then `GetClass<rareType>`?

File: io/io/inc/TEmulatedCollectionProxy.h (hunk 3 above)
Comment (vepadulano) [reply io/io/inc/TEmulatedCollectionProxy.h:141]: Reading again this code and the code in TTree, I think I understand that the comment merely mentions that the same string needs to be used in multiple different functions, so instead of repeating it multiple times in the code, it is "written once" in this function. The error will still be printed once each time this situation is triggered, as it should.

File: tree/treeplayer/test/basic.cxx (hunk 5 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: we could, it does not make a big difference since it will fall back to the signature with `typeid`

File: tree/treeplayer/test/basic.cxx (hunk 7 above)
Comment (dpiparo) [reply tree/treeplayer/test/basic.cxx]: you are right. I was busy thinking how to roll-back the status of the type-system and forgot to keep it simple. That solution would also cover Windows. I still have to admit that I find the subprocess very compact...

File: tree/treeplayer/src/TTreeReaderValue.cxx [hunk 12]
```diff
@@ -63,6 +64,11 @@ ROOT::Internal::TTreeReaderValueBase::TTreeReaderValueBase(TTreeReader *reader /
      fDict(dict),
      fOpaqueRead(opaqueRead)
 {
+   auto * cl = dynamic_cast<TClass *>(dict);
+   using namespace ROOT::Internal::TEmulatedProxyHelpers;
+   if (HasEmulatedProxy(cl)) {
```
Comment (vepadulano) [inline tree/treeplayer/src/TTreeReaderValue.cxx]: the `dict` may not be a TClass actually.
```suggestion
   if (cl && HasEmulatedProxy(cl)) {
```

**Comment by dpiparo** [comment]
I greatly simplified the test, moving it to roottest as suggested.
