### PR TITLE
[ntuple,daos] RPageSourceDaos: populate the page zero from `kTypePageZero` locators

### LINKED ISSUE #12960: [ntuple] RPageSourceDaos should be able to populate zero pages from `kTypePageZero` locators
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

After merging #12676, _all the page sources_ are required to be able to populate the page zero from the `kTypePageZero` locator.  However, for for the sake of simplifying the PR #12676 (which was already quite large), this was not included and thus left for a follow-up pull request.

### What is the expected behaviour?

`RPageSourceDaos` should be able to populate the page zero in all cases, i.e. a call to `PopulatePage()`, `LoadSealedPage()`, or `LoadClusters()`.

### How to reproduce?

n/a

### ROOT version

master

### How did you install ROOT?

custom build

### Which operating system are you using?

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jalopezg-git**
Per #12676, all storage backends should be able to populate the page zero from `kTypePageZero` locators.  This pull request adds the missing pieces in the DAOS backend.

## Changes or fixes:
- Add the `RPageStorage::PrepareLoadCluster()` helper which can be used in the implementation of `LoadClusters()` in derived classes to prepare the read of page ranges.  This function takes care of filling zero pages in the given `ROnDiskPageMap`.
- Add the missing pieces in `RPageSourceDaos`.

## Checklist:
- [x] tested changes locally

This PR fixes #12960.

### CODE REVIEW

File: tree/ntuple/v7/inc/ROOT/RPageStorage.hxx [hunk 1]
```diff
@@ -420,6 +420,30 @@ protected:
    /// `RPageAllocatorHeap`; use `RPageAllocatorHeap::DeletePage()` to deallocate returned pages.
    RPage UnsealPage(const RSealedPage &sealedPage, const RColumnElementBase &element, DescriptorId_t physicalColumnId);
 
+   /// Prepare a page range read for the column set in `clusterKey`.  Specifically, pages referencing the
+   /// `kTypePageZero` locator are filled in `pageZeroMap`; otherwise, `perPageFunc` is called for each page. This is
+   /// commonly used as part of `LoadClusters()` in derived classes.
+   template <typename PerPageFuncT>
```
Comment (jblomer) [inline tree/ntuple/v7/inc/ROOT/RPageStorage.hxx:426]: I'd prefer avoiding the template and using an `std::function` parameter instead. That would allow us to move this from header to compilation unit, and it would clarify the parameter types of `perPageFunc`.

**Review by jblomer — CHANGES_REQUESTED** [review]
Nice! See comment.

File: tree/ntuple/v7/inc/ROOT/RPageStorage.hxx (hunk 1 above)
Comment (jalopezg-git) [reply tree/ntuple/v7/inc/ROOT/RPageStorage.hxx:426]: This was a concious decision; unfortunately, using a `std::function` would make the call to the lambda non-inlineable, resulting in an indirect call for each page in the range.  For small functions, e.g. in RPageStorageFile.cxx (see [here](https://github.com/root-project/root/pull/13388/files#diff-311b1306fdf38fbec1f6e0eeb3065c34b411f6d3f6f05614eb75cc02968f2a84R444-R446)), the relative cost of the call increases.
(See also related interesting read: https://vittorioromeo.info/index/blog/passing_functions_to_functions.html)

What about leaving here only the declaration and moving the definition out-of-class at the end of RPageStorage.hxx?  I think it makes it more readable; for the parameter types of `perPageFunc`, we could document above.  What do you think?

Comment (jblomer) [reply tree/ntuple/v7/inc/ROOT/RPageStorage.hxx:426]: Ok, I understand that the call cannot be inlined. But cannot asses yet if that is a problem in this particular case. Can you collect numbers that show the performance effect.

Comment (jalopezg-git) [reply tree/ntuple/v7/inc/ROOT/RPageStorage.hxx]: Apparently, in a synthetic test reading 8 `std::uint32_t` fields and 10M entries, the cost of not inlining is negligible (~ a few $us$), especially compared to the cost of the `ReadV()` call that follows.

In light of this, I effectively moved the implementation to the .cxx file :+1:.

**Comment by jalopezg-git** [comment]
@pcanal could you take a look / approve?  Thanks :slightly_smiling_face:!

**Review by pcanal — APPROVED** [review]
LGTM
