### PR TITLE
[TTree] Avoid deletion of TFile on the stack

### LINKED ISSUE #6527: Double delete error with TTree::ChangeFile and a TFile on the stack
## Describe the bug

TTree::ChangeFile deletes the old TFile of the tree when changing it to point to a new one. If the TFile was originally created on the stack this leads to a double delete. Using TFile::Open fixes this behaviour

## Expected behavior

TTree::ChangeFile should not rely on the original TFile to be on the heap.

## To Reproduce

See the following gist:
https://gist.github.com/vepadulano/848ebbfbbb7efc95d2f5726538583b82

## Setup

1. ROOT master
2. Fedora 32
3. ROOT build with cmake: `cmake -GNinja -Ddev=ON -DCMAKE_BUILD_TYPE=Debug -Dtesting=ON -Droottest=ON`

## Additional context
Stacktrace
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff54f2535 in __GI_abort () at abort.c:79
#2  0x00007ffff5549508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff565428d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff554fc1a in malloc_printerr (str=str@entry=0x7ffff5655ff8 "double free or corruption (out)") at malloc.c:5341
#4  0x00007ffff5551730 in _int_free (av=0x7ffff568bc40 <main_arena>, p=0x7fffffffde90, have_lock=<optimized out>) at malloc.c:4306
#5  0x00007ffff7bf3dfc in TStorage::ObjectDealloc (vp=0x7fffffffdea0) at ../../../root_dbg/core/base/src/TStorage.cxx:362
#6  0x00007ffff7bd95c8 in TObject::operator delete (ptr=0x7fffffffdea0) at ../../../root_dbg/core/base/src/TObject.cxx:998
#7  0x00007ffff75db056 in TFile::~TFile (this=0x7fffffffdea0, __in_chrg=<optimized out>) at ../../../root_dbg/io/io/src/TFile.cxx:542
#8  0x00007ffff683c479 in TTree::ChangeFile (this=0x7fffffffdbd0, file=0x7fffffffdea0) at ../../../root_dbg/tree/tree/src/TTree.cxx:2792
#9  0x00007ffff6841802 in TTree::Fill (this=0x7fffffffdbd0) at ../../../root_dbg/tree/tree/src/TTree.cxx:4707
#10 0x0000555555555289 in main () at repro_vincenzo.cpp:15
```

### PR DESCRIPTION
**Pull request by eguiraud**
TObject::Delete checks the IsOnHeap() bit, while `delete obj` does not.

This fixes #6527 , at least for the provided reproducer.

### CODE REVIEW

**Comment by vepadulano** [comment]
The patch doesn't solve the reproducer for me. I get the output
```
vpadulan@fedorathinkpad-T550 [~/Projects/ROOT-10896]: ./tree_setmaxsize_seq   
Fill: Switching to new file: tree_setmaxsize_seq_1.root
free(): invalid pointer
Aborted (core dumped)
```
And from gdb:
```
Breakpoint 1, TTree::ChangeFile (this=0x7fffffffd2b0, file=0x7fffffffd580)
    at /home/vpadulan/Programs/rootproject/root/tree/tree/src/TTree.cxx:2792
warning: Source file is more recent than executable.
2792       file->Delete();
(gdb) s
TFile::~TFile (this=0x7fffffffd580, __in_chrg=<optimized out>)
    at /home/vpadulan/Programs/rootproject/root/io/io/src/TFile.cxx:503
503     TFile::~TFile()
(gdb) n
0x00007ffff7643450 in TObject::operator delete(void*)@plt ()
   from /home/vpadulan/Programs/rootproject/rootinstall/devrelease/lib/libRIO.so
(gdb) 
Single stepping until exit from function _ZN7TObjectdlEPv@plt,
which has no line number information.
TObject::operator delete (ptr=0x7fffffffd580)
    at /home/vpadulan/Programs/rootproject/root/core/base/src/TObject.cxx:997
997        if ((Long_t) ptr != fgDtorOnly)
(gdb) 
998           TStorage::ObjectDealloc(ptr);
(gdb) s
TStorage::ObjectDealloc (vp=0x7fffffffd580)
    at /home/vpadulan/Programs/rootproject/root/core/base/src/TStorage.cxx:362
362        ::operator delete(vp);
(gdb) n
0x00007ffff7aff3a0 in operator delete(void*)@plt ()
   from /home/vpadulan/Programs/rootproject/rootinstall/devrelease/lib/libCore.so
Single stepping until exit from function _ZdlPv@plt,
which has no line number information.
operator delete (ptr=0x7fffffffd580) at ../../../../libstdc++-v3/libsupc++/del_op.cc:48
48      {
(gdb) finish

munmap_chunk(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff5c3b9e5 in raise () from /lib64/libc.so.6

```

File: tree/tree/src/TTree.cxx [hunk 1]
```diff
@@ -2789,7 +2789,7 @@ TFile* TTree::ChangeFile(TFile* file)
       if (newfile) newfile->Append(obj);
       file->Remove(obj);
    }
-   delete file;
+   file->Delete();
```
Comment (pcanal) [inline tree/tree/src/TTree.cxx:2792]: "Surprisingly" this actually request the deletion/freeing of the keys' area from the file rather than calling C++ operator delete.  Try
```suggestion
   file->TObject::Delete();
```

Comment (vepadulano) [reply tree/tree/src/TTree.cxx:2792]: Yes indeed that calls `TFile::Delete` which calls `TDirectoryFile::Delete`  hence the request of key deletion .`TObject::Delete` is never called.

Comment (eguiraud) [reply tree/tree/src/TTree.cxx:2792]: :sob:

Comment (eguiraud) [reply tree/tree/src/TTree.cxx:2792]: (dangerous violation of https://en.wikipedia.org/wiki/Liskov_substitution_principle )

Comment (pcanal) [reply tree/tree/src/TTree.cxx:2792]: agreed ... :(

Comment (eguiraud) [reply tree/tree/src/TTree.cxx]: better now?

**Review by vepadulano — APPROVED** [review]
LGTM! Thanks for adding the reproducer as a test :smile:

**Review by pcanal — APPROVED** [review]

**Comment by eguiraud** [comment]
Is that a bad thing?

**Comment by vepadulano** [comment]
The user could modify the content of the original TFile, which holds a portion of the data in the TTree, i.e.

https://gist.github.com/vepadulano/ed0644351771d97ff2624f0ddf015b83

I get the output
```
Fill: Switching to new file: tree_setmaxsize_seq_1.root
Fill: Switching to new file: tree_setmaxsize_seq_2.root
Entries in tree: Error in <TFile::ReadBuffer>: error reading all requested bytes from file tree_setmaxsize_seq_2.root, got 270 of 300
Error in <TFile::Init>: tree_setmaxsize_seq_2.root failed to read the file type data.
15966
```

Maybe it's just something that we leave to the thoughtful user to avoid?

**Comment by eguiraud** [comment]
> The user could modify the content of the original TFile, which holds a portion of the data in the TTree

that shouldn't be a problem, and should certainly not corrupt the TTree entries that have already been written to the file. There is something weird going on in that gist.

**Comment by vepadulano** [comment]
Yes indeed I wasn't saving the last file of the tree (see the updated gist). Sorry!
