### PR TITLE
[ntuple] Various fixes for big-endian

### LINKED ISSUE #12426: RNTuple endian issues
- [x] Checked for duplicates

### Describe the bug

Test failures in RNTuple on s390x. Endian issues.
There are way fewer failures in 6.28.00 than in earlier versions, this report is about remaining ones.

### Expected behavior

RNTuple should work for big-endian too.

### To Reproduce

1. Build root 6.28.00 for s390x
2. Run unit tests

### Setup

1. ROOT version: 6.28.00
2. Operating system: Fedora Linux on s390x, RHEL+EPEL on s390x
3. Compilation from source.

### Additional context

The failing tests 

#### gtest-tree-ntuple-v7-test-ntuple-basics

Fatal: nread == nbytes violated
~~~
 474/1272 Test  #421: gtest-tree-ntuple-v7-test-ntuple-basics .............................***Failed   63.64 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 17 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 13 tests from RNTuple
[ RUN      ] RNTuple.ReconstructModel
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.ReconstructModel (160 ms)
[ RUN      ] RNTuple.MultipleInFile
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Fatal: nread == nbytes violated at line 1083 of `/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RMiniFile.cxx'
aborting
[ --- ]
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: Subprocess aborted
~~~

#### gtest-tree-ntuple-v7-test-ntuple-endian

Here the bytes are in the right order, but shifted 4 bytes.

$ printf '%016x\n%016x\n' 1234605615003729920 287454020
1122334400000000
0000000011223344
$ printf '%016x\n%016x\n' 6153737371142586367 1432778632
55667788ffffffff
0000000055667788
~~~
 449/1272 Test  #424: gtest-tree-ntuple-v7-test-ntuple-endian .............................***Failed    0.04 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 9 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 9 tests from RColumnElementEndian
[ RUN      ] RColumnElementEndian.Float
[       OK ] RColumnElementEndian.Float (6 ms)
[ RUN      ] RColumnElementEndian.Double
[       OK ] RColumnElementEndian.Double (3 ms)
[ RUN      ] RColumnElementEndian.Int16
[       OK ] RColumnElementEndian.Int16 (0 ms)
[ RUN      ] RColumnElementEndian.UInt16
[       OK ] RColumnElementEndian.UInt16 (0 ms)
[ RUN      ] RColumnElementEndian.Int32
[       OK ] RColumnElementEndian.Int32 (0 ms)
[ RUN      ] RColumnElementEndian.UInt32
[       OK ] RColumnElementEndian.UInt32 (0 ms)
[ RUN      ] RColumnElementEndian.Int64
[       OK ] RColumnElementEndian.Int64 (0 ms)
[ RUN      ] RColumnElementEndian.UInt64
[       OK ] RColumnElementEndian.UInt64 (0 ms)
[ RUN      ] RColumnElementEndian.Int64Int32
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_endian.cxx:286: Failure
Expected equality of these values:
  ints[0]
    Which is: 1234605615003729920
  0x0000000011223344
    Which is: 287454020
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_endian.cxx:287: Failure
Expected equality of these values:
  ints[1]
    Which is: 6153737371142586367
  0x0000000055667788
    Which is: 1432778632
[  FAILED  ] RColumnElementEndian.Int64Int32 (0 ms)
[----------] 9 tests from RColumnElementEndian (13 ms total)
[----------] Global test environment tear-down
[==========] 9 tests from 1 test suite ran. (13 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RColumnElementEndian.Int64Int32
 1 FAILED TEST
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### gtest-tree-ntuple-v7-test-ntuple-extended

This looks like an endian error:

$ printf '%x\n' 1677721600
64000000

Header length shoud be 0x00000064 = 100
~~~
 501/1272 Test  #443: gtest-tree-ntuple-v7-test-ntuple-extended ...........................***Failed   81.93 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from RNTuple
[ RUN      ] RNTuple.RealWorld1
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.RealWorld1 (5260 ms)
[ RUN      ] RNTuple.RandomAccess
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.RandomAccess (229 ms)
[ RUN      ] RNTuple.LargeFile1
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
Error in <TFile::Init>: file test_large_file1.root has an incorrect header length (1677721600) or incorrect end of file length (-1760683648)
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_extended.cxx:159: Failure
Value of: f
  Actual: false
Expected: true
 *** Break *** segmentation violation
[ --- ]
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 139
~~~

#### gtest-tree-ntuple-v7-test-ntuple-minifile

$ printf '%x\n' 1677721600
64000000

Header length shoud be 0x00000064 = 100

Fatal: nread == nbytes violated
~~~
 478/1272 Test  #440: gtest-tree-ntuple-v7-test-ntuple-minifile ...........................***Failed   65.92 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from MiniFile
[ RUN      ] MiniFile.Raw
[       OK ] MiniFile.Raw (0 ms)
[ RUN      ] MiniFile.Stream
Error in <TFile::ReadBuffer>: error reading all requested bytes from file test_ntuple_minifile_stream.root, got 0 of 6816316
Error in <TFile::Init>: test_ntuple_minifile_stream.root failed to read the file header information at 1677721600 (size=6816316)
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_minifile.cxx:84: Failure
Value of: file
  Actual: false
Expected: true
[  FAILED  ] MiniFile.Stream (191 ms)
[ RUN      ] MiniFile.Proper
Fatal: nread == nbytes violated at line 1083 of `/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RMiniFile.cxx'
aborting
[ --- ]
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: Subprocess aborted
~~~

#### gtest-tree-ntuple-v7-test-ntuple-rdf

$ printf '%x\n' 1677721600
64000000

Header length shoud be 0x00000064 = 100
~~~
 491/1272 Test  #431: gtest-tree-ntuple-v7-test-ntuple-rdf ................................***Failed   74.39 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from RNTuple
[ RUN      ] RNTuple.RDF
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Error in <TFile::Init>: file test_ntuple_rdf.root has an incorrect header length (1677721600) or incorrect end of file length (-4176807177076801536)
 *** Break *** segmentation violation
[ --- ]
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 139
~~~
#### gtest-tree-ntuple-v7-test-ntuple-serialize

Endian issue: 256 = 0x0100, expected 0x0001 = 1.
~~~
 457/1272 Test  #432: gtest-tree-ntuple-v7-test-ntuple-serialize ..........................***Failed    0.24 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 14 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 14 tests from RNTuple
[ RUN      ] RNTuple.SerializeInt
[       OK ] RNTuple.SerializeInt (0 ms)
[ RUN      ] RNTuple.SerializeString
[       OK ] RNTuple.SerializeString (0 ms)
[ RUN      ] RNTuple.SerializeColumnType
[       OK ] RNTuple.SerializeColumnType (0 ms)
[ RUN      ] RNTuple.SerializeFieldStructure
[       OK ] RNTuple.SerializeFieldStructure (0 ms)
[ RUN      ] RNTuple.SerializeEnvelope
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_serialize.cxx:121: Failure
Value of: err.what()
Expected: has substring "CRC32"
  Actual: 0x2aa065e7348 pointing to "The RNTuple format is too new (version 256) (unchecked RResult access!)\nAt:\n  static RResult<unsigned int> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeEnvelope(const void*, uint32_t, uint32_t&) [/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:629]\n  static RResult<unsigned int> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeEnvelope(const void*, uint32_t) [/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:646]\n" (of type char const*)
[  FAILED  ] RNTuple.SerializeEnvelope (0 ms)
[ RUN      ] RNTuple.SerializeFrame
[       OK ] RNTuple.SerializeFrame (0 ms)
[ RUN      ] RNTuple.SerializeFeatureFlags
[       OK ] RNTuple.SerializeFeatureFlags (0 ms)
[ RUN      ] RNTuple.SerializeLocator
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_serialize.cxx:341: Failure
Failed
unsupported locator type should throw
[  FAILED  ] RNTuple.SerializeLocator (0 ms)
[ RUN      ] RNTuple.SerializeEnvelopeLink
[       OK ] RNTuple.SerializeEnvelopeLink (0 ms)
[ RUN      ] RNTuple.SerializeClusterSummary
[       OK ] RNTuple.SerializeClusterSummary (0 ms)
[ RUN      ] RNTuple.SerializeClusterGroup
[       OK ] RNTuple.SerializeClusterGroup (0 ms)
[ RUN      ] RNTuple.SerializeEmptyHeader
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.SerializeEmptyHeader (190 ms)
[ RUN      ] RNTuple.SerializeHeader
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.SerializeHeader (0 ms)
[ RUN      ] RNTuple.SerializeFooter
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.SerializeFooter (0 ms)
[----------] 14 tests from RNTuple (190 ms total)
[----------] Global test environment tear-down
[==========] 14 tests from 1 test suite ran. (190 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] RNTuple.SerializeEnvelope
[  FAILED  ] RNTuple.SerializeLocator
 2 FAILED TESTS
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### gtest-tree-ntuple-v7-test-ntuple-types

Endian issue:

$ printf '%x\n%x\n' 180388626432 42
2a00000000
2a
~~~
 465/1272 Test  #433: gtest-tree-ntuple-v7-test-ntuple-types ..............................***Failed    5.68 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TFile.ReadWithoutGlobalRegistrationWeb:TFile.ReadWithoutGlobalRegistrationNet:RNTuple.TClassEBO
[==========] Running 18 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 18 tests from RNTuple
[ RUN      ] RNTuple.TypeName
[       OK ] RNTuple.TypeName (316 ms)
[ RUN      ] RNTuple.CreateField
[       OK ] RNTuple.CreateField (0 ms)
[ RUN      ] RNTuple.ArrayField
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.ArrayField (23 ms)
[ RUN      ] RNTuple.StdPair
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.StdPair (226 ms)
[ RUN      ] RNTuple.StdTuple
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.StdTuple (169 ms)
[ RUN      ] RNTuple.Int64_t
[       OK ] RNTuple.Int64_t (0 ms)
[ RUN      ] RNTuple.Char
[       OK ] RNTuple.Char (0 ms)
[ RUN      ] RNTuple.Int8_t
[       OK ] RNTuple.Int8_t (0 ms)
[ RUN      ] RNTuple.Int16_t
[       OK ] RNTuple.Int16_t (0 ms)
[ RUN      ] RNTuple.UInt16_t
[       OK ] RNTuple.UInt16_t (0 ms)
[ RUN      ] RNTuple.UnsupportedStdTypes
[       OK ] RNTuple.UnsupportedStdTypes (3 ms)
[ RUN      ] RNTuple.Casting
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
/builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/test/ntuple_types.cxx:280: Failure
Expected equality of these values:
  42
  *fieldCast
    Which is: 180388626432
[  FAILED  ] RNTuple.Casting (56 ms)
[ RUN      ] RNTuple.TClass
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.TClass (284 ms)
[ RUN      ] RNTuple.TClassMultipleInheritance
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.TClassMultipleInheritance (195 ms)
[ RUN      ] RNTuple.TClassTemplatedBase
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.TClassTemplatedBase (260 ms)
[ RUN      ] RNTuple.TVirtualCollectionProxy
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.TVirtualCollectionProxy (4036 ms)
[ RUN      ] RNTuple.Enums
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&)>: The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in <[ROOT.NTuple] Warning /builddir/build/BUILD/root-6.28.00/tree/ntuple/v7/src/RNTupleSerialize.cxx:1148 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&)>: Pre-release format version: RC 1
[       OK ] RNTuple.Enums (29 ms)
[ RUN      ] RNTuple.Traits
[       OK ] RNTuple.Traits (0 ms)
[----------] 18 tests from RNTuple (5604 ms total)
[----------] Global test environment tear-down
[==========] 18 tests from 1 test suite ran. (5604 ms total)
[  PASSED  ] 17 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RNTuple.Casting
 1 FAILED TEST
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

### PR DESCRIPTION
**Pull request by jblomer**
Addresses several bugs on big-endian architecture, some in the testing code only, some in the actual code. Tested manually on Power8/EL7. Also tested that RNTuple data written on little-endian can be read on big-endian and vice versa.

Fixes #12426

### CODE REVIEW

File: tree/ntuple/v7/src/RMiniFile.cxx [hunk 1]
```diff
@@ -44,7 +54,14 @@ namespace {
 class RUInt16BE {
 private:
    std::uint16_t fValBE = 0;
-   static std::uint16_t Swap(std::uint16_t val) { return (val & 0x00FF) << 8 | (val & 0xFF00) >> 8; }
+   static std::uint16_t Swap(std::uint16_t val)
+   {
+#if R__LITTLE_ENDIAN == 1
+      return RByteSwap<sizeof(fValBE)>::bswap(val);
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RMiniFile.cxx:60]: Maybe use `sizeof(val)` instead of the member `fValBE` since we are in a `static` function.

File: tree/ntuple/v7/src/RMiniFile.cxx [hunk 2]
```diff
@@ -63,8 +80,11 @@ class RUInt32BE {
    std::uint32_t fValBE = 0;
    static std::uint32_t Swap(std::uint32_t val)
    {
-      auto x = (val & 0x0000FFFF) << 16 | (val & 0xFFFF0000) >> 16;
-      return (x & 0x00FF00FF) << 8 | (x & 0xFF00FF00) >> 8;
+#if R__LITTLE_ENDIAN == 1
+      return RByteSwap<sizeof(fValBE)>::bswap(val);
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RMiniFile.cxx:84]: `sizeof(val)`

File: tree/ntuple/v7/src/RMiniFile.cxx [hunk 3]
```diff
@@ -84,8 +104,11 @@ class RInt32BE {
    std::int32_t fValBE = 0;
    static std::int32_t Swap(std::int32_t val)
    {
-      auto x = (val & 0x0000FFFF) << 16 | (val & 0xFFFF0000) >> 16;
-      return (x & 0x00FF00FF) << 8 | (x & 0xFF00FF00) >> 8;
+#if R__LITTLE_ENDIAN == 1
+      return RByteSwap<sizeof(fValBE)>::bswap(val);
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RMiniFile.cxx:108]: `sizeof(val)`

File: tree/ntuple/v7/src/RMiniFile.cxx [hunk 4]
```diff
@@ -105,9 +128,11 @@ class RUInt64BE {
    std::uint64_t fValBE = 0;
    static std::uint64_t Swap(std::uint64_t val)
    {
-      auto x = (val & 0x00000000FFFFFFFF) << 32 | (val & 0xFFFFFFFF00000000) >> 32;
-      x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
-      return (x & 0x00FF00FF00FF00FF) << 8 | (x & 0xFF00FF00FF00FF00) >> 8;
+#if R__LITTLE_ENDIAN == 1
+      return RByteSwap<sizeof(fValBE)>::bswap(val);
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RMiniFile.cxx:132]: `sizeof(val)`

**Review by hahnjo — COMMENTED** [review]
minor comment about the argument to `sizeof()` used in the `static` functions

**Review by hahnjo — APPROVED** [review]
