### PR TITLE
[df] Support std::array data members in TTree schemas

### LINKED ISSUE #14790: 1D `std::array` "has both a leaf count and a static length"
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The [EDM4hep](https://github.com/key4hep/EDM4hep) default data model definition includes multiple fields defined as fixed-length single-dimensional `std::array` of `float`, e.g. `std::array<float,6> covMatrix` in `edm4hep::TrackerHit` [1]. When data is written with these fields, it is not readable with ROOT, and an error is returned.

This is reported under EDM4hep as well, at https://github.com/key4hep/EDM4hep/issues/262, but it appears this is an issue in ROOT, not EDM4hep.

[1]: https://github.com/key4hep/EDM4hep/blob/60ad463c5474b51115345446edb5e90bf9dc33f5/edm4hep.yaml#L348

### Reproducer

To reproduce the issue with the input file [edm4hep_events.root.gz](https://github.com/root-project/root/files/14365763/edm4hep_events.root.gz) (38K), use the follwing steps.

### In ROOT interpreter:
```
ROOT::RDataFrame df("events", "edm4hep_events.root")
df.Describe()
```
returns
```
root [0] ROOT::RDataFrame df("events", "edm4hep_events.root")
(ROOT::RDataFrame &) A data frame built on top of the events dataset.
root [1] df.Describe()
Error in <TRint::HandleTermInput()>: std::runtime_error caught: TTree leaf TrackerHitPlanes.covMatrix[6] has both a leaf count and a static length. This is not supported.
```

### In Python interpreter:
```
import ROOT
df = ROOT.RDataFrame("events", "edm4hep_events.root")
df.Describe()
```
returns
```
In [1]: import ROOT
   ...: df = ROOT.RDataFrame("events", "edm4hep_events.root")
   ...: df.Describe()
   ...: 
Installed ROOT event loop hook.
---------------------------------------------------------------------------
runtime_error                             Traceback (most recent call last)
Cell In[1], line 3
      1 import ROOT
      2 df = ROOT.RDataFrame("events", "edm4hep_events.root")
----> 3 df.Describe()

runtime_error: ROOT::RDF::RDFDescription ROOT::RDF::RInterfaceBase::Describe() =>
    runtime_error: TTree leaf TrackerHitPlanes.covMatrix[6] has both a leaf count and a static length. This is not supported.
```

### Generation of the input file

To generate the input file [edm4hep_events.root.gz](https://github.com/root-project/root/files/14365763/edm4hep_events.root.gz) (38K), use the follwing steps.

1. Load the Key4hep environment:
```console
source /cvmfs/sw.hsf.org/key4hep/setup.sh
```
2. Create a plain EDM4hep file, using the unit tests in EDM4hep.
```console
git clone -b v00-10-05 https://github.com/key4hep/edm4hep /tmp/edm4hep
cmake -B/tmp/edm4hep/build -S/tmp/edm4hep
make -C/tmp/edm4hep/build
ctest --test-dir /tmp/edm4hep/build
```
4. The EDM4hep file will be in `/tmp/edm4hep/build/test/edm4hep_events.root`.

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/02                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 18 2024, 03:09:46                 |
  | From heads/master@tags/v6-30-02                                  |
  | With g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0                         |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

Various: Key4hep via /cvmfs/sw.hsf.org/, spack

### Operating system

Linux Ubuntu 22.04

### Additional context

In a couple of places [1] [2] the breadcrumbs lead to the JIRA tickets https://its.cern.ch/jira/browse/ROOT-9509, however that is for multidimensional arrays.

[1]: https://root-forum.cern.ch/t/removing-entire-columns-from-rdataframe-object/52119
[2]: https://root-forum.cern.ch/t/rdataframe-functionality-missing/54505

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes https://github.com/root-project/root/issues/14790

Include tests that both check the fixed behaviour and document limitations and currently unsupported schemas or operations on them that are closely related to the one described above.

Note that this PR shows the testing infrastructure for the equivalent RNTuple schemas, but provides no support for it. After internal discussion, it has become evident that the RNTuple data source would need more work for support of partial reading of class data members with types different than the on-disk one.

## Note for posterity

Another approach could have been to standardise in which way RDF can read collection types such as the ones addressed in this PR. This was proposed and discussed at PPP194 https://indico.cern.ch/event/1660527/ . After discussion, the proposal was rejected. Find more details in the minutes attached to the agenda.

### CODE REVIEW

**Comment by vepadulano** [comment]
Marking the PR ready for review as all the wanted changes are there. There is a leftover failure on Windows related to an issue with CMake that has been understood and will be dealt with in a separate PR (that will become a requirement for this one).

File: tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx [hunk 1]
```diff
@@ -99,6 +100,9 @@ private:
    /// We return a reference to this RVec to clients, to guarantee a stable address and contiguous memory layout.
    RVec<Byte_t> fRVec{};
 
+   /// When the user explicitly requests std::vector<T>, we use this std::vector as a stable storage.
+   std::vector<Byte_t> fStdVector{};
```
Comment (pcanal) [inline tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx:104]: This seems to be here 'just' in case.  Do we understand the extra memory cost (if any) overall (i.e. for the cases that do no use it)?

File: tree/dataframe/src/RDFUtils.cxx [hunk 2]
```diff
@@ -251,9 +251,14 @@ std::string GetLeafTypeName(TLeaf *leaf, const std::string &colName)
...
    } else if (leaf->GetLeafCount() != nullptr && leaf->GetLenStatic() > 1) {
-      // we do not know how to deal with this branch
-      throw std::runtime_error("TTree leaf " + colName +
-                               " has both a leaf count and a static length. This is not supported.");
+      // This case is encountered when a branch is a collection (e.g. std::vector) of a user-defined class which has
+      // a data member that is a fixed-size array. Here, 'leaf' is said data member, and the user could read it
+      // partially as std::vector<std::array<T, N>>. We expose it as ROOT::RVec<std::array<T, N>> for consistency with
+      // other collection types.
+      // WARNING: Currently this considers only the possibility of a 1-dim array, as TLeaf does not expose information
+      // to get all dimension lengths of a multi-dim array.
```
Comment (pcanal) [inline tree/dataframe/src/RDFUtils.cxx]: Technically I think it is only 'does not clearly expose' (or simply or straighforwardly) as the information is there either in the `TLeafElement` or its corresponding `TStreamerElement` or in the `Title` for the other leaf types.

File: tree/treeplayer/inc/TTreeReaderArray.h [hunk 3]
```diff
@@ -26,6 +26,14 @@ Base class of TTreeReaderArray.
 */
 
 class TTreeReaderArrayBase : public TTreeReaderValueBase {
+   struct StreamerElementArrayInfo {
```
Comment (pcanal) [inline tree/treeplayer/inc/TTreeReaderArray.h:29]: Is this information really (or just currently) limited to the `TLeafElement/TStreamerElement` case?

File: tree/treeplayer/src/TTreeReaderArray.cxx [hunk 4]
```diff
@@ -671,7 +674,52 @@ void ROOT::Internal::TTreeReaderArrayBase::CreateProxy()
...
+            return false;
+         auto streamerInfo = cl->GetStreamerInfo();
+         if (!streamerInfo)
+            return false;
+
+         auto streamerElements = streamerInfo->GetElements();
+         if (!streamerElements)
+            return false;
+
+         // We don't know what to do when there is more than one streamer element
```
Comment (pcanal) [inline tree/treeplayer/src/TTreeReaderArray.cxx]: Why not?  Each `TBranchElement` (and thus `TLeafElement`) knows exactly which `TStreamerElement` it correspond to (see `TBranchElement::fID`).

Comment (pcanal) [reply tree/treeplayer/src/TTreeReaderArray.cxx]: humm .. and `GetID` is actually used later on ... What am I missing?

File: tree/treeplayer/inc/TTreeReaderArray.h (hunk 3 above)
Comment (vepadulano) [reply tree/treeplayer/inc/TTreeReaderArray.h:29]: No idea about that tbh, given that this is a development done for a specific use case, I started with a specific naming

File: tree/treeplayer/src/TTreeReaderArray.cxx (hunk 4 above)
Comment (vepadulano) [reply tree/treeplayer/src/TTreeReaderArray.cxx]: So you're telling me that `streamerElements->GetEntries()` can only ever be `1`?

Comment (pcanal) [reply tree/treeplayer/src/TTreeReaderArray.cxx]: No, the opposite .. it is almost always more than 1 (well except for the case of a struct introduced just for the purpose of being able to store a collection of std::array).

File: tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx (hunk 1 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx:104]: The extra memory cost is `sizeof(std::vector<std::byte>)` once per reader, i.e. once per unique column that the user explicitly requests that has a collection type.

File: tree/dataframe/src/RDFUtils.cxx (hunk 2 above)
Comment (vepadulano) [reply tree/dataframe/src/RDFUtils.cxx]: Agreed, not for this PR.

File: tree/treeplayer/inc/TTreeReaderArray.h (hunk 3 above)
Comment (vepadulano) [reply tree/treeplayer/inc/TTreeReaderArray.h:29]: Without clear reason to change the name, I will leave it as is for now.

File: tree/treeplayer/src/TTreeReaderArray.cxx (hunk 4 above)
Comment (vepadulano) [reply tree/treeplayer/src/TTreeReaderArray.cxx]: I will rephrase the sentence to
```suggestion
         // This part of the logic currently supports the specific use cases where there is only one streamer element corresponding to the array data member that we are trying to partially read into a collection. Without further use cases surfacing, we do not support more than one streamer element
```

**Comment by vepadulano** [comment]
@dpiparo I would like to propose for this bugfix to be included in 6.40

**Review by pcanal — APPROVED** [review]
LGTM.  Thanks.

**Comment by dpiparo** [comment]
moved to rc1
