### PR TITLE
 TBranch::GetBulkEntries proper handling of already loaded basket

### LINKED ISSUE #6416: TBulkRead fails with "fExtraBasket should have been set to nullptr by GetFreshBasket"
## Describe the bug

I am trying to use the new TBulkRead API. I have a set of branches that I read with (updated with full reproducer):

```c++
#include <TBufferFile.h>
#include <TFile.h>
#include <TTree.h>
#include <iostream>

void foo() {
  auto f = TFile::Open("http://hyperloop.cern.ch/train-workdir/testdata/LFN/alice/data/2015/LHC15o/000245064/pass5_lowIR/PWGZZ/Run3_Conversion/71_20200915-2255_child_1/0935/AO2D.root");
  auto t = (TTree*)f->Get("O2track");
  auto e = t->GetEntries();
  auto b = t->GetBranch("fAlpha");
  assert(b);
  int pos = 0;
  while (pos < e) {
    TBufferFile buf(TBuffer::EMode::kWrite, 32*1024);
    auto &r = b->GetBulkRead();
    auto s = r.GetBulkEntries(pos, buf);
    pos += s;
    std::cout << "Read " << s << " elements " << std::endl;
    b->Print();
  }
}
```

however when I get to read the last but one buffer, I get:

```c++
Read 1000 elements
*Br 3398 :fAlpha    : fAlpha/F                                               *
*Entries :  3399743 : Total  Size=   13939349 bytes  File Size  =   11798760 *
*Baskets :     3399 : Basket Size=       1000 bytes  Compression=   1.17     *
*............................................................................*
Fatal: fExtraBasket == nullptr && "fExtraBasket should have been set to nullptr by GetFreshBasket" violated at line 1474 of `/Users/ktf/src/sw/SOURCES/ROOT/v6-20-02-alice7/v6-20-02-alice7/tree/tree/src/TBranch.cxx'
aborting
```

## Expected behavior

Reading all the baskets, with the last one returning the appropriate number of entries.

## Setup

6.20.0

## Additional context

TFile with a few TTree in it, all the branches have basic types or arrays of basic types.

### LINKED ISSUE #6417: TBulkRead does not work when TFile is missing
## Standalone TTree does not allow for TBulkRead

I created a standalone TTree, without a backing TFile, for test purposes. While using TTreeReader works just fine, using TBulkRead does not work.

## Expected behavior

Given the API to request a TBulkRead does not involve a TFile, I would have expected it to work without.

## Setup

6.20.0

##

### PR DESCRIPTION
**Pull request by pcanal**
TBranch::GetBulkEntries proper handling of already loaded basket

This fixes #6416 and fixes #6417

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by ktf** [comment]
For the record, this works for me.

**Comment by pcanal** [comment]
The test failures are unrelated (mac1015/cxx17 : python configuration problem.  WIndows: test with known problem, this time "maybe" related to the message `Warning in <TClassTable::Add>: class ROOT::Detail::TTypedIter<class TEnumConstant> already in TClassTable`

**Comment by pcanal** [comment]
I..e now completely ready for review.

**Comment by stwunsch** [comment]
> Build failed on mac1015/cxx17.
> Running on macphsft20.dyndns.cern.ch:/Users/sftnight/build/workspace/root-pullrequests-build
> [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/97532/console).
> 
> ### Failing tests:
> * [projectroot.runtutorials.test_import_pandas](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/97532/testReport/projectroot/runtutorials/test_import_pandas/)
> * [projectroot.roottest.python.cling.roottest_python_cling_api](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/97532/testReport/projectroot.roottest.python/cling/roottest_python_cling_api/)
> * [projectroot.roottest.python.cling.roottest_python_cling_class](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/97532/testReport/projectroot.roottest.python/cling/roottest_python_cling_class/)

I fixed that!

File: tree/tree/test/BulkApi.cxx [hunk 1]
```diff
@@ -74,48 +82,108 @@ TEST_F(BulkApiTest, stdRead)
    delete hfile;
 }
 
-TEST_F(BulkApiTest, simpleRead)
+void SimpleReadFunc(const char *filename, const char *treename)
 {
-   auto hfile = TFile::Open(fFileName.c_str());
-   printf("Starting read of file %s.\n", fFileName.c_str());
+   auto hfile = TFile::Open(filename);
+   printf("Starting read of file %s.\n", filename);
```
Comment (jblomer) [inline tree/tree/test/BulkApi.cxx:88]: Should this and the following `printf`s become a `R__INFO` so that the verbosity of the test can be controlled?

File: tree/tree/test/BulkApi.cxx [hunk 2]
```diff
@@ -152,3 +220,38 @@ TEST_F(BulkApiTest, fastRead)
...
+   t.Branch("fAlpha",&i);
+   for(i = 0; i < 100000; ++i)
+      t.Fill();
+
+   TBufferFile buf(TBuffer::EMode::kWrite, 32*1024);
+   auto &r = t.GetBranch("fAlpha")->GetBulkRead();
+
+   {
+      auto s = r.GetBulkEntries(0, buf);
+      ASSERT_EQ(s, 7982) << "Did not read the expected number of entries.";
```
Comment (jblomer) [inline tree/tree/test/BulkApi.cxx:237]: GTest works better if the expected value comes first in the equality checks.  Otherwise the error message reads "upside down".

**Review by jblomer — CHANGES_REQUESTED** [review]

File: tree/tree/test/BulkApi.cxx (hunk 1 above)
Comment (pcanal) [reply tree/tree/test/BulkApi.cxx:88]: Probably, I just "continued" the style of the test ... i.e. let's do that in another PR.

File: tree/tree/test/BulkApi.cxx (hunk 2 above)
Comment (pcanal) [reply tree/tree/test/BulkApi.cxx:237]: fair enough.

**Comment by pcanal** [comment]
The macos failure is infrastructure related (git area needs cleanup, an incomplete apply has left traces).
