### PR TITLE
Fix the computation of the Confidence band of TRatioPlot

### LINKED ISSUE #14838: Problems with Confidence Band of TRatioPlot
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

As reported in https://root-forum.cern.ch/t/tratioplot-confidence-bands-limiting-asymmetry/58045
TRatioPlot has a bug in the computation of the confidence interval of the fitted function. 

The problem seems due to a bug indexing the histogram with bin number starting from 1 and the TGraohErrors representing the confidence band with points indexing from 0. 

There is also a bug in retrieving the fit function from the fit. When another object is present in the histogram list of functions (e.g. the statistic box from the fit) the fit function is not found by TRatioPlot. 

### Reproducer

See Forum post

### ROOT version

all

### Installation method

all

### Operating system

all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lmoneta**
The wrong index was used when filling the TGraphError for the lower plot. TGraph starts from 0 while histogram binning from 1.

Fix also retrieving the fitted function from the histogram

This PR fixes #14838

### CODE REVIEW

**Review by couet — APPROVED** [review]

File: graf2d/gpad/src/TRatioPlot.cxx [hunk 1]
```diff
@@ -607,8 +607,15 @@ void TRatioPlot::Draw(Option_t *option)
...
 
    if (fMode == TRatioPlot::CalculationMode::kFitResidual) {
-      TF1 *func = dynamic_cast<TF1*>(fH1->GetListOfFunctions()->At(0));
-
+      // use last function in the list
+      TF1 * func = nullptr;
+      for (int i = fH1->GetListOfFunctions()->GetSize()-1; i >= 0; i--) {
+         auto obj = fH1->GetListOfFunctions()->At(i);
+         if (obj->InheritsFrom(TF1::Class()) ) {
+            func = dynamic_cast<TF1*>(fH1->GetListOfFunctions()->At(0));
```
Comment (ferdymercury) [inline graf2d/gpad/src/TRatioPlot.cxx:615]:
```suggestion
            func = dynamic_cast<TF1*>(obj);
```

Comment (lmoneta) [reply graf2d/gpad/src/TRatioPlot.cxx]: Thanks for spotting this!
