### PR TITLE
[math] Properly treat the xyexpo, xygausn and xylandaun 2D function

### LINKED ISSUE #20733: [math] xyexpo does not work in TFormula
### Check duplicate issues.

- [x] Checked for duplicates

### Description

This was noticed in #20719.
The problem is that the user friendly name `xyexpo` is not correctly parsed by TFormula. Moreover, the formula stored for xyexpo is wrong.

### Reproducer

Just do `TFormula("f","xyexpo").

### ROOT version

all

### Installation method

all

### Operating system

all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dpiparo**
and add a unit test.
Fixes #20733

### CODE REVIEW

File: hist/hist/test/test_TFormula.cxx [hunk 1]
```diff
@@ -13,6 +13,13 @@ TEST(TFormula, Interp)
   TFormula f("func", "TGeoBBox::DeclFileLine()");
 }
 
+TEST(TFormula, xyexpo)
+{
+
+   TFormula f2("f2", "xyexpo");
+   EXPECT_EQ(f2.GetExpFormula(), TString("exp([p0]+[p1]*x+[p2]*y"));
```
Comment (ferdymercury) [inline hist/hist/test/test_TFormula.cxx]:
```suggestion
   TFormula f2("f2", "xyexpo");
   EXPECT_EQ(f2.GetExpFormula(), TString("exp([p0]+[p1]*x+[p2]*y)"));
```
missing parenthesis.

consider also adding a test for xylandaun that is also failing

Thanks for tackling this!

**Review by lmoneta — APPROVED** [review]
LGTM after adding the missing ")" in the test. 
Thanks for fixing  this and adding a test
