### PR TITLE
[RF] Fix RooMCStudy module dataset size mismatch on failed fits

### LINKED ISSUE #6949: RooMCStudyModule finalizeRun() bug
I initially reported this on the [root forum](https://root-forum.cern.ch/t/roodllsignificancemcsmodule-merge-error/42702)

### Describe the bug
RooAbsMCStudyModule::finalizeRun() returning a RooDataSet sometimes causes a merge error which is difficult to avoid.
Caused by RooMCStudy::_fitParData and RooAbsMCStudyModule data being different sizes

### Expected behavior
RooMCStudy and RooAbsMCStudyModule data merging correctly,
OR
A way to consistently make the datasets the same size

### To Reproduce
Run included macro

`

#include "RooRealVar.h"
#include "RooGaussian.h"
#include "RooConstVar.h"
#include "RooAddPdf.h"
#include "RooMCStudy.h"
#include "RooFFTConvPdf.h"
#include "RooArgusBG.h"
#include "RooDLLSignificanceMCSModule.h"

using namespace RooFit;
const double xmin = 4.3, xmax = 4.55, bratio = 0.3, m0 = 4.482;
const int nevents = 100;

void min_mcsign_error() {
	RooRealVar x("mresp", "x", 4.3, 4.55);

	// signal
	RooRealVar mean_res("#mean_{gauss}", "mean_res", 4.47);
	RooRealVar sigma_res("#sigma_{gauss}", "sigma_res", 0.05);
	RooGaussian sig("gs_res", "gs_res", x, mean_res, sigma_res);

	// background
	RooRealVar argpar("shape", "argus shape parameter", -7);
	RooRealVar power("power", "argus power parameter", 0.75);
	RooArgusBG bkg("bkg", Form("Background ARGUS, m_{0} = %.3f", m0), x, RooConst(m0), argpar, power);

	// generating distribution
	RooRealVar nsig("nsig", "signal number", bratio);
	RooRealVar nbg("nbg", "bg number", 1.-bratio); 
	RooAddPdf mcdist("distribution", "BW+a", RooArgList(sig, bkg), RooArgList(nsig, nbg));

	// signal used in model
	RooRealVar fitmean_res("#mean_{gauss}", "mean_res", 4.2, 4., 5.);
	RooRealVar fitsigma_res("#sigma_{gauss}", "sigma_res", 0.1, 0., 1.);
	RooGaussian fitsig("gs_res", "gs_res", x, fitmean_res, fitsigma_res);
	
	// background used in model
	RooRealVar fitargpar("shape", "fit argus shape parameter", -6.5, -8, -6);
	RooRealVar fitpower("power", "fit argus power parameter", 0.5, 0, 1);
	RooArgusBG fitbkg("fitbkg", "Fit Background ARGUS", x, RooConst(m0), fitargpar, fitpower);
	RooRealVar fitnsig("nsig", "signal number", 0.6 * nevents, 0, 1.2 * nevents);
	RooRealVar fitnbg("nbg", "bg number", 0.4 * nevents, 0, 1.2 * nevents);

	// fitting model
	RooAddPdf model("model", "BW+a fitted", RooArgList(fitsig, fitbkg), RooArgList(fitnsig, fitnbg));

	RooMCStudy* mcstudy =
		new RooMCStudy(mcdist, x, FitModel(model), Binned(kFALSE), Silence(), Extended(kFALSE),
			FitOptions(Extended(kFALSE), PrintEvalErrors(-1), Save(kTRUE)));

	RooDLLSignificanceMCSModule sigModule("nsig", 0);
	mcstudy->addModule(sigModule);

	mcstudy->generateAndFit(100, nevents, kTRUE);

	std::cout << mcstudy->fitParDataSet() << std::endl;
}
`

which results in 

`
[#0] ERROR:InputArguments -- RooDataSet::merge(fitParData_model_distribution) ERROR: datasets have different size
RooDataSet::fitParData_model_distribution[#mean_{gauss},#sigma_{gauss},nbg,nsig,power,shape,NLL,ngen,#mean_{gauss}err,#mean_{gauss}pull,#sigma_{gauss}err,#sigma_{gauss}pull,nbgerr,nbgpull,nsigerr,nsigpull,powererr,powerpull,shapeerr,shapepull] = 84 entries
`

### Setup
ROOT 6.22/02
WSL v2 with Ubuntu 20.04 
Binay download (built for linuxx8664gcc)

### Additional context
RooDLLSignificanceMCSModule::finalizeRun() states that ` If a RooDataSet is returned, it must have a length equal to the number of toy experiments performed and will merged with the fitpar dataset of RooMCStudy. `, however that is not true.
If some of the toy experiments performed did not converge, the RooMCStudy dataset size is lower than the number of experiments.

At the same time, there is no way (that i could find) to access  the fit result status of current run from RooAbsMCStudyModule, making it hard to consistently avoid the merge error

### PR DESCRIPTION
**Pull request by guitargeek**
RooMCStudy stores fit results only for successful fits in the internal
`_fitParData` dataset. However, RooAbsMCStudyModule implementations had
no way to detect whether a fit succeeded, while `finalizeRun()` requires
modules to return datasets with the same number of entries as the
fit parameter dataset.

This mismatch could lead to merge errors:
```
  RooDataSet::merge(...) ERROR: datasets have different size
```

This fix suggests to propagate fit success status to study modules via
`RooAbsMCStudyModule::processAfterFit`, making it also pure virtual to
enforce correct handling in all modules. It is then correctly
implemented in all RooAbsMCStudyModule-derived classes.

Closes https://github.com/root-project/root/issues/6949.

### CODE REVIEW

File: roofit/roofit/inc/RooChi2MCSModule.h [hunk 1]
```diff
@@ -29,9 +29,9 @@ class RooChi2MCSModule : public RooAbsMCStudyModule {
   ~RooChi2MCSModule() override ;
 
   bool initializeInstance() override ;
-  bool initializeRun(Int_t /*numSamples*/) override ;
+  bool initializeRun(Int_t numSamples) override ;
   RooDataSet* finalizeRun() override ;
-  bool processAfterFit(Int_t /*sampleNum*/) override  ;
+  bool processAfterFit(Int_t sampleNum, bool fitOk) override  ;
```
Comment (lmoneta) [inline roofit/roofit/inc/RooChi2MCSModule.h]: It seems to me that sampleNum is not used in any implementation. If this is the case should not be removed from the interface? In any case by adding "fitOK", the backward compatibility is broken

**Review by lmoneta — APPROVED** [review]
LGTM! Just a comment on the processAfterFit interface.
Thank you Jonas for this fix!

File: roofit/roofit/inc/RooChi2MCSModule.h (hunk 1 above)
Comment (guitargeek) [reply roofit/roofit/inc/RooChi2MCSModule.h]: That's true. I'll update it.
