### PR TITLE
Fix clang-tidy issues in net classes

### LINKED ISSUE #7528: [net] Clang-Tidy Clazy Warnings
```
/opt/root_src/net/auth/src/TAuthenticate.cxx:400:4: warning: Value stored to 'st' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'st' is never read in /opt/root_src/net/auth/src/TAuthenticate.cxx:400
/opt/root_src/net/auth/src/TAuthenticate.cxx:1183:8: warning: Branch condition evaluates to a garbage value [clang-analyzer-core.uninitialized.Branch]
 1: Assuming 'gGlobalMutex' is null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 2: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 3: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 4: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 5: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 6: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 7: Assuming 'pwdhash' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 8: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 9: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
10: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
11: Assuming field 'fVersion' is <= 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
12: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
13: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1875
14: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1875
15: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1879
16: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1879
17: Assuming 'kind' is not equal to kROOTD_AUTH in /opt/root_src/net/auth/src/TAuthenticate.cxx:1884
18: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1884
19: Assuming 'kind' is not equal to kROOTD_ERR in /opt/root_src/net/auth/src/TAuthenticate.cxx:1890
20: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1890
21: Assuming the condition is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:1916
22: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1916
23: Calling 'TAuthenticate::PromptPasswd' in /opt/root_src/net/auth/src/TAuthenticate.cxx:1919
24: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1146
25: Left side of '||' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1146
26: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1146
27: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1146
28: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1156
29: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1156
30: Assuming 'fgPasswdDialog' is non-null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1167
31: Left side of '&&' is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:1167
32: Assuming the condition is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:1167
33: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1167
34: Loop condition is false. Execution continues on line 1183 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1173
35: Branch condition evaluates to a garbage value in /opt/root_src/net/auth/src/TAuthenticate.cxx:1183
/opt/root_src/net/auth/src/TAuthenticate.cxx:1619:16: warning: Value stored to 'needsalt' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'needsalt' is never read in /opt/root_src/net/auth/src/TAuthenticate.cxx:1619
/opt/root_src/net/auth/src/TAuthenticate.cxx:1648:17: warning: Potential leak of memory pointed to by 'tmpsalt' [clang-analyzer-cplusplus.NewDeleteLeaks]
 1: Assuming 'gGlobalMutex' is null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 2: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 3: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 4: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 5: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 6: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 7: Assuming 'pwdhash' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 8: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 9: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
10: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
11: Assuming field 'fVersion' is > 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
12: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
13: Assuming 'pw' is null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1547
14: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1547
15: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1565
16: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1570
17: Assuming 'stat' is not equal to kErrNotAllowed in /opt/root_src/net/auth/src/TAuthenticate.cxx:1573
18: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1573
19: 'kind' is not equal to kROOTD_AUTH in /opt/root_src/net/auth/src/TAuthenticate.cxx:1577
20: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1577
21: 'anon' is equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
22: Left side of '&&' is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
23: Assuming 'cryptopt' is equal to 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
24: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
25: Assuming 'kind' is equal to kROOTD_RSAKEY in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
26: Left side of '||' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
27: Assuming 'stat' is >= 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
28: Left side of '||' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
29: Assuming 'stat' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
30: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
31: Assuming 'gDebug' is <= 3 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1601
32: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1601
33: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1608
34: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1608
35: 'needsalt' is 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1612
36: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1612
37: Calling 'TAuthenticate::SecureRecv' in /opt/root_src/net/auth/src/TAuthenticate.cxx:1615
38: 'str' is non-null in /opt/root_src/net/auth/src/TAuthenticate.cxx:2874
39: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2874
40: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2878
41: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2878
42: Assuming 'gDebug' is <= 3 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2881
43: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2881
44: Assuming 'len' is not equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2884
45: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2884
46: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2887
47: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2887
48: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2891
49: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2891
50: 'key' is equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2893
51: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2893
52: 'dec' is equal to 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2894
53: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2894
54: Memory is allocated in /opt/root_src/net/auth/src/TAuthenticate.cxx:2903
55: Returned allocated memory via 4th parameter in /opt/root_src/net/auth/src/TAuthenticate.cxx:1615
56: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1615
57: Assuming 'slen' is 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1622
58: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1622
59: Potential leak of memory pointed to by 'tmpsalt' in /opt/root_src/net/auth/src/TAuthenticate.cxx:1648
/opt/root_src/net/auth/src/TAuthenticate.cxx:2925:10: warning: Null pointer passed to 1st parameter expecting 'nonnull' [clang-analyzer-core.NonNullParamChecker]
 1: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:4153
 2: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4153
 3: Assuming 'kind' is equal to kROOTD_RSAKEY in /opt/root_src/net/auth/src/TAuthenticate.cxx:4162
 4: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4162
 5: Assuming the condition is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:4164
 6: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4164
 7: Assuming the condition is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:4165
 8: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4165
 9: Assuming the condition is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:4172
10: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4172
11: Assuming 'fKey' is non-null in /opt/root_src/net/auth/src/TAuthenticate.cxx:4173
12: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4173
13: Assuming 'klen' is > 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:4175
14: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:4175
15: 'pwd' initialized to a null pointer value in /opt/root_src/net/auth/src/TAuthenticate.cxx:4193
16: Calling 'TAuthenticate::SecureRecv' in /opt/root_src/net/auth/src/TAuthenticate.cxx:4194
17: 'str' is non-null in /opt/root_src/net/auth/src/TAuthenticate.cxx:2874
18: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2874
19: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2878
20: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2878
21: Assuming 'gDebug' is <= 3 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2881
22: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2881
23: Assuming 'len' is not equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2884
24: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2884
25: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2887
26: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2887
27: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:2891
28: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2891
29: Assuming 'key' is not equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2893
30: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2893
31: Assuming 'key' is equal to 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2906
32: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2906
33: Assuming 'gDebug' is <= 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:2915
34: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:2915
35: Null pointer passed to 1st parameter expecting 'nonnull' in /opt/root_src/net/auth/src/TAuthenticate.cxx:2925
/opt/root_src/net/auth/src/TAuthenticate.cxx:3148:14: warning: Passed-by-value struct argument contains uninitialized data (e.g., field: 'n_len') [clang-analyzer-core.CallAndMessage]
 1: Assuming 'gGlobalMutex' is null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 2: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 3: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1513
 4: expanded from macro 'R__LOCKGUARD2' in /opt/root_src/core/base/inc/TVirtualMutex.h:94
 5: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 6: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1515
 7: Assuming 'pwdhash' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 8: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1523
 9: Assuming 'gDebug' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
10: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1527
11: Assuming field 'fVersion' is > 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
12: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1535
13: Assuming 'pw' is null in /opt/root_src/net/auth/src/TAuthenticate.cxx:1547
14: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1547
15: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1565
16: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1570
17: Assuming 'stat' is not equal to kErrNotAllowed in /opt/root_src/net/auth/src/TAuthenticate.cxx:1573
18: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1573
19: 'kind' is not equal to kROOTD_AUTH in /opt/root_src/net/auth/src/TAuthenticate.cxx:1577
20: Left side of '&&' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1577
21: 'anon' is equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
22: Left side of '&&' is true in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
23: Assuming 'cryptopt' is equal to 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
24: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1589
25: Assuming 'kind' is equal to kROOTD_RSAKEY in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
26: Left side of '||' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
27: Assuming 'stat' is >= 1 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
28: Left side of '||' is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
29: Assuming 'stat' is <= 2 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
30: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1592
31: Assuming 'gDebug' is <= 3 in /opt/root_src/net/auth/src/TAuthenticate.cxx:1601
32: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:1601
33: Calling 'TAuthenticate::SendRSAPublicKey' in /opt/root_src/net/auth/src/TAuthenticate.cxx:1608
34: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:3119
35: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:3119
36: Assuming 'gDebug' is <= 3 in /opt/root_src/net/auth/src/TAuthenticate.cxx:3121
37: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:3121
38: Assuming the condition is false in /opt/root_src/net/auth/src/TAuthenticate.cxx:3137
39: Taking false branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:3137
40: 'key' is equal to 0 in /opt/root_src/net/auth/src/TAuthenticate.cxx:3146
41: Taking true branch in /opt/root_src/net/auth/src/TAuthenticate.cxx:3146
42: Passed-by-value struct argument contains uninitialized data (e.g., field: 'n_len') in /opt/root_src/net/auth/src/TAuthenticate.cxx:3148
/opt/root_src/net/auth/src/rsaaux.cxx:271:4: warning: Value stored to 'l' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'l' is never read in /opt/root_src/net/auth/src/rsaaux.cxx:271
/opt/root_src/net/auth/src/rsaaux.cxx:436:11: warning: Assigned value is garbage or undefined [clang-analyzer-core.uninitialized.Assign]
 1: Loop condition is false. Execution continues on line 1108 in /opt/root_src/net/auth/src/rsaaux.cxx:1103
 2: Calling 'm_exp' in /opt/root_src/net/auth/src/rsaaux.cxx:1112
 3: Calling 'a_assign' in /opt/root_src/net/auth/src/rsaaux.cxx:652
 4: 's' is not equal to 'd' in /opt/root_src/net/auth/src/rsaaux.cxx:251
 5: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:251
 6: Assuming 'l' is 0 in /opt/root_src/net/auth/src/rsaaux.cxx:254
 7: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:254
 8: Returning from 'a_assign' in /opt/root_src/net/auth/src/rsaaux.cxx:652
 9: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsaaux.cxx:655
10: Assuming the condition is true in /opt/root_src/net/auth/src/rsaaux.cxx:656
11: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsaaux.cxx:656
12: Calling 'm_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:657
13: Calling 'a_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:640
14: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:427
15: Loop condition is false. Execution continues on line 434 in /opt/root_src/net/auth/src/rsaaux.cxx:430
16: Loop condition is false. Execution continues on line 448 in /opt/root_src/net/auth/src/rsaaux.cxx:434
17: Loop condition is false. Execution continues on line 454 in /opt/root_src/net/auth/src/rsaaux.cxx:449
18: Returning from 'a_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:640
19: Calling 'n_div' in /opt/root_src/net/auth/src/rsaaux.cxx:641
20: Assuming field 'n_len' is not equal to 0 in /opt/root_src/net/auth/src/rsaaux.cxx:475
21: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:475
22: 'r' is non-null in /opt/root_src/net/auth/src/rsaaux.cxx:478
23: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:478
24: 'q' is null in /opt/root_src/net/auth/src/rsaaux.cxx:480
25: Taking true branch in /opt/root_src/net/auth/src/rsaaux.cxx:480
26: Calling 'a_assign' in /opt/root_src/net/auth/src/rsaaux.cxx:483
27: 's' is equal to 'd' in /opt/root_src/net/auth/src/rsaaux.cxx:251
28: Taking true branch in /opt/root_src/net/auth/src/rsaaux.cxx:251
29: Returning from 'a_assign' in /opt/root_src/net/auth/src/rsaaux.cxx:483
30: Assuming 'l' is < 0 in /opt/root_src/net/auth/src/rsaaux.cxx:495
31: Loop condition is false. Execution continues on line 523 in /opt/root_src/net/auth/src/rsaaux.cxx:495
32: 'lq' is <= 0 in /opt/root_src/net/auth/src/rsaaux.cxx:527
33: Left side of '&&' is false in /opt/root_src/net/auth/src/rsaaux.cxx:527
34: Returning from 'n_div' in /opt/root_src/net/auth/src/rsaaux.cxx:641
35: Returning from 'm_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:657
36: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsaaux.cxx:656
37: Calling 'm_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:657
38: Calling 'a_mult' in /opt/root_src/net/auth/src/rsaaux.cxx:640
39: Assuming the condition is false in /opt/root_src/net/auth/src/rsaaux.cxx:427
40: Taking false branch in /opt/root_src/net/auth/src/rsaaux.cxx:427
41: Loop condition is false. Execution continues on line 434 in /opt/root_src/net/auth/src/rsaaux.cxx:430
42: Assuming 'i' is < 'l1' in /opt/root_src/net/auth/src/rsaaux.cxx:434
43: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsaaux.cxx:434
44: Assigned value is garbage or undefined in /opt/root_src/net/auth/src/rsaaux.cxx:436
/opt/root_src/net/auth/src/rsaaux.cxx:1006:10: warning: Assigned value is garbage or undefined [clang-analyzer-core.uninitialized.Assign]
 1: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsaaux.cxx:1004
 2: The value -1 is assigned to 'i' in /opt/root_src/net/auth/src/rsaaux.cxx:1005
 3: Assigned value is garbage or undefined in /opt/root_src/net/auth/src/rsaaux.cxx:1006
/opt/root_src/net/auth/src/rsalib.cxx:394:18: warning: 2nd function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
 1: Assuming the condition is false in /opt/root_src/net/auth/src/rsalib.cxx:458
 2: Left side of '&&' is false in /opt/root_src/net/auth/src/rsalib.cxx:458
 3: Taking false branch in /opt/root_src/net/auth/src/rsalib.cxx:467
 4: Calling 'rsa_num_sget' in /opt/root_src/net/auth/src/rsalib.cxx:470
 5: Assuming the condition is false in /opt/root_src/net/auth/src/rsalib.cxx:389
 6: Taking false branch in /opt/root_src/net/auth/src/rsalib.cxx:389
 7: Assuming 'bi' is > 0 in /opt/root_src/net/auth/src/rsalib.cxx:393
 8: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsalib.cxx:393
 9: Assuming pointer value is null in /opt/root_src/net/auth/src/rsalib.cxx:394
10: Assuming 'hp' is non-null in /opt/root_src/net/auth/src/rsalib.cxx:394
11: Taking true branch in /opt/root_src/net/auth/src/rsalib.cxx:394
12: Assuming 'ab' is < rsa_MAXBIT in /opt/root_src/net/auth/src/rsalib.cxx:406
13: Loop condition is false. Execution continues on line 393 in /opt/root_src/net/auth/src/rsalib.cxx:406
14: Assuming 'bi' is > 0 in /opt/root_src/net/auth/src/rsalib.cxx:393
15: Loop condition is true.  Entering loop body in /opt/root_src/net/auth/src/rsalib.cxx:393
16: 2nd function call argument is an uninitialized value in /opt/root_src/net/auth/src/rsalib.cxx:394
/opt/root_src/net/http/civetweb/civetweb.c:1635:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:1635
/opt/root_src/net/http/civetweb/civetweb.c:3243:3: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3243
/opt/root_src/net/http/civetweb/civetweb.c:3365:11: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3365
 3: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
/opt/root_src/net/http/civetweb/civetweb.c:3502:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3502
/opt/root_src/net/http/civetweb/civetweb.c:3633:23: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
 3: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3633
 4: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 5: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
/opt/root_src/net/http/civetweb/civetweb.c:3878:5: warning: Call to function 'sprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3878
/opt/root_src/net/http/civetweb/civetweb.c:3937:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:3937
/opt/root_src/net/http/civetweb/civetweb.c:5799:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:5799
/opt/root_src/net/http/civetweb/civetweb.c:6620:4: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6620
/opt/root_src/net/http/civetweb/civetweb.c:6829:2: warning: Call to function 'sprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6829
/opt/root_src/net/http/civetweb/civetweb.c:6884:9: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6884
 3: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
/opt/root_src/net/http/civetweb/civetweb.c:6914:8: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6914
 3: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
/opt/root_src/net/http/civetweb/civetweb.c:6937:7: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
 3: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6937
 4: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 5: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
/opt/root_src/net/http/civetweb/civetweb.c:6945:7: warning: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 2: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
 3: Call to function 'vsnprintf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'vsnprintf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:6945
 4: expanded from macro 'vsnprintf_impl' in /opt/root_src/net/http/civetweb/civetweb.c:781
 5: expanded from macro 'IGNORE_UNUSED_RESULT' in /opt/root_src/net/http/civetweb/civetweb.c:226
/opt/root_src/net/http/civetweb/civetweb.c:7374:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7374
/opt/root_src/net/http/civetweb/civetweb.c:7477:4: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7477
/opt/root_src/net/http/civetweb/civetweb.c:7535:2: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7535
/opt/root_src/net/http/civetweb/civetweb.c:7556:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7556
/opt/root_src/net/http/civetweb/civetweb.c:7631:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7631
/opt/root_src/net/http/civetweb/civetweb.c:7708:7: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7708
/opt/root_src/net/http/civetweb/civetweb.c:7717:10: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7717
/opt/root_src/net/http/civetweb/civetweb.c:7726:10: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7726
/opt/root_src/net/http/civetweb/civetweb.c:7735:10: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7735
/opt/root_src/net/http/civetweb/civetweb.c:7746:4: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7746
/opt/root_src/net/http/civetweb/civetweb.c:7927:4: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:7927
/opt/root_src/net/http/civetweb/civetweb.c:8127:8: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8127
/opt/root_src/net/http/civetweb/civetweb.c:8412:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8412
/opt/root_src/net/http/civetweb/civetweb.c:8637:2: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:8637
/opt/root_src/net/http/civetweb/civetweb.c:8638:2: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:8638
/opt/root_src/net/http/civetweb/civetweb.c:8656:7: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8656
/opt/root_src/net/http/civetweb/civetweb.c:8705:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8705
/opt/root_src/net/http/civetweb/civetweb.c:8724:4: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8724
/opt/root_src/net/http/civetweb/civetweb.c:8750:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:8750
/opt/root_src/net/http/civetweb/civetweb.c:9169:4: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:9169
/opt/root_src/net/http/civetweb/civetweb.c:9223:4: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:9223
/opt/root_src/net/http/civetweb/civetweb.c:9502:9: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:9502
/opt/root_src/net/http/civetweb/civetweb.c:9911:11: warning: Although the value stored to 'p' is used in the enclosing expression, the value is never actually read from 'p' [clang-analyzer-deadcode.DeadStores]
 1: Although the value stored to 'p' is used in the enclosing expression, the value is never actually read from 'p' in /opt/root_src/net/http/civetweb/civetweb.c:9911
/opt/root_src/net/http/civetweb/civetweb.c:9918:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:9918
/opt/root_src/net/http/civetweb/civetweb.c:10419:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:10419
/opt/root_src/net/http/civetweb/civetweb.c:11294:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11294
/opt/root_src/net/http/civetweb/civetweb.c:11508:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11508
/opt/root_src/net/http/civetweb/civetweb.c:11591:6: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11591
/opt/root_src/net/http/civetweb/civetweb.c:11602:13: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11602
/opt/root_src/net/http/civetweb/civetweb.c:11609:14: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11609
/opt/root_src/net/http/civetweb/civetweb.c:11610:17: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11610
/opt/root_src/net/http/civetweb/civetweb.c:11666:6: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:11666
/opt/root_src/net/http/civetweb/civetweb.c:12186:5: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12186
/opt/root_src/net/http/civetweb/civetweb.c:12187:5: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12187
/opt/root_src/net/http/civetweb/civetweb.c:12222:5: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12222
/opt/root_src/net/http/civetweb/civetweb.c:12224:5: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12224
/opt/root_src/net/http/civetweb/civetweb.c:12234:5: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12234
/opt/root_src/net/http/civetweb/civetweb.c:12278:5: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12278
/opt/root_src/net/http/civetweb/civetweb.c:12281:5: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12281
/opt/root_src/net/http/civetweb/civetweb.c:12447:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12447
/opt/root_src/net/http/civetweb/civetweb.c:12454:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12454
/opt/root_src/net/http/civetweb/civetweb.c:12455:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12455
/opt/root_src/net/http/civetweb/civetweb.c:12462:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12462
/opt/root_src/net/http/civetweb/civetweb.c:12834:8: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12834
/opt/root_src/net/http/civetweb/civetweb.c:12835:11: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12835
/opt/root_src/net/http/civetweb/civetweb.c:12859:29: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:12859
/opt/root_src/net/http/civetweb/civetweb.c:14262:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14262
/opt/root_src/net/http/civetweb/civetweb.c:14271:6: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14271
/opt/root_src/net/http/civetweb/civetweb.c:14291:17: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14291
/opt/root_src/net/http/civetweb/civetweb.c:14308:13: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14308
/opt/root_src/net/http/civetweb/civetweb.c:14332:3: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14332
/opt/root_src/net/http/civetweb/civetweb.c:14337:8: warning: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'sscanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'sscanf_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14337
/opt/root_src/net/http/civetweb/civetweb.c:14471:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14471
/opt/root_src/net/http/civetweb/civetweb.c:14472:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:14472
/opt/root_src/net/http/civetweb/civetweb.c:16593:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:16593
/opt/root_src/net/http/civetweb/civetweb.c:17184:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:17184
/opt/root_src/net/http/civetweb/civetweb.c:17324:2: warning: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memcpy' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memcpy_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:17324
/opt/root_src/net/http/civetweb/civetweb.c:17584:4: warning: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memmove' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memmove_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:17584
/opt/root_src/net/http/civetweb/civetweb.c:17916:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:17916
/opt/root_src/net/http/civetweb/civetweb.c:17939:29: warning: 1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
 1: Calling 'master_thread_run' in /opt/root_src/net/http/civetweb/civetweb.c:18156
 2: Assuming 'ctx' is non-null in /opt/root_src/net/http/civetweb/civetweb.c:18021
 3: Taking false branch in /opt/root_src/net/http/civetweb/civetweb.c:18021
 4: Assuming field 'init_thread' is null in /opt/root_src/net/http/civetweb/civetweb.c:18049
 5: Taking false branch in /opt/root_src/net/http/civetweb/civetweb.c:18049
 6: Assuming field 'stop_flag' is equal to 0 in /opt/root_src/net/http/civetweb/civetweb.c:18059
 7: Loop condition is true.  Entering loop body in /opt/root_src/net/http/civetweb/civetweb.c:18059
 8: Assuming 'i' is < field 'num_listening_sockets' in /opt/root_src/net/http/civetweb/civetweb.c:18060
 9: Loop condition is true.  Entering loop body in /opt/root_src/net/http/civetweb/civetweb.c:18060
10: Assuming 'i' is >= field 'num_listening_sockets' in /opt/root_src/net/http/civetweb/civetweb.c:18060
11: Loop condition is false. Execution continues on line 18065 in /opt/root_src/net/http/civetweb/civetweb.c:18060
12: Assuming the condition is true in /opt/root_src/net/http/civetweb/civetweb.c:18065
13: Taking true branch in /opt/root_src/net/http/civetweb/civetweb.c:18065
14: Loop condition is true.  Entering loop body in /opt/root_src/net/http/civetweb/civetweb.c:18066
15: Field 'stop_flag' is equal to 0 in /opt/root_src/net/http/civetweb/civetweb.c:18072
16: Left side of '&&' is true in /opt/root_src/net/http/civetweb/civetweb.c:18072
17: Assuming the condition is true in /opt/root_src/net/http/civetweb/civetweb.c:18072
18: Taking true branch in /opt/root_src/net/http/civetweb/civetweb.c:18072
19: Calling 'accept_new_connection' in /opt/root_src/net/http/civetweb/civetweb.c:18073
20: Assuming the condition is false in /opt/root_src/net/http/civetweb/civetweb.c:17937
21: Taking false branch in /opt/root_src/net/http/civetweb/civetweb.c:17937
22: 1st function call argument is an uninitialized value in /opt/root_src/net/http/civetweb/civetweb.c:17939
/opt/root_src/net/http/civetweb/civetweb.c:18152:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:18152
/opt/root_src/net/http/civetweb/civetweb.c:18334:2: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:18334
/opt/root_src/net/http/civetweb/civetweb.c:18899:3: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:18899
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:18914:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:18914
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:18969:3: warning: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 [clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling]
 1: Call to function 'memset' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'memset_s' in case of C11 in /opt/root_src/net/http/civetweb/civetweb.c:18969
/opt/root_src/net/http/civetweb/civetweb.c:18984:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:18984
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19012:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19012
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19071:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19071
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19143:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19143
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19234:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19234
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19241:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19241
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/http/civetweb/civetweb.c:19242:4: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
 1: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
 2: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119 in /opt/root_src/net/http/civetweb/civetweb.c:19242
 3: expanded from macro 'strcat0' in /opt/root_src/net/http/civetweb/civetweb.c:18868
/opt/root_src/net/net/src/TNetFile.cxx:697:7: warning: Value stored to 'read' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'read' is never read in /opt/root_src/net/net/src/TNetFile.cxx:697
/opt/root_src/net/net/src/TNetFile.cxx:722:7: warning: Value stored to 'recreate' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'recreate' is never read in /opt/root_src/net/net/src/TNetFile.cxx:722
/opt/root_src/net/net/src/TNetFile.cxx:728:7: warning: Value stored to 'update' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'update' is never read in /opt/root_src/net/net/src/TNetFile.cxx:728
/opt/root_src/net/net/src/TSQLMonitoring.cxx:178:99: warning: Called C++ object pointer is null [clang-analyzer-core.CallAndMessage]
 1: Assuming field 'fDB' is non-null in /opt/root_src/net/net/src/TSQLMonitoring.cxx:89
 2: Taking false branch in /opt/root_src/net/net/src/TSQLMonitoring.cxx:89
 3: Assuming 'values' is non-null in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 4: Left side of '||' is false in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 5: 'values' is non-null in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 6: Left side of '&&' is true in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 7: Assuming the condition is false in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 8: Taking false branch in /opt/root_src/net/net/src/TSQLMonitoring.cxx:95
 9: Loop condition is true.  Entering loop body in /opt/root_src/net/net/src/TSQLMonitoring.cxx:102
10: Assuming the condition is true in /opt/root_src/net/net/src/TSQLMonitoring.cxx:103
11: Taking true branch in /opt/root_src/net/net/src/TSQLMonitoring.cxx:103
12: Loop condition is false. Execution continues on line 119 in /opt/root_src/net/net/src/TSQLMonitoring.cxx:102
13: 'bulk' is true in /opt/root_src/net/net/src/TSQLMonitoring.cxx:126
14: Taking false branch in /opt/root_src/net/net/src/TSQLMonitoring.cxx:126
15: Calling 'TIter::operator()' in /opt/root_src/net/net/src/TSQLMonitoring.cxx:175
16: Calling 'TIter::Next' in /opt/root_src/core/cont/inc/TCollection.h:248
17: Assuming field 'fIterator' is non-null in /opt/root_src/core/cont/inc/TCollection.h:249
18: '?' condition is true in /opt/root_src/core/cont/inc/TCollection.h:249
19: Returning pointer, which participates in a condition later in /opt/root_src/core/cont/inc/TCollection.h:249
20: Returning pointer in /opt/root_src/core/cont/inc/TCollection.h:249
21: Returning from 'TIter::Next' in /opt/root_src/core/cont/inc/TCollection.h:248
22: Returning pointer, which participates in a condition later in /opt/root_src/core/cont/inc/TCollection.h:248
23: Returning pointer in /opt/root_src/core/cont/inc/TCollection.h:248
24: Returning from 'TIter::operator()' in /opt/root_src/net/net/src/TSQLMonitoring.cxx:175
25: Value assigned to 'o' in /opt/root_src/net/net/src/TSQLMonitoring.cxx:175
26: Assuming 'os' is null in /opt/root_src/net/net/src/TSQLMonitoring.cxx:177
27: Taking true branch in /opt/root_src/net/net/src/TSQLMonitoring.cxx:177
28: Called C++ object pointer is null in /opt/root_src/net/net/src/TSQLMonitoring.cxx:178
/opt/root_src/net/net/src/TWebFile.cxx:931:7: warning: Value stored to 'ret' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'ret' is never read in /opt/root_src/net/net/src/TWebFile.cxx:931
/opt/root_src/net/net/src/TWebFile.cxx:1355:34: warning: Null pointer passed to 1st parameter expecting 'nonnull' [clang-analyzer-core.NonNullParamChecker]
 1: Assuming 'maxsize' is > 0 in /opt/root_src/net/net/src/TWebFile.cxx:1260
 2: Taking false branch in /opt/root_src/net/net/src/TWebFile.cxx:1260
 3: Loop condition is true.  Entering loop body in /opt/root_src/net/net/src/TWebFile.cxx:1265
 4: Assuming 'pklen' is >= 0 in /opt/root_src/net/net/src/TWebFile.cxx:1271
 5: Taking false branch in /opt/root_src/net/net/src/TWebFile.cxx:1271
 6: Passing value via 2nd parameter 'peeked' in /opt/root_src/net/net/src/TWebFile.cxx:1274
 7: Calling 'TWebFile::HttpTerminator' in /opt/root_src/net/net/src/TWebFile.cxx:1274
 8: Assuming 'start' is null in /opt/root_src/net/net/src/TWebFile.cxx:1354
 9: Taking false branch in /opt/root_src/net/net/src/TWebFile.cxx:1354
10: Null pointer passed to 1st parameter expecting 'nonnull' in /opt/root_src/net/net/src/TWebFile.cxx:1355
/opt/root_src/net/rpdutils/src/net.cxx:314:15: warning: Potential leak of memory pointed to by 'tmpbuf' [clang-analyzer-cplusplus.NewDeleteLeaks]
 1: Calling 'NetRecv' in /opt/root_src/net/rpdutils/src/net.cxx:341
 2: Calling 'NetRecvAllocate' in /opt/root_src/net/rpdutils/src/net.cxx:313
 3: Taking false branch in /opt/root_src/net/rpdutils/src/net.cxx:290
 4: 'len' is >= 0 in /opt/root_src/net/rpdutils/src/net.cxx:294
 5: Taking false branch in /opt/root_src/net/rpdutils/src/net.cxx:294
 6: Assuming 'len' is not equal to 0 in /opt/root_src/net/rpdutils/src/net.cxx:296
 7: Taking true branch in /opt/root_src/net/rpdutils/src/net.cxx:296
 8: Memory is allocated in /opt/root_src/net/rpdutils/src/net.cxx:297
 9: Returned allocated memory in /opt/root_src/net/rpdutils/src/net.cxx:313
10: Taking true branch in /opt/root_src/net/rpdutils/src/net.cxx:313
11: Potential leak of memory pointed to by 'tmpbuf' in /opt/root_src/net/rpdutils/src/net.cxx:314
/opt/root_src/net/rpdutils/src/net.cxx:541:4: warning: Value stored to 'port1' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'port1' is never read in /opt/root_src/net/rpdutils/src/net.cxx:541
/opt/root_src/net/rpdutils/src/rpdutils.cxx:668:15: warning: Although the value stored to 'nr' is used in the enclosing expression, the value is never actually read from 'nr' [clang-analyzer-deadcode.DeadStores]
 1: Although the value stored to 'nr' is used in the enclosing expression, the value is never actually read from 'nr' in /opt/root_src/net/rpdutils/src/rpdutils.cxx:668
/opt/root_src/net/rpdutils/src/rpdutils.cxx:743:21: warning: Although the value stored to 'nr' is used in the enclosing expression, the value is never actually read from 'nr' [clang-analyzer-deadcode.DeadStores]
 1: Although the value stored to 'nr' is used in the enclosing expression, the value is never actually read from 'nr' in /opt/root_src/net/rpdutils/src/rpdutils.cxx:743
/opt/root_src/net/rpdutils/src/rpdutils.cxx:793:13: warning: Value stored to 'fsize' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'fsize' is never read in /opt/root_src/net/rpdutils/src/rpdutils.cxx:793
/opt/root_src/net/rpdutils/src/rpdutils.cxx:1631:13: warning: Value stored to 'jm' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'jm' is never read in /opt/root_src/net/rpdutils/src/rpdutils.cxx:1631
/opt/root_src/net/rpdutils/src/rpdutils.cxx:2736:7: warning: Value stored to 'err' is never read [clang-analyzer-deadcode.DeadStores]
 1: Value stored to 'err' is never read in /opt/root_src/net/rpdutils/src/rpdutils.cxx:2736
/opt/root_src/net/auth/src/TAuthenticate.cxx
/opt/root_src/net/auth/src/rsaaux.cxx
/opt/root_src/net/auth/src/rsalib.cxx
/opt/root_src/net/http/civetweb/civetweb.c
/opt/root_src/net/net/src/TNetFile.cxx
/opt/root_src/net/net/src/TSQLMonitoring.cxx
/opt/root_src/net/net/src/TWebFile.cxx
/opt/root_src/net/rpdutils/src/net.cxx
/opt/root_src/net/rpdutils/src/rpdutils.cxx
```

### PR DESCRIPTION
**Pull request by linev**
Fixes #7528 
Civetweb not touched, need to be updated soon anyway

### CODE REVIEW

File: net/net/src/TNetFile.cxx [hunk 1]
```diff
@@ -694,7 +694,6 @@ void TNetFile::Create(const char * /*url*/, Option_t *option, Int_t netopt)
    Bool_t update   = (fOption == "UPDATE") ? kTRUE : kFALSE;
    Bool_t read     = (fOption == "READ") ? kTRUE : kFALSE;
    if (!create && !recreate && !update && !read) {
-      read    = kTRUE;
```
Comment (pcanal) [inline net/net/src/TNetFile.cxx:697]: This is one code pattern where I see "some" value in updating the variable even if it is, currently, not used.

If this routine is update at a later date, the developer might assume that the variable 'read' is true is all cases of 'reading mode' even the default one.

On the other hand, not having it at all might be event clearer.  i.e. except for the slight extra run-time cost, I think the fillowing code has the same net effect:
```
Bool_t update = (fOption == "UPDATE") ? kTRUE : kFALSE;
if (!create && !recreate && !update) {
     fOption = "READ";
}
```
with a spurrious re-assignment in case `fOption == "READ"` ... 
So actually maybe even:
```
Bool_t update = (fOption == "UPDATE") ? kTRUE : kFALSE;
if (!create && !recreate && !update && (fOption != "READ")) {
     fOption = "READ";
}
```

Comment (linev) [reply net/net/src/TNetFile.cxx:697]: I am not sure.
`fOption` can be accessed via `TFile::GetOption()` method - user can always check that was original option he/she provide. 
None of other TFile-based classes, including TFile itself, change fOption in such case.
Either we do it consistently in all places, or do not change it here.

Comment (linev) [reply net/net/src/TNetFile.cxx:697]: > None of other TFile-based classes, including TFile itself, change fOption in such case.

Sorry, I am wrong. I will update PR

**Review by pcanal — APPROVED** [review]
