### PR TITLE
[FreeBSD] Fix TThread related tests

### LINKED ISSUE #13068: [FreeBSD] TThread related tests fail
### Check duplicate issues.

- [X] Checked for duplicates

### Description

tests fail

### Reproducer

ctest -R "TThread"

### ROOT version

master

### Installation method

source

### Operating system

FreeBSD

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mkrzewic**
this fixes the TThread tests

# This Pull request:

## Changes or fixes:
#13068

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #13068

### CODE REVIEW

**Comment by hahnjo** [comment]
Hello @mkrzewic, we try to avoid patching our copy of LLVM / Clang if we can help it. What's the deal with `_REENTRANT`, are there FreeBSD headers expecting this to be set or is this ROOT checking something that isn't needed on FreeBSD?

**Comment by mkrzewic** [comment]
I see, indeed makes sense to not touch llvm too much:)
The problem is somewhere in root, I think it was some locking mechanism in TThread(.*) that expects _reentrant to be defined. Did not want to touch it since it is a bit more convoluted than what llvm does;)

**Comment by mkrzewic** [comment]
so after a quick git grep _REENTRANT through the system sources I see that nothing noteworthy is defining/using this macro, so i guess libc and other guts are thread safe by default (unless you count ncurses as guts ;) ). Now the interpreter thing: the build defs seem to be set by interpreter/llvm/src/tools/clang/lib/Basic/Targets/OSTargets.h for interpreted code - and that can rely on _REENTRANT being defined. Maybe there is some other place I don't know about.
Now the following patch also works, at least for TThread...

File: core/thread/src/TThread.cxx [hunk 1]
```diff
@@ -320,7 +320,7 @@ void TThread::Init()
 {
    if (fgThreadImp || fgIsTearDown) return;
 
-#if !defined (_REENTRANT) && !defined (WIN32)
+#if !defined (R__FBSD) || !defined (_REENTRANT) && !defined (WIN32)
```
Comment (hahnjo) [inline core/thread/src/TThread.cxx:323]: should be
```suggestion
#if !defined (R__FBSD) && !defined (_REENTRANT) && !defined (WIN32)
```
I think (even though it may not be needed at all if you pass `-D_REENTRANT` in `cmake/modules/SetUpFreeBSD.cmake`)

File: interpreter/llvm/src/tools/clang/lib/Basic/Targets/OSTargets.h [hunk 2]
```diff
@@ -218,6 +218,8 @@ class LLVM_LIBRARY_VISIBILITY FreeBSDTargetInfo : public OSTargetInfo<Target> {
     Builder.defineMacro("__KPRINTF_ATTRIBUTE__");
     DefineStd(Builder, "unix", Opts);
     Builder.defineMacro("__ELF__");
+    //if (Opts.POSIXThreads)
+    //  Builder.defineMacro("_REENTRANT");
```
Comment (hahnjo) [inline interpreter/llvm/src/tools/clang/lib/Basic/Targets/OSTargets.h:222]: please remove entirely

File: core/base/inc/TVirtualMutex.h [hunk 3]
```diff
@@ -94,7 +94,7 @@ class TLockGuard {
 // TMutex m; R__LOCKGUARD(&m);
 // Warning: if program is compiled without pthread support, _REENTRANT will
 // be undefined and the macro has (silently) no effect, no locks are performed.
-#if defined (_REENTRANT) || defined (WIN32)
+#if defined (_REENTRANT) || defined (WIN32) || defined (R__FBSD)
```
Comment (hahnjo) [inline core/base/inc/TVirtualMutex.h:97]: I think for good measure you should apply the same change to `core/base/inc/TVirtualRWMutex.h`, `core/cont/inc/TCollection.h`, and `core/meta/inc/TInterpreter.h`

**Review by hahnjo — COMMENTED** [review]
Yes, I think that's a good middle ground: Pass `_REENTRANT` during library compilation and adapt the header files to work with Cling.

**Comment by hahnjo** [comment]
@phsft-bot build!

File: core/base/inc/TVirtualMutex.h (hunk 3 above)
Comment (pcanal) [inline core/base/inc/TVirtualMutex.h:97]: At this comment implies that test for `_REENTRANT` is an indirect way to check that the option `-pthread` is being passed to the compiler.  In FreeBSD is it essentially 'always' the case?

Comment (mkrzewic) [reply core/base/inc/TVirtualMutex.h:97]: in essence, yes. The choice was to build with pthread support on FreeBSD (since this is currently THE supported thread model on the platform afaik. support for some older things (N:M libkse) might still be there, but nowadays it seems all pthread to the point that _REENTRANT is not even defined anywhere in the base system (and, in particular, not set by -pthread). Which means it needs to be handled somehow manually for headers that do rely on it. What is done here is somehow a consequence of that, since llvm/interpreter does not set _REENTRANT for freebsd.

Comment (mkrzewic) [reply core/base/inc/TVirtualMutex.h:97]: actually, now that I had a second look, I think in the headers, if we need them to be parsable by the interpreter __FreeBSD__ needs to be defined instead of R__FBSD (as that is that llvm exports). Again, unless there is some other mechanism to set build options for interpreted code.

Comment (hahnjo) [reply core/base/inc/TVirtualMutex.h:97]: > This comment seems to imply that test for `_REENTRANT` is an indirect way to check that the option `-pthread` is being passed to the compiler.

Yes, as far as I understand, this is basically a historical side-effect of older C libraries requiring that define to enable thread-safe functions. However, `_REENTRANT  is  now  obsolete` even according to the man page of `libc` (`man feature_test_macros` to be precise) on EL8. So I would argue that we should get rid of relying on it in ROOT, with FreeBSD just being the first platform that doesn't define it anymore.

> `__FreeBSD__`  needs to be defined instead of `R__FBSD`

This should be fine because as soon as we are in ROOT headers, we (should) have `RConfig.hxx` included somewhere.

> Again, unless there is some other mechanism to set build options for interpreted code...

If we really, really wanted to, we should be able to add a `-D` definition in the constructor `TCling::TCling`. However, as I argue above, I personally think we should rather move away from relying on `_REENTRANT` because it is obsolete anyway.

Comment (pcanal) [reply core/base/inc/TVirtualMutex.h:97]: > `_REENTRANT` is now obsolete

Fair enough.  We also now require (more exactly we don't offer a cmake consider that does not) build with `-pthread`.   So technically we could update (all) the code to act as if `_REENTRANT` is always defined.

Comment (hahnjo) [reply core/base/inc/TVirtualMutex.h:97]: Yes, I think that's a good plan going forward, but I think that's on us as the team and should not block fixing test failures on FreeBSD right now. Do you agree?

Comment (pcanal) [reply core/base/inc/TVirtualMutex.h:97]: Of course :)

**Review by hahnjo — APPROVED** [review]
