### PR TITLE
[io] Remove from url parameters parsed by TXNetFile

### LINKED ISSUE #18623: DaviX errors from ROOT.File.Cp
### Check duplicate issues.

- [x] Checked for duplicates

### Description

In both 6.32 and 6.34 we have started observing error messages from DaviX when trying to access files from WebEOS sites, specifically the following site:
https://atlas-groupdata.web.cern.ch/atlas-groupdata/
We see different behaviour when ROOT.TFile.Cp is used in a single step, versus when the TFile is opened first (see reproducer). This is an issue due to a piece of software used in ATLAS (PathResolver) that uses this single step. 

### Reproducer

CASE 1 (doesn't work):

```python
import ROOT
ROOT.TFile.Cp("https://atlas-groupdata.web.cern.ch/ElectronEfficiencyCorrection/2015_2018/rel21.2/Precision_Summer2020_v1/trigger/efficiencySF.SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0.TightLLH_d0z0_v13_isolTight.root", "/tmp/test.root")
```

```
Error in <TDavixFile::DavixReadBuffer>: can not read data with davix: HTTP 403 : Permission refused  (17)
Error in <TFile::Cp>: cannot read from source file https://atlas-groupdata.web.cern.ch/ElectronEfficiencyCorrection/2015_2018/rel21.2/Precision_Summer2020_v1/trigger/efficiencySF.SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0.TightLLH_d0z0_v13_isolTight.root. readsize=81971 read=0 readop=1
False
```

CASE 2 (works):

```python
import ROOT
f=ROOT.TFile.Open("https://atlas-groupdata.web.cern.ch/ElectronEfficiencyCorrection/2015_2018/rel21.2/Precision_Summer2020_v1/trigger/efficiencySF.SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0.TightLLH_d0z0_v13_isolTight.root")

f.Cp("/tmp/test.root")
```

```
[TFile::Cp] Total 0.08 MB	|====================| 100.00 % [12.9 MB/s]
True
```

### ROOT version

6.34.04-x86_64-el9-gcc13-opt
6.32.08-x86_64-el9-gcc13-opt

### Installation method

CVMFS via AtlasSetup

### Operating system

AlmaLinux9 (LXPLUS)

### Additional context

It is possible that these issues are due to some settings changing on the site in question, but we aren't sure what to report. Some specific statement from a DaviX expert of the form "X was probably changed to Y and this is why there is an error" would help us to revert whatever was changed, if this is indeed the cause of the issue.

### PR DESCRIPTION
**Pull request by dpiparo**
since the entire netx code was removed for 6.34 by 65088a9

Fixes #18623

### CODE REVIEW

File: io/io/src/TFile.cxx [hunk 1]
```diff
@@ -5185,20 +5185,6 @@ Bool_t TFile::Cp(const char *src, const char *dst, Bool_t progressbar,
...
-   // Set optimization options for the source file
-   TString opt = sURL.GetOptions();
-   if (opt != "") opt += "&";
-   opt += raw;
-   // Netx-related options:
-   //    cachesz = 4*buffersize     -> 4 buffers as peak mem usage
-   //    readaheadsz = 2*buffersize -> Keep at max 4*buffersize bytes outstanding when reading
-   //    rmpolicy = 1               -> Remove from the cache the blk with the least offset
-   opt += TString::Format("&cachesz=%d&readaheadsz=%d&rmpolicy=1", 4*buffersize, 2*buffersize);
-   sURL.SetOptions(opt);
```
Comment (pcanal) [inline io/io/src/TFile.cxx:5200]: Only this part is related to `Netx`, a priori the `filetype=raw` is still needed/wanted.
