### PR TITLE
[cling] Add back support for printing std::array

### LINKED ISSUE #21255: Wrong value printed by cling for std::array
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Cling currently prints the wrong value at the prompt for std::array, because of this commit https://github.com/root-project/root/commit/c8a3d6a8c0113800d4fd4f5894cb2ecd83339fbf

### Reproducer

```
$: root -l
root [0] std::array<int, 3> arr{1,2,3}
(std::array<int, 3> &) { <recursion detected>, 2, 3 }
```

### ROOT version

master

### Installation method

Source

### Operating system

Any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #21255 

@devajithvs I am not sure how to run the cling tests (specifically this `Collections.C` file), guidance is welcome.

### CODE REVIEW

**Comment by devajithvs** [comment]
> Fixes #21255
> 
> @devajithvs I am not sure how to run the cling tests (specifically this `Collections.C` file), guidance is welcome.

If you have a build with `-Dclingtest=ON`, I usually just do this manually (or however it is defined in the source file at the top)

```
cat YourTestFile.C | ./interpreter/llvm-project/llvm/bin/cling | ./interpreter/llvm-project/llvm/bin/FileCheck YourTestFile.C
```

But once you've run/built everything needed for `check-cling`, you should be able to use `llvm-lit` to run a specific test/folder:

```
./interpreter/llvm-project/llvm/bin/llvm-lit interpreter/cling/test/ValuePrinter
```

File: interpreter/cling/test/Prompt/ValuePrinter/Collections.C [hunk 1]
```diff
@@ -79,5 +79,13 @@ S
 MM
```
Comment (devajithvs) [inline interpreter/cling/test/Prompt/ValuePrinter/Collections.C:80]: We need `#include <array>`

File: interpreter/cling/test/Prompt/ValuePrinter/Collections.C [hunk 2]
```diff
@@ -79,5 +79,13 @@ S
...
 // (std::map<std::string, std::map<int, std::pair<int, std::string> > > &) { "0" => { 0 => {0 , "00"}, 1 => {3 , "05"}, 2 => {6 , "010"} }, "1" => { 0 => {0 , "10"}, 1 => {3 , "15"}, 2 => {6 , "110"} }, "2" => { 0 => {0 , "20"}, 1 => {3 , "25"}, 2 => {6 , "210"} }, "3" => { 0 => {0 , "30"}, 1 => {3 , "35"}, 2 => {6 , "310"} }, "4" => { 0 => {0 , "40"}, 1 => {3 , "45"}, 2 => {6 , "410"} } }
```
Comment (devajithvs) [inline interpreter/cling/test/Prompt/ValuePrinter/Collections.C]:
```suggestion
// CHECK-NEXT: (std::map<std::string, std::map<int, std::pair<int, std::string> > > &) { "0" => { 0 => {0 , "00"}, 1 => {3 , "05"}, 2 => {6 , "010"} }, "1" => { 0 => {0 , "10"}, 1 => {3 , "15"}, 2 => {6 , "110"} }, "2" => { 0 => {0 , "20"}, 1 => {3 , "25"}, 2 => {6 , "210"} }, "3" => { 0 => {0 , "30"}, 1 => {3 , "35"}, 2 => {6 , "310"} }, "4" => { 0 => {0 , "40"}, 1 => {3 , "45"}, 2 => {6 , "410"} } }
```

File: interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h [hunk 3]
```diff
@@ -228,6 +228,29 @@ namespace cling {
...
+      const void* M = TypeTest::isMap(obj);
+
+      std::string str("{ ");
+      str += printValue(&(*iter), M);
+
+      while (++iter != iterEnd) {
+        str += ", ";
+        str += printValue(&(*iter), M);
+      }
+      return str + " }";
```
Comment (hahnjo) [inline interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h]: If we want to keep a separate implementation, I think this can be heavily simplified by taking advantage of the knowledge that we have a `std::array`. An alternative, that I think I would prefer, is to modify the generic implementation above to disable the recursion guard for some types...

Comment (vepadulano) [reply interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h]: Integrated in the latest commit, please review at your convenience.

**Comment by vepadulano** [comment]
Just for reference, here is the test run on my machine:
```
./interpreter/llvm-project/llvm/bin/llvm-lit interpreter/cling/test/Prompt/ValuePrinter
llvm-lit: /Users/vpadulan/Programs/rootproject/root/interpreter/llvm-project/llvm/utils/lit/lit/llvm/config.py:506: note: using clang: /Users/vpadulan/Programs/rootproject/rootbuild/cling-print-std-array-minimal-testing/interpreter/llvm-project/llvm/bin/clang
llvm-lit: /Users/vpadulan/Programs/rootproject/root/interpreter/llvm-project/llvm/utils/lit/lit/util.py:473: note: using SDKROOT: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
-- Testing: 11 tests, 11 workers --
PASS: Cling :: Prompt/ValuePrinter/UnkownType.C (1 of 11)
PASS: Cling :: Prompt/ValuePrinter/Templates.C (2 of 11)
PASS: Cling :: Prompt/ValuePrinter/Recursion.C (3 of 11)
PASS: Cling :: Prompt/ValuePrinter/Destruction.C (4 of 11)
PASS: Cling :: Prompt/ValuePrinter/Assignments.C (5 of 11)
PASS: Cling :: Prompt/ValuePrinter/Ptrs.C (6 of 11)
PASS: Cling :: Prompt/ValuePrinter/TuplesAndPairs.C (7 of 11)
PASS: Cling :: Prompt/ValuePrinter/Strings.C (8 of 11)
PASS: Cling :: Prompt/ValuePrinter/Regression.C (9 of 11)
PASS: Cling :: Prompt/ValuePrinter/SourceLocation.C (10 of 11)
PASS: Cling :: Prompt/ValuePrinter/Collections.C (11 of 11)

Testing Time: 1.34s

Total Discovered Tests: 11
  Passed: 11 (100.00%)
```
