### PR TITLE
[rootcling] Emit using std after user headers, fixes #6343:

### LINKED ISSUE #6343: Problem with "using namespace std" in generated dictionary files
In the autogenerated dictionary sources I see

```
// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
```

(this is from 6.14.08. 6.22.02 has a slightly different comment of `The generated code does not explicitly qualifies STL entities` (sic), but still does the `using...`)

This is placed very early on, even before the include of the header files passed as arguments.

Unfortunately, this causes problems, specifically when one of those header files pulls in Kokkos core headers, and there's a name clash with `rank` which is a free function in the kokkos namespace, and std::rank.

```
/opt/kokkos/cuda/3.2-shlib/include/Kokkos_View.hpp:1896:30: error: return type specified for deduction guide
 KOKKOS_INLINE_FUNCTION constexpr unsigned rank(const View<D, P...>& V) {
                              ^
/opt/kokkos/cuda/3.2-shlib/include/Kokkos_View.hpp:1895:42: error: decl-specifier in declaration of deduction guide
 template <typename D, class... P>
                                          ^       
/opt/kokkos/cuda/3.2-shlib/include/Kokkos_View.hpp:1895:32: error: decl-specifier in declaration of deduction guide
 template <typename D, class... P>
                                ^~       
/opt/kokkos/cuda/3.2-shlib/include/Kokkos_View.hpp:1896:30: error: 'signed' or 'unsigned' invalid for '__dguide_rank'
 KOKKOS_INLINE_FUNCTION constexpr unsigned rank(const View<D, P...>& V) {
                              ^
/opt/kokkos/cuda/3.2-shlib/include/Kokkos_View.hpp:1896:1: error: deduction guide for 'std::rank< <template-parameter-1-1> >' must have trailing return type
 KOKKOS_INLINE_FUNCTION constexpr unsigned rank(const View<D, P...>& V) {
 ^~~~
/bld4/opt/gcc/8.4.0/include/c++/8.4.0/type_traits:1251:8: note: 'template<class> struct std::rank' declared here
     struct rank
        ^~~~
```

Is there any way to make the `using namespace` appear AFTER the include of the user header files instead of before?

If I manually edit the generated file, and move the `using namespace` to after the includes,  it compiles fine.

FWIW, the actual compilation is done with nvcc 11, and c++17.

thanks, Charles.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
`using namespace std` can have detrimental side effects on user headers.
Assume that they are compilable, given that they will be included in the
dictionary source. Given this, move the using directive after the inclusion
of user headers, to not affect them, but only the generated dictionary
source code (CINT-compatible std-less type names etc).

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
@pcanal suggestions to get us out of this situation? We can break valid code by exposing our `using namespace std`, we break backwards compatibility by not doing it. I'd argue only ACLiC needs to expose `using namespace std` to user code, that would give the best of both worlds. Agreed?

**Comment by pcanal** [comment]
I agree.  For code that is usually compiled by itself it is unlikely that the header are relying on the dictionary to provide the using namespace std (so they either don't need it or have it on their own).   By scripts and thus ACLiC are a different story.  If we have 50 cases users are also likely to have a lot.

File: core/dictgen/src/rootcling_impl.cxx [hunk 1]
```diff
@@ -4537,6 +4537,7 @@ int RootClingMain(int argc,
    }
 
    std::ostream &dictStream = (!gOptIgnoreExistingDict && !gOptDictionaryFileName.empty()) ? fileout : std::cout;
+   bool isACLiC = linkdef.length() > 16 && !linkdef.compare(linkdef.size() - 16, 16, "_ACLiC_linkdef.h");
```
Comment (vgvassilev) [inline core/dictgen/src/rootcling_impl.cxx:4540]: Why not just using `strstr`?

Comment (Axel-Naumann) [reply core/dictgen/src/rootcling_impl.cxx:4540]: Because it's slower (scans the whole string) and less precise (picks up any occurrence, not just at the end)?

Comment (vgvassilev) [reply core/dictgen/src/rootcling_impl.cxx:4540]: But is also clearer and consistent to other cases of implementing `isACLiC` in the codebase.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build
