### PR TITLE
[df] Extend lifetime of Python-bound TTree dataset

### LINKED ISSUE #17691: Crash when building dataframe from TChain
### Check duplicate issues.

- [x] Checked for duplicates

### Description

When I try to make dataframes from TChains I see a crash. The chains do not seem to be owned by the dataframe and when the chains go out of scope, accessing the dataframe will cause the crash.

### Reproducer

```python
import numpy
from ROOT import RDataFrame, RDF, TChain

# ----------------------------------
class Data:
    l_file = ['a.root', 'b.root', 'c.root']
# ----------------------------------
def _make_file(name : str) -> None:
    arr_x = numpy.random.uniform(0, 1, 1000)
    arr_y = numpy.random.uniform(0, 1, 1000)

    rdf   = RDF.FromNumpy({'x' : arr_x, 'y' : arr_y})
    rdf.Snapshot('tree', name)
# ----------------------------------
def _make_files():
    for name in Data.l_file:
        _make_file(name=name)
# ----------------------------------
def _get_rdf() -> RDataFrame:
    chain = TChain('tree')
    for file in Data.l_file:
        chain.Add(file)

    rdf = RDataFrame(chain)
    #rdf.chain = chain  # Uncomment this line to get the crash

    return rdf
# ----------------------------------
def main():
    _make_files()
    rdf = _get_rdf()
    rdf.Display().Print()

main()
```

### ROOT version

6.34.02

### Installation method

conda

### Operating system

Alma9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
If a TTree dataset is created in a Python application and the RDataFrame constructor that takes in a `TTree &` parameter is used, the ownership of the TTree might result ambiguous for the user. Specifically, a Python user might expect the following to work out of the box:
```py
def foo():
    ch = ROOT.TChain()
    return ROOT.RDataFrame(ch)
```
Whereas it won't since the chain will become a dangling reference by the end of the function scope.

To cope with this unfortunate interaction of the C++ API and Python, we introduce an internal mechanism to keep track of the shared ownership of the *Python* proxy object. The implementation features a C++ wrapper in the ROOT CPython extension, which increases/decreases the Python reference count of a `PyObject *` data member. If this Python object is carefully given, i.e. if it is always pointing to the same underlying C++ object, then the reference counting will work correctly and destroy the C++ object only when there are no more Python objects referencing it. In order to keep the wrapper alive, a `std::any` data member is added to RLoopManager which represents the C++ counterpart of the Python lifeline. Within the same computation graph, different nodes share the same RLoopManager, so the Python object will stay alive as long as at least one node of the computation graph is still alive. If the same TTree is used (via a reference) by multiple computation graphs, then the wrapper mechanism will ensure that reference counting is correct across the different RDataFrame objects.

This PR fixes #17691

### CODE REVIEW

File: tree/dataframe/src/RInterface.cxx [hunk 1]
```diff
@@ -56,3 +56,8 @@ std::string ROOT::Internal::RDF::GetDataSourceLabel(const ROOT::RDF::RNode &node
       return "EmptyDS";
    }
 }
+
+void ROOT::Internal::RDF::SetTTreeLifeline(ROOT::RDF::RNode &node, const std::any &lifeline)
+{
+   node.GetLoopManager()->SetPythonTTreeLifeline(lifeline);
+}
```
Comment (guitargeek) [inline tree/dataframe/src/RInterface.cxx:63]:
```suggestion
void ROOT::Internal::RDF::SetTTreeLifeline(ROOT::RDF::RNode &node, const std::any &lifeline)
{
   node.GetLoopManager()->SetTTreeLifeline(lifeline);
}
```

Mentioning Python in the names, or lifeline, is maybe too specific? This is a general way to manage resources used for the RLoopManager. Maybe reflect this generality in the names? Otherwise, the reader of the code might think it's actually coupled to C Python.

I mean you could even use this from C++ and it would also make sense:
```c++
ROOT::Internal::RDF::SetTTreeLifeline(rdf, std::make_any<std::shared_ptr<TTree>>(tree)); // or something like that
```

Another way to see the `std::any` here is as a smart and general alternative to `void*` and `std::shared_ptr` for managing resources:
https://devblogs.microsoft.com/cppblog/stdany-how-when-and-why/

File: bindings/pyroot/pythonizations/src/PyROOTModule.cxx [hunk 2]
```diff
@@ -60,6 +61,69 @@ PyObject *RegisterExecutorAlias(PyObject * /*self*/, PyObject *args)
    Py_RETURN_NONE;
 }
 
+namespace Internal {
```
Comment (guitargeek) [inline bindings/pyroot/pythonizations/src/PyROOTModule.cxx:64]:
```suggestion
```
Just a nitpick: but, `.cxx` sources are always internal anyway so `Internal`/`Detail` namespaces have no meaning IMHO

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx [hunk 3]
```diff
@@ -93,6 +94,7 @@ void ChangeBeginAndEndEntries(const RNode &node, Long64_t begin, Long64_t end);
 void ChangeSpec(const ROOT::RDF::RNode &node, ROOT::RDF::Experimental::RDatasetSpec &&spec);
 void TriggerRun(ROOT::RDF::RNode node);
 std::string GetDataSourceLabel(const ROOT::RDF::RNode &node);
+void SetTTreeLifeline(ROOT::RDF::RNode &node, const std::any &lifeline);
```
Comment (guitargeek) [inline tree/dataframe/inc/ROOT/RDF/RInterface.hxx:97]:
```suggestion
void SetTTreeLifeline(ROOT::RDF::RNode &node, std::any lifeline);
```
...and then `std::move()` the `lifeline` inside the function to elide a copy. Also makes the signature more compact and highlights the fact that the wrapped type should be cheaply copyable.

Also, maybe consider a more general name like `SetSharedResource`? I'm thinking that we will also re-use this interface to manage other resources from the Python side, like NumPy arrays and so on

File: bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py [hunk 4]
```diff
@@ -77,9 +77,20 @@ def _rdataframe(local_rdf, distributed_rdf):
     """
 
     def rdataframe(*args, **kwargs):
+        import ROOT
+        from libROOTPythonizations import CreatePyObjRefCountWrapper
```
[the remark this answers is not in the document]
Comment (guitargeek) [reply bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py:81]: ...on the other hand, the `std::any` is the wrapper. Well the name just feels a bit long

**Review by guitargeek — CHANGES_REQUESTED** [review]
A few suggestions inline.

Also, we should consider to implement the RVecDS that was [refactored last year](https://github.com/root-project/root/pull/15031) with the same `std::any` pattern. It uses the `std::function<void()>` pattern, which is less general and I also think we should solve similar problems with the same pattern for a sustainable codebase.

File: bindings/pyroot/pythonizations/src/PyROOTModule.cxx [hunk 5]
```diff
@@ -60,6 +61,69 @@ PyObject *RegisterExecutorAlias(PyObject * /*self*/, PyObject *args)
...
+   {
+      Reset(other.fObject);
+      other.Reset(nullptr);
+   }
+
+   PyObjRefCountWrapper &operator=(PyObjRefCountWrapper &&other)
+   {
+      Reset(other.fObject);
+      other.Reset(nullptr);
+      return *this;
```
Comment (guitargeek) [inline bindings/pyroot/pythonizations/src/PyROOTModule.cxx:111]:
```suggestion
      fObject = other.fObject);
      other.fObject = nullptr;
      return *this;
```
To avoid incrementing and decrementing the reference counter, making moving truly cheap (can also be done for the move constructor).

File: bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (guitargeek) [reply bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py:81]: Also, maybe we should use a name that is "invertible", because maybe we'll need one day a function to do the inverse, unpacking the Python type from the `std::any`? Not that I have a usecase now, it's just something so consider for naming.

Maybe `PyObjectToStdAny`, and the other would be `StdAnyToPyObject`?

File: bindings/pyroot/pythonizations/src/PyROOTModule.cxx [hunk 6]
```diff
@@ -60,6 +61,69 @@ PyObject *RegisterExecutorAlias(PyObject * /*self*/, PyObject *args)
...
+namespace Internal {
+/// \brief A PyObject wrapper to track reference counting of external objects
+///
+/// This wrapper can be useful in shared ownership scenarios when a C++ object
+/// is created on the Python side and there is no easy way to track its ownership
+/// on the C++ side. If multiple instances of this class are given the same
+/// Python proxy, they will increase/decrease its reference counting following
+/// Python rules and ensure proper destruction of the underlying C++ object when
+/// no other Python objects are referencing it.
+class PyObjRefCountWrapper final {
```
Comment (guitargeek) [inline bindings/pyroot/pythonizations/src/PyROOTModule.cxx:73]:
```suggestion
class PyObjRefCount final {
```
As said in the other comment: the `std::any` is the wrapper, so maybe not use "Wrapper" in this class name?

File: bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (vepadulano) [reply bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py:81]: There is no notion of `std::any` in the implementation of `PyObjRefCountWrapper`, so I'm unsure on linking the two names. On the other hand, without `std::any` the class doesn't make sense, so...

File: tree/dataframe/inc/ROOT/RDF/RInterface.hxx (hunk 3 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/RInterface.hxx:97]: > Also, maybe consider a more general name like SetSharedResource? I

This function is specifically meant for setting the value of the data member of the RLoopManager. Before making it more generic, I would like to see how we would use the same pattern for another class (e.g. the RVecDS). I would say that's for another PR

**Review by guitargeek — APPROVED** [review]
Thank you for considering my comments! For me it's good now

File: bindings/pyroot/pythonizations/src/PyROOTModule.cxx (hunk 2 above)
Comment (pcanal) [reply bindings/pyroot/pythonizations/src/PyROOTModule.cxx]: The equivalent for a source file is to use the anonymous namespace.  Note that both solution (anonymous namespace or Internal namespace) had the advantage of hiding (mangling) the `PyObjRefCounter` symbols from the linker.

Comment (guitargeek) [reply bindings/pyroot/pythonizations/src/PyROOTModule.cxx]: Yes I have thought about that as well with the linker, it's a good point. But it's already in the `PyROOT` namespace, which I double will collide with anything (`PyROOT::Internal` is not reducing the probability that much further)
