### PR TITLE
Do not complain about the internal of unique_ptr.  Do not complain about transient std::tuple.

### LINKED ISSUE #13574: rootcling/root-io error loading std::filesystem::path
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Rootcling fails to load correctly std::filesystem::path.

This is discussed in [this post](https://root-forum.cern.ch/t/rootcling-with-std-filesystem/55388), from which I am reproducing here the provided example.

### Reproducer

Create the following two files:

test.hh:
```C++
#ifndef test_hh
#define test_hh
#include <iostream>
#include <filesystem>
namespace fs = std::filesystem;

class test
{
public:
    test();
    ~test();

private:
    fs::path path;
};

#endif
```

test.cpp:
```C++
#include "test.hh"
test::test()
{
    std::cout << "test constructor" << std::endl;
    this->path = ".";
}

test::~test()
{
    std::cout << "test destructor" << std::endl;
}
```

Then load with ACLiC:
```
$ root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/06                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Aug 30 2023, 16:45:00                 |
  | From tags/v6-28-06@v6-28-06                                      |
  | With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                   |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] .L test.cpp+
Info in <TUnixSystem::ACLiC>: creating shared library /data/giraudpf/tmp/./test_cpp.so
input_line_11:6:22: error: '_List' is a private member of 'std::filesystem::path'
   filesystem::path::_List::_Impl_deleter _1;
                     ^
/usr/include/c++/11/bits/fs_path.h:636:12: note: declared private here
    struct _List
           ^
input_line_11:7:22: error: '_List' is a private member of 'std::filesystem::path'
   filesystem::path::_List::_Impl* _0;
                     ^
/usr/include/c++/11/bits/fs_path.h:636:12: note: declared private here
    struct _List
           ^
Error in <Load>: Could not declare TEmulatedTuple<filesystem::path::_List::_Impl*,filesystem::path::_List::_Impl_deleter>
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/06                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Aug 30 2023, 16:45:00                 |
  | From tags/v6-28-06@v6-28-06                                      |
  | With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                   |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

```

### Installation method

Built from source

### Operating system

Ubuntu 22.04

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pcanal**
This fixes #13574

This prevents complains about the internals of `unique_ptr` when we are just investigating its suitability for streaming.  

Also do not complains about a transient `std::tuple` even if we can not stream it (for example if one of component is a private entity).

Test at https://github.com/root-project/roottest/pull/1030

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2204/nortcxxmod

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
@phsft-bot

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
This is passing the test on Jenkins and thus ready for review (how does one trigger reruns of the actions?)

File: core/clingutils/src/TClingUtils.cxx [hunk 1]
```diff
@@ -4356,6 +4356,43 @@ const clang::Type *ROOT::TMetaUtils::GetUnderlyingType(clang::QualType type)
...
+      case clang::AS_public:
+         return !ctxt || IsCtxtReacheable(*ctxt);
+      case clang::AS_protected:
+         return false;
+      case clang::AS_private:
+         return false;
+      case clang::AS_none:
+         return !ctxt || IsCtxtReacheable(*ctxt);
+      default:
+         // IMPOSSIBLE
```
Comment (jblomer) [inline core/clingutils/src/TClingUtils.cxx:4391]: Should we then `assert(false)` here?

File: core/metacling/src/TCling.cxx [hunk 2]
```diff
@@ -2678,6 +2678,14 @@ void TCling::InspectMembers(TMemberInspector& insp, const void* obj,
       return;
    }
 
+   if (TClassEdit::IsUniquePtr(cl->GetName())) {
+      // Ignore error caused by the inside of std::unique_ptr
+      // This is needed solely because of rootclingIO's IsUnsupportedUniquePointer
+      // which check the numbers of data members.
+      // If this usage is remove, this can be replace with a return statement.
+      isTransient = true;
```
Comment (jblomer) [inline core/metacling/src/TCling.cxx:2686]: Could you point out where it is further down in this function that the `isTransient == true` prevents an error?

File: core/metacling/src/TClingMethodInfo.cxx [hunk 3]
```diff
@@ -478,13 +478,13 @@ long TClingMethodInfo::Property() const
    }
    switch (Access) {
       case clang::AS_public:
-         property |= kIsPublic;
+         property |= kIsPublic | kIsNotReacheable;
```
Comment (jblomer) [inline core/metacling/src/TClingMethodInfo.cxx:481]: Should this move down to the `clang::AS_protected` case?

File: core/metacling/src/TClingTypeInfo.cxx [hunk 4]
```diff
@@ -134,6 +134,28 @@ long TClingTypeInfo::Property() const
...
+            break;
+         case clang::AS_private:
+            property |= kIsPrivate | kIsNotReacheable;
+            break;
+         case clang::AS_none:
+            if (TD->getDeclContext()->isNamespace())
+               property |= kIsPublic;
+            break;
+         default:
+            // IMPOSSIBLE
```
Comment (jblomer) [inline core/metacling/src/TClingTypeInfo.cxx:152]: `assert(false)`?

**Review by jblomer — COMMENTED** [review]
Thank you! I left some comments but would leave the approval to someone more familiar with the code.

File: core/metacling/src/TClingTypeInfo.cxx (hunk 4 above)
Comment (pcanal) [reply core/metacling/src/TClingTypeInfo.cxx:152]: Sure.

File: core/metacling/src/TClingMethodInfo.cxx (hunk 3 above)
Comment (pcanal) [reply core/metacling/src/TClingMethodInfo.cxx:481]: Indeed.

File: core/metacling/src/TCling.cxx (hunk 2 above)
Comment (pcanal) [reply core/metacling/src/TCling.cxx:2686]: It is the 'whole' thing; this function is used (indirectly) to populate the "list of real data". If rootclingIO's IsUnsupportedUniquePointer was not looking at that list, we could afford to keep it empty.

**Comment by hahnjo** [comment]
As far as I understand, the new test is still failing?

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
Indeed, unrelated fixes uncovered additional problems :(

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
The last failure may be related to the LLVM 16 upgrade (maybe)

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

File: bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx [hunk 5]
```diff
@@ -269,7 +269,8 @@ bool CPyCppyy::InsertDispatcher(CPPScope* klass, PyObject* bases, PyObject* dct,
     Cppyy::TCppIndex_t nData = Cppyy::GetNumDatamembers(baseType);
     if (nData) code << "public:\n";
     for (Cppyy::TCppIndex_t idata = 0; idata < nData; ++idata) {
-        if (Cppyy::IsProtectedData(baseType, idata)) {
+        if (Cppyy::IsProtectedData(baseType, idata)
+            && !Cppyy::IsEnumData(baseType, idata)) {
```
Comment (jblomer) [inline bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx:273]: How is this change related to the rest of the PR?

Comment (pcanal) [reply bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx:273]: It is not.  I will remove it.

File: core/base/src/TMemberInspector.cxx [hunk 6]
```diff
@@ -121,7 +121,7 @@ void TMemberInspector::GenericShowMembers(const char *topClassName, const void *
       }
    }
 
-   TClass *top = TClass::GetClass(topClassName);
+   TClass *top = TClass::GetClass(topClassName, true, isTransient);
```
Comment (vepadulano) [inline core/base/src/TMemberInspector.cxx:124]: Maybe just add a comment so we remember not to remove the `isTransient` flag from the function call in the future

File: core/meta/src/TDataMember.cxx [hunk 7]
```diff
@@ -595,7 +595,14 @@ Long_t TDataMember::Property() const
    if (!fInfo || !gCling->DataMemberInfo_IsValid(fInfo)) return 0;
    int prop  = gCling->DataMemberInfo_Property(fInfo);
    int propt = gCling->DataMemberInfo_TypeProperty(fInfo);
-   t->fProperty = prop|propt;
+   t->fProperty = (prop | propt) & ~(kIsPublic | kIsProtected | kIsPrivate);
+   // Set to the strictess access of the member and the type
```
Comment (vepadulano) [inline core/meta/src/TDataMember.cxx:599]:
```suggestion
   // Set to the strictest access of the member and the type
```

File: core/metacling/src/TCling.cxx [hunk 8]
```diff
@@ -2716,6 +2716,14 @@ void TCling::InspectMembers(TMemberInspector& insp, const void* obj,
       return;
    }
 
+   if (TClassEdit::IsUniquePtr(cl->GetName())) {
+      // Ignore error caused by the inside of std::unique_ptr
```
Comment (vepadulano) [inline core/metacling/src/TCling.cxx:2720]: Since this is a crucial part of the mechanism, I would still like to see a bit more explanation here. I can imagine at least:
1. Adding some reference to where this `isTransient` flag is used within this function or to which functions it is passed where it becomes important for the logic. By quickly looking at the code, I see it's used in the calls to `InspectMember`.
2. A reference to the GitHub issue that triggered this change.

File: core/metacling/src/TCling.cxx [hunk 9]
```diff
@@ -2716,6 +2716,14 @@ void TCling::InspectMembers(TMemberInspector& insp, const void* obj,
...
+      // This is needed solely because of rootclingIO's IsUnsupportedUniquePointer
+      // which check the numbers of element in the GetListOfRealData.
```
Comment (vepadulano) [inline core/metacling/src/TCling.cxx:2722]:
```suggestion
      // which checks the number of elements in the GetListOfRealData.
```

File: io/rootpcm/src/rootclingIO.cxx [hunk 10]
```diff
@@ -82,7 +82,9 @@ static bool IsUnsupportedUniquePointer(const char *normName, TDataMember *dm)
          return true;
       }
 
-      clm->BuildRealData();
+      // TODO: Is it not clear what situation we are checking for by checking if
+      // the unique_ptr class has any data members.
+      clm->BuildRealData(nullptr, true);
```
Comment (vepadulano) [inline io/rootpcm/src/rootclingIO.cxx:87]: I don't think this comment is clear if read out of context from this PR. It also makes me doubt, why are we introducing all this new logic if we don't know which situation it is addressing?

**Review by vepadulano — CHANGES_REQUESTED** [review]
Thanks for this huge amount of work! I have some comments for discussion.

Also, I feel like before merging the PR the list of commits should be shrunk by some margin, not sure yet about the correct amount though.

File: core/base/src/TMemberInspector.cxx (hunk 6 above)
Comment (pcanal) [reply core/base/src/TMemberInspector.cxx:124]: It was not removed, just forgotten to be added when introduced :)

File: bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx (hunk 5 above)
Comment (pcanal) [reply bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx]: It is not.

File: core/metacling/src/TCling.cxx (hunk 8 above)
Comment (pcanal) [reply core/metacling/src/TCling.cxx:2720]: There is 81 uses of `isTransient` throughout `core and an additional 120 uses of the related `silent`.
The semantic of these 2 is essential `please do your thing but don't print out any complaint if something is odd because it is not for persistency and thus not important`

File: io/rootpcm/src/rootclingIO.cxx (hunk 10 above)
Comment (pcanal) [reply io/rootpcm/src/rootclingIO.cxx:87]: This is not new logic.  The comment is pondering why the code has been here for a while.  The change made is to set it to ignore warning and errors related to the schema.

File: core/metacling/src/TCling.cxx (hunk 8 above)
Comment (vepadulano) [reply core/metacling/src/TCling.cxx:2720]: Understood, thanks!

**Review by vepadulano — APPROVED** [review]
I believe the changes look good overall, before merging it would be nice to apply the clang-format suggestions.

Thanks again for this large effort!
