### PR TITLE
[teve] Do not try to open a gdml file as a root file

### LINKED ISSUE #7987: Error message when opening a GDML with TEveManager
- [x] Checked for duplicates

### Describe the bug

When opening a GDML geometry with TEveManager I get this error message:
```
Error in <TFile::Init>: HERD.gdml not a ROOT file
```
Apart from the message, there's no evident malfunctioning and everything works as expected.

### Expected behavior

No error message if really there is no malfunctioning triggered by using a GDML file.

### To Reproduce

This can be simply reproduced in the Root shell by opening any GDML file as:
```
$ root
root [0] TEveManager m(500, 500)
(TEveManager &) @0x7fbabb351008
root [1] m.GetGeometry("HERD.gdml")
TEveManager::GetGeometry  loading: 'HERD.gdml' -> 'HERD.gdml'.
Info in <TGeoManager::Import>: Reading geometry from file: HERD.gdml
Info in <TGeoManager::TGeoManager>: Geometry GDMLImport, Geometry imported from GDML created
Info in <TGeoManager::SetTopVolume>: Top volume is worldLogical. Master volume is worldLogical
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::CheckGeometry>: Fixing runtime shapes...
Info in <TGeoManager::CheckGeometry>: ...Nothing to fix
Info in <TGeoManager::CloseGeometry>: Counting nodes...
Info in <TGeoManager::Voxelize>: Voxelizing...
Info in <TGeoManager::CloseGeometry>: Building cache...
Info in <TGeoManager::CountLevels>: max level = 4, max placements = 7497
Info in <TGeoManager::CloseGeometry>: 15080 nodes/ 33 volume UID's in Geometry imported from GDML
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
Error in <TFile::Init>: HERD.gdml not a ROOT file
(TGeoManager *) 0x55710546f930
```

### Setup
1. ROOT version: 6.22.08
2. Operating system: Archlinux with GCC 10.2.0
3. Self-built Root instance

### PR DESCRIPTION
**Pull request by dpiparo**
Fixes #7987

### CODE REVIEW

File: graf3d/eve/src/TEveManager.cxx [hunk 1]
```diff
@@ -790,7 +790,7 @@ TGeoManager* TEveManager::GetGeometry(const TString& filename)
       gGeoManager->GetTopVolume()->VisibleDaughters(true);
 
       // Import colors exported by Gled, if they exist.
-      {
+      if (exp_filename.EndsWith(".root")) {
```
Comment (pcanal) [inline graf3d/eve/src/TEveManager.cxx:793]: Note that:
```
if (gROOT->IsRootFile(exp_filename)) {
```
would not rely on the name convention (but would peek at the actual file content/header to make the decision)
