### PR TITLE
v628: IO: Fix StreamerInfo record write during file update.

### LINKED ISSUE #12783: [IO] Writing HistFactory model file twice gives strange results since ROOT 6.26.02
## Problem description

Since 6.26.02, there is a problem when writing different HistFactory workspaces in the same script/executable. The second workspace file is corrupt, even if the only difference for the second time is the output file prefix.

That the second workspace is corrupt gets apparent in two ways:
1. It can't be opened with newer ROOT versions (but surprisingly it can be opened with the same 6.26 version)
2. The file sizes are much smaller

The first in commit in the 6.26 branch that shows this problem was found with git bisect (see the end of this comment).

I marked this issue as **high** priority, because writing out HistFactory workspaces is a common practice in ATLAS. And recently, several ATLAS workspaces unexplainably appear corrupt. Fixing this issue could fix these problems.

## To reproduce

1. Run the following script with ROOT 6.26.02 (or any newer 6.26 commit):
   ```c++
   {
      TFile f("myFile.root", "RECREATE");
      TH1D h("myHist", "", 10, 0, 10);
      h.Write();
   }
   std::vector<std::string> names = {"ws1", "ws2"};
   for (auto name : names) {
      RooStats::HistFactory::Measurement meas(name.c_str(), name.c_str());
      meas.SetOutputFilePrefix((name + "/WS").c_str());
      meas.SetPOI("mu");
      meas.SetLumi(1);
      meas.AddConstantParam("Lumi");
      meas.SetExportOnly(true);
      RooStats::HistFactory::Channel chan("SR");
      chan.SetData("", "");
      RooStats::HistFactory::Sample sample("samp");
      sample.SetHistoName("myHist");
      sample.SetInputFile("myFile.root");
      sample.AddNormFactor("mu", 1, 0, 100);
      chan.AddSample(sample);
      meas.AddChannel(chan);
      meas.CollectHistograms();
      //if(name == "ws2")
      //delete RooStats::HistFactory::MakeModelAndMeasurementFast(meas);
      RooStats::HistFactory::MakeModelAndMeasurementFast(meas);
   }
   ```
2. Validate the file sizes:
   ```bash
   ls -lah ws1 ws2
   ```
4. Try to open the second workspace with any ROOT 6.28 version:
   ```bash
   root ws2/WS_combined_ws2_model.root -b -q -e "combined->GetName()"
   ```

There will be errors such as:
```
Error in <TBufferFile::ReadClassBuffer>: Could not find the StreamerInfo for version 2 of the class RooAbsReal, object skipped at offset 6484979
Error in <TBufferFile::CheckByteCount>: object of class RooAbsReal read too few bytes: 2 instead of 336
```

## Information on the origin of the problem

The first bad commit in the 6.26 branch is 00ca5ca9b23f2 from the PR https://github.com/root-project/root/pull/10215.
The comes from a backport of https://github.com/root-project/root/pull/9486 to the 6.26 patch release branch.

Before that commit, when you run the reproducer script above, the `ws1` and `ws2` files are compatible:
```bash
ls -lah ws1 ws2
```
```txt
ws1:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:31 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:31 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:31 WS_combined_ws1_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:31 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:31 WS_SR_ws1_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:31 WS_ws1.root

ws2:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:31 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:31 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:31 WS_combined_ws2_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:31 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:31 WS_SR_ws2_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:31 WS_ws2.root
```

from 00ca5ca9b23f2 onward, the second workspace files are smaller from some reason:
```txt
ws1:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:28 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:28 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:28 WS_combined_ws1_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:28 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:28 WS_SR_ws1_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:28 WS_ws1.root

ws2:
total 56K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:28 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:28 ..
-rw-r--r-- 1 rembserj rembserj  20K May  7 23:28 WS_combined_ws2_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:28 WS_results.table
-rw-r--r-- 1 rembserj rembserj  19K May  7 23:28 WS_SR_ws2_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:28 WS_ws2.root
```

So the problem somehow seems to be related to multithreaded IO?

### PR DESCRIPTION
**Pull request by pcanal**
Fix #12783

Since "66dfb08bd7 - [IO] Do not process the streamerinfo record of a file if we read the si already read"
which was extended in scope by "7cf9d5dc8c - fix hashing of streamer info,"

if a file is opened in update mode and the reading of its `StreamerInfo` record is skip (but
an identical record was already read) *and* some data is stored in the file, the new
`StreamerInfo` record written was missing all the classes in the original record that
were not used during the update.

To resolve this we record not only the fact that the record has been read and process
but also its content (via a collectin of uid of the `TStreamerInfo` objects).
Upon skipping the `StreamerInfo` record, we now mark of its `TStreamerInfo` objects has
been used by the file (and thus upon writing the record is complete).

This behavior was seen #12783 due an awkward 'create, fill, close, update immediately' cycle
for a couple of files.

### CODE REVIEW

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx [hunk 1]
```diff
@@ -20,12 +21,15 @@ class TRWSpinLock;
...
 namespace Internal {
 
-struct RHashSet;
+struct RHashMap;
+using RUidColl = std::vector<Int_t>;
 
-/// This class is a TS set of unsigned set
+/// This class is a thread-safe associative collection connecting
+/// a 256 bits digest/hash to a collection of uid (integer)
+/// This is used in the handling of the StreamerInfo record in TFile.
```
Comment (Axel-Naumann) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:29]: This doesn't seem to belong to `tread/` - it's not a threading utility, it's a utility for StreamerInfo. Consider moving to `io/io`?

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx [hunk 2]
```diff
@@ -38,16 +42,23 @@ public:
       HashValue() = default;
       HashValue(const char *data, int len);
       ULong64_t const *Get() const { return fDigest; }
+
+      /// Return the hash value for this object
+      size_t Hash() const noexcept {
```
Comment (Axel-Naumann) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:47]: It's *very* confusing that `HashValue` has a function `Hash`. To hash a hash value?! Please consider renaming `HashValue` to `Digest`.

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx [hunk 3]
```diff
@@ -20,12 +21,15 @@ class TRWSpinLock;
 
 namespace Internal {
 
-struct RHashSet;
+struct RHashMap;
+using RUidColl = std::vector<Int_t>;
```
Comment (Axel-Naumann) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: Why is this not a class member?

File: core/thread/src/RConcurrentHashColl.cxx [hunk 4]
```diff
@@ -46,10 +61,10 @@ RConcurrentHashColl::HashValue RConcurrentHashColl::Hash(char *buffer, int len)
 }
 
 /// If the buffer is there, return false. Otherwise, insert the hash and return true
-bool RConcurrentHashColl::Insert(const HashValue &hash) const
+bool RConcurrentHashColl::Insert(const HashValue &hash, RUidColl &&values) const
 {
    ROOT::TRWSpinLockWriteGuard wg(*fRWLock);
-   auto ret = fHashSet->fSet.insert(hash);
+   auto ret = fHashMap->fHashMap.insert({hash, std::move(values)});
```
Comment (Axel-Naumann) [inline core/thread/src/RConcurrentHashColl.cxx:67]:
```suggestion
   auto ret = fHashMap->fHashMap.emplace({hash, std::move(values)});
```
?

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 3 above)
Comment (Axel-Naumann) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]:
```suggestion
using RUidColl = std::vector<int>;
```
It's new code, no need for `_t`s.

File: io/io/src/TFile.cxx [hunk 5]
```diff
@@ -3613,6 +3611,7 @@ void TFile::ReadStreamerInfo()
       }
    }
 
+   std::vector<Int_t> si_uids;
```
Comment (Axel-Naumann) [inline io/io/src/TFile.cxx:3614]: Why is this not `RUidColl`?
```suggestion
   RUidColl si_uids;
```

**Review by Axel-Naumann — APPROVED** [review]
Several comments, though - probably just for master?

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx [hunk 6]
```diff
@@ -38,16 +42,23 @@ public:
       HashValue() = default;
       HashValue(const char *data, int len);
       ULong64_t const *Get() const { return fDigest; }
+
+      /// Return the hash value for this object
+      size_t Hash() const noexcept {
+         std::hash<ULong64_t> hasher;
+         return hasher(fDigest[0]) ^ hasher(fDigest[1])
```
Comment (Axel-Naumann) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:49]: See https://feloneouscat.wordpress.com/2016/03/31/stupid-hash-functions/ btw

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 2 above)
Comment (pcanal) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:47]: Technically it is a (shorter) hash value for a (longer) hash value and the outer name is pre-existing ...  but it's internal so we can probably change it.

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 3 above)
Comment (pcanal) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: No particular reason anymore.

Comment (pcanal) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: Maybe ... but `Int_t` (32 bits) is not the same as `int` (some number of bits)

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 1 above)
Comment (pcanal) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:29]: Until this PR it was used only in multi-thread environment (hence the original location).

File: io/io/src/TFile.cxx (hunk 5 above)
Comment (pcanal) [reply io/io/src/TFile.cxx:3614]: oversight.

File: core/thread/src/RConcurrentHashColl.cxx (hunk 4 above)
Comment (pcanal) [reply core/thread/src/RConcurrentHashColl.cxx:67]:
```
/Users/pcanal/root_working/code/rootcling/core/thread/src/RConcurrentHashColl.cxx:64:34: error: no matching member function for call to 'emplace'
   auto ret = fHashMap->fHashMap.emplace({hash, std::move(values)});
              ~~~~~~~~~~~~~~~~~~~^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/unordered_map:1257:26: note: candidate template ignored: substitution failure: deduced incomplete pack <(no value)> for template parameter '_Args'
    pair<iterator, bool> emplace(_Args&&... __args) {
                         ^
1 error generated.
```

Comment (pcanal) [reply core/thread/src/RConcurrentHashColl.cxx:67]:
```suggestion
   auto ret = fHashMap->fHashMap.emplace(hash, std::move(values));
```

File: io/io/src/TFile.cxx (hunk 5 above)
Comment (pcanal) [reply io/io/src/TFile.cxx:3614]: I think I will leave it as is.  It feel clearer with the concrete type here and the match is guaranteed by the `std::move` used later on.

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 1 above)
Comment (Axel-Naumann) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:29]: That's an excellent historical motivation but not a reason to stay this way today :-)

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 3 above)
Comment (Axel-Naumann) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: In new style code (classes starting with R) we don't use ROOT's _t types anymore but the standard types. So please use int or int32_t or whatever you see for.

File: io/io/src/TFile.cxx (hunk 5 above)
Comment (Axel-Naumann) [reply io/io/src/TFile.cxx:3614]: Then why introduce the public type alias at all?

Comment (pcanal) [reply io/io/src/TFile.cxx:3614]: To shorten the header, to self document the header.

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx (hunk 3 above)
Comment (pcanal) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: > So please use int or int32_t or whatever you see for.

I disagree here because this type must match what I put it (which is `Int_t`) [And `int` is definitively 'wrong' (on some platform it is `long`] [And using `int32_t` as a general rule is premature as the I/O does not support it properly (`int32_t` will be seen by the I/O as the underlying type and it will change from platform to platform and will either lead to CheckSum check failure when using ClassDef or with having to deal with (at least) 2 checksums when writing I/O rules (without a ClassDef)).

I.e. I *hope* we did not mistakenly rule that using raw `int` and `std::*_t` is okay for anything that wants to be stored in file.

Comment (Axel-Naumann) [reply core/thread/inc/ROOT/RConcurrentHashColl.hxx:25]: Thanks, I understand. But I wonder how much "new interface style" this class brings with it, also because it doesn't seem to be user facing? Or do you foresee use cases for users? Maybe given the fact it's Internal:: we don't actually care about any of this? :-)
