### PR TITLE
[hadd] Fix file equivalence test in case of remote files

### LINKED ISSUE #20872: hadd crashes when already existing output file is used with remote file input paths
### Check duplicate issues.

- [x] Checked for duplicates

### Description

I am seeing the error when running the following:

```
hadd -ff -j 1 /opt/dirac/work/ProductionManagement/HistogramMergingAgent/MergeHistograms/Gauss_00341224_0_1.Hist.root @/tmp/tmpsulgw29m
stdout:
stderr: Info in <hadd>: parallelizing  with 1 processes.
Info in <hadd>: target file: /opt/dirac/work/ProductionManagement/HistogramMergingAgent/MergeHistograms/Gauss_00341224_0_1.Hist.root
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot check file equivalence: No such file or directory [root://snipped_out@eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/MC/2018/GAUSSHIST/00341224/0000/Gauss_00341224_00000051_1.Hist.root] [/opt/dirac/work/ProductionManagement/HistogramMergingAgent/MergeHistograms/Gauss_00341224_0_1.Hist.root]
```
where `/tmp/tmpsulgw29m` is a list of input `root:// URLs

I believe this commit is the source:
https://github.com/root-project/root/commit/1b8fbed243501b4fee4e3d60ca5469ade77924ff#diff-db547cc4d138dcfa1595ecf75c752a6192fc2c64cbae7dc4bac9d840263ec302R133-R648

### Reproducer

The following fails with the above described error

```
touch testmerge_fromremote_indirect_txt.root # file has to exist for the segfault to occur
echo "root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root" > input_files.txt
echo "root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magup_OD_workshop_example.root" >> input_files.txt
hadd -ff -j 1 testmerge_fromremote_indirect_txt.root @input_files.txt

Info in <hadd>: parallelizing  with 1 processes.
Info in <hadd>: target file: testmerge_fromremote.root
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot check file equivalence: No such file or directory [root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root] [testmerge_fromremote.root]
Aborted (core dumped)
```

The following works
```
bash-5.2$ hadd -ff -j 1 testmerge_fromremote.root root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magup_OD_workshop_example.root
Info in <hadd>: parallelizing  with 1 processes.
Info in <hadd>: target file: testmerge_fromremote.root
Info in <hadd>: compression setting for all output: 101
Info in <hadd>: each process should handle at least 3 files for efficiency. Setting the number of processes to: 1
hadd Source file 1: root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root
hadd Source file 2: root://eospublic.cern.ch//eos/opendata/lhcb/upload/Bs2JpsiKK_magup_OD_workshop_example.root
hadd Target path: testmerge_fromremote.root:/
hadd Target path: testmerge_fromremote.root:/Bs2JpsiKK
```

The following works

```
bash-5.2$ hadd -ff -j 1 testmerge.root /eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root /eos/opendata/lhcb/upload/Bs2JpsiKK_magup_OD_workshop_example.root
Info in <hadd>: parallelizing  with 1 processes.
Info in <hadd>: target file: testmerge.root
Info in <hadd>: compression setting for all output: 101
Info in <hadd>: each process should handle at least 3 files for efficiency. Setting the number of processes to: 1
hadd Source file 1: /eos/opendata/lhcb/upload/Bs2JpsiKK_magdown_OD_workshop_example.root
hadd Source file 2: /eos/opendata/lhcb/upload/Bs2JpsiKK_magup_OD_workshop_example.root
hadd Target path: testmerge.root:/
hadd Target path: testmerge.root:/Bs2JpsiKK
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.36.04                        https://root.cern |
  | (c) 1995-2025, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Nov 10 2025, 08:17:11                 |
  | From tags/6-36-04@6-36-04                                        |
  | With                                                             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

conda from conda-forge

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by silverweed**
`hadd` is trying to use `std::filesystem::equivalent` indiscriminately for any source and target files, but the function only makes sense for local files.

This PR adds a function that checks if the files are remote and, if so, if simply compares their URL.

**NOTE**: this PR should be backported to 6.38.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #20872

### CODE REVIEW

File: main/src/hadd.cxx [hunk 1]
```diff
@@ -614,6 +614,20 @@ static Int_t ParseFilterFile(const std::optional<std::string> &filterFileName,
...
 }
 
+static bool FilesAreEquivalent(std::string_view source, std::string_view target)
+{
+   const bool sourceIsLocal = source.find_first_of("://") == std::string_view::npos;
+   const bool targetIsLocal = target.find_first_of("://") == std::string_view::npos;
+   if (sourceIsLocal != targetIsLocal)
+      return false;
+
+   // We cannot use std::filesystem functions for remote files.
```
Comment (pcanal) [inline main/src/hadd.cxx:624]:
```suggestion
   // We cannot use std::filesystem functions for remote files nor local files 
   // expressed with a protocol.
```
eg `auto f = TFile::Open("file://t1.root", "RECREATE")` creates a local file.

File: main/src/hadd.cxx [hunk 2]
```diff
@@ -614,6 +614,20 @@ static Int_t ParseFilterFile(const std::optional<std::string> &filterFileName,
    return 0;
 }
 
+static bool FilesAreEquivalent(std::string_view source, std::string_view target)
+{
+   const bool sourceIsLocal = source.find_first_of("://") == std::string_view::npos;
```
Comment (pcanal) [inline main/src/hadd.cxx:619]:
```suggestion
   const bool sourceHasProtocol = source.find_first_of("://") == std::string_view::npos;
```
See https://github.com/root-project/root/pull/20878/changes#r2694519784
