### PR TITLE
[Tree] Fix cases in which GetLeaf(branchname, leafname) ignores the branchname argument

### LINKED ISSUE #6944: RDataFrame misidentifies vector<XYZTVector> type of a friend tree with identical branch name to another friend tree
The issue is initially reported and discussed on the ROOT forum [here](https://root-forum.cern.ch/t/rdataframe-tree-friends-branches-with-identical-variable-name-but-different-types/42701/4)

### Describe the bug

RDataFrame has two tree friends.
Both tree friends have a branch with identical name.
Type of a branch in the 1st friend tree: XYZVector
Type of a branch in the 2nd friend tree: vector\<XYZTVector>

1st friend tree is attached to RDataFrame before 2nd friend tree.
Access of 2nd friend tree branch results in error due to unexpected type of the branch assumed by RDataFrame as shown in the stand alone example bellow.

### To Reproduce

Run this stand alone example:

```
import ROOT

vectors = '''
#include "Math/Vector3D.h"
#include "Math/Vector4D.h"
#include "TFile.h"
#include "TTree.h"
#include <vector>
using namespace ROOT::Math;
using namespace ROOT::VecOps;

RVec <double> getArrZ(const RVec<XYZTVector>& vec){
    auto getItemZ = [](const XYZTVector& item) { return item.Z(); };
    return Map(vec, getItemZ);
}

'''

ROOT.gInterpreter.Declare(vectors)

if __name__ == "__main__":
  ROOT.RDataFrame(1).Define("vec", "XYZVector(10, 10, 10)").Snapshot("Particle", "f1.root")
  ROOT.RDataFrame(1).Define("vec", "XYZVector(20, 20, 20)").Snapshot("Cluster", "f2.root")
  ROOT.RDataFrame(1).Define("vec", "std::vector<XYZTVector>{XYZTVector(30, 30, 30, 30)}").Snapshot("Vertex", "f3.root")

  ch1 = ROOT.TChain("Particle")
  ch1.Add("f1.root")
  ch2 = ROOT.TChain("Cluster")
  ch2.Add("f2.root")
  ch3 = ROOT.TChain("Vertex")
  ch3.Add("f3.root")

  ch1.AddFriend(ch2, "cluster")
  ch1.AddFriend(ch3, "vertex")

  df = ROOT.RDataFrame(ch1)
  print(df.Define("particle_z", "vec.Z()").Histo1D("particle_z").GetMean())
  print(df.Define("cluster_z", "cluster.vec.Z()").Histo1D("cluster_z").GetMean())
  print(df.Define("vertex_z", "getArrZ(vertex.vec)").Histo1D("vertex_z").GetMean())
```

which results in the error on 3rd print. Full output:

```
10.0
20.0
input_line_99:2:142: error: no matching function for call to 'getArrZ'
  ...= [](ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag>& var0){return getArrZ(var0)
                                                                                                                                     ^~~~~~~
input_line_42:10:15: note: candidate function not viable: no known conversion from 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,
      ROOT::Math::DefaultCoordinateSystemTag>' (aka 'DisplacementVector3D<Cartesian3D<double>, ROOT::Math::DefaultCoordinateSystemTag>') to
      'const RVec<ROOT::Math::XYZTVector>' (aka 'const RVec<LorentzVector<PxPyPzE4D<double> > >') for 1st argument
RVec <double> getArrZ(const RVec<XYZTVector>& vec){
              ^
input_line_103:2:142: error: no matching function for call to 'getArrZ'
  ...= [](ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag>& var0){return getArrZ(var0)
                                                                                                                                     ^~~~~~~
input_line_42:10:15: note: candidate function not viable: no known conversion from 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,
      ROOT::Math::DefaultCoordinateSystemTag>' (aka 'DisplacementVector3D<Cartesian3D<double>, ROOT::Math::DefaultCoordinateSystemTag>') to
      'const RVec<ROOT::Math::XYZTVector>' (aka 'const RVec<LorentzVector<PxPyPzE4D<double> > >') for 1st argument
RVec <double> getArrZ(const RVec<XYZTVector>& vec){
              ^
input_line_104:2:142: error: no matching function for call to 'getArrZ'
  ...= [](ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag>& var0){return getArrZ(var0)
                                                                                                                                     ^~~~~~~
input_line_42:10:15: note: candidate function not viable: no known conversion from 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,
      ROOT::Math::DefaultCoordinateSystemTag>' (aka 'DisplacementVector3D<Cartesian3D<double>, ROOT::Math::DefaultCoordinateSystemTag>') to
      'const RVec<ROOT::Math::XYZTVector>' (aka 'const RVec<LorentzVector<PxPyPzE4D<double> > >') for 1st argument
RVec <double> getArrZ(const RVec<XYZTVector>& vec){
              ^
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    print(df.Define("vertex_z", "getArrZ(vertex.vec)").Histo1D("vertex_z").GetMean())
cppyy.gbl.std.runtime_error: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: 
RDataFrame: An error occurred during just-in-time compilation. The lines above might indicate the cause of the crash
 All RDF objects that have not run an event loop yet should be considered in an invalid state.

  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: 
RDataFrame: An error occurred during just-in-time compilation. The lines above might indicate the cause of the crash
 All RDF objects that have not run an event loop yet should be considered in an invalid state.

  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: 
RDataFrame: An error occurred during just-in-time compilation. The lines above might indicate the cause of the crash
 All RDF objects that have not run an event loop yet should be considered in an invalid state.
```

### Expected behavior

Expected behavior that identical branch names don't interfere as they accessed with different tree aliases `cluster.vec` and `vertex.vec` and should be distinguished with the following output:

```
10.0
20.0
30.0
```

### Setup
1. ROOT version 6.22/00 from /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/bin/root
2. OS: RedHat CentOS 7.9.2009
3. Python 3.7.6 from /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/bin/python

### Additional context
1) **With** Cluster tree attached as a friend `df.GetColumnType("vertex.vec")` yields :
```
ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag>
```

2) **Without** Cluster tree attached as a friend `df.GetColumnType("vertex.vec")` yields :
```
ROOT::VecOps::RVec<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >>
```

### LINKED ISSUE #6964: [TTree] GetLeaf ignores the branchname arg if friend trees are present
- [X] Checked for duplicates

### Describe the bug

`GetLeaf(branchname, leafname)` seems to ignore the `branchname` argument if friend trees are present -- or in any case, it returns a non-null pointer even for a bogus `branchname` argument, but only if friend trees are present.

Note that depending on the situation this might result in wrong data being read.

### Expected behavior

`GetLeaf(branchname, leafname)` should return the same pointer whether a friend tree is present or not.

### To Reproduce

```cpp
#include <TFile.h>
#include <TTree.h>
#include <iostream>

int main() {
   {
      TFile f("f.root", "recreate");
      TTree t("t", "t");
      int x = 42;
      t.Branch("x", &x);
      t.Fill();
      t.Write();
   }

   TFile f("f.root");
   auto *t = f.Get<TTree>("t");
   std::cout << t->GetLeaf("asdklj", "x") << '\n'; // prints 0 as expected

   TFile f2("f.root");
   auto *t2 = f2.Get<TTree>("t");
   t->AddFriend(t2);
   std::cout << t->GetLeaf("asdklj", "x") << '\n'; // prints the address of leaf `x`, unexpected

   return 0;
}
```

### Setup

I am using master@a7cceb7478e .

### Additional context

This seems to be the root cause of #6944 .

### PR DESCRIPTION
**Pull request by eguiraud**
This fixes and adds tests for #6964 and should also fix #6944 .

### CODE REVIEW

File: tree/tree/src/TTree.cxx [hunk 1]
```diff
@@ -6021,9 +6021,7 @@ TLeaf* TTree::GetLeafImpl(const char* branchname, const char *leafname)
    }
    TIter nextl(GetListOfLeaves());
    while ((leaf = (TLeaf*)nextl())) {
-      if (!strcmp(leaf->GetFullName(),leafname))
-         return leaf;
-      if (strcmp(leaf->GetName(),leafname))
+      if (strcmp(leaf->GetFullName(), leafname) && strcmp(leaf->GetName(), leafname))
```
Comment (pcanal) [inline tree/tree/src/TTree.cxx:6024]: If the `leafname` argument matches the return value of `GetFullName` then (if all is as intended), it does by definition match the branch name (which is included in the `full name`).  However indeed the user could be calling 
```
GetLeaf("somebranchname", "someotherbranchname.leafname")
```
.. right and this might somehow be valid / intentional.  To support this we might need:
```suggestion
      if (!strcmp(leaf->GetFullName(), leafname) {
          if (!strcmp(leaf->GetBranch()->GetName(), branchname)
             return;
          else
             continue;
      }
      if (strcmp(leaf->GetName(), leafname))
```

Comment (eguiraud) [reply tree/tree/src/TTree.cxx:6024]: > If the leafname argument matches the return value of GetFullName then (if all is as intended), it does by definition match the branch name

This is not true e.g. for `GetLeaf("notavalidbranch", "branchelementname")`. This patch fixes precisely this case: we were returning a non-null pointer as if `GetLeaf("branchelementname")` was called, and now we correctly return a null pointer.

Why is the patch problematic?

Comment (pcanal) [reply tree/tree/src/TTree.cxx:6024]: Because the "shortcut" (that includes more precise match):
```
if (!strcmp(leaf->GetFullName(),leafname))
   return leaf;
```
is removed and thus we are returning to the prior incorrect and/or slow match.

I.e. ROOT-10942 is likely to return in some shape or form.

Comment (pcanal) [reply tree/tree/src/TTree.cxx:6024]: I.e. I think that the change I propose should keep the shortcut and fix your use case.

Comment (eguiraud) [reply tree/tree/src/TTree.cxx:6024]: ok, thanks! i'll be back on this after the holidays :)

**Comment by eguiraud** [comment]
@phsft-bot build please

File: tree/tree/src/TTree.cxx (hunk 1 above)
Comment (eguiraud) [reply tree/tree/src/TTree.cxx:6024]: Slightly reworked version (fixed missing brackets, added check for `!branchname`, added comments):

```suggestion
      if (!strcmp(leaf->GetFullName(), leafname)) {
         // if branchname is also a match, it's the correct leaf, else keep looking
         if (!branchname || !strcmp(leaf->GetBranch()->GetName(), branchname))
            return leaf;
         else
            continue;
      }
      if (strcmp(leaf->GetName(), leafname)) // no match
```

However: why is it ok to just check `leaf->GetBranch()->GetName()` against `branchname` here, while a few lines below, in order to check whether the branch name is a match, we need a much more complex logic (including parent branches etc.)?

Comment (pcanal) [reply tree/tree/src/TTree.cxx:6024]: humm ... isn't it because it is a "shortcut"/"easy match" and that the complex check should only be implemented once?

Comment (pcanal) [reply tree/tree/src/TTree.cxx:6024]: humm ... except for the "continue" being in the way ...

```suggestion
      if (!strcmp(leaf->GetFullName(), leafname)) {
         // if branchname is also a match, it's the correct leaf, else keep looking
         if (!branchname || !strcmp(leaf->GetBranch()->GetName(), branchname))
            return leaf;
      }
      if (strcmp(leaf->GetName(), leafname)) // no match
```

Comment (eguiraud) [reply tree/tree/src/TTree.cxx:6024]: Should be resolved as agreed after discussion in the latest commits

**Review by pcanal — APPROVED** [review]
