### PR TITLE
[io] Fix TFileMerger getDirectory not considering full path

### LINKED ISSUE #16190: TFileMerger behaviour when the directory structure contains repeated names
### Check duplicate issues.

- [X] Checked for duplicates

### Description

For a ROOT file structured with top-level directories A and B, it seems that if B contains a subdirectory also named A the objects in that subdirectory may fail being properly merged when using **_hadd_**; instead the outcome is a simple copy of the object in the first source file...

The getDirectory() helper in TFilerMerger::MergeOne() indeed apparently favours a lookup based on the directory name and not the full path, which may not always pick the intended directory:
https://github.com/root-project/root/blob/0aa2b6b8760b78dff2cffd873f955735fa1b0ef3/io/io/src/TFileMerger.cxx#L548

### Reproducer

Save self-contained script below to mwe.cxx and execute with **_root -l -b -q mwe.cxx++_**
```
#include "TFileMerger.h"
#include "TFile.h"
#include "TH1D.h"
#include <iostream>

void createSrcFile(const char* name)
{
  TFile f(name, "RECREATE");
  f.mkdir("A", "");
  f.mkdir("B/A", "");
  f.mkdir("C/D/A", "");
  f.cd("A");
  TH1D h1("H1", "H1", 1, 0., 1.);
  h1.SetBinContent(1, 1);
  h1.Write();
  f.cd("B/A");
  TH1D h2("H2", "H2", 1, 0., 1.);
  h2.SetBinContent(1, 10);
  h2.Write();
  f.cd("C/D/A");
  TH1D h3("H3", "H3", 1, 0., 1.);
  h3.SetBinContent(1, 100);
  h3.Write();
  f.Close();
}


void check(const char* filename, const char* deco)
{
  TFile f(filename, "READ");
  std::cout << deco
	    << f.Get<TH1D>("A/H1")->GetBinContent(1)
	    << " "
            << f.Get<TH1D>("B/A/H2")->GetBinContent(1)
	    << " "
	    << f.Get<TH1D>("C/D/A/H3")->GetBinContent(1)
	    << std::endl;
  f.Close();
}


void mwe()
{
  createSrcFile("src1.root");
  createSrcFile("src2.root");
  TFileMerger mg;
  mg.AddFile("src1.root", kFALSE);
  mg.AddFile("src2.root", kFALSE);
  mg.OutputFile("dest.root", kTRUE);
  mg.Merge();
  check("src1.root", "  ");
  check("src2.root", "+ ");
  std::cout << "------------\n";
  check("dest.root", "= ");
}
```

### ROOT version

6.32.02

### Installation method

lxplus native

### Operating system

RHEL 9.4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by silverweed**
# This Pull request:
fixes `getDirectory` inside `TFileMerger.cxx` which is looking up objects by name rather than by full path.

Added regression test: https://github.com/root-project/roottest/pull/1191

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #16190 and #16474

### CODE REVIEW

File: io/io/src/TFileMerger.cxx [hunk 1]
```diff
@@ -543,9 +555,10 @@ Bool_t TFileMerger::MergeOne(TDirectory *target, TList *sourcelist, Int_t type,
    Bool_t canBeMerged = kTRUE;
 
    TList dirtodelete;
-   auto getDirectory = [&dirtodelete](TDirectory *parent, const char *name, const TString &pathname)
+   auto getDirectory = [&dirtodelete](TDirectory *parent, const TString &pathname)
    {
-      TDirectory *result = dynamic_cast<TDirectory*>(parent->GetList()->FindObject(name));
+      auto pathPieces = ROOT::Split(pathname, "\\/");
+      TDirectory *result = LookupObjByFullPath(parent, pathname, pathPieces);
```
Comment (pcanal) [inline io/io/src/TFileMerger.cxx:561]: Is there a concrete difference between this and 'just' executing directly line 550/563:
```
          result = parent->GetDirectory(pathname);
```
?

The original idea of the call to `FindObject` was to save time if the answer was findable without parsing (which seems reintroduced by the split)

Comment (pcanal) [reply io/io/src/TFileMerger.cxx:561]: Actually no, I was remembering wrong ... the intent is completely different and is broken by the new code.

The core of the lambda function is to determine whether the `TDirectory` we are looking for is already in memory or needs to be loaded from file and hence added to the list of things to cleanup.

The `parent->GetList()->FindObject(name)` is the part that checks whether it is already in memory while the call to `GetDirectory` will return the requested pointer either from memory or after loading it from disk.

See commit e97dc3678ae9da6628242afceca3142d6c319832 and the (incomplete first part) 30fd4c79425c8be12be7af6fe1936317d1f5eec7.

This might be fixable by tweaks the new line 444.

**Review by pcanal — CHANGES_REQUESTED** [review]
Need to keep the behavior introduced by commit e97dc3678ae

File: io/io/src/TFileMerger.cxx (hunk 1 above)
Comment (silverweed) [reply io/io/src/TFileMerger.cxx:561]: I don't understand how calling `FindObject` can work if it only considers the basename of the directory. Besides, even with my change I'm still going through the logic at lines 563-567, so the adding to the delete list is still happening, no?

Comment (silverweed) [reply io/io/src/TFileMerger.cxx:561]: Actually, thinking about it, couldn't `getDirectory()` be just this?
```
   auto getDirectory = [&dirtodelete](TDirectory *parent, const TString &pathname)
   {
      TDirectory *result = parent->GetDirectory(pathname);
      if (result && result != parent)
         dirtodelete.Add(result);
      return result;
   };

```

Comment (pcanal) [reply io/io/src/TFileMerger.cxx]: > The FindObject part is wrong because it will incorrectly return an existing directory Foo even when we're looking for Bar/Baz/Foo, 

This is indeed the bug we are trying to fix here.

> but it looks to me like we can just omit it..?

Not exactly.  Calling `FindObject` before/instead of `GetDirectory` is a way to cheaply get the answer to the question `did GetDirectory allocate a TDirectory or return an existing one?`.

> Unless the idea is that we mustn't add the directory to the list if it was already in memory; but in this case can't we simply deduplicate the elements from dirtodelete?

Yes this will likely have the right semantic.  However we have to make this work efficiently with file with upwards of `O(100,000)` directories in them ...

**Comment by silverweed** [comment]
@pcanal I changed the key for the `dirtodelete` map to include all 3 arguments: parent, name and pathname, as I think it's the only reliable way to know whether we're talking about the same directory or not.
The benchmarks remain basically the same as before and the tests are passing, so I think this could be a good solution.

File: io/io/src/TFileMerger.cxx [hunk 2]
```diff
@@ -542,17 +543,19 @@ Bool_t TFileMerger::MergeOne(TDirectory *target, TList *sourcelist, Int_t type,
...
-   auto getDirectory = [&dirtodelete](TDirectory *parent, const char *name, const TString &pathname)
-   {
-      TDirectory *result = dynamic_cast<TDirectory*>(parent->GetList()->FindObject(name));
-      if (!result) {
-         result = parent->GetDirectory(pathname);
-         if (result && result != parent)
-            dirtodelete.Add(result);
+   std::map<std::tuple<std::string, std::string, std::string>, TDirectory*> dirtodelete;
+   auto getDirectory = [&dirtodelete](TDirectory *parent, const char *name, const TString &pathname) {
+      auto mapkey = std::make_tuple(parent->GetName(), std::string{name}, std::string{pathname});
```
Comment (pcanal) [inline io/io/src/TFileMerger.cxx:548]: For consistency:
```suggestion
      auto mapkey = std::make_tuple(parent->GetName(), name, std::string{pathname});
```
or
```suggestion
      auto mapkey = std::make_tuple(std::string{parent->GetName()}, std::string{name}, std::string{pathname});
```
or even
```suggestion
      auto mapkey = std::make_tuple(parent->GetName(), name, pathname.Data());
```

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
We will also need a follow up PR for testing.
