### PR TITLE
[geom] split TGeoChecker class into separate library

### LINKED ISSUE #18881: Overlaps found with 6.32 no longer found in 6.34+
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Known overlaps visible by eye in the OGL viewer are not detected in new versions (6.34.08+?) when they were detected correctly in 6.32.08.

### Reproducer

File with geometry: https://cernbox.cern.ch/s/RkfJhNsWlj3tkRT

Reproducible easily in interactive ROOT session:
```c++
auto f = TFile::Open("geofile_full.conical.Pythia8-TGeant4.root");
FAIRGeom->CheckOverlaps();
FAIRGeom->PrintOverlaps();
```
Expected output:
```
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for cave and daughters within 0.1
Warning in <TGeoMatrix::dtor>: Registered matrix  was removed00:00
Warning in <TGeoMatrix::dtor>: Registered matrix Identity was removed
Warning in <TGeoMatrix::dtor>: Registered matrix  was removed0:08
Warning in <TGeoMatrix::dtor>: Registered matrix  was removed
Check overlaps:      [==========] 45747 [100.00 %]           0:11
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 2

=== Overlaps for FAIRGeom ===
 = Overlap ov00000: cave/Cavern_1 overlapping cave/SHiPMagnet_1/magyoke_1 ovlp=94
 = Overlap ov00001: cave/Cavern_1 overlapping cave/SHiPMagnet_1/MCoil3_1 ovlp=69
```

Actual output:
```
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for cave and daughters within 0.1
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 0
```

Overlap also visible using `FAIRGeom->GetMasterVolume()->Draw("ogl")`

### ROOT version

Working:
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.08                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Nov 14 2024, 09:59:57                 |
  | From tags/v6-32-08@v6-32-08                                      |
  | With c++ (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```
Broken:
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.34.08                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Apr 07 2025, 20:28:44                 |
  | From tags/v6-34-08@v6-34-08                                      |
  | With c++ (GCC) 11.5.0 20240719 (Red Hat 11.5.0-5)                |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

6.30.* also works, 6.36 also demonstrates the issue.

### Installation method

Both taken from LCG builds on CVMFS, but also reproducible using ROOT built in the SHiP software stack.

### Operating system

Almalinux 9 (LXPLUS)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by linev**
Up to now all kind of checking were performed via `TGeoPainter` interface.
Thus `TGeoChecker` was possible to use only with 'classical' TGeoPainter but not with web-based painter.
It was observed in https://github.com/root-project/root/issues/18881

Now `TGeoChecker` has own `TVirtualGeoChecker` plugin interface and instance created directly by `TGeoManager`.
This allows to use checker also with web painting. 

Remove correspondent virtual interface from `TVirtualGeoPainter` class as useless.  

PR fixes #18881

### CODE REVIEW

**Comment by dpiparo** [comment]
Thanks for this PR! The changes look fine to me, however I'd feel more comfortable if:
1) @agheata has a look in case we are missing something subtle
2) we had a test (is it possible to add one?)

**Comment by linev** [comment]
> we had a test (is it possible to add one?)

We have test which checks `TGeoChecker` functionality.
It is `geom/test/test_boolean_extrusion.cxx`.

File: geom/geom/src/TVirtualGeoChecker.cxx [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+#include "TROOT.h"
+#include "TVirtualGeoChecker.h"
+#include "TPluginManager.h"
+#include "TGeoManager.h"
+
+TVirtualGeoChecker *TVirtualGeoChecker::fgGeoChecker = nullptr;
+
+////////////////////////////////////////////////////////////////////////////////
+/// Geometry painter default constructor
```
Comment (agheata) [inline geom/geom/src/TVirtualGeoChecker.cxx]:
```suggestion
/// Geometry checker default constructor
```

File: geom/geom/src/TVirtualGeoChecker.cxx [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+TVirtualGeoChecker::TVirtualGeoChecker() {}
+
+////////////////////////////////////////////////////////////////////////////////
+/// Geometry painter default destructor
```
Comment (agheata) [inline geom/geom/src/TVirtualGeoChecker.cxx]:
```suggestion
/// Geometry checker destructor
```

**Review by agheata — APPROVED** [review]
Thanks @linev for this nice decoupling ! Just a few minor `painter` leftovers in comments.
