### PR TITLE
ACLiC: enable O *and* g

### LINKED ISSUE #7377: In CompileMacro, the "g" option disables optimizations
- [X] Checked for duplicates

### Describe the bug

Calling `CompileMacro("macro.C", "gO")` only adds debug flags, not optimization flags. This is surprising as it is not the behavior of compilers (passing both `-g` and `-O2` is fine) and the lack of optimization is completely invisible to most users.

### Expected behavior

Compilers allow debug and optimization flags leaving side by side without issues, `CompileMacro` should do the same.  

### To Reproduce

Calling `CompileMacro("macro.C", "fO")` with a high enough `gDebug` value shows the problem.

### Additional context

I found an [old jira ticket](https://sft.its.cern.ch/jira/browse/ROOT-5803) where @pcanal suggests to use this behavior as a feature, explicitly passing "g" to disable optimizations in a case where they were not desired.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Fixes #7377

### CODE REVIEW

**Review by eguiraud — APPROVED** [review]
LGTM, I guess testing this is pretty complicated.

@pcanal [has suggested](https://sft.its.cern.ch/jira/browse/ROOT-5803) leveraging the old behavior to disable optimizations before, so I would wait for his ok before merging.

EDIT: just to be clear, I am convinced the old behavior is a bug

File: core/base/src/TSystem.cxx [hunk 1]
```diff
@@ -2865,9 +2865,9 @@ int TSystem::CompileMacro(const char *filename, Option_t *opt,
    if (mode==kDefault) {
       TString rootbuild = ROOTBUILD;
       if (rootbuild.Index("debug",0,TString::kIgnoreCase)==kNPOS) {
-         mode=kOpt;
+         mode |= kOpt;
```
Comment (pcanal) [inline core/base/src/TSystem.cxx:2868]: In this section mode is zero (kDefault) so the new code is strictly equivalent to the old code just ... more confusing.

Comment (eguiraud) [reply core/base/src/TSystem.cxx:2868]: Imho the new version does a good job at expressing that `mode` can (in general) be a combination of values rather than one specific value. `mode=kOpt` will more easily become wrong after refactoring.

**Comment by pcanal** [comment]
> > @pcanal has suggested leveraging the old behavior to disable optimizations before, so I would wait for his ok before merging.
> EDIT: just to be clear, I am convinced the old behavior is a bug

The old behavior was:
```
+g -> -g (and default compiler optimization)
+O -> -O3 (or more exactly the optimization level select at ROOT configuration time)
+gO -> -g  (and default compiler optimization)
+ -> -g or -O3 depending on whether ROOT was build in debug mode ... except that this is broken since the move to CMake :( so actually always -O3
```
The new behavior seems to be:
```
+g -> -g (and default compiler optimization)
+O -> -O3 (or more exactly the optimization level select at ROOT configuration time)
+gO -> -g  -O3 
+ -> -g or -O3 depending on whether ROOT was build in debug mode ... except that this is broken since the move to CMake :( so actually always -O3
```
So this is fine as we **MUST** have a way to completely disable optimization.

File: core/base/src/TSystem.cxx (hunk 1 above)
Comment (pcanal) [reply core/base/src/TSystem.cxx:2868]: Except that *unless* you go back and look at the value of kDefault, the reader of *this* portion of the code can be distracted in thinking that *here* it is a combination while *here* it is actually *explicitly* an exact assignment (knowing that the two are here the same requires more thought and searches through the header file)

Comment (Axel-Naumann) [reply core/base/src/TSystem.cxx]: Agreed!

**Comment by Axel-Naumann** [comment]
I can only test this once we chop `CompileMacro` in testable pieces. I tried that once in the distant past, I'm not ready to do it again just yet (🐰 🕳️ )
