### PR TITLE
[ntuple] RField: resolve typedefs to the underlying type

### LINKED ISSUE #9202: [ntuple] Members of an aliased type do not resolve to the underlying type
- [X] Checked for duplicates
### Describe the bug
```c++
namespace SG { typedef uint32_t sgkey_t; }
class X {  SG::sgkey_t  sgkey = 123; };
```

Produces the same error: "Field sgkey has unknown type SG::sgkey_t"

Cheers, Marcin.

### Setup
Using ROOT from `master` branch.

### PR DESCRIPTION
**Pull request by jalopezg-r00t**
This pull-request modifies the implementation of RField `GetNormalizedType()` to resolve typedefs via `TClassEdit::ResolveTypedef()`.

## Changes or fixes:
- GetNormalizedType: use `TClassEdit::ResolveTypedef()` to resolve type aliases.
- GetNormalizedType: move to a type translation map.

## Checklist:
- [x] tested changes locally

This PR fixes #9202.

### CODE REVIEW

**Comment by jalopezg-r00t** [comment]
@phsft-bot build just on mac1015/python3

File: tree/ntuple/v7/src/RField.cxx [hunk 1]
```diff
@@ -75,34 +113,14 @@ std::vector<std::string> TokenizeTypeList(std::string templateType) {
...
-   if (normalizedType == "string") normalizedType = "std::string";
+   std::string normalizedType(
+      TClassEdit::ResolveTypedef(TClassEdit::CleanType(typeName.c_str(),
+                                                       /*mode=*/2).c_str()));
+
+   auto translatedType = typeTranslationMap.find(normalizedType);
+   if (translatedType != typeTranslationMap.end())
+      normalizedType = translatedType->second;
+
    if (normalizedType.substr(0, 7) == "vector<") normalizedType = "std::" + normalizedType;
```
Comment (pcanal) [inline tree/ntuple/v7/src/RField.cxx:124]: Note that this is probably not enough (case of nested vector).  You could try to use `TClassEdit::InsertStd`.

**Review by pcanal — APPROVED** [review]

File: tree/ntuple/v7/src/RField.cxx (hunk 1 above)
Comment (jalopezg-r00t) [reply tree/ntuple/v7/src/RField.cxx:124]: Thanks for the review, @pcanal!

I think we can leave it as-is, given that this function is executed once per created RField, i.e. for a `vector<vector<int>>`, it will run once for the outer type turning it into `std::vector<...>`, once for the inner vector turning it into `std::vector<int>`, and once for `int`, turning it into `std::int32_t`.
