### PR TITLE
[DF]  Remove SaveGraph static members; Add SaveGraph tutorials

### LINKED ISSUE #9145: [DF] Various improvements in SaveGraph
[SaveGraph](https://root.cern/doc/master/namespaceROOT_1_1RDF.html#ac06a36e745255fb8744b1e0a563074c9) would benefit from the following improvements:

- [ ] usage of static variables should be removed, in order to make `SaveGraph` safe to be called concurrently from multiple threads
- [ ] a tutorial should be added, and an example usage should be included in the docs in the reference guide
- [ ] the information contained in some nodes could be made more helpful, e.g. `Histo1D` nodes could display the names of the columns used for filling the histogram and/or the name of the histogram produced

### Additional context

Related old jira tickets:
- https://sft.its.cern.ch/jira/browse/ROOT-11023 (this is the original issue regarding the usage of statics in the implementation of SaveGraph)
- https://sft.its.cern.ch/jira/browse/ROOT-9721 (this contains a draft tutorial and an old SaveGraph bug report)

### PR DESCRIPTION
**Pull request by ikabadzhov**
# This Pull request:
[DF] Added SaveGraph Tutorials
[DF] Remove static members from SaveGraph (Apply improvements from #9145)

## Changes or fixes:

Removed the static GraphNode id initializer (relevant for SaveGraph).

Removed static maps, which were used to check if a define/filter/range node were already on the computation graph.
Solution is to pass a (non-static) map, which is created at each call of SaveGraph. The visited map is now only one and has signature `std::unordered_map<void *, std::shared_ptr<GraphNode>>` - in this manner, different type of nodes can use the same map.

The size of the map of visited nodes is used to assign unique ids. Now, also the action nodes are in the visited map.

Moreover, some friend methods are now redundant.

Tests were adapted accordingly.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #9145

### CODE REVIEW

File: tutorials/dataframe/df034_SaveGraph.C [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+   ROOT::RDF::RResultPtr<unsigned long long> branch2_2 = branch2.Count();
+
+   /*
+   First, some RDataFrame computation graph is created with Defines, Filters and methods (such as Mean, Count, etc.).
+
+   After that SaveGraph can be called either on the RDataFrame, or alternatively on a specific branch.
+   Moreover, if SaveGraph is called with 1 argument it simply returns a string.
+   And if SaveGraph is called with 2 argument, then it write to a file (passed as the second argument).
+   */
```
Comment (eguiraud) [inline tutorials/dataframe/df034_SaveGraph.C:37]: Move this comment at the beginning of main, otherwise the reader will have no idea what's going on until they reach this point.

```suggestion
   /*
   First, a RDataFrame computation graph is created with Defines, Filters and methods (such as Mean, Count, etc.).

   After that, SaveGraph can be called either on the root RDataFrame object or on a specific node of the computation graph: in the first case, the graph returned will span the full computation graph, in the second case it will show only the branch of the computation graph that the node belongs to.
   
   If a filename is passed as second argument, the graph is saved to that file, otherwise it is returned as a string.
   */
```

File: tutorials/dataframe/df034_SaveGraph.C [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+   ROOT::RDF::SaveGraph(rd1, "macro1.dot");
+   gSystem->Exec("dot -Tpng macro1.dot -o macro1.png");
+   /* Independently of SaveGraph, we can convert the produced .dot file to corresponding .png. */
```
Comment (eguiraud) [inline tutorials/dataframe/df034_SaveGraph.C:41]:
```suggestion
   ROOT::RDF::SaveGraph(rd1, /*output_file=*/"rdf_savegraph_tutorial.dot");
   // SaveGraph produces content in the standard DOT file format (https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29):
   // it can be converted to e.g. an image file using standard tools such as the `dot` CLI program.
   gSystem->Exec("dot -Tpng rdf_savegraph_tutorial.dot -o rdf_savegraph_tutorial.png");
```

File: tutorials/dataframe/df034_SaveGraph.py [hunk 3]
```diff
@@ -0,0 +1,44 @@
+'''
+Use SaveGraph to inspect the sequence of RDataFrame actions.
+
+The tutorial shows how to use SaveGraph action.
+'''
```
Comment (eguiraud) [inline tutorials/dataframe/df034_SaveGraph.py:5]: Tutorials need a header with a bit more structure, see e.g. df001_introduction.py for an example

File: tutorials/dataframe/df034_SaveGraph.py [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+branch2_2 = branch2.Count()
+
+'''
+First, some RDataFrame computation graph is created with Defines, Filters and methods (such as Mean, Count, etc.).
+
+After that SaveGraph can be called either on the RDataFrame, or alternatively on a specific branch.
+Moreover, if SaveGraph is called with 1 argument it simply returns a string.
+And if SaveGraph is called with 2 argument, then it write to a file (passed as the second argument).
+'''
```
Comment (eguiraud) [inline tutorials/dataframe/df034_SaveGraph.py:41]: move this above the code, apply same suggestions as for the C++ version

File: tutorials/dataframe/df034_SaveGraph.py [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+
+print(ROOT.RDF.SaveGraph(branch1_1))
+ROOT.RDF.SaveGraph(rd1, "exampleGraph.dot")
```
Comment (eguiraud) [inline tutorials/dataframe/df034_SaveGraph.py:44]: newline missing at the end of the file

**Review by eguiraud — CHANGES_REQUESTED** [review]
Alright, the approach and the logic is correct!

I see that you went with the idea of using the size of the `fVisitedMap` for the counters rather than removing all the counter logic and taking care of it only later in `FromGraphLeafToDot`. That's ok, but then please also add the `RLoopManager` to the map -- this has two benefits:
- nodes with id 0 won't appear multiple times in the output dotfile as it happens now 
- we don't need to "remember" to manually set the RLoopManager's counter to 0

See some more comments inline.

File: tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx [hunk 6]
```diff
@@ -35,20 +35,7 @@ class RRangeBase;
...
 namespace RDF {
 class RColumnRegister;
-
 namespace GraphDrawing {
-std::shared_ptr<GraphNode>
-CreateDefineNode(const std::string &columnName, const ROOT::Detail::RDF::RDefineBase *columnPtr);
-
-std::shared_ptr<GraphNode> CreateFilterNode(const ROOT::Detail::RDF::RFilterBase *filterPtr);
-
-std::shared_ptr<GraphNode> CreateRangeNode(const ROOT::Detail::RDF::RRangeBase *rangePtr);
```
[the remark this answers is not in the document]
Comment (ikabadzhov) [reply tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx:45]: `CreateDefineNode` was previously needed because of the friend on line 72 in the same file.

Currently `CreateDefineNode` is only defined (once) and only called (once) in `dataframe/src/RDFGraphUtils.cxx`.

It is the similar case for the other Creates as well.

[the remark this answers is not in the document]
Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx:45]: Right, `CreateDefineNode` is only needed in `RDFGraphUtils.cxx`. Then it needs to go in an anonymous namespace and be made static, to mark it as something that we only expect to call from that same translation unit.

`CreateFilterNode` and `CreateRangeNode` are called from `RFilter.hxx` and `RRange.hxx` respectively, if I read correctly.

[the remark this answers is not in the document]
Comment (ikabadzhov) [reply tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx:45]: For `CreateFilterNode`: It is declared in `RFilter.hxx` and there is some method (GetGraph) that is calling `RFilter` in  `RFilter.hxx`.
Note that `RFilter` is already declared in `namespace GraphDrawing`.

The actual implementation of `RFilter.hxx` is in `RDFGraphUtils.cxx`, which is again in the same namespace and implements the function as declared in `RFilter.hxx`.

The case of `CreateRangeNode` is very similar.

I am not seeing the need of the declarations inside `GraphUtils.hxx`.

Moreover,  I just recompiled with "wrong declarations" in `GraphUtils.hxx`, i.e. not including the `fVisitedMap` as argument (other declarations have it); and all tests are passing.

[the remark this answers is not in the document]
Comment (eguiraud) [reply tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx:45]: > I am not seeing the need of the declarations inside GraphUtils.hxx.

`CreateFilterNode` and `CreateRangeNode` are functions defined in this section of the source code that are used by other sections of the source code. As such, they need a declaration in the corresponding header. It's good practice and anyway it's how the rest of our code is written.

The fact that `RFilter.hxx` and `RRange.hxx` prefer to forward-declare the functions rather than include the corresponding header does not change that.

The fact that wrong declarations in `GraphUtils.hxx` do not lead to a compilation error points to a separate problem: definitions of free functions in the `.cxx` file should have the form:

```cpp
std::shared_ptr<GraphNode> GraphDrawing::CreateDefineNode
```
rather than
```cpp
namespace GraphDrawing {
std::shared_ptr<GraphNode> CreateDefineNode
}
```

(but fixing this is out of the scope of this PR)

**Review by eguiraud — APPROVED** [review]
LGTM, thank you very much @ikabadzhov ! :rocket:
