### PR TITLE
[Math] Change TRandom::Poisson to return a ULong64_t

### LINKED ISSUE #6927: Overflow in TRandom::Poisson
`TRandom::Poisson(double mu)` returns an 32 bit integer.
When passing a value `mu>=int_max` (i.e. ~ 2.E9) it returns -2147483648. Also this happens when my is a NaN. 
This can create confusions. 
I think an error message should be produced such that users needs to take actions and protect it. 
In addition one the function return value could be changed from int to unsigned long 

To reproduce: 

```
cout << gRandom->Poisson(1.E10) << endl;
cout << gRandom->Poisson(TMath::QuietNaN()) << endl;
```

### PR DESCRIPTION
**Pull request by dpnrlz**
Add error message for overflow in converting double to ULong64_t

## Changes or fixes:
This routine returns now an unsigned 64 bit integer
For large values, larger than 1.84e+19, we print an error message
advising to use the Trandom::PoissonD for such large values,
and return the max value UINT64_MAX

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #6927

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build

File: math/mathcore/src/TRandom.cxx [hunk 1]
```diff
@@ -434,12 +437,17 @@ Int_t TRandom::Poisson(Double_t mean)
          t = 0.9*(1.0 + y*y)* TMath::Exp(em*alxm - TMath::LnGamma(em + 1.0) - g);
       } while( Rndm() > t );
 
-      return static_cast<Int_t> (em);
+      return static_cast<ULong64_t> (em);
 
    }
    else {
       // use Gaussian approximation vor very large values
```
Comment (ferdymercury) [inline math/mathcore/src/TRandom.cxx:444]:
```suggestion
      // use Gaussian approximation for very large values
```

**Comment by lmoneta** [comment]
phsft-bot build on ROOT-ubuntu2204/nortcxxmod

**Review by lmoneta — APPROVED** [review]
LGTM!
