### PR TITLE
[ntuple] allow for writing into TFile subdir

### LINKED ISSUE #14007: Cannot create a RNtuple into a TDirectory
### Check duplicate issues.

- [x] Checked for duplicates

### Description

I am naively trying to create a RNTuple inside a TDirectory, and I fail to do so. Moreover, when looking at the produced TFile with TBrowser, I see some weird recursive structure.

image

### Reproducer

I tried a few permutations of the following, all giving me weird results.

```C++
#include <TFile.h>
#include <TTree.h>
#include <TDirectory.h>
#include <ROOT/RNTuple.hxx>
#include <ROOT/RNTupleModel.hxx>
#undef NDEBUG
#include <cassert>

int writeTree()
{
  TFile* f;
  int x = 0;
  f = new TFile("foo.root", "RECREATE");
  auto* dir = f->mkdir("dir");
  dir->cd();
  auto* tree = new TTree("T", "a Tree");
  tree->Branch("x", &x, "x/D");
  for (int i = 0; i < 10; i++) {
    x = i;
    tree->Fill();
  }
  tree->Write();

  using namespace ROOT::Experimental;
  // Create and fill an RNTuple
  auto model = RNTupleModel::Create();
  auto wrPt = model->MakeField<float>("pt", 42.0);

  {
    RNTupleWriteOptions options;
    options.SetContainerFormat(ENTupleContainerFormat::kBare);
    auto* bar = f->mkdir("bar");
    bar->cd();
    
    auto ntuple = RNTupleWriter::Append(std::move(model), "f", *f, options);
    bool ok = bar->cd();

    ntuple->Fill();
    ntuple->CommitCluster();
    *wrPt = 24.0;
    ntuple->Fill();
    *wrPt = 12.0;
    ntuple->Fill();
    ntuple->CommitCluster();
  }

  return 0;
}
```

### ROOT version
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/04                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on Nov 01 2023, 10:33:00                   |
  | From tags/v6-28-04-alice3@v6-28-04-3-g186ec88ba4                 |
  | With Apple clang version 15.0.0 (clang-1500.0.40.1)              |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```
### Installation method

aliBuild

### Operating system

macOS Ventura

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jblomer**
With the patch, `RNTupleWriter::Append()` can take a sub directory in a TFile. On the reading side, the RNTupleReader understands a ntuple name of the form `[/]foo/bar/ntpl` and opens it correctly. Opening from the anchor directly anyway worked.

Fixes #14007

### CODE REVIEW

File: tree/ntuple/v7/src/RMiniFile.cxx [hunk 1]
```diff
@@ -1105,12 +1105,27 @@ ROOT::Experimental::Internal::RNTupleFileWriter::Recreate(std::string_view ntupl
...
+
+   return std::make_pair(nameAndDir.substr(0, posLastSlash), nameAndDir.substr(posLastSlash + 1));
+}
+
 std::unique_ptr<ROOT::Experimental::Internal::RNTupleFileWriter>
 ROOT::Experimental::Internal::RNTupleFileWriter::Append(std::string_view ntupleName, TFile &file,
                                                         std::uint64_t maxKeySize)
 {
-   auto writer = std::unique_ptr<RNTupleFileWriter>(new RNTupleFileWriter(ntupleName, maxKeySize));
+   auto [dir, name] = SplitNTupleName(ntupleName);
```
Comment (pcanal) [inline tree/ntuple/v7/src/RMiniFile.cxx:1125]: Note that it would also be nice to have:
```
ROOT::Experimental::Internal::RNTupleFileWriter::Append(std::string_view ntupleName, TDIrectory &dir,
                                                        std::uint64_t maxKeySize) 
{
     if (!dir.GetFile())
        throw "We need a file";
   auto writer = std::unique_ptr<RNTupleFileWriter>(new RNTupleFileWriter(name, maxKeySize));
   writer->fFileProper.fFile = dir->GetFile();
   writer->fFileProper.fDirectory = &dir; 
```
(oups the type of `fDirectory` is wrong.

File: tree/ntuple/v7/inc/ROOT/RMiniFile.hxx [hunk 2]
```diff
@@ -104,6 +104,7 @@ class RNTupleFileWriter {
 private:
    struct RFileProper {
       TFile *fFile = nullptr;
+      std::string fDirectory;
```
Comment (pcanal) [inline tree/ntuple/v7/inc/ROOT/RMiniFile.hxx:107]: Either
```suggestion
      TDirectory* fDirectory;
```
or
```suggestion
      std::string fDirectoryPath;
```

**Comment by jblomer** [comment]
@pcanal for the `RBlob` keys of the ntuple within a directory, the current code sets their parent to `kBEGIN`. This imitates what TTree does for the `TBasket` keys of a tree in a sub directory. Is this the expected behavior or should the parent of the `RBlob` / `TBasket` keys be rather the directory into which the tree/ntuple is stored?

File: tree/ntuple/v7/inc/ROOT/RMiniFile.hxx [hunk 3]
```diff
@@ -107,7 +114,10 @@ public:
 
 private:
    struct RFileProper {
+      /// If fDirectory is set, fFile is equal to fDirectory->GetFile()
       TFile *fFile = nullptr;
```
Comment (silverweed) [inline tree/ntuple/v7/inc/ROOT/RMiniFile.hxx:118]: Why do we need this? Can't we use `fDirectory` in either case?

Comment (jblomer) [reply tree/ntuple/v7/inc/ROOT/RMiniFile.hxx:118]: `TFile` has some file specific methods that we need, such as `Seek()` and `WriteBuffer()`.

Comment (jblomer) [reply tree/ntuple/v7/inc/ROOT/RMiniFile.hxx]: Ah, yes that makes sense.

File: tree/ntuple/v7/src/RNTupleWriter.cxx [hunk 4]
```diff
@@ -92,14 +92,20 @@ ROOT::Experimental::RNTupleWriter::Recreate(std::initializer_list<std::pair<std:
...
+   auto file = fileOrDirectory.GetFile();
+   if (!file) {
+      throw RException(R__FAIL("RNTupleWriter only supports writing to a ROOT file. Cannot write into a directory "
+                               "that is not backed by a file"));
+   }
+   if (!file->IsBinary()) {
       throw RException(R__FAIL("RNTupleWriter only supports writing to a ROOT file. Cannot write into " +
-                               std::string(file.GetName())));
+                               std::string(file->GetName())));
+   }
```
Comment (hahnjo) [inline tree/ntuple/v7/src/RNTupleWriter.cxx:106]: unrelated to this PR, but we should probably have the same checks in `RNTupleParallelWriter::Append`...

**Review by hahnjo — COMMENTED** [review]
In principle this LGTM, but it creates a bit of an asymmetry between reading and writing: Why do we need to support reading with the recursive directory traversal? Maybe we can just require the user to get the RNTuple anchor from the subdirectory?

**Comment by jblomer** [comment]
> In principle this LGTM, but it creates a bit of an asymmetry between reading and writing: Why do we need to support reading with the recursive directory traversal? Maybe we can just require the user to get the RNTuple anchor from the subdirectory?

This is true, but we need the string-based API for RDataFrame. In the end, I'm not sure if the symmetry gap is an issue.

**Review by hahnjo — APPROVED** [review]
> This is true, but we need the string-based API for RDataFrame.

Oh, and also the `RNTupleProcessor`!

LGTM, I can take care of the `RNTupleParallelWriter` in a follow-up PR.
