### PR TITLE
[ntuple] Fix field construction for friends

### LINKED ISSUE #14748: [ntuple] `Show` and `PrintInfo` does not work for friend RNTuples
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Calling `Show` on an RNTupleReader that contains friends raises the following exception:
```
no type name specified for Field ntpl1 (unchecked RResult access!)
At:
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&, const std::string&) [/home/florine/cern/root/src/tree/ntuple/v7/src/RField.cxx:493]
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&) [/home/florine/cern/root/src/tree/ntuple/v7/src/RField.cxx:485]
```

The reason for this is that RNTuple friends are (virtually) represented as untyped record fields. One solution could be to create an artificial `RRecordField` to bind the fields to, in a similar fashion to what is done here: https://github.com/root-project/root/blob/f3fc75b2078cec442c0f6060d2bfd4e86cf83b06/tree/ntuple/v7/src/RNTupleDescriptor.cxx#L65-L77

With the reproducer below this would result in the following:
``` 
// Show
{
  "ntpl1": {
    "foo": 3.14
  },
  "ntpl2": {
    "bar": 2.72
  }
}

// PrintInfo
************************************ NTUPLE ************************************
* N-Tuple : _friends                                                           *
* Entries : 10                                                                 *
********************************************************************************
* Field 1       : ntuple1                                                      *
*   Field 1.1   : x (std::int32_t)                                             *
* Field 2       : ntuple2                                                      *
*   Field 2.1   : y (std::int32_t)                                             *
********************************************************************************
```
As a quick fix this is fine, but it might be nicer to have a representation that better respects the meaning of befriended RNTuples.

### Reproducer

```cpp
void show_friends() {
   {
      auto model = RNTupleModel::Create();
      auto foo = model->MakeField<float>("foo");
      auto writer = RNTupleWriter::Recreate(std::move(model), "ntpl1", "ntpl1.root");
      *foo = 3.14;
      writer->Fill();
   }
   {
      auto model = RNTupleModel::Create();
      auto bar = model->MakeField<float>("bar");
      auto writer = RNTupleWriter::Recreate(std::move(model), "ntpl2", "ntpl2.root");
      *bar = 2.72;
      writer->Fill();
   }

   std::vector<RNTupleReader::ROpenSpec> friends = {{"ntpl1", "ntpl1.root"},
                                                    {"ntpl2", "ntpl2.root"}};
   auto ntuple = RNTupleReader::OpenFriends(friends);
   ntuple->Show(0);
   // same for ntuple->PrintInfo();
}
```

### ROOT version

any

### Installation method

any

### Operating system

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by enirolf**
This PR for now fixes #14748, but IMO down the line we might need a more tailored representation for friends (at least in how they are presented to the user).

Friends are (virtually) represented as untyped records. To properly create them as fields (neede e.g. for `Show` and `PrintInfo`), we artificially bind them to an untyped `RRecordField`.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

File: tree/ntuple/v7/src/RNTupleDescriptor.cxx [hunk 1]
```diff
@@ -62,18 +62,26 @@ ROOT::Experimental::RFieldDescriptor::Clone() const
...
-      auto recordField = std::make_unique<RRecordField>("_0", memberFields);
-      auto collectionField = std::make_unique<RVectorField>(GetFieldName(), std::move(recordField));
-      collectionField->SetOnDiskId(fFieldId);
-      return collectionField;
+      if (GetStructure() == ENTupleStructure::kRecord) {
+         auto recordField = std::make_unique<RRecordField>(GetFieldName(), memberFields);
+         recordField->SetOnDiskId(fFieldId);
+         return recordField;
+      }
+      if (GetStructure() == ENTupleStructure::kCollection) {
```
Comment (jblomer) [inline tree/ntuple/v7/src/RNTupleDescriptor.cxx:79]: else if

File: tree/ntuple/v7/src/RNTupleDescriptor.cxx [hunk 2]
```diff
@@ -62,18 +62,26 @@ ROOT::Experimental::RFieldDescriptor::Clone() const
...
+         auto recordField = std::make_unique<RRecordField>("_0", memberFields);
+         auto collectionField = std::make_unique<RVectorField>(GetFieldName(), std::move(recordField));
+         collectionField->SetOnDiskId(fFieldId);
+         return collectionField;
+      }
```
Comment (jblomer) [inline tree/ntuple/v7/src/RNTupleDescriptor.cxx:84]: else: warn? or throw exception?

**Review by jblomer — APPROVED** [review]
In principle LGTM, we can consider a stricter check when the type name is empty.
