### PR TITLE
[math][fit] Fix Fitter class for temporary FitData (issue #11154)

### LINKED ISSUE #11154: [math][fit] FitResult is empty or corrupted after FitData class is deleted
As shown in the code attached in https://root-forum.cern.ch/t/error-on-fitresult-scan/51014
one cannot use FitResult::Scan when the Fitter class has been deleted.

### PR DESCRIPTION
**Pull request by lmoneta**
# This Pull request:

This PR implements the correct copy constructors for the FitData classes and, when the user provides to teh Fitter, a reference to a Fit data classes, the data are copied. 
An interface using a `shared_ptr` to the data exists to avoid copying. 

This PR fixes #11154

### CODE REVIEW

File: math/mathcore/inc/Fit/BinData.h [hunk 1]
```diff
@@ -243,10 +253,12 @@ public :
 
       if ( fErrorType == kNoError )
          return nullptr;
-      // assert( fErrorType == kCoordError );
       return &fDataErrorPtr[ ipoint ];
    }
 
+   /// Return the error on the given point.
+   /// Safer method returing in any case the error and not the inverse as in the
+   /// function above.
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/BinData.h:261]:
```
   /// Return the error on the given point.
   /// Safer method returning in any case the error and not the inverse as in the
   /// function above.
```

File: math/mathcore/inc/Fit/BinData.h [hunk 2]
```diff
@@ -243,10 +253,12 @@ public :
 
       if ( fErrorType == kNoError )
          return nullptr;
-      // assert( fErrorType == kCoordError );
       return &fDataErrorPtr[ ipoint ];
    }
 
+   /// Return the error on the given point.
+   /// Safer method returing in any case the error and not the inverse as in the
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/BinData.h:260]:
```suggestion
   /// Safer method returning in any case the error and not the inverse as in the
```

File: math/mathcore/inc/Fit/BinData.h [hunk 3]
```diff
@@ -109,20 +109,24 @@ public :
...
    /**
-      preallocate a data set with given size ,  dimension and error type (to get the full point size)
-      If the data set already exists and it is having the compatible point size space for the new points
-      is created in the data sets, while if not compatible the old data are erased and new space of
-      new size is allocated.
-      (i.e if exists initialize is equivalent to a resize( NPoints() + maxpoints)
+      Preallocate a data set with given size ,  dimension and error type.
+      If the data set already exists newPoints are appended to the existing dataset.
+      (i.e if the data exists Initialize is equivalent to a resize( NPoints() + maxpoints).
+      Initialize and Append are equivalent.
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/BinData.h:120]:
```suggestion
      Preallocate a dataset with given size,  dimension and error type.
      If the dataset already exists, `newPoints` are appended to the existing dataset
      (i.e., if the data exists, Initialize() is equivalent to a `resize( NPoints() + maxpoints )`).
      Initialize() and Append() are equivalent.
```
Id suggest to write `dataset` consistently, improve punctuation and referencing functions such that doxygen can recognize it

File: math/mathcore/inc/Fit/BinData.h [hunk 4]
```diff
@@ -109,20 +109,24 @@ public :
...
    */
+   void Initialize( unsigned int newPoints, unsigned int dim = 1, ErrorType err = kValueError ){
+      Append(newPoints,dim,err);
+   }
 
+   /// Equivalent to Initialize
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/BinData.h:126]:
```suggestion
   /// Equivalent to Initialize().
```
I think that is necessary for doxygen to make the link, but I'm not 100 % sure

File: math/mathcore/inc/Fit/BinData.h [hunk 5]
```diff
@@ -231,9 +235,15 @@ public :
...
-      return error on the value for the given fit point
-      Safe (but slower) method returning correctly the error on the value
-      in case of asymm errors return the average 0.5(eu + el)
+      Return a pointer to the error (or the inverse error) on the value for a given point
+      depending on the type of data.
+      - If the data contains only value error (e.g. from histograms) returns a pointer to
+        the inverse of the errors.
+      - If the data contains errors in coordinates and value (e.g from TGraphErrors) returns a
+        pointer to the corresponding value error (NOT the inverse).
+      - If the data contains asymmetric errors return a ponter to the average error (NOT the inverse):
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/BinData.h:244]:
```suggestion
      - If the data contains asymmetric errors return a pointer to the average error (NOT the inverse):
```

File: math/mathcore/inc/Fit/FitData.h [hunk 6]
```diff
@@ -35,7 +35,8 @@ namespace ROOT {
 
    namespace Fit {
 
-      //class used for making shared_ptr of data classes managed by the user (i.e. when we don;t want to delete the contained object)
+      //class used for making shared_ptr of data classes managed by the user
+      // (i.e. when we don't want to delete the contained object)
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/FitData.h:39]:
```suggestion
      // Class used for making shared_ptr of data classes managed by the user
      // (i.e. when we don't want to delete the contained object).
```

File: math/mathcore/src/SparseData.cxx [hunk 7]
```diff
@@ -193,28 +192,39 @@ namespace ROOT {
...
-      { delete fList; }
+      SparseData::SparseData(const SparseData & rhs) :
+         FitData(rhs)
+      {
+         fList = std::make_unique<ProxyListBox>(*rhs.fList);
+      }
+      SparseData & SparseData::operator=(const SparseData & rhs)
+      {
+         FitData::operator=( rhs );
+         fList.reset(new ProxyListBox(*rhs.fList));
```
Comment (guitargeek) [inline math/mathcore/src/SparseData.cxx:223]:
```suggestion
         fList = std::make_unique<ProxyListBox>(*rhs.fList);
```
I think like in the other changes you made, `make_unique` should be preferred to not have the explicit `new`.

File: math/mathcore/inc/Fit/SparseData.h [hunk 8]
```diff
@@ -23,42 +24,56 @@ namespace ROOT {
...
 
-         // Debug method to print the list of bins stored
+         /// Debug method to print the list of bins stored
          void PrintList() const;
 
-         // Transforms the data into a ROOT::Fit::BinData structure
+         /// Transforms the data into a ROOT::Fit::BinData structure
          void GetBinData(BinData&) const;
-         // Same as before, but with integral format
+         /// Same as before, but returning a BInData with integral format (containing bin edges)
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/SparseData.h:70]:
```suggestion
         /// Same as before, but returning a BinData with integral format (containing bin edges)
```

File: math/mathcore/inc/Fit/SparseData.h [hunk 9]
```diff
@@ -23,42 +24,56 @@ namespace ROOT {
...
 
-         //Constructor with a dimension and two arrays
+         /// Constructor with a dimension and two arrays
          SparseData(const unsigned int dim, double min[], double max[]);
 
-         //Destructor
+         /// Copy constructor
+         SparseData(const SparseData & rhs);
+
+         /// Destructor
```
Comment (guitargeek) [inline math/mathcore/inc/Fit/SparseData.h:46]:
```suggestion
         /// Destructor
```
The destructor is now empty, you could get rid of it

Comment (lmoneta) [reply math/mathcore/inc/Fit/SparseData.h:46]: Actually this is needed in order to forward declare ProxyListBox.

**Comment by lmoneta** [comment]
@guitargeek thank you for the comments. 
The PR is updated now!

File: math/mathcore/inc/Fit/SparseData.h (hunk 9 above)
Comment (guitargeek) [reply math/mathcore/inc/Fit/SparseData.h:46]: Okay!

**Review by guitargeek — APPROVED** [review]
LGTM, thanks for addressing the review comments!
