### PR TITLE
[ntuple] fix type names with [U]Long64_t template args

### LINKED ISSUE #20282: [ntuple] use meta normalized name for streamer info records
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

The different in integer handling between ROOT Meta and RNTuple can result in missing dictionaries when the streamer info records are written, as reported in https://github.com/cms-sw/cmssw/issues/49298

RNTuple should use the ROOT Meta normalized spelling when creating streamer info records.

### Reproducer

https://github.com/cms-sw/cmssw/issues/49298

### ROOT version

master

### Installation method

from sources

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jblomer**
Custom classes with [U]Long64_t template arguments need to use their
meta-normalized name as type alias. Otherwise, during reconstruction
with the RNTuple normalized name, the streamer info for the
`std::[u]int64_t` argument will be requested (typically `long`
instead of `long long`).

Fixes #20282

### CODE REVIEW

File: tree/ntuple/src/RFieldUtils.cxx [hunk 1]
```diff
@@ -531,6 +532,39 @@ std::string ROOT::Internal::GetRenormalizedTypeName(const std::string &metaNorma
    return GetRenormalizedMetaTypeName(metaNormalizedName);
 }
 
+bool ROOT::Internal::NeedsMetaNameAsAlias(const std::string &metaNormalizedName, std::string &renormalizedAlias)
```
Comment (pcanal) [inline tree/ntuple/src/RFieldUtils.cxx]: This seems similar to (but better than): `TClassEdit::GetLong64_Name`, isn't it?

File: tree/ntuple/test/ntuple_type_name.cxx [hunk 2]
```diff
@@ -380,3 +380,19 @@ TEST(RNTuple, ContextDependentTypeNames)
...
+   std::string renormalizedAlias;
+   EXPECT_FALSE(NeedsMetaNameAsAlias("bool", renormalizedAlias));
+   EXPECT_FALSE(NeedsMetaNameAsAlias("std::vector<long>", renormalizedAlias));
+   EXPECT_FALSE(NeedsMetaNameAsAlias("std::vector<Long64_t>", renormalizedAlias));
+   EXPECT_TRUE(NeedsMetaNameAsAlias("::MyClass<Long64_t>", renormalizedAlias));
+   EXPECT_EQ("MyClass<Long64_t>", renormalizedAlias);
+   EXPECT_TRUE(NeedsMetaNameAsAlias("MyClass<ULong64_t>", renormalizedAlias));
+   EXPECT_TRUE(NeedsMetaNameAsAlias("std::vector<MyClass<Long64_t> >", renormalizedAlias));
+   EXPECT_EQ("std::vector<MyClass<Long64_t>>", renormalizedAlias);
+   EXPECT_FALSE(NeedsMetaNameAsAlias("MyClass<ROOT::RVec<Long64_t>>", renormalizedAlias));
```
Comment (pcanal) [inline tree/ntuple/test/ntuple_type_name.cxx]: We should also test `map`, i.e. when the `long long` is the second or third argument.  We should also test when the argument is nested (eg `EdmWrapper<map<int, UserStruct<something, Long64_t>>>`).

File: tree/ntuple/test/rfield_class.cxx [hunk 3]
```diff
@@ -391,41 +392,56 @@ TEST(RNTuple, TClassMetaName)
...
+      {"std::pair<float, float>", {}, ""},
+      {"std::map<int, float>", {}, ""},
+      {"CustomStruct", {"CustomStruct"}, ""},
+      {"std::vector<CustomStruct>", {"CustomStruct"}, ""},
+      {"std::map<int, CustomStruct>", {"CustomStruct"}, ""},
+      {"DerivedA", {"DerivedA", "CustomStruct"}, ""},
+      {"std::pair<CustomStruct, DerivedA>", {"DerivedA", "CustomStruct"}, ""},
+      {"EdmWrapper<long long>", {"EdmWrapper<Long64_t>"}, "EdmWrapper<Long64_t>"},
+      {"EdmContainer", {"EdmContainer", "EdmWrapper<Long64_t>"}, ""},
+      {"EdmWrapper<long long>::Inner", {"EdmWrapper<Long64_t>::Inner"}, "EdmWrapper<Long64_t>::Inner"},
```
Comment (pcanal) [inline tree/ntuple/test/rfield_class.cxx:427]: Do we also test (besides for `std`) other combination of class template instance and regular class/namespaces? eg. `CL::TP<long long>::CL2`, `CL::CL2::TP<long long>`, etc.

**Review by pcanal — APPROVED** [review]
LGTM

**Review by hahnjo — COMMENTED** [review]
Should this be mentioned in "Type Name Normalization" of `BinaryFormatSpecification.md`?

**Comment by jblomer** [comment]
> Should this be mentioned in "Type Name Normalization" of `BinaryFormatSpecification.md`?

Done in the latest commit

File: tree/ntuple/test/rfield_class.cxx (hunk 3 above)
Comment (jblomer) [reply tree/ntuple/test/rfield_class.cxx:427]: Added a test for these cases to `ntuple_type_name.cxx` (`NeedsMetaNameAsAlias`)

File: tree/ntuple/test/ntuple_type_name.cxx (hunk 2 above)
Comment (jblomer) [reply tree/ntuple/test/ntuple_type_name.cxx]: Added tests and a fix for the `MyClass<std::vector<Long64_t>>` nesting case.

File: tree/ntuple/src/RFieldUtils.cxx (hunk 1 above)
Comment (jblomer) [reply tree/ntuple/src/RFieldUtils.cxx]: Perhaps. This routine goes through the same machinery than the "normal" RNTuple type normalization, just that it fixes up instances of `[U]Long64_t` in template parameters where necessary.

File: tree/ntuple/src/RFieldUtils.cxx [hunk 4]
```diff
@@ -62,7 +62,8 @@ const std::unordered_map<std::string_view, std::string_view> typeTranslationMap{
    {"ULong64_t", "unsigned long long"},
    {"uint64_t", "std::uint64_t"}};
 
-// Natively supported types drop the default template arguments and the CV qualifiers in template arguments.
+// Natively supported types drop the default template arguments and the CV qualifiers in template arguments;
+// the also keep Long64_t as template argument untouched.
 bool IsUserClass(const std::string &typeName)
```
Comment (hahnjo) [inline tree/ntuple/src/RFieldUtils.cxx]: I'm not sure I understand this comment for `IsUserClass`? Should the newly added line be "it also keeps" - but then it / the function is not actually modifying anything?!

File: tree/ntuple/doc/BinaryFormatSpecification.md [hunk 5]
```diff
@@ -1,4 +1,4 @@
-# RNTuple Binary Format Specification 1.0.1.0
+# RNTuple Binary Format Specification 1.0.2.0
```
Comment (hahnjo) [inline tree/ntuple/doc/BinaryFormatSpecification.md]: Hm, is this really a minor increment that "indicates new, optional format features" such as the RNTuple Attributes were? I was expecting a patch increment...

File: tree/ntuple/doc/BinaryFormatSpecification.md [hunk 6]
```diff
@@ -888,6 +888,17 @@ For example, the type name `const pair<size_t, array<class ::Event, 2>>` will be
...
+A noteworthy implementation detail of the ROOT implemetation is the treatment of ROOT typedefs for fundamental types.
+The types `Bool_t`, `Float_t`, `Double_t`, `[U]Char_t`, `[U]Short_t`, `[U]Int_t`, `[U]Long[64]_t`
+are not treated as typedefs but they are directly mapped to the corresponding normalized RNTuple fundamental types.
+An exception is `[U]Long64_t` that appears as a template parameter of a user-defined class,
+either directly or indirectly.
+This case is treated as a normal typedef,
+i.e. the RNTuple alias type will contain the type spelling that uses `[U]Long64_t`.
+For example, the type `MyClass<std::set<Long64_t>>` will be normalized to `MyClass<std::set<std::int64_t>>`
+with a type alias that is equal to the original spelling.
+This treatment is necessary for compatibility betwwen the RNTuple schema and the ROOT streamer info records.
```
Comment (hahnjo) [inline tree/ntuple/doc/BinaryFormatSpecification.md]:
```suggestion
This treatment is necessary for compatibility between the RNTuple schema and the ROOT streamer info records.
```

File: tree/ntuple/doc/BinaryFormatSpecification.md [hunk 7]
```diff
@@ -888,6 +888,17 @@ For example, the type name `const pair<size_t, array<class ::Event, 2>>` will be
 `std::pair<std::uint64_t,std::array<Event,2>>` with an alias type name
 `std::pair<size_t,std::array<Event,2>>`.
 
+A noteworthy implementation detail of the ROOT implemetation is the treatment of ROOT typedefs for fundamental types.
+The types `Bool_t`, `Float_t`, `Double_t`, `[U]Char_t`, `[U]Short_t`, `[U]Int_t`, `[U]Long[64]_t`
+are not treated as typedefs but they are directly mapped to the corresponding normalized RNTuple fundamental types.
+An exception is `[U]Long64_t` that appears as a template parameter of a user-defined class,
```
Comment (hahnjo) [inline tree/ntuple/doc/BinaryFormatSpecification.md:897]: Should we (again) mention `Double32_t` here? It has its own dedicated section, but maybe it's good to spell out that it is also kept in the type alias for template arguments?

File: tree/ntuple/src/RFieldUtils.cxx (hunk 4 above)
Comment (jblomer) [reply tree/ntuple/src/RFieldUtils.cxx]: Clarified

**Comment by makortel** [comment]
Thanks for the fix! Do I understand correctly that with this PR using the `Long64_t` type alias, e.g. `SomeTemplate<Long64_t>`, with `RStreamerField` would work correctly, but if one would use the `long long`, e.g. `SomeTemplate<long long>` directly, that would not work but lead to similar issue we saw earlier (https://github.com/root-project/root/issues/20282 / https://github.com/cms-sw/cmssw/issues/49298)?

(CMS' demangling should result in `Long64_t` in the template arguments in any case, so I'm asking just to understand the subtle details)

**Comment by makortel** [comment]
Would you be (eventually) comfortable in backporting this PR to 6.36?
