### PR TITLE
[tree] Propagate IMT settings of TChain to internal TTrees

### LINKED ISSUE #8720: Apply TChain::SetImplicitMT() to underlying trees
- [X] Checked for duplicates

### Describe the bug
Setting `TChain::SetImplicitMT()` does not apply the setting to the underlying trees.

### Expected behavior
A call to `TChain::SetImplicitMT()` should influence current and future (`TChain::LoadTree`) backing trees.

### Additional context
Discussed in the I/O MM channel.

### PR DESCRIPTION
**Pull request by dpiparo**
Fixes #8720

### CODE REVIEW

File: tree/tree/src/TChain.cxx [hunk 1]
```diff
@@ -1273,6 +1273,22 @@ Int_t TChain::LoadBaskets(Long64_t /*maxmemory*/)
    return 0;
 }
 
+namespace ROOT::Internal::TChain {
+class TTreeIMTSetterRAII {
+private:
+   TTree *&fTree;
```
Comment (vepadulano) [inline tree/tree/src/TChain.cxx:1279]: Why not just?
```
TTree *fTree;
```

File: tree/tree/src/TChain.cxx [hunk 2]
```diff
@@ -1273,6 +1273,22 @@ Int_t TChain::LoadBaskets(Long64_t /*maxmemory*/)
    return 0;
 }
 
+namespace ROOT::Internal::TChain {
```
Comment (vepadulano) [inline tree/tree/src/TChain.cxx:1276]: I don't think we need to declare this namespace here, a simple unnamed namespace suffices

**Review by vepadulano — CHANGES_REQUESTED** [review]
Thanks a lot! See some suggestions

File: tree/tree/src/TChain.cxx (hunk 1 above)
Comment (dpiparo) [reply tree/tree/src/TChain.cxx:1279]: because the value of the fTree variable can change in the body of the method, e.g. here https://github.com/root-project/root/pull/14691/files#diff-3b55a8f62d4fb5deab481fa4caa779a4180e66bc608396c37365d22e567c8501R1535 .

File: tree/tree/src/TChain.cxx (hunk 2 above)
Comment (dpiparo) [reply tree/tree/src/TChain.cxx:1276]: You have a point. The unnamed namespace should also hide the symbol because of the internal linkage. Given that this symbol is effectively useless outside of this translation unit, this seems the right thing to do.

File: tree/tree/test/ImplicitMT.cxx [hunk 3]
```diff
@@ -28,4 +29,33 @@ TEST(TTreeImplicitMT, flushBaskets)
...
+   c.SetImplicitMT(true);
+   c.Add(fname0);
+   c.Add(fname1);
+   c.LoadTree(0);
+   EXPECT_TRUE(c.GetTree()->GetImplicitMT());
+   c.LoadTree(1);
+   EXPECT_TRUE(c.GetTree()->GetImplicitMT());
+
+   gSystem->Unlink(fname0);
+   gSystem->Unlink(fname1);
```
[the remark this answers is not in the document]
Comment (dpiparo) [reply tree/tree/test/ImplicitMT.cxx:58]: I thought about it, to also use it for the other test. But wouldn't it be a convoluted RAII? Note in the second example, the TFile is created in a scope and the file has to exist to be picked up by the TChain. Of course I may not be seeing a potential simplification and am very open to implement any!

File: tree/tree/src/TChain.cxx [hunk 4]
```diff
@@ -1297,6 +1313,10 @@ Int_t TChain::LoadBaskets(Long64_t /*maxmemory*/)
 ///
 Long64_t TChain::LoadTree(Long64_t entry)
 {
+
+   // At exit, if the tree is available, we propagate the IMT setting to it
+   ROOT::Internal::TChain::TTreeIMTSetterRAII treeImtSetterRAAI(fTree, fIMTEnabled);
```
Comment (pcanal) [inline tree/tree/src/TChain.cxx:1318]: Are there more than one update to `fTree` to justify this added complexity? (So far I can only find (original) line 1515.   Alternatively wouldn't a Setter (`void SetLocalTree(TTree *newtree) { fTree = newtree; ... more stuff; };`) be another clearer alternative?

Comment (vepadulano) [reply tree/tree/src/TChain.cxx:1318]: My question here is whether we need to propagate the `fImtEnabled` setting at the beginning of `LoadTree` or at the end. As it stands now, the RAII struct does the equivalent of calling the local setter Philippe proposes just at the end of the function + setting it in any case the function throws an exception. Is this the actual behaviour we want? If the function throws do we need to set the data member?

Comment (pcanal) [reply tree/tree/src/TChain.cxx:1318]: This function is not exception safe as it is.  Even if it was, there will be no point is have the setting done as the exception would theoretically would/should leave `fTree` either unchanged or more likely set to nullptr.

Comment (vepadulano) [reply tree/tree/src/TChain.cxx:1318]: So IIUC you are saying that we could call `fTree->SetImplicitMT` at the end of `LoadTree` without any extra logic around it

**Comment by dpiparo** [comment]
hopefully, all comments addressed. Let's see the tests.

File: tree/tree/src/TChain.cxx [hunk 5]
```diff
@@ -1340,6 +1340,10 @@ Long64_t TChain::LoadTree(Long64_t entry)
       // (the friends of the chain will be updated in the
       // next loop).
       fTree->LoadTree(treeReadEntry);
+
+      // Propagate the IMT settings
+      fTree->SetImplicitMT(fIMTEnabled);
```
Comment (pcanal) [inline tree/tree/src/TChain.cxx:1345]: Humm .. that's an interesting case.  In this case the `TTree` is not 'new' and thus (given the rest of this PR) the only reason that we would have `fTree->fIMTEnabled == fIMTEnabled` would be if the user did:
```
chain->SetImplicitMT(true);
chain->LoadTree(e);
chain->GetTree()->SetImplicitMT(false);
chain->LoadTree(e); (or some other entry).
```
It debatable if after this sequence we should have `chain->GetTree()->fIMTEnabled` equal to true or false.  Either way it sounds like we should document the choice.

**Review by pcanal — CHANGES_REQUESTED** [review]
See comment https://github.com/root-project/root/pull/14691/files#r1556362788

File: tree/tree/test/ImplicitMT.cxx [hunk 6]
```diff
@@ -28,4 +29,32 @@ TEST(TTreeImplicitMT, flushBaskets)
    gSystem->Unlink(ofileName);
 }
 
+//# 8720
+TEST(TChainImplicitMT, propagateToTTree)
+{
+   ROOT::DisableImplicitMT();
+
+   const auto fname0 = "propagateToTTree0.root";
+   const auto fname1 = "propagateToTTree0.root";
```
Comment (pcanal) [inline tree/tree/test/ImplicitMT.cxx:38]: The two filename seem to be the same.  Is that the intent?

Comment (dpiparo) [reply tree/tree/test/ImplicitMT.cxx:38]: no. Fixing.

**Review by pcanal — APPROVED** [review]
