### PR TITLE
I/O Customizaton Rules: add support for changing the input type.

### LINKED ISSUE #17346: I/O Customization rules fails in case of changes in the inputs types.
As seen in https://gist.github.com/pcanal/b5af2762530bef88bbb79b480ee9daa4, there is several issue with the support where the requested type from an I/O customization rules does not match exactly the type of the element in the targeted StreamerInfo.  In particular this makes it harder to write rule to schema evolution collection of enums.

See also https://github.com/root-project/root/pull/17009#issuecomment-2522228598

### PR DESCRIPTION
**Pull request by pcanal**
With these changes, one can request the schema evolution (usually implicit) of the input data members from the on-file type to a custom type.  Example of the changes support in the test  roottest/root/io/evolution/rules/execSourceTypes.cxx added by the [companion roottest PR](https://github.com/root-project/roottest/pull/1247)

This fixes #17346 17346

### CODE REVIEW

File: io/io/src/TStreamerInfo.cxx [hunk 1]
```diff
@@ -253,6 +253,62 @@ namespace {
       TStreamerInfo* fInfo;
    };
 
+   decltype(auto) GetSourceType(ROOT::TSchemaRule::TSources *s)
```
Comment (jblomer) [inline io/io/src/TStreamerInfo.cxx]: Why do we need `decltype(auto)` instead of the spelled out type `std::pair<...>`?

File: io/io/src/TStreamerInfoReadBuffer.cxx [hunk 2]
```diff
@@ -326,15 +326,21 @@ Int_t TStreamerInfo::ReadBufferSkip(TBuffer &b, const T &arr, const TCompInfo *c
...
       // skip Class *  not derived from TObject with comment field  //->
-      case TStreamerInfo::kSkip + TStreamerInfo::kAnyp: {
+      case TStreamerInfo::kSkip + TStreamerInfo::kAnyp:
+      case TStreamerInfo::kSkip + TStreamerInfo::kAnyp + TStreamerInfo::kOffsetL:
+      {
          DOLOOP {
-            b.SkipObjectAny();
+            for (Int_t j=0;j<compinfo->fLength;j++) {
+               b.SkipObjectAny();
+            }
```
Comment (jblomer) [inline io/io/src/TStreamerInfoReadBuffer.cxx:335]: I think this is not tested by https://github.com/root-project/roottest/pull/1247. In this case, can a test be added?

File: io/io/src/TStreamerInfo.cxx [hunk 3]
```diff
@@ -257,13 +257,14 @@ namespace {
    {
       std::string localtypename(s->GetUnderlyingTypeName());
       Int_t ndim = 0;
-      Int_t totaldim = 1;
+      Int_t totaldim = 0;
```
Comment (jblomer) [inline io/io/src/TStreamerInfo.cxx:260]: Perhaps merge this with the commit adding `totaldim`

File: core/meta/src/TClass.cxx [hunk 4]
```diff
@@ -7403,7 +7403,7 @@ void TClass::RemoveStreamerInfo(Int_t slot)
    if (fStreamerInfo->GetSize() >= slot) {
       R__LOCKGUARD(gInterpreterMutex);
       TVirtualStreamerInfo *info = (TVirtualStreamerInfo*)fStreamerInfo->At(slot);
-      fStreamerInfo->RemoveAt(fClassVersion);
+      fStreamerInfo->RemoveAt(slot);
```
[the remark this answers is not in the document]
Comment (pcanal) [reply core/meta/src/TClass.cxx:7471]: Done.

File: io/io/src/TStreamerInfoReadBuffer.cxx (hunk 2 above)
Comment (pcanal) [reply io/io/src/TStreamerInfoReadBuffer.cxx:335]: It is.  See line 49 in  execSourceTypes.cxx in https://github.com/root-project/roottest/pull/1247

File: tree/treeplayer/src/TBranchProxy.cxx [hunk 5]
```diff
@@ -517,13 +517,19 @@ bool ROOT::Detail::TBranchProxy::Setup()
...
+               fMemberOffset = 0;
+            } else if (fMemberOffset == TVirtualStreamerInfo::kMissing) {
+               Error("Setup","%s",Form("Missing data member in a TClonesArray, %s in %s and %s",
+                     fDataMember.Data(), fBranch->GetName(),
+                     bcount ? bcount->GetName() : "unknown"));
+               fMemberOffset = 0;
             }
 
-         } else if (fClass) {
+         } else if (fParent && fClass) {
```
[the remark this answers is not in the document]
Comment (pcanal) [reply tree/treeplayer/src/TBranchProxy.cxx:532]: It is not clear that the code is not even dead code.   Small test seems to show it is not active/useful in any of the tests.

Similarly, the `if (fMemberOffset < 0) {` part is unclear.

File: io/io/src/TStreamerInfo.cxx (hunk 1 above)
Comment (pcanal) [reply io/io/src/TStreamerInfo.cxx]: To avoid redundant typing of the types.  For example, this function started with 2 return values (in this commit )  and grew to 5 later on without having to change this line.  Since this in an internal routine, I think it is fine to keep it opaque.

File: tree/treeplayer/src/TBranchProxy.cxx (hunk 5 above)
[the remark this answers is not in the document]
Comment (pcanal) [reply tree/treeplayer/src/TBranchProxy.cxx:532]: I will move the investigation in a separate stream/pr, for now it is record at https://gist.github.com/pcanal/3bf0224cd1caa24a3c62f459d00ef9a9

**Review by dpiparo — APPROVED** [review]

File: core/meta/src/TClass.cxx [hunk 6]
```diff
@@ -3593,23 +3593,19 @@ TRealData* TClass::GetRealData(const char* name) const
...
+   TObjLink* lnk = fRealData->FirstLink();
+   while (lnk) {
+      TObject* obj = lnk->GetObject();
+      std::string objName(obj->GetName());
+      std::string::size_type pos = objName.find_first_of("[");
+      if (pos != std::string::npos) {
+         objName.erase(pos);
       }
+      if (objName == nameNoDim) {
+         return static_cast<TRealData*>(obj);
```
[the remark this answers is not in the document]
Comment (pcanal) [reply core/meta/src/TClass.cxx:3636]: Indeed.  For the purpose of closing this PR, this will be done in a subsequent PR.  See https://gist.github.com/pcanal/3bf0224cd1caa24a3c62f459d00ef9a9/edit

File: io/io/src/TStreamerInfo.cxx (hunk 3 above)
Comment (pcanal) [reply io/io/src/TStreamerInfo.cxx:260]: Done.

**Comment by smuzaffar** [comment]
@pcanal , while testing this in cmssw , we get build error/warning like [a]. the classes_def.xml file is https://github.com/cms-sw/cmssw/blob/master/DataFormats/HcalIsolatedTrack/src/classes_def.xml . Do we need some cleanup in cmssw to avoid this warning?

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-276a04/43859/build-logs/DataFormats/HcalIsolatedTrack/log.html
```
>> Building LCG reflex dict from header file src/DataFormats/HcalIsolatedTrack/src/classes.h
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.35.1-d947221dfef9ef0f4c58e17a5214a16a/bin/rootcling -reflex -f tmp/el8_amd64_gcc12/src/DataFormats/HcalIsolatedTrack/src/DataFormatsHcalIsolatedTrack/lcgdict/DataFormatsHcalIsolatedTrack_xr.cc -inlineInputHeader -failOnWarnings -rmf tmp/el8_amd64_gcc12/src/DataFormats/HcalIsolatedTrack/src/DataFormatsHcalIsolatedTrack/lcgdict/DataFormatsHcalIsolatedTrack_xr.rootmap -rml libDataFormatsHcalIsolatedTrack.so -m DataFormatsRecoCandidate_xr_rdict.pcm -m DataFormatsEgammaReco_xr_rdict.pcm -m DataFormatsGsfTrackReco_xr_rdict.pcm -m DataFormatsTrackReco_xr_rdict.pcm -m DataFormatsTrackCandidate_xr_rdict.pcm -m DataFormatsTrajectorySeed_xr_rdict.pcm -m DataFormatsL1Trigger_xr_rdict.pcm -m DataFormatsTrackingRecHit_xr_rdict.pcm -m DataFormatsL1TrackTrigger_xr_rdict.pcm -m DataFormatsTrackerCommon_xr_rdict.pcm -m DataFormatsBeamSpot_xr_rdict.pcm -m DataFormatsCaloTowers_xr_rdict.pcm -m DataFormatsEcalRecHit_xr_rdict.pcm -m DataFormatsGeometryCommonDetAlgo_xr_rdict.pcm -m DataFormatsSiStripCluster_xr_rdict.pcm -m DataFormatsCandidate_xr_rdict.pcm -m DataFormatsEcalDigi_xr_rdict.pcm -m DataFormatsGeometrySurface_xr_rdict.pcm -m DataFormatsL1GlobalCaloTrigger_xr_rdict.pcm -m DataFormatsTrajectoryState_xr_rdict.pcm -m DataFormatsCLHEP_xr_rdict.pcm -m DataFormatsCaloRecHit_xr_rdict.pcm -m DataFormatsEcalDetId_xr_rdict.pcm -m DataFormatsForwardDetId_xr_rdict.pcm -m DataFormatsGeometryVector_xr_rdict.pcm -m DataFormatsHcalDetId_xr_rdict.pcm -m DataFormatsL1CaloTrigger_xr_rdict.pcm -m DataFormatsMuonDetId_xr_rdict.pcm -m DataFormatsSiPixelDetId_xr_rdict.pcm -m DataFormatsSiStripDetId_xr_rdict.pcm -m DataFormatsDetId_xr_rdict.pcm -m DataFormatsL1GlobalMuonTrigger_xr_rdict.pcm -m DataFormatsMath_xr_rdict.pcm -m DataFormatsPhase2TrackerDigi_xr_rdict.pcm -m DataFormatsScouting_xr_rdict.pcm -m DataFormatsSiPixelCluster_xr_rdict.pcm -m DataFormatsSiStripDigi_xr_rdict.pcm -m DataFormatsCommon_xr_rdict.pcm -m DataFormatsProvenance_xr_rdict.pcm -DALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128 -DALPAKA_DISABLE_VENDOR_RNG -DCMS_DICT_IMPL -D_REENTRANT -DGNUSOURCE -D__STRICT_ANSI__ -DGNU_GCC -D_GNU_SOURCE -DTBB_USE_GLIBCXX_VERSION=120301 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DCMSSW_GIT_HASH="CMSSW_15_0_ROOT6_X_2025-01-19-2300" -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_15_0_ROOT6_X_2025-01-19-2300" -Isrc -Ipoison -I/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02873/el8_amd64_gcc12/cms/cmssw/CMSSW_15_0_ROOT6_X_2025-01-19-2300/src -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/alpaka/1.1.0-8e7128ba865cc169d302ab17150849de/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/pcre/8.43-2d141998cfe5424b8f7aff48035cc2da/include -isystem/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/boost/1.80.0-24621bb5019ee7e7984682e0f80b5fcf/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include -isystem/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/clhep/2.4.7.1-d3a3e353d370e701238f7949a0d7909f/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/gsl/2.6-f7574c606b0ce57ff601d3ca9534cd01/include -isystem/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/hls/2019.08-e6beae7d560007d8bb20c2cf88bfde9a/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include -isystem/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.35.1-d947221dfef9ef0f4c58e17a5214a16a/include -isystem/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/tbb/v2021.9.0-573155027234b8f945d29403a2749d52/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/zlib/1.2.13-d217cdbdd8d586e845e05946de2796be/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/eigen/3bb6a48d8c171cf20b5f8e48bfb4e424fbd4f79e-e265b266d2b30c1bebdd883980d0f9d0/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/eigen/3bb6a48d8c171cf20b5f8e48bfb4e424fbd4f79e-e265b266d2b30c1bebdd883980d0f9d0/include/eigen3 -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/fmt/10.2.1-e35fd1db5eb3abc8ac0452e8ee427196/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/OpenBLAS/0.3.27-70a9dd2c9f309171934f13e3003b0540/include -I/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/tinyxml2/6.2.0-f99ae2781d074227d47e8a3e7c8ec87e/include -DCMSSW_REFLEX_DICT src/DataFormats/HcalIsolatedTrack/src/classes.h src/DataFormats/HcalIsolatedTrack/src/classes_def.xml
  Warning: 2 Rule(s) for target class reco::LeafParticle was not used!
   gmake: *** [tmp/el8_amd64_gcc12/src/DataFormats/HcalIsolatedTrack/src/DataFormatsHcalIsolatedTrack/lcgdict/DataFormatsHcalIsolatedTrack_xr.cc] Error 1
```

**Comment by pcanal** [comment]
This indicates a 'real' error and the 2 rules whose `targetClass` is `reco::LeafParticle` are being ignored.  The likely cause is that the dictionary generation that has [DataFormats/HcalIsolatedTrack/src/classes_def.xml](https://github.com/cms-sw/cmssw/blob/master/DataFormats/HcalIsolatedTrack/src/classes_def.xml?rgh-link-date=2025-01-20T14%3A33%3A07Z) as argument is not seeing any header that declares `reco::LeafParticle`

Previously those rules were (likely) silently ignored.

To enable them add something like `#include "reco/LeafParticle.h"` to the dictionary generation steps.

**Comment by smuzaffar** [comment]
> To enable them add something like #include "reco/LeafParticle.h" to the dictionary generation steps.

thanks @pcanal , I will try this
