### PR TITLE
[ntuple] Fix processing of classes with enum definitions

### LINKED ISSUE #8901: RNTuple: Can not create a Field for a user class with anonymous enum
RFieldBase::Create("fieldname", "classame") in ROOT 6.24.0 returns an error when the class contains an anonymous enum. 
To reproduce execute a ROOT macro EmumTest.C containing:
```
class ContainsEnum { public:  enum { EnumField1, EnumField2 }; };   
void EnumTest() {   
  try {  auto field = ROOT::Experimental::Detail::RFieldBase::Create("HasEnum", "ContainsEnum").Unwrap();   
  } catch(const std::exception& exc) {   
      std::cout << "ERROR: " << exc.what() << std::endl;   
  }   
}
``` 
```root [0] 
Processing EnumTest.C...
ERROR: Field EnumField1 has unknown type ContainsEnum::(anonymous) (unchecked RResult access!)
At:
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::Detail::RFieldBase> > ROOT::Experimental::Detail::RFieldBase::Create(const string&, const string&) [/build/jenkins/workspace/lcg_release_pipeline/build/projects/ROOT-v6.24.00/src/ROOT/v6.24.00/tree/ntuple/v7/src/RField.cxx:225]
```
Marcin

### PR DESCRIPTION
**Pull request by jblomer**
Fixes #8901

### CODE REVIEW

File: tree/ntuple/v7/test/CustomStructLinkDef.h [hunk 1]
```diff
@@ -16,4 +16,7 @@
 
 #pragma link C++ class ComplexStruct+;
 
+#pragma link C++ class BaseOfStructWithEnums + ;
+#pragma link C++ class StructWithEnums + ;
```
Comment (jalopezg-r00t) [inline tree/ntuple/v7/test/CustomStructLinkDef.h:20]:
```suggestion
#pragma link C++ class BaseOfStructWithEnums+;
#pragma link C++ class StructWithEnums+;
```

File: tree/ntuple/v7/src/RField.cxx [hunk 2]
```diff
@@ -785,7 +787,14 @@ ROOT::Experimental::RClassField::RClassField(std::string_view fieldName, std::st
 	     RSubFieldInfo{kBaseClass, static_cast<std::size_t>(baseClass->GetDelta())});
       i++;
    }
+   std::unordered_set<void *> realMembers;
+   for (auto rm : ROOT::Detail::TRangeStaticCast<TRealData>(*fClass->GetListOfRealData()))
+      realMembers.insert(rm->GetDataMember());
    for (auto dataMember : ROOT::Detail::TRangeStaticCast<TDataMember>(*fClass->GetListOfDataMembers())) {
+      // Skip, for instance, unscoped enum constants defined in the class
+      if (realMembers.count(dataMember) == 0)
+         continue;
```
Comment (jalopezg-r00t) [inline tree/ntuple/v7/src/RField.cxx:796]: I think that, instead of iterating twice over the list of data members, perhaps we can use `TDataMember::IsEnum()` in combination with either `GetTypeName()` (which should contain `something::(anonymous)`) or `GetOffset()` (which for enumerators of an unscoped enum that appear in the parent scope, returns strangely high values), e.g. for `StructWithEnums`:
```
a: IsEnum=0 type=int offset @4
b: IsEnum=0 type=int offset @8
A1: IsEnum=1 type=StructWithEnums::(anonymous) offset @94646202990808
A2: IsEnum=1 type=StructWithEnums::(anonymous) offset @94646202990896
E1: IsEnum=1 type=StructWithEnums::DeclE offset @94646202991224
E2: IsEnum=1 type=StructWithEnums::DeclE offset @94646202991312
E42: IsEnum=1 type=StructWithEnums::DeclE offset @94646202991464
```

Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:796]: The problem here is that also real data members that are declared as enums have `IsEnum() == true`. While at the moment we don't support enums, at some point we want to.  And then we need to distinguish between `enum { E1 };` and `E1 e1;`.

File: tree/ntuple/v7/test/CustomStructLinkDef.h (hunk 1 above)
Comment (jblomer) [reply tree/ntuple/v7/test/CustomStructLinkDef.h:20]: As discussed in the Shush channel, that's `clang-format`s decision

**Comment by jblomer** [comment]
@pcanal could you have a look at this?

File: tree/ntuple/v7/test/CustomStructLinkDef.h (hunk 1 above)
Comment (pcanal) [reply tree/ntuple/v7/test/CustomStructLinkDef.h:20]: clang-format should probably not be run on LinkDef files.

**Comment by pcanal** [comment]
@phsft-bot build just on mac11/cxx17

File: tree/ntuple/v7/src/RField.cxx (hunk 2 above)
Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx:796]: The definitive comprehensive answer to all your question is in: `TStreamerInfo::Build` :)

The short answer to skip enum declaration is:
```
      if (dataMember->Property() & kIsUnionMember) {
         continue;
      }
```

File: tree/ntuple/v7/test/CustomStructLinkDef.h (hunk 1 above)
Comment (jblomer) [reply tree/ntuple/v7/test/CustomStructLinkDef.h:20]: All right, I created #10448 to keep track of it.

File: tree/ntuple/v7/src/RField.cxx (hunk 2 above)
Comment (jblomer) [reply tree/ntuple/v7/src/RField.cxx:796]: Are you sure that you don't mean `kIsStatic`?

File: tree/ntuple/v7/src/RField.cxx [hunk 3]
```diff
@@ -31,6 +31,7 @@
 #include <TDataMember.h>
 #include <TError.h>
 #include <TList.h>
+#include <TRealData.h>
```
Comment (jalopezg-r00t) [inline tree/ntuple/v7/src/RField.cxx:34]: I think we don't need this anymore.
```suggestion
```

File: tree/ntuple/v7/src/RField.cxx [hunk 4]
```diff
@@ -40,6 +41,7 @@
 #include <iostream>
 #include <type_traits>
 #include <unordered_map>
+#include <unordered_set>
```
Comment (jalopezg-r00t) [inline tree/ntuple/v7/src/RField.cxx:44]:
```suggestion
```

File: tree/ntuple/v7/test/CustomStructLinkDef.h (hunk 1 above)
Comment (jalopezg-r00t) [reply tree/ntuple/v7/test/CustomStructLinkDef.h:20]: I guess `rootcling` parses this correctly even with the extra whitespace?

**Review by jalopezg-r00t — APPROVED** [review]
LGTM (but see comments)!

File: tree/ntuple/v7/src/RField.cxx (hunk 2 above)
Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx]: In `TStreamerInfo::Build`, `static` is indirectly taken care  of by:
```
      TMemberStreamer* streamer = 0;
      Int_t offset = GetDataMemberOffset(dm, streamer);
      if (offset == kMissing) {
         continue;
      }
```
where the static data member have the offset `kMissing` (i.e. -1)

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx]: In `TStreamerInfo::Build`, `static` is indirectly taken care  of by:
```
      TMemberStreamer* streamer = 0;
      Int_t offset = GetDataMemberOffset(dm, streamer);
      if (offset == kMissing) {
         continue;
      }
```
where the static data member have the return value of `TStreamerInfo::GetDataMemberOffset` is  `kMissing`

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx]: This is obviously sub-optiomal and we should consider updating `TDataMember` to mark the `static` and `union` members are transient.

Comment (pcanal) [reply tree/ntuple/v7/src/RField.cxx]: > Are you sure that you don't mean kIsStatic?

And actually @jblomer, you are completely right ... I mis-read the code last night (`Union` vs `Enum`).
