### PR TITLE
IO: Fix StreamerInfo record write during file update.

### LINKED ISSUE #12783: [IO] Writing HistFactory model file twice gives strange results since ROOT 6.26.02
## Problem description

Since 6.26.02, there is a problem when writing different HistFactory workspaces in the same script/executable. The second workspace file is corrupt, even if the only difference for the second time is the output file prefix.

That the second workspace is corrupt gets apparent in two ways:
1. It can't be opened with newer ROOT versions (but surprisingly it can be opened with the same 6.26 version)
2. The file sizes are much smaller

The first in commit in the 6.26 branch that shows this problem was found with git bisect (see the end of this comment).

I marked this issue as **high** priority, because writing out HistFactory workspaces is a common practice in ATLAS. And recently, several ATLAS workspaces unexplainably appear corrupt. Fixing this issue could fix these problems.

## To reproduce

1. Run the following script with ROOT 6.26.02 (or any newer 6.26 commit):
   ```c++
   {
      TFile f("myFile.root", "RECREATE");
      TH1D h("myHist", "", 10, 0, 10);
      h.Write();
   }
   std::vector<std::string> names = {"ws1", "ws2"};
   for (auto name : names) {
      RooStats::HistFactory::Measurement meas(name.c_str(), name.c_str());
      meas.SetOutputFilePrefix((name + "/WS").c_str());
      meas.SetPOI("mu");
      meas.SetLumi(1);
      meas.AddConstantParam("Lumi");
      meas.SetExportOnly(true);
      RooStats::HistFactory::Channel chan("SR");
      chan.SetData("", "");
      RooStats::HistFactory::Sample sample("samp");
      sample.SetHistoName("myHist");
      sample.SetInputFile("myFile.root");
      sample.AddNormFactor("mu", 1, 0, 100);
      chan.AddSample(sample);
      meas.AddChannel(chan);
      meas.CollectHistograms();
      //if(name == "ws2")
      //delete RooStats::HistFactory::MakeModelAndMeasurementFast(meas);
      RooStats::HistFactory::MakeModelAndMeasurementFast(meas);
   }
   ```
2. Validate the file sizes:
   ```bash
   ls -lah ws1 ws2
   ```
4. Try to open the second workspace with any ROOT 6.28 version:
   ```bash
   root ws2/WS_combined_ws2_model.root -b -q -e "combined->GetName()"
   ```

There will be errors such as:
```
Error in <TBufferFile::ReadClassBuffer>: Could not find the StreamerInfo for version 2 of the class RooAbsReal, object skipped at offset 6484979
Error in <TBufferFile::CheckByteCount>: object of class RooAbsReal read too few bytes: 2 instead of 336
```

## Information on the origin of the problem

The first bad commit in the 6.26 branch is 00ca5ca9b23f2 from the PR https://github.com/root-project/root/pull/10215.
The comes from a backport of https://github.com/root-project/root/pull/9486 to the 6.26 patch release branch.

Before that commit, when you run the reproducer script above, the `ws1` and `ws2` files are compatible:
```bash
ls -lah ws1 ws2
```
```txt
ws1:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:31 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:31 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:31 WS_combined_ws1_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:31 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:31 WS_SR_ws1_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:31 WS_ws1.root

ws2:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:31 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:31 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:31 WS_combined_ws2_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:31 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:31 WS_SR_ws2_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:31 WS_ws2.root
```

from 00ca5ca9b23f2 onward, the second workspace files are smaller from some reason:
```txt
ws1:
total 88K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:28 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:28 ..
-rw-r--r-- 1 rembserj rembserj  36K May  7 23:28 WS_combined_ws1_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:28 WS_results.table
-rw-r--r-- 1 rembserj rembserj  34K May  7 23:28 WS_SR_ws1_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:28 WS_ws1.root

ws2:
total 56K
drwxr-xr-x 2 rembserj rembserj 4.0K May  7 23:28 .
drwxr-xr-x 4 rembserj rembserj 4.0K May  7 23:28 ..
-rw-r--r-- 1 rembserj rembserj  20K May  7 23:28 WS_combined_ws2_model.root
-rw-r--r-- 1 rembserj rembserj   14 May  7 23:28 WS_results.table
-rw-r--r-- 1 rembserj rembserj  19K May  7 23:28 WS_SR_ws2_model.root
-rw-r--r-- 1 rembserj rembserj  423 May  7 23:28 WS_ws2.root
```

So the problem somehow seems to be related to multithreaded IO?

### PR DESCRIPTION
**Pull request by pcanal**
Fix #12783

Since "66dfb08bd7 - [IO] Do not process the streamerinfo record of a file if we read the si already read"
which was extended in scope by "7cf9d5dc8c - fix hashing of streamer info,"

if a file is opened in update mode and the reading of its `StreamerInfo` record is skip (but
an identical record was already read) *and* some data is stored in the file, the new
`StreamerInfo` record written was missing all the classes in the original record that
were not used during the update.

To resolve this we record not only the fact that the record has been read and process
but also its content (via a collectin of uid of the `TStreamerInfo` objects).
Upon skipping the `StreamerInfo` record, we now mark of its `TStreamerInfo` objects has
been used by the file (and thus upon writing the record is complete).

This behavior was seen #12783 due an awkward 'create, fill, close, update immediately' cycle
for a couple of files.

### CODE REVIEW

File: core/thread/inc/ROOT/RConcurrentHashColl.hxx [hunk 1]
```diff
@@ -38,16 +42,23 @@ public:
...
+         std::hash<ULong64_t> hasher;
+         return hasher(fDigest[0]) ^ hasher(fDigest[1])
+               ^ hasher(fDigest[2]) ^ hasher(fDigest[3]);
+      }
    };
 
    RConcurrentHashColl();
    ~RConcurrentHashColl();
 
    /// Return true if the hash is already in already there
```
Comment (jblomer) [inline core/thread/inc/ROOT/RConcurrentHashColl.hxx:57]: The comment could be fixed up to follow the code change.  Also for `Insert()`

File: core/thread/src/RConcurrentHashColl.cxx [hunk 2]
```diff
@@ -46,10 +61,10 @@ RConcurrentHashColl::HashValue RConcurrentHashColl::Hash(char *buffer, int len)
 }
 
 /// If the buffer is there, return false. Otherwise, insert the hash and return true
```
Comment (jblomer) [inline core/thread/src/RConcurrentHashColl.cxx:63]: Remove comment (or move here from header)

File: core/thread/src/RConcurrentHashColl.cxx [hunk 3]
```diff
@@ -23,20 +34,24 @@ RConcurrentHashColl::HashValue::HashValue(const char *data, int len)
...
    ROOT::TRWSpinLockReadGuard rg(*fRWLock);
-   return (fHashSet->fSet.end() != fHashSet->fSet.find(hash));
+   auto iter = fHashMap->fHashMap.find(hash);
+   if (iter != fHashMap->fHashMap.end())
+      return &(iter->second);
+   else
+      return nullptr;
 }
 
 /// If the buffer is there, return false. Otherwise, insert the hash and return true
```
Comment (jblomer) [inline core/thread/src/RConcurrentHashColl.cxx:57]: Remove comment (or move here from header)

File: io/io/inc/TFile.h [hunk 4]
```diff
@@ -34,11 +34,8 @@
 // #include "TMap.h"
 // #endif
 
-#ifdef R__USE_IMT
```
Comment (jblomer) [inline io/io/inc/TFile.h:37]: Why was this guard removed?

**Review by jblomer — COMMENTED** [review]
LGTM but I don't feel familiar enough to judge.

**Review by Axel-Naumann — APPROVED** [review]
Let's get this in.

**Comment by Axel-Naumann** [comment]
Removed milestone - timeout.

File: io/io/inc/TFile.h (hunk 4 above)
Comment (pcanal) [reply io/io/inc/TFile.h]: Actually it was not needed.
