### PR TITLE
fix: speed up `RDataFrame::Display`

### LINKED ISSUE #14511: `RDataFrame::Display` excrutiatingly slow?
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

(At least) On a 2023 MacBook (14.2) `RDataFrame::Display` is infinitely slower than `TTree::Scan` (real number is maybe around 400 times slower).

### Reproducer

Using hsimple.root:
```
$ root.exe -b -l tutorials/hsimple.root 
root [0] 
Attaching file tutorials/hsimple.root as _file0...
(TFile *) 0x13b63d330
root [1] gROOT->Time()
Real time 0:00:06.038826, CP time 0.090
root [2] ntuple->Scan("","","",4,0)
************************************************************************
*    Row   *     px.px *     py.py *     pz.pz * random.ra *       i.i *
************************************************************************
*        0 * 0.0194094 * 0.0118254 * 0.0005165 * 0.2826178 *         0 *
*        1 * 0.3271895 * 0.0378782 * 0.1084877 * 0.4849736 *         1 *
*        2 * -0.294611 * -0.010545 * 0.0869072 * 0.5400436 *         2 *
*        3 * -0.774589 * 0.0484584 * 0.6023372 * 0.6586366 *         3 *
************************************************************************
(long long) 4
Real time 0:00:00.542977, CP time 0.540
root [3] ROOT::RDataFrame df(*ntuple)
(ROOT::RDataFrame &) A data frame built on top of the ntuple dataset.
Real time 0:00:01.649577, CP time 1.420
root [4] df.Display("px")->Print()
+-----+------------+
| Row | px         | 
+-----+------------+
| 0   | 0.0194095f | 
+-----+------------+
| 1   | 0.327190f  | 
+-----+------------+
| 2   | -0.294612f | 
+-----+------------+
| 3   | -0.774590f | 
+-----+------------+
| 4   | -1.43080f  | 
+-----+------------+
Real time 0:00:24.774113, CP time 24.480
root [5] df.Display("px")->Print()
+-----+------------+
| Row | px         | 
+-----+------------+
| 0   | 0.0194095f | 
+-----+------------+
| 1   | 0.327190f  | 
+-----+------------+
| 2   | -0.294612f | 
+-----+------------+
| 3   | -0.774590f | 
+-----+------------+
| 4   | -1.43080f  | 
+-----+------------+
Real time 0:00:16.596351, CP time 16.420
root [6] ntuple->Scan("","","",4,0)
************************************************************************
*    Row   *     px.px *     py.py *     pz.pz * random.ra *       i.i *
************************************************************************
*        0 * 0.0194094 * 0.0118254 * 0.0005165 * 0.2826178 *         0 *
*        1 * 0.3271895 * 0.0378782 * 0.1084877 * 0.4849736 *         1 *
*        2 * -0.294611 * -0.010545 * 0.0869072 * 0.5400436 *         2 *
*        3 * -0.774589 * 0.0484584 * 0.6023372 * 0.6586366 *         3 *
************************************************************************
(long long) 4
Real time 0:00:00.035943, CP time 0.030
```

### ROOT version

master

### Installation method

debug build

### Operating system

MacOS but likely any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ianna**
# This Pull request:

Do not use `cling::printValue` for printing the column elements of the arithmetic types.

## Changes or fixes:

This <strike>require a proper specialisation, however it already</strike> gives `x10` performance improvement on my laptop.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes # 

fixes #14511

@vepadulano - FYI

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build

File: tree/ntuple/v7/inc/ROOT/RField.hxx [hunk 1]
```diff
@@ -125,6 +125,7 @@ protected:
    struct RSharedPtrDeleter {
       std::unique_ptr<RFieldBase::RDeleter> fDeleter;
       void operator()(void *objPtr) { fDeleter->operator()(objPtr, false /* dtorOnly*/); }
+      RSharedPtrDeleter(const RSharedPtrDeleter& deleter) : fDeleter( new RFieldBase::RDeleter(*deleter.fDeleter)) {}
```
Comment (ianna) [inline tree/ntuple/v7/inc/ROOT/RField.hxx:128]: @vepadulano - this change can be ignored. I need it to build root on my MacOS 11.6.

File: tree/dataframe/inc/ROOT/RDF/RDisplay.hxx [hunk 2]
```diff
@@ -90,17 +91,23 @@ private:
...
    {
-      stream << "*((std::string*)" << ROOT::Internal::RDF::PrettyPrintAddr(&(fRepresentations[index]))
-             << ") = cling::printValue((" << fTypes[index] << "*)" << ROOT::Internal::RDF::PrettyPrintAddr(&element) << ");";
+      if (!std::is_arithmetic_v<T>) {
+         stream << "*((std::string*)" << ROOT::Internal::RDF::PrettyPrintAddr(&(fRepresentations[index]))
+                << ") = cling::printValue((" << fTypes[index] << "*)" << ROOT::Internal::RDF::PrettyPrintAddr(&element) << ");";
+      } else {
+         stream << "*((std::string*)" << ROOT::Internal::RDF::PrettyPrintAddr(&(fRepresentations[index]))
+                << ") = std::to_string(*(" << fTypes[index] << "*)" << ROOT::Internal::RDF::PrettyPrintAddr(&element) << ");";
+      }
```
Comment (ianna) [inline tree/dataframe/inc/ROOT/RDF/RDisplay.hxx:110]: @vepadulano - the tests fail because `cling::printValue` and `std::to_string ` use different number of significant figures for floating point numbers:
`2.000000` vs `2.0000000`

**Review by ianna — COMMENTED** [review]
as discussed the performance can be improved even more by providing a specialisation for `RVec<T>` where `T` is an arithmetic type.

**Review by ianna — COMMENTED** [review]
baseline before changing the default precision: 
```
Fixathon_13_02_2024 % root.exe -b -l myinstall/tutorials/hsimple.root
root [0] 
Attaching file myinstall/tutorials/hsimple.root as _file0...
(TFile *) 0x7fbed7f9fe70
root [1] gROOT->Time()
Real time 0:00:00.651355, CP time 0.020
root [2] ntuple->Scan("","","",4,0)
************************************************************************
*    Row   *     px.px *     py.py *     pz.pz * random.ra *       i.i *
************************************************************************
*        0 * 0.0194094 * 0.0118254 * 0.0005165 * 0.2826178 *         0 *
*        1 * 0.3271895 * 0.0378782 * 0.1084877 * 0.4849736 *         1 *
*        2 * -0.294611 * -0.010545 * 0.0869072 * 0.5400436 *         2 *
*        3 * -0.774589 * 0.0484584 * 0.6023373 * 0.6586366 *         3 *
************************************************************************
(long long) 4
Real time 0:00:00.353118, CP time 0.340
root [3] ROOT::RDataFrame df(*ntuple)
(ROOT::RDataFrame &) A data frame built on top of the ntuple dataset.
Real time 0:00:01.421842, CP time 1.400
root [4] df.Display("px")->Print()
+-----+-----------+
| Row | px        | 
+-----+-----------+
| 0   | 0.019409  | 
+-----+-----------+
| 1   | 0.327190  | 
+-----+-----------+
| 2   | -0.294612 | 
+-----+-----------+
| 3   | -0.774590 | 
+-----+-----------+
| 4   | -1.430795 | 
+-----+-----------+
Real time 0:00:03.486781, CP time 3.480
root [5] df.Display("px")->Print()
+-----+-----------+
| Row | px        | 
+-----+-----------+
| 0   | 0.019409  | 
+-----+-----------+
| 1   | 0.327190  | 
+-----+-----------+
| 2   | -0.294612 | 
+-----+-----------+
| 3   | -0.774590 | 
+-----+-----------+
| 4   | -1.430795 | 
+-----+-----------+
Real time 0:00:01.333107, CP time 1.330
root [6] ntuple->Scan("","","",4,0)
************************************************************************
*    Row   *     px.px *     py.py *     pz.pz * random.ra *       i.i *
************************************************************************
*        0 * 0.0194094 * 0.0118254 * 0.0005165 * 0.2826178 *         0 *
*        1 * 0.3271895 * 0.0378782 * 0.1084877 * 0.4849736 *         1 *
*        2 * -0.294611 * -0.010545 * 0.0869072 * 0.5400436 *         2 *
*        3 * -0.774589 * 0.0484584 * 0.6023373 * 0.6586366 *         3 *
************************************************************************
(long long) 4
Real time 0:00:00.010452, CP time 0.010
root [7] 
```

**Comment by hahnjo** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
@phsft-bot build

**Comment by ianna** [comment]
@vepadulano - the RDF Display tests will fail to compare the strings with floats due to different precision between `std::to_string` and `cling::printValue`. I'll leave it to you to decide what you want to do: either update the tests or change the precision when floats are converted to a string.

File: tree/ntuple/v7/inc/ROOT/RField.hxx (hunk 1 above)
Comment (ianna) [reply tree/ntuple/v7/inc/ROOT/RField.hxx]: removed

**Comment by ianna** [comment]
@vepadulano - I think, now all the tests should pass.

**Comment by ianna** [comment]
@hahnjo - could you, please trigger the tests? Thanks!

**Comment by hahnjo** [comment]
@phsft-bot build

File: tree/dataframe/inc/ROOT/RDF/RDisplay.hxx [hunk 3]
```diff
@@ -90,17 +91,32 @@ private:
...
    ////////////////////////////////////////////////////////////////////////////
-   /// Appends a cling::printValue call to the stringstream.
+   /// Appends a string if the T type is an arithmetic type.
    /// \tparam T the type of the event to convert
    /// \param[in] stream Where the conversion function call will be chained.
    /// \param[in] element The event to convert to its string representation
    /// \param[in] index To which column the event belongs to
    /// \return false, the event is not a collection
-   template <typename T, std::enable_if_t<!ROOT::Internal::RDF::IsDataContainer<T>::value, int> = 0>
+   template <typename T, typename std::enable_if_t<std::is_floating_point<T>::value && !ROOT::Internal::RDF::IsDataContainer<T>::value, int> = 0>
```
Comment (ianna) [inline tree/dataframe/inc/ROOT/RDF/RDisplay.hxx:100]: I'm restricting it to floating point type to make sure the booleans are treated as they are now.

**Review by ianna — COMMENTED** [review]
@vepadulano - hopefully this is the last fix for now. Could you, please, trigger the build? Thanks!

**Comment by vepadulano** [comment]
@phsft-bot build

File: tree/dataframe/inc/ROOT/RDF/RDisplay.hxx [hunk 4]
```diff
@@ -91,32 +91,38 @@ private:
...
+   /// This overload works for arithmetic data types that are trivially
+   /// convertible to string.
    /// \tparam T the type of the event to convert
-   /// \param[in] stream Where the conversion function call will be chained.
    /// \param[in] element The event to convert to its string representation
    /// \param[in] index To which column the event belongs to
    /// \return false, the event is not a collection
-   template <typename T, typename std::enable_if_t<!std::is_floating_point<T>::value && !ROOT::Internal::RDF::IsDataContainer<T>::value, int> = 0>
-   bool AddInterpreterString(std::stringstream &stream, T &element, const int &index)
+   template <typename T, std::enable_if_t<std::is_arithmetic_v<T>, int> = 0>
```
Comment (ianna) [inline tree/dataframe/inc/ROOT/RDF/RDisplay.hxx:120]: @vepadulano - you need to make sure that booleans are excluded

**Review by ianna — COMMENTED** [review]
The tests fail because bool is treated as an arithmetic type:
```
With diff:
@@ -1,28 +1,28 @@
-+-----+-----------+------+------+----------------+
-| Row | col1      | col3 | col6 | col8           | 
-+-----+-----------+------+------+----------------+
-| 0   | 3.140000  | 0    | 0    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 1   | 4.140000  | 0    | 2    | \"R,Data,Frame\" | 
-+-----+-----------+------+------+----------------+
-| 2   | nan       | 1    | 3    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 3   | 5.140000  | 1    | 4    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 4   | -6.140000 | 1    | 5    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 5   | -7.140000 | 1    | 6    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 6   | nan       | 1    | 7    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 7   | nan       | 1    | 8    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 8   | 3.150000  | 1    | 9    | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 9   | 5.150000  | 1    | 10   | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 10  | 6.150000  | 1    | 11   | \"nan\"          | 
-+-----+-----------+------+------+----------------+
-| 11  | 6.150000  | 1    | 12   | \"nan\"          | 
-|     |           |      |      |                | 
-+-----+-----------+------+------+----------------+\n
++-----+-----------+-------+------+----------------+
+| Row | col1      | col3  | col6 | col8           | 
++-----+-----------+-------+------+----------------+
+| 0   | 3.140000  | false | 0    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 1   | 4.140000  | false | 2    | \"R,Data,Frame\" | 
++-----+-----------+-------+------+----------------+
+| 2   | nan       | true  | 3    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 3   | 5.140000  | true  | 4    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 4   | -6.140000 | true  | 5    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 5   | -7.140000 | true  | 6    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 6   | nan       | true  | 7    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 7   | nan       | true  | 8    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 8   | 3.150000  | true  | 9    | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 9   | 5.150000  | true  | 10   | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 10  | 6.150000  | true  | 11   | \"nan\"          | 
++-----+-----------+-------+------+----------------+
+| 11  | 6.150000  | true  | 12   | \"nan\"          | 
+|     |           |       |      |                | 
++-----+-----------+-------+------+----------------+\n
```

File: tree/dataframe/inc/ROOT/RDF/RDisplay.hxx (hunk 4 above)
Comment (vepadulano) [reply tree/dataframe/inc/ROOT/RDF/RDisplay.hxx:120]: Right! Apologies I had missed the previous comment about this issue, now is fixed in the latest commit

**Comment by vepadulano** [comment]
@phsft-bot build

**Review by vepadulano — APPROVED** [review]
@ianna Thank you so much for your contribution!
