### PR TITLE
Fix issue #6743 ROOT crashes if a TApplication is not present and tree->StartViewer() is called

### LINKED ISSUE #6743: ROOT crashes with no helpful error messages if a TApplication is not present and tree->StartViewer() is called
# Describe the bug

The following reproducer crashes with the stacktrace below (with a debug build of ROOT -- just a segfault for non-debug builds):

```cpp
#include <TTree.h>
#include <TFile.h>
#include <TApplication.h>

int main()
{
   //TApplication app("app", nullptr, nullptr);
   TFile *outputFile = new TFile("output.root", "RECREATE");

   TTree *tree = new TTree("tree", "treeliberated tree");
   outputFile->Write();

   tree->StartViewer();

   //app.Run();
   outputFile->Close();
}
```

```
#8  0x00007fd6cf22b8c2 in TGCompositeFrame::TGCompositeFrame (this=0x56036dc34a10, p=0x0, w=10, h=10, options=3, back=0) at ../../../root_dbg/gui/gui/src/TGFrame.cxx:853
#9  0x00007fd6cf22d4cc in TGMainFrame::TGMainFrame (this=0x56036dc34a10, p=0x0, w=10, h=10, options=2) at ../../../root_dbg/gui/gui/src/TGFrame.cxx:1430
#10 0x00007fd6d64b9a6c in TTreeViewer::TTreeViewer (this=0x56036dc34a10, tree=0x56036d05df80) at ../../../root_dbg/tree/treeviewer/src/TTreeViewer.cxx:349
#11 0x00007fd6d809e059 in ?? ()
#12 0x000056036c1be340 in ?? ()
#13 0x000056036c1be340 in ?? ()
#14 0x000056036dc34a10 in ?? ()
#15 0x000056036dc34a10 in ?? ()
#16 0x00007fff775fd220 in ?? ()
#17 0x00007fff775fd3d8 in ?? ()
#18 0x00007fff775fdc20 in ?? ()
#19 0x00007fff775fd3f8 in ?? ()
#20 0x00000001775fd3e0 in ?? ()
#21 0x0000000000000000 in ?? ()
```

### Expected behavior

The crash is due to a nullptr dereference in `TGCompositeFrame::TGCompositeFrame` (`fParent` is null), which in turn is caused by a failed check in `TGWindow::TGWindow` at `TGWindow.cxx:54`:

```
if (!p && gClient) {
   p = gClient->GetRoot();
}
```

In the condition above, if the user created no `TApplication`, `gClient` is false-y.

Rather than crash and burning, we could detect the situation and produce a helpful error message.

### Additional context

At least [one user](https://root-forum.cern.ch/t/break-segmentation-violation-for-a-compiled-program/42022/12) could have used a better error message :smile:

### PR DESCRIPTION
**Pull request by bellenot**
Fixes #6743 ROOT crashes with no helpful error messages if a TApplication is not present and tree->StartViewer() is called. Now it prints the following warning:
```
Warning in <TTreePlayer::StartViewer>: The tree viewer cannot run in batch mode
```

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

File: gui/gui/src/TGWindow.cxx [hunk 1]
```diff
@@ -51,6 +53,13 @@ TGWindow::TGWindow(const TGWindow *p, Int_t x, Int_t y, UInt_t w, UInt_t h,
    fParent = 0;
    fNeedRedraw = kFALSE;
 
+   if (!p && !gClient && !gApplication) {
+      ::Error("TGWindow::TGWindow",
+              "gClient and gApplication are nullptr!\n"
+              "Please add a TApplication instance in the main() function of your application\n");
+      std::exit(EXIT_FAILURE);
```
Comment (pcanal) [inline gui/gui/src/TGWindow.cxx:60]: Why not use `::Fatal` ?

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: > Why not use `::Fatal` ?

I tried, but it crashes (at least on Windows), but this should never happen anyway...

**Review by eguiraud — APPROVED** [review]
lgtm! (shallow review -- not an expert)

File: gui/gui/src/TGWindow.cxx (hunk 1 above)
Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: What do you mean by 'crash' :) ?   Fatal is suppose to exit the process.  Does Fatal not work just here or in general on Windows?

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: You know, it's the usual GUI stuff with the Window Manager. Do you need me to reproduce and provide the complete stack trace (if any)?

Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: This sounds like TROOT::Terminate is not 'waiting' for the GUI to properly tear down.   So yes, **if** it is not time consuming to step, a reproducer + stack traces will be helpful.

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: Working on it...

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: Here is the stack trace:
```
aborting

==========================================
=============== STACKTRACE ===============
==========================================


================ Thread 0 ================
  C:\Users\bellenot\git\master\core\foundation\src\TError.cxx(152): ErrorHandler()
  C:\Users\bellenot\git\master\core\foundation\src\TError.cxx(249): Fatal()
  C:\Users\bellenot\git\master\gui\gui\src\TGWindow.cxx(57): TGWindow::TGWindow()
  C:\Users\bellenot\git\master\gui\gui\src\TGFrame.cxx(147): TGFrame::TGFrame()
  C:\Users\bellenot\git\master\gui\gui\src\TGFrame.cxx(847): TGCompositeFrame::TGCompositeFrame()
  C:\Users\bellenot\git\master\gui\gui\src\TGFrame.cxx(1430): TGMainFrame::TGMainFrame()
  C:\Users\bellenot\git\master\tree\treeviewer\src\TTreeViewer.cxx(346): TTreeViewer::TTreeViewer()
  0x2c30ae ??
  C:\Users\bellenot\git\master\core\metacling\src\TClingCallFunc.cxx(1842): TClingCallFunc::exec()
  C:\Users\bellenot\git\master\core\metacling\src\TClingCallFunc.cxx(2042): <lambda_45b0f5d8ad983e3738d89b1979c56f47>::operator()()
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\type_traits(1579): std::_Invoker_functor::_Call<<lambda_45b0f5d8ad983e3738d89b1979c56f47> &,void *,cling::Value &>()
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\type_traits(1579): std::invoke<<lambda_45b0f5d8ad983e3738d89b1979c56f47> &,void *,cling::Value &>()
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\type_traits(1597): std::_Invoker_ret<void,1>::_Call<<lambda_45b0f5d8ad983e3738d89b1979c56f47> &,void *,cling::Value &>()
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\functional(926): std::_Func_impl_no_alloc<<lambda_45b0f5d8ad983e3738d89b1979c56f47>,void,void *,cling::Value &>::_Do_call()
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\functional(970): std::_Func_class<void,void *,cling::Value &>::operator()()
  C:\Users\bellenot\git\master\core\metacling\src\TClingCallFunc.cxx(2065): TClingCallFunc::exec_with_valref_return()
  C:\Users\bellenot\git\master\core\metacling\src\TClingCallFunc.cxx(2119): TClingCallFunc::ExecT<long>()
  C:\Users\bellenot\git\master\core\metacling\src\TClingCallFunc.cxx(2132): TClingCallFunc::ExecInt()
  C:\Users\bellenot\git\master\core\metacling\src\TCling.cxx(7742): TCling::CallFunc_ExecInt()
  C:\Users\bellenot\git\master\core\meta\src\TMethodCall.cxx(457): TMethodCall::Execute()
  C:\Users\bellenot\git\master\core\meta\inc\TMethodCall.h(136): TMethodCall::Execute()
  C:\Users\bellenot\git\master\core\base\inc\TPluginManager.h(162): TPluginHandler::ExecPluginImpl<TTree *>()
  C:\Users\bellenot\git\master\core\base\inc\TPluginManager.h(173): TPluginHandler::ExecPlugin<TTree *>()
  C:\Users\bellenot\git\master\tree\treeplayer\src\TTreePlayer.cxx(2969): TTreePlayer::StartViewer()
  C:\Users\bellenot\git\master\tree\tree\src\TTree.cxx(9264): TTree::StartViewer()
  C:\Users\bellenot\rootdev\test_treeviewer.cxx(22): main()
  d:\agent\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

================ Thread 1 ================
  ntdll!ZwWaitForWorkViaWorkerFactory()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

================ Thread 2 ================
  ntdll!ZwWaitForWorkViaWorkerFactory()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

================ Thread 3 ================
  ntdll!ZwWaitForWorkViaWorkerFactory()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

================ Thread 4 ================
  ntdll!NtDelayExecution()
  KERNELBASE!Sleep()
  C:\Users\bellenot\git\master\core\winnt\src\TWinNTSystem.cxx(4377): TWinNTSystem::TimerThread()
  C:\Users\bellenot\git\master\core\winnt\inc\TWinNTSystem.h(99): TWinNTSystem::ThreadStub()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

================ Thread 5 ================
  win32u!NtUserGetMessage()
  C:\Users\bellenot\git\master\core\winnt\src\TWinNTSystem.cxx(496): `anonymous namespace'::GUIThreadMessageProcessingLoop()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlGetAppContainerNamedObjectPath()
  ntdll!RtlGetAppContainerNamedObjectPath()

==========================================
============= END STACKTRACE =============
==========================================
```

Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: The intended behavior of Fatal (you can run it on linux to see), i.e. abort and print a stack trace.
Now we could discuss whether ::Fatal should close down the other thread first.

Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: If you want to avoid the stack trace.  Then rather that std::exit, I would prefer a call to Terminate or Exit.

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: OK, I'll investigate how to make it working on Windows and Linux. Going to take quite some time...

Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: I am confused.  ::Fatal already working as expected and alternatively replacing std::exit with gSystem->Exit should be straight-forward.  What am I missing? (I.e. what do you mean to investigate?)

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx:60]: Sorry, I was referring to this:
> The intended behavior of Fatal (you can run it on linux to see), i.e. abort and print a stack trace.
> Now we could discuss whether ::Fatal should close down the other thread first.

And about this statement
> I am confused. ::Fatal already working as expected and alternatively replacing std::exit with gSystem->Exit should be straight-forward. What am I missing? (I.e. what do you mean to investigate?)
`::Fatal` doesn't work, it produces the stack trace I posted. And I'll try `gSystem->Exit`. It's what I mean by "I'll investigate".

Comment (pcanal) [reply gui/gui/src/TGWindow.cxx:60]: ok

Comment (bellenot) [reply gui/gui/src/TGWindow.cxx]: @pcanal ok, using `gSystem->Exit()` works. Please let me know if it's good enough for you now.

**Review by pcanal — APPROVED** [review]
